DATA LIST FILE='BDBR31FL.DAT' RECORDS = 1
 /
  CASEID      1-15   (A)
  BIDX       16-17  
  V000       18-20   (A)
  V001       21-28  
  V002       29-32  
  V003       33-35  
  V004       36-39  
  V005       40-47  
  V006       48-49  
  V007       50-51  
  V008       52-55  
  V009       56-57  
  V010       58-59  
  V011       60-63  
  V012       64-65  
  V013       66-66  
  V014       67-67  
  V015       68-68  
  V016       69-70  
  V017       71-74  
  V018       75-76  
  V019       77-78  
  V020       79-79  
  V021       80-83  
  V022       84-87  
  V023       88-89  
  V024       90-91  
  V025       92-92  
  V026       93-93  
  V027       94-94  
  V028       95-97  
  V029       98-99  
  V030      100-101 
  V031      102-103 
  V032      104-105 
  V033      106-113 
  V034      114-115 
  V101      116-117 
  V102      118-118 
  V103      119-119 
  V104      120-121 
  V105      122-122 
  V106      123-123 
  V107      124-125 
  V108      126-126 
  V109      127-127 
  V110      128-128 
  V111      129-129 
  V112      130-130 
  V113      131-132 
  V114      133-134 
  V115      135-137 
  V116      138-139 
  V119      140-140 
  V120      141-141 
  V121      142-142 
  V122      143-143 
  V123      144-144 
  V124      145-145 
  V125      146-146 
  V127      147-148 
  V128      149-150 
  V129      151-152 
  V130      153-153 
  V131      154-155 
  V133      156-157 
  V134      158-158 
  V135      159-159 
  V136      160-161 
  V137      162-163 
  V138      164-165 
  V139      166-167 
  V140      168-168 
  V141      169-169 
  V142      170-170 
  V144      171-171 
  V148      172-172 
  V149      173-173 
  V150      174-175 
  V151      176-176 
  V152      177-178 
  V153      179-179 
  V154      180-181 
  AWFACTT   182-186 
  AWFACTU   187-191 
  AWFACTR   192-196 
  AWFACTE   197-201 
  V201      202-203 
  V202      204-205 
  V203      206-207 
  V204      208-209 
  V205      210-211 
  V206      212-213 
  V207      214-215 
  V208      216-216 
  V209      217-217 
  V210      218-218 
  V211      219-222 
  V212      223-224 
  V213      225-225 
  V214      226-227 
  V215      228-230 
  V216      231-231 
  V217      232-232 
  V218      233-234 
  V219      235-236 
  V220      237-237 
  V221      238-240 
  V222      241-243 
  V223      244-244 
  V224      245-246 
  V225      247-247 
  V226      248-250 
  V227      251-251 
  V228      252-252 
  V229      253-254 
  V230      255-256 
  V231      257-260 
  V232      261-261 
  V233      262-263 
  V234      264-264 
  V235      265-266 
  V236      267-267 
  V237      268-268 
  V238      269-269 
  V310      270-271 
  V311      272-272 
  V312      273-274 
  V313      275-275 
  V314      276-276 
  V315      277-278 
  V316      279-280 
  V317      281-284 
  V318      285-285 
  V319      286-286 
  V320      287-287 
  V321      288-288 
  V322      289-289 
  V323      290-291 
  V325      292-297 
  V326      298-299 
  V327      300-300 
  V328      301-302 
  V337      303-305 
  V359      306-307 
  V360      308-309 
  V361      310-310 
  V362      311-311 
  V363      312-313 
  V364      314-314 
  V366A     315-315 
  V366B     316-316 
  V367      317-317 
  V369      318-319 
  V369B     320-320 
  V372      321-321 
  V375A     322-323 
  V376      324-325 
  V376A     326-326 
  V379      327-328 
  V380      329-329 
  V384A     330-330 
  V384B     331-331 
  V384C     332-332 
  V384D     333-333 
  V384E     334-334 
  V393      335-335 
  V394      336-336 
  V395      337-337 
  V396      338-338 
  V397      339-339 
  V398      340-340 
  V399      341-341 
  V401      342-342 
  V404      343-343 
  V405      344-344 
  V406      345-345 
  V407      346-347 
  V408      348-349 
  V409      350-350 
  V409A     351-351 
  V410      352-352 
  V410A     353-353 
  V411      354-354 
  V411A     355-355 
  V412      356-356 
  V413A     357-357 
  V413B     358-358 
  V413C     359-359 
  V413D     360-360 
  V413      361-361 
  V414A     362-362 
  V414B     363-363 
  V414C     364-364 
  V414D     365-365 
  V414E     366-366 
  V414F     367-367 
  V414G     368-368 
  V414H     369-369 
  V415      370-370 
  V416      371-371 
  V417      372-372 
  V418      373-373 
  V419      374-374 
  V420      375-376 
  V421      377-378 
  V426      379-381 
  V436      382-384 
  V437      385-388 
  V438      389-392 
  V439      393-396 
  V440      397-400 
  V441      401-405 
  V442      406-410 
  V443      411-415 
  V444      416-420 
  V444A     421-424 
  V445      425-428 
  V446      429-432 
  V447      433-433 
  V448      434-434 
  V449      435-435 
  V450A     436-436 
  V450B     437-437 
  V450C     438-438 
  V450D     439-439 
  V450E     440-440 
  V450F     441-441 
  V450G     442-442 
  V450H     443-443 
  V450I     444-444 
  V450J     445-445 
  V450K     446-446 
  V450L     447-447 
  V450M     448-448 
  V450X     449-449 
  V450Z     450-450 
  V451A     451-451 
  V451B     452-452 
  V451C     453-453 
  V451D     454-454 
  V451E     455-455 
  V451F     456-456 
  V451G     457-457 
  V451H     458-458 
  V451I     459-459 
  V451J     460-460 
  V451K     461-461 
  V451X     462-462 
  V451Z     463-463 
  V501      464-464 
  V502      465-465 
  V503      466-466 
  V504      467-467 
  V505      468-469 
  V506      470-471 
  V507      472-473 
  V508      474-475 
  V509      476-479 
  V510      480-480 
  V511      481-482 
  V512      483-484 
  V513      485-485 
  V525      486-487 
  V527      488-490 
  V528      491-492 
  V529      493-495 
  V530      496-496 
  V531      497-498 
  V532      499-499 
  V534      500-500 
  V535      501-501 
  V602      502-502 
  V603      503-505 
  V604      506-506 
  V605      507-507 
  V606      508-508 
  V610      509-509 
  V611      510-510 
  V612      511-511 
  V613      512-513 
  V614      514-514 
  V616      515-517 
  V618      518-518 
  V621      519-519 
  V623      520-520 
  V624      521-522 
  V625      523-523 
  V626      524-525 
  V627      526-527 
  V628      528-529 
  V629      530-531 
  V630A     532-532 
  V630B     533-533 
  V630C     534-534 
  V630D     535-535 
  V630E     536-536 
  V630F     537-537 
  V630G     538-538 
  V630H     539-539 
  V630I     540-540 
  V630J     541-541 
  V630K     542-542 
  V630L     543-543 
  V630X     544-544 
  V701      545-545 
  V702      546-547 
  V704      548-550 
  V705      551-552 
  V707      553-553 
  V714      554-554 
  V715      555-556 
  V716      557-559 
  V717      560-561 
  V718      562-562 
  V719      563-563 
  V720      564-564 
  V721      565-565 
  V723      566-567 
  V729      568-568 
  V730      569-570 
  V731      571-571 
  V732      572-572 
  V733      573-574 
  V734      575-575 
  V735      576-578 
  V736      579-586 
  V737      587-593 
  V738      594-600 
  V739      601-601 
  V740      602-602 
  BORD      603-604 
  B0        605-605 
  B1        606-607 
  B2        608-609 
  B3        610-613 
  B4        614-614 
  B5        615-615 
  B6        616-618 
  B7        619-621 
  B8        622-623 
  B9        624-624 
  B10       625-625 
  B11       626-628 
  B12       629-631 
  B13       632-632 
  B14       633-633 
  B15       634-634 
  MIDX      635-635 
  M1        636-636 
  M2A       637-637 
  M2B       638-638 
  M2C       639-639 
  M2D       640-640 
  M2E       641-641 
  M2F       642-642 
  M2G       643-643 
  M2H       644-644 
  M2I       645-645 
  M2J       646-646 
  M2K       647-647 
  M2L       648-648 
  M2M       649-649 
  M2N       650-650 
  M3A       651-651 
  M3B       652-652 
  M3C       653-653 
  M3D       654-654 
  M3E       655-655 
  M3F       656-656 
  M3G       657-657 
  M3H       658-658 
  M3I       659-659 
  M3J       660-660 
  M3K       661-661 
  M3L       662-662 
  M3M       663-663 
  M3N       664-664 
  M4        665-666 
  M5        667-668 
  M6        669-670 
  M7        671-672 
  M8        673-674 
  M9        675-676 
  M10       677-677 
  M11       678-680 
  M13       681-682 
  M14       683-684 
  M15       685-686 
  M17       687-687 
  M18       688-688 
  M19       689-692 
  M19A      693-693 
  M21       694-695 
  M27       696-696 
  M28       697-697 
  M29       698-698 
  M30       699-699 
  M31       700-700 
  M32       701-701 
  M33       702-702 
  M34       703-705 
  M35       706-707 
  M36       708-709 
  M37A      710-710 
  M37B      711-711 
  M37C      712-712 
  M37D      713-713 
  M37E      714-714 
  M37F      715-715 
  M37G      716-716 
  M37H      717-717 
  M37I      718-718 
  M37J      719-719 
  M37K      720-720 
  M37L      721-721 
  M37M      722-722 
  M37N      723-723 
  M37O      724-724 
  M37P      725-725 
  M37Q      726-726 
  M37R      727-727 
  M37S      728-728 
  M37T      729-729 
  M38       730-730 
  M39       731-731 
  M40A      732-732 
  M40B      733-733 
  M40C      734-734 
  M40D      735-735 
  M40E      736-736 
  M40F      737-737 
  M40G      738-738 
  M40H      739-739 
  M40I      740-740 
  M40J      741-741 
  M40K      742-742 
  M40L      743-743 
  M40M      744-744 
  M40N      745-745 
  M40O      746-746 
  HIDX      747-747 
  H1        748-748 
  H2        749-749 
  H2D       750-751 
  H2M       752-753 
  H2Y       754-755 
  H3        756-756 
  H3D       757-758 
  H3M       759-760 
  H3Y       761-762 
  H4        763-763 
  H4D       764-765 
  H4M       766-767 
  H4Y       768-769 
  H5        770-770 
  H5D       771-772 
  H5M       773-774 
  H5Y       775-776 
  H6        777-777 
  H6D       778-779 
  H6M       780-781 
  H6Y       782-783 
  H7        784-784 
  H7D       785-786 
  H7M       787-788 
  H7Y       789-790 
  H8        791-791 
  H8D       792-793 
  H8M       794-795 
  H8Y       796-797 
  H9        798-798 
  H9D       799-800 
  H9M       801-802 
  H9Y       803-804 
  H0        805-805 
  H0D       806-807 
  H0M       808-809 
  H0Y       810-811 
  H10       812-812 
  H11       813-813 
  H11B      814-814 
  H11C      815-816 
  H12A      817-817 
  H12B      818-818 
  H12C      819-819 
  H12D      820-820 
  H12E      821-821 
  H12F      822-822 
  H12G      823-823 
  H12H      824-824 
  H12I      825-825 
  H12J      826-826 
  H12K      827-827 
  H12L      828-828 
  H12M      829-829 
  H12N      830-830 
  H12O      831-831 
  H12P      832-832 
  H12Q      833-833 
  H12R      834-834 
  H12S      835-835 
  H12T      836-836 
  H12U      837-837 
  H12V      838-838 
  H12W      839-839 
  H12X      840-840 
  H12Y      841-841 
  H12Z      842-842 
  H13       843-843 
  H14       844-844 
  H15       845-845 
  H15A      846-846 
  H15B      847-847 
  H15C      848-848 
  H15D      849-849 
  H15E      850-850 
  H15F      851-851 
  H15G      852-852 
  H15H      853-853 
  H16       854-854 
  H18       855-855 
  H20       856-856 
  H21A      857-857 
  H21       858-858 
  H22       859-859 
  H31       860-860 
  H31B      861-861 
  H32A      862-862 
  H32B      863-863 
  H32C      864-864 
  H32D      865-865 
  H32E      866-866 
  H32F      867-867 
  H32G      868-868 
  H32H      869-869 
  H32I      870-870 
  H32J      871-871 
  H32K      872-872 
  H32L      873-873 
  H32M      874-874 
  H32N      875-875 
  H32O      876-876 
  H32P      877-877 
  H32Q      878-878 
  H32R      879-879 
  H32S      880-880 
  H32T      881-881 
  H32U      882-882 
  H32V      883-883 
  H32W      884-884 
  H32X      885-885 
  H32Y      886-886 
  H32Z      887-887 
  HWIDX     888-888 
  HW1       889-890 
  HW2       891-893 
  HW3       894-897 
  HW4       898-901 
  HW5       902-905 
  HW6       906-910 
  HW7       911-914 
  HW8       915-918 
  HW9       919-923 
  HW10      924-927 
  HW11      928-931 
  HW12      932-936 
  HW13      937-937 
  HW14      938-938 
  HW15      939-939 
  HW16      940-941 
  HW17      942-943 
  HW18      944-945 
  HW19      946-947 
  HW20      948-950 
  HW21      951-954 
  HW22      955-958 
  HW23      959-963 
  HW24      964-967 
  HW25      968-971 
  HW26      972-976 
  SDFORMAT  977-977 
  SADJUST   978-978 
  SINTM     979-980 
  SINTY     981-982 
  SDIV      983-983 
  SDISTR    984-985 
  S114A     986-986 
  S114B     987-987 
  S114C     988-988 
  S114D     989-989 
  S114E     990-990 
  S119      991-993 
  S119A     994-996 
  S123      997-998 
  S124A     999-999 
  S124B    1000-1000
  S124C    1001-1001
  S124D    1002-1002
  S124I    1003-1003
  S229M    1004-1005
  S229Y    1006-1009
  S233A    1010-1010
  S233B    1011-1011
  S233C    1012-1012
  S233DM   1013-1014
  S233DY   1015-1018
 .
VARIABLE LABELS
  CASEID   "Case Identification"
 /BIDX     "Birth column number"
 /V000     "Country code and phase"
 /V001     "Cluster number"
 /V002     "Household number"
 /V003     "Respondent's line number"
 /V004     "Ultimate area unit"
 /V005     "Sample weight"
 /V006     "Month of interview"
 /V007     "Year of interview"
 /V008     "Date of interview (CMC)"
 /V009     "Respondent's month of birth"
 /V010     "Respondent's year of birth"
 /V011     "Date of birth (CMC)"
 /V012     "Current age - respondent"
 /V013     "Age 5-year groups"
 /V014     "Completeness of information"
 /V015     "Result of individual interview"
 /V016     "Day of interview"
 /V017     "CMC start of calendar"
 /V018     "Row of month of interview"
 /V019     "Length of calendar"
 /V020     "Ever-married sample"
 /V021     "Primary sampling unit"
 /V022     "Sample stratum number"
 /V023     "Sample domain"
 /V024     "Region"
 /V025     "Type of place of residence"
 /V026     "De facto place of residence"
 /V027     "Number of visits"
 /V028     "Interviewer identification"
 /V029     "Keyer identification"
 /V030     "Field supervisor -NA"
 /V031     "Field editor -NA"
 /V032     "Office editor -NA"
 /V033     "Ultimate area selection prob."
 /V034     "Line number of husband"
 /V101     "Region"
 /V102     "Type of place of residence"
 /V103     "Childhood place of residen -NA"
 /V104     "Years lived in place of res."
 /V105     "Type of place of previous res."
 /V106     "Highest educational level"
 /V107     "Highest year of education"
 /V108     "Literacy"
 /V109     "Reads newspaper once a week"
 /V110     "Watches TV every week"
 /V111     "Listens to radio every day -NA"
 /V112     "Listens to radio every week"
 /V113     "Source of drinking water"
 /V114     "Source of non-drinking water"
 /V115     "Time to get to water source"
 /V116     "Type of toilet facility"
 /V119     "Has electricity"
 /V120     "Has radio"
 /V121     "Has television"
 /V122     "Has refrigerator -NA"
 /V123     "Has bicycle"
 /V124     "Has motorcycle -NA"
 /V125     "Has car -NA"
 /V127     "Main floor material"
 /V128     "Main wall material"
 /V129     "Main roof material"
 /V130     "Religion"
 /V131     "Ethnicity -NA"
 /V133     "Education in single years"
 /V134     "De facto place of residence"
 /V135     "Usual resident or visitor"
 /V136     "Number of household members"
 /V137     "Number of children 5 and under"
 /V138     "Number of eligible women in HH"
 /V139     "De jure region of residence"
 /V140     "De jure type of place of res."
 /V141     "De jure place of residence"
 /V142     "Same source of water"
 /V144     "Communities lived in >Jan.8-NA"
 /V148     "Respondent still in school"
 /V149     "Educational attainment"
 /V150     "Relationship to household head"
 /V151     "Sex of household head"
 /V152     "Age of household head"
 /V153     "Has telephone -NA"
 /V154     "Reason stop attending schoo-NA"
 /AWFACTT  "All woman factor - total"
 /AWFACTU  "All woman factor - urban/rural"
 /AWFACTR  "All woman factor - regional"
 /AWFACTE  "All woman factor - educational"
 /V201     "Total children ever born"
 /V202     "Sons at home"
 /V203     "Daughters at home"
 /V204     "Sons elsewhere"
 /V205     "Daughters elsewhere"
 /V206     "Sons who have died"
 /V207     "Daughters who have died"
 /V208     "Births in last five years"
 /V209     "Births in past year"
 /V210     "Births in month of interview"
 /V211     "Date of first birth (CMC)"
 /V212     "Age of respondent at 1st birth"
 /V213     "Currently pregnant"
 /V214     "Duration of current pregnancy"
 /V215     "Time since last menstrual perd"
 /V216     "Menstruated in last six weeks"
 /V217     "Knowledge of ovulatory cycl-NA"
 /V218     "Number of living children"
 /V219     "Living children + current preg"
 /V220     "Living children + curr preg 6+"
 /V221     "Marriage to first birth int."
 /V222     "Last birth to interview"
 /V223     "Completeness of curr preg. inf"
 /V224     "Entries in birth history"
 /V225     "Current pregnancy wanted"
 /V226     "Time since last period (comp)"
 /V227     "Flag for last period"
 /V228     "Ever had a terminated preg."
 /V229     "Month pregnancy ended"
 /V230     "Year pregnancy ended"
 /V231     "CMC pregnancy ended"
 /V232     "Completeness of last term. inf"
 /V233     "Months when pregnancy ended"
 /V234     "Other such pregnancies"
 /V235     "Index last child prior to cal."
 /V236     "Last birth interval >= 4 ye-NA"
 /V237     "Birth between last & interv-NA"
 /V238     "Births in last three years"
 /V310     "Living children at first use"
 /V311     "Children at first use (grpd)"
 /V312     "Current contraceptive method"
 /V313     "Current use by method type"
 /V314     "Method of periodic abstinen-NA"
 /V315     "Month of sterilization"
 /V316     "Year of sterilization"
 /V317     "Date of sterilization (CMC)"
 /V318     "Completeness of information"
 /V319     "Years since sterilization"
 /V320     "Age at sterilization"
 /V321     "Marital duration at steriliz."
 /V322     "Parity at sterilization"
 /V323     "Brand of pill used"
 /V325     "Cost of pills"
 /V326     "Last source for current users"
 /V327     "Last source for users by type"
 /V328     "Main reason use current sou-NA"
 /V337     "Months of use of current meth"
 /V359     "Last method disc. last 5 years"
 /V360     "Reason of last discontinuation"
 /V361     "Pattern of use"
 /V362     "Intention to use"
 /V363     "Preferred future method"
 /V364     "Contraceptive use & intention"
 /V366A    "Acceptability of radio message"
 /V366B    "Acceptability of TV message-NA"
 /V367     "Wanted last child"
 /V369     "First method used"
 /V369B    "First use to space or limit-NA"
 /V372     "Shown pill package"
 /V375A    "Main reason not using a method"
 /V376     "Main reason not to use a meth."
 /V376A    "Would ever use method if ma-NA"
 /V379     "Source known for any method"
 /V380     "Source known for any method"
 /V384A    "Heard FP on radio last months"
 /V384B    "Heard FP on TV last months"
 /V384C    "Heard FP newspaper last mon-NA"
 /V384D    "Heard FP on poster last months"
 /V384E    "Heard FP brochures last mon-NA"
 /V393     "Visited by FP worker last 6m"
 /V394     "Visited health facil. last 12m"
 /V395     "At health facility, told of FP"
 /V396     "Breastfeeding affect pregnancy"
 /V397     "Pregnancy risk of breastfee-NA"
 /V398     "Relied breastfeed. avoid pr-NA"
 /V399     "Currently rely on breastfee-NA"
 /V401     "Last birth ceasarean sectio-NA"
 /V404     "Currently breastfeeding"
 /V405     "Currently amenorrheic"
 /V406     "Currently abstaining"
 /V407     "Times breastfed during night"
 /V408     "Times breastfed during day"
 /V409     "Gave child plain water"
 /V409A    "Gave child sugar water"
 /V410     "Gave child juice"
 /V410A    "Gave child herbal tea"
 /V411     "Gave child powder/tinned mi-NA"
 /V411A    "Gave child baby formula"
 /V412     "Gave child fresh milk"
 /V413A    "Country specific other liqu-NA"
 /V413B    "Country specific other liqu-NA"
 /V413C    "Country specific other liqu-NA"
 /V413D    "Country specific other liqu-NA"
 /V413     "Gave child other liquid"
 /V414A    "Country specific other food-NA"
 /V414B    "Country specific other food-NA"
 /V414C    "Country specific other food-NA"
 /V414D    "Other solid, semi-solid foods"
 /V414E    "Food made from local grain -NA"
 /V414F    "Food made from local tuber -NA"
 /V414G    "Gave child eggs, fish, poul-NA"
 /V414H    "Gave child meat"
 /V415     "Drank from bottle with nipp-NA"
 /V416     "Heard of oral rehydration"
 /V417     "Entries in maternity table"
 /V418     "Entries in health table"
 /V419     "Entries in height/weight ta-NA"
 /V420     "Measurer's code -NA"
 /V421     "Assistant measurer's code -NA"
 /V426     "When child put to breast"
 /V436     "Arm circumference (cms-1d) -NA"
 /V437     "Respondent's weight (kilos--NA"
 /V438     "Respondent's height (cms-1d-NA"
 /V439     "Ht/A Percentile (resp.) -NA"
 /V440     "Ht/A Standard deviations (r-NA"
 /V441     "Ht/A Percent ref. median (r-NA"
 /V442     "Wt/Ht Percent ref. median (-NA"
 /V443     "Wt/Ht Percent ref. median (-NA"
 /V444     "Wt/Ht Percent ref. median (-NA"
 /V444A    "Wt/Ht Std deviations(resp) -NA"
 /V445     "Body mass index for respond-NA"
 /V446     "Rohrer's index for responde-NA"
 /V447     "Result of measurement of re-NA"
 /V448     "Drinking pattern with diarr-NA"
 /V449     "Eating pattern with diarrhe-NA"
 /V450A    "Diarrhea: repeat watery sto-NA"
 /V450B    "Diarrhea: Any watery stools-NA"
 /V450C    "Diarrhea: Repeated vomiting-NA"
 /V450D    "Diarrhea: Any vomiting -NA"
 /V450E    "Diarrhea: Blood in stools -NA"
 /V450F    "Diarrhea: Fever -NA"
 /V450G    "Diarrhea: Marked thirst -NA"
 /V450H    "Diarrhea: Not eating/drinki-NA"
 /V450I    "Diarrhea: Getting sicker -NA"
 /V450J    "Diarrhea: Not getting bette-NA"
 /V450K    "Diarrhea: Country specific -NA"
 /V450L    "Diarrhea: Country specific -NA"
 /V450M    "Diarrhea: Country specific -NA"
 /V450X    "Diarrhea: Other responses -NA"
 /V450Z    "Diarrhea: Does not know -NA"
 /V451A    "Cough: Fast breathing -NA"
 /V451B    "Cough: Difficult breathing -NA"
 /V451C    "Cough: Noisy breathing -NA"
 /V451D    "Cough: Fever -NA"
 /V451E    "Cough: Unable to drink -NA"
 /V451F    "Cough: Not eating/drinking -NA"
 /V451G    "Cough: Getting sicker -NA"
 /V451H    "Cough: Not getting better -NA"
 /V451I    "Cough: Country specific -NA"
 /V451J    "Cough: Country specific -NA"
 /V451K    "Cough: Country specific -NA"
 /V451X    "Cough: Other responses -NA"
 /V451Z    "Knows no sign of illness -NA"
 /V501     "Current marital status"
 /V502     "Currently/formerly/never marr."
 /V503     "Number of unions"
 /V504     "Husband lives in house"
 /V505     "Number of other wives - NA"
 /V506     "Wife rank number - NA"
 /V507     "Month of first marriage"
 /V508     "Year of first marriage"
 /V509     "Date of first marriage (CMC)"
 /V510     "Completeness of date inform."
 /V511     "Age at first marriage"
 /V512     "Years since first marriage"
 /V513     "Marital duration (grouped)"
 /V525     "Age at first intercourse - NA"
 /V527     "Time since last intercourse"
 /V528     "Time since last intercourse(g)"
 /V529     "Time since last intercourse(im"
 /V530     "Flag for V529"
 /V531     "Age at first intercourse - NA"
 /V532     "Flag for V531 -NA"
 /V534     "Have a regular sex partne - NA"
 /V535     "Have ever been married"
 /V602     "Fertility preference"
 /V603     "Preferred waiting time"
 /V604     "Preferred waiting time (grpd)"
 /V605     "Desire for more children"
 /V606     "Attitude toward becoming preg."
 /V610     "Husband approves FP"
 /V611     "Discussed FP with partner"
 /V612     "Respondent approves FP"
 /V613     "Ideal number of children"
 /V614     "Ideal number of children (grp)"
 /V616     "Time for future birth"
 /V618     "Reason regrets sterilization"
 /V621     "Husbands desire for children"
 /V623     "Exposure"
 /V624     "Unmet need"
 /V625     "Exposure (definition 2)"
 /V626     "Unmet need (definition 2)"
 /V627     "Ideal number of boys"
 /V628     "Ideal number of girls"
 /V629     "Ideal number of either sex"
 /V630A    "Discussed FP with partner - NA"
 /V630B    "Discussed FP with mother - NA"
 /V630C    "Discussed FP with father - NA"
 /V630D    "Discussed FP with sister( - NA"
 /V630E    "Discussed FP with brother - NA"
 /V630F    "Discussed FP with daughte - NA"
 /V630G    "Discussed FP with mother- - NA"
 /V630H    "Discussed FP with friends - NA"
 /V630I    "Discussed FP -country spe - NA"
 /V630J    "Discussed FP -country spe - NA"
 /V630K    "Discussed FP -country spe - NA"
 /V630L    "Discussed FP -country spe - NA"
 /V630X    "Discussed FP with others - NA"
 /V701     "Partner's education level"
 /V702     "Highest year of education"
 /V704     "Partner's occupation"
 /V705     "Partner's occupation"
 /V707     "Type of land where works"
 /V714     "Respondent currently working"
 /V715     "Husbands education-single yrs"
 /V716     "Respondent's occupation"
 /V717     "Respondent's occupation"
 /V718     "Current type of employment"
 /V719     "Work for family, others, self"
 /V720     "Earns cash for work"
 /V721     "Works at home or away"
 /V723     "Child minder"
 /V729     "Partner's educational attainm."
 /V730     "Partners age -NA"
 /V731     "Worked in last 12 months - NA"
 /V732     "Employment all year/seasonal"
 /V733     "Months worked in last 12 - NA"
 /V734     "Days in a week normally w - NA"
 /V735     "Days worked in last 12 mo - NA"
 /V736     "Earnings for work - NA"
 /V737     "Daily earnings for work - NA"
 /V738     "Yearly earnings for work - NA"
 /V739     "Who decides how to spend money"
 /V740     "Type of land where resp. works"
 /BORD     "Birth order number"
 /B0       "Child is twin"
 /B1       "Month of birth"
 /B2       "Year of birth"
 /B3       "Date of birth (CMC)"
 /B4       "Sex of child"
 /B5       "Child is alive"
 /B6       "Age at death"
 /B7       "Age at death (months-imputed)"
 /B8       "Current age of child"
 /B9       "Who child lives with"
 /B10      "Completeness of information"
 /B11      "Preceding birth interval"
 /B12      "Succeeding birth interval"
 /B13      "Flag for age at death"
 /B14      "Birth interval >= 4 years -NA"
 /B15      "Live birth between births -NA"
 /MIDX     "Index to birth history"
 /M1       "Tetanus injections bef. birth"
 /M2A      "Prenatal: doctor"
 /M2B      "Prenatal: nurse/midwife"
 /M2C      "Prenatal: auxiliary midwife-NA"
 /M2D      "Prenatal: Family Welf.Visitor"
 /M2E      "Prenatal: CS health profess-NA"
 /M2F      "Prenatal: trained birth att."
 /M2G      "Prenatal: trad.birth attendant"
 /M2H      "Prenatal: relative -NA"
 /M2I      "Prenatal: CS other person -NA"
 /M2J      "Prenatal: CS other person -NA"
 /M2K      "Prenatal: other resp (uncoded)"
 /M2L      "Prenatal: CS other -NA"
 /M2M      "Prenatal: CS other -NA"
 /M2N      "Prenatal: no one"
 /M3A      "Assistance: doctor"
 /M3B      "Assistance: nurse/midwife"
 /M3C      "Delivery: auxiliary midwife-NA"
 /M3D      "Delivery: Family Welf.Visitor"
 /M3E      "Assistance: CS health profe-NA"
 /M3F      "Assistance: trained birth att."
 /M3G      "Assistance: trad.birth attend."
 /M3H      "Assistance: relative, friend"
 /M3I      "Assistance: CS other person-NA"
 /M3J      "Assistance: CS other person-NA"
 /M3K      "Assistance: other resp (uncod)"
 /M3L      "Assistance: CS other -NA"
 /M3M      "Assistance: CS other"
 /M3N      "Assistance: no one"
 /M4       "Duration of breastfeeding"
 /M5       "Months of breastfeeding"
 /M6       "Duration of amenorrhea"
 /M7       "Months of amenorrhea"
 /M8       "Duration of abstinence"
 /M9       "Months of abstinence"
 /M10      "Time wanted pregnancy"
 /M11      "Time would have waited -NA"
 /M13      "Timing of 1st antenatal check"
 /M14      "Antenatal visits for pregnancy"
 /M15      "Place of delivery"
 /M17      "Delivery by caesarian secti-NA"
 /M18      "Size of child at birth -NA"
 /M19      "Birth weight (kilos - 3 dec-NA"
 /M19A     "Weight at birth recall -NA"
 /M21      "Reason stopped breastfeeding"
 /M27      "Flag for breastfeeding"
 /M28      "Flag for amenorrhea"
 /M29      "Flag for abstinence"
 /M30      "At birth - prolonged labor -NA"
 /M31      "At birth - excessive bleedi-NA"
 /M32      "At birth - high fever/disch-NA"
 /M33      "At birth - convulsions -NA"
 /M34      "When child put to breast"
 /M35      "Times breastfed during night"
 /M36      "Times breastfed during day"
 /M37A     "Gave child plain water"
 /M37B     "Gave child sugar water"
 /M37C     "Gave child juice"
 /M37D     "Gave child herbal tea"
 /M37E     "Gave child powder/tinned mi-NA"
 /M37F     "Gave child baby formula"
 /M37G     "Gave child fresh milk"
 /M37H     "Country specific other liqu-NA"
 /M37I     "Country specific other liqu-NA"
 /M37J     "Country specific other liqu-NA"
 /M37K     "Country specific other liqu-NA"
 /M37L     "Gave child other liquid"
 /M37M     "Country specific other food-NA"
 /M37N     "Country specific other food-NA"
 /M37O     "Country specific other food-NA"
 /M37P     "Other solid, semi-solid foods"
 /M37Q     "Food made from local grain -NA"
 /M37R     "Food made from local tuber -NA"
 /M37S     "Gave child eggs, fish, poul-NA"
 /M37T     "Gave child meat"
 /M38      "Drank from bottle with nipp-NA"
 /M39      "Times ate other food yester-NA"
 /M40A     "Last 7 days - plain water -NA"
 /M40B     "Last 7 days - milk -NA"
 /M40C     "Last 7 days - other liquids-NA"
 /M40D     "Last 7 days - local grain f-NA"
 /M40E     "Last 7 days - local tuber f-NA"
 /M40F     "Last 7 days - egg/fish/poul-NA"
 /M40G     "Last 7 days - meat -NA"
 /M40H     "Last 7 days - other solid f-NA"
 /M40I     "Last 7 days - country speci-NA"
 /M40J     "Last 7 days - country speci-NA"
 /M40K     "Last 7 days - country speci-NA"
 /M40L     "Last 7 days - country speci-NA"
 /M40M     "Last 7 days - country speci-NA"
 /M40N     "Last 7 days - country speci-NA"
 /M40O     "Last 7 days - country speci-NA"
 /HIDX     "Index to birth history"
 /H1       "Has health card"
 /H2       "Received BCG"
 /H2D      "BCG day"
 /H2M      "BCG month"
 /H2Y      "BCG year"
 /H3       "Received DPT 1"
 /H3D      "DPT 1 day"
 /H3M      "DPT 1 month"
 /H3Y      "DPT 1 year"
 /H4       "Received POLIO 1"
 /H4D      "POLIO 1 day"
 /H4M      "POLIO 1 month"
 /H4Y      "POLIO 1 year"
 /H5       "Received DPT 2"
 /H5D      "DPT 2 day"
 /H5M      "DPT 2 month"
 /H5Y      "DPT 2 year"
 /H6       "Received POLIO 2"
 /H6D      "POLIO 2 day"
 /H6M      "POLIO 2 month"
 /H6Y      "POLIO 2 year"
 /H7       "Received DPT 3"
 /H7D      "DPT 3 day"
 /H7M      "DPT 3 month"
 /H7Y      "DPT 3 year"
 /H8       "Received POLIO 3"
 /H8D      "POLIO 3 day"
 /H8M      "POLIO 3 month"
 /H8Y      "POLIO 3 year"
 /H9       "Received MEASLES"
 /H9D      "MEASLES day"
 /H9M      "MEASLES month"
 /H9Y      "MEASLES year"
 /H0       "Polio 0 -NA"
 /H0D      "Polio 0 day"
 /H0M      "POLIO 0 month"
 /H0Y      "POLIO 0 year"
 /H10      "Ever had vaccination"
 /H11      "Had diarrhea recently"
 /H11B     "Blood in the stools"
 /H11C     "Bowel movements in worst da-NA"
 /H12A     "Diarrhea: government hosp."
 /H12B     "Diarrhea: govt health center"
 /H12C     "Diarrhea: govt health post -NA"
 /H12D     "Diarrhea: mobile clinic -NA"
 /H12E     "Diarrhea: comm.health worker"
 /H12F     "Diarrhea: Satellite clinic -CS"
 /H12G     "Diarrhea: CS public sector -NA"
 /H12H     "Diarrhea: CS public sector -NA"
 /H12I     "Diarrhea: CS public sector -NA"
 /H12J     "Diarrhea: private hosp/clinic"
 /H12K     "Diarrhea: private pharmacy"
 /H12L     "Diarrhea: private doctor"
 /H12M     "Diarrhea: private mobile cl-NA"
 /H12N     "Diarrhea: comm.health worke-NA"
 /H12O     "Diarrhea: CS med.priv secto-NA"
 /H12P     "Diarrhea: CS med.priv secto-NA"
 /H12Q     "Diarrhea: CS med.priv secto-NA"
 /H12R     "Diarrhea: CS med.priv secto-NA"
 /H12S     "Diarrhea: shop"
 /H12T     "Diarrhea: traditional pract."
 /H12U     "Diarrhea: CS oth.priv secto-NA"
 /H12V     "Diarrhea: CS oth.priv secto-NA"
 /H12W     "Diarrhea: CS oth.priv secto-NA"
 /H12X     "Diarrhea: Other"
 /H12Y     "Diarrhea: no treatment"
 /H12Z     "Diarrhea: medical treatment"
 /H13      "Given oral rehydration"
 /H14      "Given recommend. home solution"
 /H15      "Given other pills or syrups"
 /H15A     "Given antibiotics (CS) -NA"
 /H15B     "Given an injection"
 /H15C     "Given an intravenous (IV)"
 /H15D     "Given home remedy, herbal med."
 /H15E     "Given CS other treatment -NA"
 /H15F     "Given CS other treatment -NA"
 /H15G     "Given CS other treatment -NA"
 /H15H     "Given CS other treatment -NA"
 /H16      "Increase or decrease fluids"
 /H18      "Increase or decrease in foo-NA"
 /H20      "Given other treatment"
 /H21A     "Given no treatment"
 /H21      "Received any treatment"
 /H22      "Had fever in last two weeks-NA"
 /H31      "Had cough in last two weeks"
 /H31B     "Short, rapid breaths"
 /H32A     "Fever/cough: government hosp."
 /H32B     "Fever/cough: govt health cntr"
 /H32C     "Fever/cough: govt health po-NA"
 /H32D     "Fever/cough: mobile clinic -NA"
 /H32E     "Fever/cough: comm.health wrkr"
 /H32F     "Fever/cough: Satellite clinic"
 /H32G     "Fever/cough: CS public sect-NA"
 /H32H     "Fever/cough: CS public sect-NA"
 /H32I     "Fever/cough: CS public sect-NA"
 /H32J     "Fever/cough: private hosp/clin"
 /H32K     "Fever/cough: private pharmacy"
 /H32L     "Fever/cough: private doctor"
 /H32M     "Fever/cough: private mobile-NA"
 /H32N     "Fever/cough: comm.health wr-NA"
 /H32O     "Fever/cough: CS med.priv se-NA"
 /H32P     "Fever/cough: CS med.priv se-NA"
 /H32Q     "Fever/cough: CS med.priv se-NA"
 /H32R     "Fever/cough: CS med.priv se-NA"
 /H32S     "Fever/cough: shop"
 /H32T     "Fever/cough: traditional pract"
 /H32U     "Fever/cough: CS oth.priv se-NA"
 /H32V     "Fever/cough: CS oth.priv se-NA"
 /H32W     "Fever/cough: CS oth.priv se-NA"
 /H32X     "Fever/cough: Other"
 /H32Y     "Fever/cough: no treatment"
 /H32Z     "Fever/cough: medical treatment"
 /HWIDX    "Index to birth history - NA"
 /HW1      "Age in months - NA"
 /HW2      "Weight in kilograms (1 de - NA"
 /HW3      "Height in centimeters (1 - NA"
 /HW4      "Ht/A Percentile - NA"
 /HW5      "Ht/A Standard deviations - NA"
 /HW6      "Ht/A Percent of ref. medi - NA"
 /HW7      "Wt/A Percentile - NA"
 /HW8      "Wt/A Standard deviations - NA"
 /HW9      "Wt/A Percent of ref. medi - NA"
 /HW10     "Wt/Ht Percentile - NA"
 /HW11     "Wt/Ht Standard deviations - NA"
 /HW12     "Wt/Ht Percent of ref. med - NA"
 /HW13     "Reason not measured"
 /HW14     "BCG scar on arm or should - NA"
 /HW15     "Height: lying or standing - NA"
 /HW16     "Day of birth of child - NA"
 /HW17     "Date measured (day) - NA"
 /HW18     "Date measured (month) - NA"
 /HW19     "Date measured (year) - NA"
 /HW20     "Arm circumference (cms - - NA"
 /HW21     "Arm circ/A Percentile - NA"
 /HW22     "Arm circ/A Standard devia - NA"
 /HW23     "Arm c/A Percent of ref. m - NA"
 /HW24     "Arm circ/Ht Percentile - NA"
 /HW25     "Arm cir/Ht Standard devia - NA"
 /HW26     "Arm cir/Ht Percent ref. m - NA"
 /SDFORMAT "Date format of questionnaire"
 /SADJUST  "Month of interview adjusted 1m"
 /SINTM    "Month of interview(unadjusted)"
 /SINTY    "Year of interview(unadjusted)"
 /SDIV     "Division"
 /SDISTR   "District of residence"
 /S114A    "Grameen Bank"
 /S114B    "BRAC"
 /S114C    "BRDP"
 /S114D    "Mothers club"
 /S114E    "Other"
 /S119     "Time to get to water (mins)"
 /S119A    "Time to wait to get water:mins"
 /S123     "Toilet facility : children"
 /S124A    "Almirah"
 /S124B    "Table/chair/bench"
 /S124C    "Watch/clock"
 /S124D    "Cot/bed"
 /S124I    "Agricultural land"
 /S229M    "Month pregnancy ended"
 /S229Y    "Year pregnancy ended"
 /S233A    "Ever had unwanted pregnancy"
 /S233B    "Pregancy aborted/menst.reg'ltn"
 /S233C    "Pregnancy ended by MR/D&C"
 /S233DM   "When pr. ended : Month"
 /S233DY   "When pregnancy ended :Year"
 .
MISSING VALUE
  V015     (9)
 /V026     (9)
 /V028     (999)
 /V029     (99)
 /V030     (99)
 /V031     (99)
 /V032     (99)
 /V034     (99)
 /V103     (9)
 /V104     (99)
 /V105     (9)
 /V106     (9)
 /V107     (99)
 /V108     (9)
 /V109     (9)
 /V110     (9)
 /V111     (9)
 /V112     (9)
 /V113     (99)
 /V114     (99)
 /V115     (999)
 /V116     (99)
 /V119     (9)
 /V120     (9)
 /V121     (9)
 /V122     (9)
 /V123     (9)
 /V124     (9)
 /V125     (9)
 /V127     (99)
 /V128     (99)
 /V129     (99)
 /V130     (9)
 /V131     (99)
 /V133     (99)
 /V134     (9)
 /V135     (9)
 /V139     (99)
 /V140     (9)
 /V141     (9)
 /V142     (9)
 /V144     (9)
 /V148     (9)
 /V149     (9)
 /V150     (99)
 /V152     (99)
 /V153     (9)
 /V154     (99)
 /V215     (999)
 /V225     (9)
 /V226     (999)
 /V228     (9)
 /V229     (99)
 /V230     (99)
 /V231     (9999)
 /V233     (99)
 /V234     (9)
 /V310     (99)
 /V311     (9)
 /V312     (99)
 /V313     (9)
 /V314     (9)
 /V323     (99)
 /V325     (999999)
 /V326     (99)
 /V327     (9)
 /V328     (99)
 /V337     (999)
 /V359     (99)
 /V360     (99)
 /V362     (9)
 /V363     (99)
 /V366A    (9)
 /V367     (9)
 /V369     (99)
 /V372     (9)
 /V375A    (99)
 /V376     (99)
 /V376A    (9)
 /V379     (99)
 /V380     (9)
 /V384A    (9)
 /V384B    (9)
 /V384D    (9)
 /V393     (9)
 /V394     (9)
 /V395     (9)
 /V396     (9)
 /V399     (9)
 /V401     (9)
 /V407     (99)
 /V408     (99)
 /V409     (9)
 /V409A    (9)
 /V410     (9)
 /V410A    (9)
 /V411     (9)
 /V411A    (9)
 /V412     (9)
 /V413A    (9)
 /V413B    (9)
 /V413C    (9)
 /V413D    (9)
 /V413     (9)
 /V414A    (9)
 /V414B    (9)
 /V414C    (9)
 /V414D    (9)
 /V414E    (9)
 /V414F    (9)
 /V414G    (9)
 /V414H    (9)
 /V416     (9)
 /V426     (999)
 /V450B    (9)
 /V450E    (9)
 /V450F    (9)
 /V450G    (9)
 /V501     (9)
 /V502     (9)
 /V503     (9)
 /V504     (9)
 /V527     (999)
 /V528     (99)
 /V529     (999)
 /V535     (9)
 /V602     (9)
 /V603     (999)
 /V604     (9)
 /V605     (9)
 /V606     (9)
 /V610     (9)
 /V611     (9)
 /V612     (9)
 /V613     (99)
 /V616     (999)
 /V618     (9)
 /V621     (9)
 /V623     (9)
 /V624     (99)
 /V625     (9)
 /V626     (99)
 /V627     (99)
 /V628     (99)
 /V629     (99)
 /V701     (9)
 /V702     (99)
 /V704     (999)
 /V705     (99)
 /V707     (9)
 /V714     (9)
 /V715     (99)
 /V716     (999)
 /V717     (99)
 /V718     (9)
 /V719     (9)
 /V720     (9)
 /V721     (9)
 /V723     (99)
 /V729     (9)
 /V730     (99)
 /V732     (9)
 /V739     (9)
 /V740     (9)
 /B6       (999)
 /B9       (9)
 /B14      (9)
 /B15      (9)
 /M1       (9)
 /M2A      (9)
 /M2B      (9)
 /M2C      (9)
 /M2D      (9)
 /M2E      (9)
 /M2F      (9)
 /M2G      (9)
 /M2H      (9)
 /M2I      (9)
 /M2J      (9)
 /M2K      (9)
 /M2N      (9)
 /M3A      (9)
 /M3B      (9)
 /M3D      (9)
 /M3F      (9)
 /M3G      (9)
 /M3H      (9)
 /M3K      (9)
 /M3M      (9)
 /M3N      (9)
 /M4       (99)
 /M5       (99)
 /M6       (99)
 /M7       (99)
 /M8       (99)
 /M9       (99)
 /M10      (9)
 /M13      (99)
 /M14      (99)
 /M15      (99)
 /M21      (99)
 /M34      (999)
 /M35      (99)
 /M36      (99)
 /M37A     (9)
 /M37B     (9)
 /M37C     (9)
 /M37D     (9)
 /M37E     (9)
 /M37F     (9)
 /M37G     (9)
 /M37H     (9)
 /M37I     (9)
 /M37J     (9)
 /M37K     (9)
 /M37L     (9)
 /M37P     (9)
 /M37R     (9)
 /M37T     (9)
 /M39      (9)
 /M40L     (9)
 /H1       (9)
 /H2       (9)
 /H2D      (99)
 /H2M      (99)
 /H2Y      (99)
 /H3       (9)
 /H3D      (99)
 /H3M      (99)
 /H3Y      (99)
 /H4       (9)
 /H4D      (99)
 /H4M      (99)
 /H4Y      (99)
 /H5       (9)
 /H5D      (99)
 /H5M      (99)
 /H5Y      (99)
 /H6       (9)
 /H6D      (99)
 /H6M      (99)
 /H6Y      (99)
 /H7       (9)
 /H7D      (99)
 /H7M      (99)
 /H7Y      (99)
 /H8       (9)
 /H8D      (99)
 /H8M      (99)
 /H8Y      (99)
 /H9       (9)
 /H9D      (99)
 /H9M      (99)
 /H9Y      (99)
 /H0D      (99)
 /H0M      (99)
 /H0Y      (99)
 /H10      (9)
 /H11      (9)
 /H11B     (9)
 /H12A     (9)
 /H12B     (9)
 /H12D     (9)
 /H12E     (9)
 /H12F     (9)
 /H12G     (9)
 /H12J     (9)
 /H12K     (9)
 /H12L     (9)
 /H12S     (9)
 /H12T     (9)
 /H12X     (9)
 /H12Y     (9)
 /H12Z     (9)
 /H13      (9)
 /H14      (9)
 /H15      (9)
 /H15A     (9)
 /H15B     (9)
 /H15C     (9)
 /H15D     (9)
 /H15E     (9)
 /H15F     (9)
 /H16      (9)
 /H20      (9)
 /H21A     (9)
 /H21      (9)
 /H31      (9)
 /H31B     (9)
 /H32A     (9)
 /H32B     (9)
 /H32C     (9)
 /H32D     (9)
 /H32E     (9)
 /H32F     (9)
 /H32G     (9)
 /H32H     (9)
 /H32I     (9)
 /H32J     (9)
 /H32K     (9)
 /H32L     (9)
 /H32M     (9)
 /H32N     (9)
 /H32O     (9)
 /H32P     (9)
 /H32Q     (9)
 /H32R     (9)
 /H32S     (9)
 /H32T     (9)
 /H32U     (9)
 /H32V     (9)
 /H32W     (9)
 /H32X     (9)
 /H32Y     (9)
 /H32Z     (9)
 /HW13     (9)
 /S114A    (9)
 /S114B    (9)
 /S114C    (9)
 /S114D    (9)
 /S114E    (9)
 /S119     (999)
 /S119A    (999)
 /S123     (99)
 /S124A    (9)
 /S124B    (9)
 /S124C    (9)
 /S124D    (9)
 /S124I    (9)
 /S229M    (99)
 /S229Y    (9999)
 /S233A    (9)
 /S233B    (9)
 /S233C    (9)
 /S233DM   (99)
 /S233DY   (9999)
 .
VALUE LABELS
  V013    
      0 "10-14"
      1 "15-19"
      2 "20-24"
      3 "25-29"
      4 "30-34"
      5 "35-39"
      6 "40-44"
      7 "45-49"
 /V014    
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
 /V015    
      1 "Completed"
      2 "Not at home"
      3 "Postponed"
      4 "Refused"
      5 "Partly completed"
      6 "Incapacitated"
      7 "Other"
 /V018    
      0 "No calendar"
 /V019    
      0 "No calendar"
 /V020    
      0 "All woman sample"
      1 "Ever married sample"
 /V023    
      0 "National"
      1 "Country specific"
 /V024    
      1 "Barishal"
      2 "Chittagong"
      3 "Dhaka"
      4 "Khulna"
      5 "Rajshani"
 /V025    
      1 "Urban"
      2 "Rural"
 /V026    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
 /V030    
      0 ""
 /V031    
      0 ""
 /V032    
      0 ""
 /V034    
      0 "Husband not in HH"
 /V101    
      1 "Barishal"
      2 "Chittagong"
      3 "Dhaka"
      4 "Khulna"
      5 "Rajshani"
 /V102    
      1 "Urban"
      2 "Rural"
 /V103    
      0 ""
 /V104    
     95 "Always"
     96 "Visitor"
     97 "Inconsistent"
     98 "Don't know"
 /V105    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
 /V106    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
 /V108    
      1 "Reads easily"
      2 "Reads with difficult"
      3 "Cannot read"
 /V109    
      0 "No"
      1 "Yes"
 /V110    
      0 "No"
      1 "Yes"
 /V111    
      0 ""
 /V112    
      0 "No"
      1 "Yes"
 /V113    
     10 "PIPED WATER"
     11 "Piped inside dwelln'"
     12 "Piped outside dwellg"
     20 "WELL WATER"
     21 "Tubewell"
     22 "Surface/other well"
     30 "SURFACE WATER"
     31 "Pond/tank/lake"
     32 "River/stream"
     41 "Rainwater"
     96 "Other"
 /V114    
     10 "PIPED WATER"
     11 "Piped inside dwelln'"
     12 "Piped outside dwellg"
     20 "WELL WATER"
     21 "Tubewell"
     22 "Surface/other well"
     30 "SURFACE WATER"
     31 "Pond/tank/lake"
     32 "River/stream"
     41 "Rainwater"
     96 "Other"
 /V115    
    996 "On premises"
 /V116    
     10 "FLUSH TOILET"
     20 "PIT TOILET LATRINE"
     30 "NO FACILITY"
     31 ""
     96 "OTHER"
 /V119    
      0 "No"
      1 "Yes"
 /V120    
      0 "No"
      1 "Yes"
 /V121    
      0 "No"
      1 "Yes"
 /V122    
      0 ""
 /V123    
      0 "No"
      1 "Yes"
 /V124    
      0 ""
 /V125    
      0 ""
 /V127    
     10 "NATURAL"
     11 "Earth"
     20 "RUDIMENTARY"
     21 "Wood"
     30 "FINISHED"
     31 "Cement/concrete"
     96 "OTHER"
 /V128    
     10 "NATURAL"
     11 "Jute/bamboo/mud"
     20 "RUDIMENTARY"
     21 "Wood"
     30 "FINISHED"
     31 "Brick/cement"
     32 "Tin"
     96 "OTHER"
 /V129    
     10 "NATURAL"
     11 "Jute/bamboo/mud"
     20 "RUDIMENTARY"
     21 "Tin"
     30 "FINISHED"
     31 "Cement/concrete"
     96 "OTHER"
 /V130    
      1 "Islam"
      2 "Christianity"
      3 "Hinduism"
      4 "Buddhism"
      5 "Other"
 /V131    
      0 ""
 /V133    
     97 "Inconsistent"
 /V134    
      0 "Capital, large city"
      1 "Small city"
      2 "Town"
      3 "Countryside"
 /V135    
      1 "Usual resident"
      2 "Visitor"
 /V139    
      1 "Barishal"
      2 "Chittagong"
      3 "Dhaka"
      4 "Khulna"
      5 "Rajshani"
 /V140    
      0 "Abroad"
      1 "Urban"
      2 "Rural"
 /V141    
      0 "Capital, large city"
      1 "City"
      2 "Town"
      3 "Countryside"
      4 "Abroad"
 /V142    
      0 "No"
      1 "Yes"
 /V144    
      0 ""
 /V148    
      0 "No"
      1 "Yes"
 /V149    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
 /V150    
      1 "Head"
      2 "Wife"
      3 "Daughter"
      4 "Daughter-in-law"
      5 "Grand-daughter"
      6 "Mother"
      7 "Mother-in-law"
      8 "Sister"
      9 "Co-spouse"
     10 "Other relative"
     11 "Adopted/foster child"
     12 "Not related"
     98 "DK"
 /V151    
      1 "Male"
      2 "Female"
 /V152    
     96 "96+"
 /V153    
      0 ""
 /V154    
      0 ""
 /V213    
      0 "No or unsure"
      1 "Yes"
 /V215    
    994 "In menopause"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
 /V216    
      0 "No"
      1 "Yes"
 /V217    
      0 ""
 /V220    
      6 "6+"
 /V221    
    996 "Negative interval"
 /V223    
      7 "Month - exact date"
      8 "None - date placed"
 /V225    
      1 "Then"
      2 "Later"
      3 "Not at all"
 /V226    
    994 "In menopause"
    995 "Before last birth"
    996 "Never menstruated"
    997 "Inconsistent"
    998 "Don't know"
 /V227    
      0 "No flag"
      1 "N > int. since birth"
      2 "N + amen. > interval"
      3 "N, but per. not ret."
      4 "95, but no birth"
      5 "96, but per.returned"
      6 "95, but per.returned"
      7 "N, last per. in preg"
      8 "96, had children"
      9 "N, per.bef.last birt"
 /V228    
      0 "No"
      1 "Yes"
 /V229    
     97 "Inconsistent"
     98 "DK"
 /V230    
     97 "Inconsistent"
     98 "DK"
 /V231    
   9997 "Inconsistent"
   9998 "DK"
 /V232    
      1 "Month and year"
      2 "From calendar"
      5 "Year"
      6 ""
      7 "Month"
      8 "None"
 /V233    
     97 "Inconsistent"
     98 "Don't know"
 /V234    
      0 "No"
      1 "Yes"
 /V235    
      0 "No prior child"
 /V236    
      0 ""
 /V237    
      0 ""
 /V311    
      4 "4+"
      5 "Never used"
 /V312    
      0 "Not using"
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm/Foam/Jelly"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Specific method 1"
     14 "Specific method 2"
     15 "Specific method 3"
 /V313    
      0 "No method"
      1 "Folkloric method"
      2 "Traditional method"
      3 "Modern method"
 /V314    
      0 ""
 /V318    
      1 "Month and year"
      5 "Year - m imp, a calc"
      6 ""
      7 "Month - date placed"
      8 "None - date placed"
 /V319    
      1 "<2"
      2 "2-3"
      3 "4-5"
      4 "6-7"
      5 "8-9"
      6 "10+"
 /V320    
      1 "<25"
      2 "25-29"
      3 "30-34"
      4 "35-39"
      5 "40-44"
      6 "45-49"
 /V321    
      0 "Single,before marr."
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25+"
 /V322    
      5 "5+"
 /V323    
      1 "Maya"
      2 "Ovacon"
      3 "Norquest"
      4 "Noriday"
      5 "Ovral"
      6 "Combination-5"
      7 "Ovostat"
      8 "Restovar-NA"
      9 "Lyndiol"
     10 "Nordette"
     11 "Marvelou"
     96 "Other pill brand"
 /V326    
     10 "PUBLIC"
     11 "Hospital/Medical clg"
     12 "Family welfare cent."
     13 "Thana health complex"
     14 "Satellite clinic"
     20 "PRIVATE MEDICAL"
     21 "Private clinic,doct."
     22 "Traditional doctor"
     23 "Pharmacy"
     30 "OTHER PRIVATE"
     31 "Shop"
     32 "Friends, relatives"
     41 "Fieldworker, FWA"
     96 "OTHER"
     97 ""
     98 "DK"
 /V327    
      1 "Govt Clinical/Pharm"
      2 "Govt Home/Comm deliv"
      3 "NGO"
      4 "Private Clin/Deliv"
      5 "Private Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
 /V328    
      0 ""
 /V337    
     95 "All cal. {A core}"
     96 "96+ {B core}"
    997 "Inconsistent"
    998 "Don't know"
 /V359    
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm/Foam/Jelly"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Specific method 1"
     14 "Specific method 2"
     15 "Specific method 3"
 /V360    
      1 "Became pregnant"
      2 "Wanted to become prg"
      3 "Husband disapproved"
      4 "Side effects"
      5 "Health concerns"
      6 "Access, availability"
      7 "Wanted more eff.meth"
      8 "Inconvenient to use"
      9 "Infreq.sex,husb away"
     10 "Cost"
     11 "Fatalistic"
     12 "Diff.preg.,menopause"
     13 "Marital dissolution"
     14 "Other"
     98 "Don't know"
 /V361    
      1 "Currently using"
      2 "Used since last brth"
      3 "Used before last brt"
      4 "Never used"
 /V362    
      1 "In next 12 months"
      2 "Use later"
      3 "Unsure about timing"
      4 "Unsure about use"
      5 "Does not intend"
      6 "Never had sex"
 /V363    
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm/Foam/Jelly"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Specific method 1"
     14 "Specific method 2"
     15 "Specific method 3"
     98 "Don't know"
 /V364    
      1 "Using modern method"
      2 "Using tradit. method"
      3 "Non-user intend to"
      4 "Does not intend to"
      5 "Never had sex"
 /V366A   
      0 "Not acceptable"
      1 "Acceptable"
      8 "Don't know"
 /V366B   
      0 ""
 /V367    
      1 "Wanted then"
      2 "Wanted later"
      3 "Wanted no more"
 /V369    
      0 "Never used"
      1 "Pill"
      2 "IUD"
      3 "Injections"
      4 "Diaphragm/Foam/Jelly"
      5 "Condom"
      6 "Female Sterilization"
      7 "Male Sterilization"
      8 "Periodic Abstinence"
      9 "Withdrawal"
     10 "Other"
     11 "Norplant"
     12 "Abstinence"
     13 "Specific method 1"
     14 "Specific method 2"
     15 "Specific method 3"
 /V369B   
      0 ""
 /V372    
      0 "Package not seen"
      1 "Package seen"
 /V375A   
     11 "Not married"
     20 "FERTILITY-RELATED"
     21 "Not having sex"
     22 "Infrequent sex"
     23 "Menopausal, hyster."
     24 "Subfecund, infecund"
     25 "Postpartum, breastf."
     26 "Wants more children"
     27 "Pregnant"
     30 "OPPOSITION TO USE"
     31 "Respondent opposed"
     32 "Husband opposed"
     33 "Others opposed"
     34 "Religious prohibit."
     35 "Fatalistic"
     40 "LACK OF KNOWLEDGE"
     41 "Knows no method"
     42 "Knows no source"
     50 "METHOD-RELATED"
     51 "Health concerns"
     52 "Fear side effects"
     53 "Lack of access"
     54 "Cost too much"
     55 "Inconvenient to use"
     56 "Interfere with body"
     96 "Other"
     98 "DK"
 /V376    
     11 "Not married"
     20 "FERTILITY-RELATED"
     21 ""
     22 "Infrequent sex"
     23 "Menopausal, hyster."
     24 "Subfecund, infecund"
     25 ""
     26 "Wants more children"
     30 "OPPOSITION TO USE"
     31 "Respondent opposed"
     32 "Husband opposed"
     33 "Others opposed"
     34 "Religious prohibit."
     35 "Fatalistic"
     40 "LACK OF KNOWLEDGE"
     41 "Knows no method"
     42 "Knows no source"
     50 "METHOD-RELATED"
     51 "Health concerns"
     52 "Fear side effects"
     53 "Lack of access"
     54 "Cost too much"
     55 "Inconvenient to use"
     56 "Interfere with body"
     96 "Other"
     98 "DK"
 /V376A   
      0 ""
 /V379    
     10 "PUBLIC"
     11 "Hospital/Medical clg"
     12 "Family welfare cent."
     13 "Thana health complex"
     14 "Satellite clinic"
     20 "PRIVATE MEDICAL"
     21 "Private clinic,doct."
     22 "Traditional doctor"
     23 "Pharmacy"
     30 "OTHER PRIVATE"
     31 "Shop"
     32 "Friends, relatives"
     41 "Fieldworker, FWA"
     96 "OTHER"
     97 ""
     98 "DK"
 /V380    
      1 "Govt Clinical/Pharm"
      2 "Govt Home/Comm deliv"
      3 "NGO"
      4 "Private Clin/Deliv"
      5 "Private Pharmacy"
      6 "Shop, church, friend"
      7 "Other"
      8 "Don't know"
 /V384A   
      0 "No"
      1 "Yes"
 /V384B   
      0 "No"
      1 "Yes"
 /V384C   
      0 ""
 /V384D   
      0 "No"
      1 "Yes"
 /V384E   
      0 ""
 /V393    
      0 "No"
      1 "Yes - 6 months"
      8 "Don't know"
 /V394    
      0 "No"
      1 "Yes"
 /V395    
      0 "No"
      1 "Yes"
 /V396    
      0 "No"
      1 "Yes"
      8 "DK"
 /V397    
      0 ""
 /V398    
      0 ""
 /V399    
      0 ""
 /V401    
      0 "No"
      1 "Yes"
 /V404    
      0 "No"
      1 "Yes"
 /V405    
      0 "No"
      1 "Yes"
 /V406    
      0 "No"
      1 "Yes"
 /V407    
     96 "On demand"
 /V408    
     96 "On demand"
 /V409    
      0 "No"
      1 "Yes"
 /V409A   
      0 "No"
      1 "Yes"
 /V410    
      0 "No"
      1 "Yes"
 /V410A   
      0 "No"
      1 "Yes"
 /V411    
      0 ""
 /V411A   
      0 "No"
      1 "Yes"
 /V412    
      0 "No"
      1 "Yes"
 /V413A   
      0 ""
 /V413B   
      0 ""
 /V413C   
      0 ""
 /V413D   
      0 ""
 /V413    
      0 "No"
      1 "Yes"
 /V414A   
      0 ""
 /V414B   
      0 ""
 /V414C   
      0 ""
 /V414D   
      0 "No"
      1 "Yes"
 /V414E   
      0 "No"
      1 "Yes"
 /V414F   
      0 "No"
      1 "Yes"
 /V414G   
      0 "No"
      1 "Yes"
 /V414H   
      0 "No"
      1 "Yes"
 /V415    
      0 ""
 /V416    
      0 "Never heard of"
      1 "Used ORS"
      2 "Heard of ORS"
 /V419    
      0 ""
 /V420    
      0 ""
 /V421    
      0 ""
 /V426    
      0 "Immediately"
 /V436    
      0 ""
 /V437    
      0 ""
 /V438    
      0 ""
 /V439    
      0 ""
 /V440    
      0 ""
 /V441    
      0 ""
 /V442    
      0 ""
 /V443    
      0 ""
 /V444    
      0 ""
 /V444A   
      0 ""
 /V445    
      0 ""
 /V446    
      0 ""
 /V447    
      0 ""
 /V448    
      0 ""
 /V449    
      0 ""
 /V450A   
      0 ""
 /V450B   
      0 ""
 /V450C   
      0 ""
 /V450D   
      0 ""
 /V450E   
      0 ""
 /V450F   
      0 ""
 /V450G   
      0 ""
 /V450H   
      0 ""
 /V450I   
      0 ""
 /V450J   
      0 ""
 /V450K   
      0 ""
 /V450L   
      0 ""
 /V450M   
      0 ""
 /V450X   
      0 ""
 /V450Z   
      0 ""
 /V451A   
      0 ""
 /V451B   
      0 ""
 /V451C   
      0 ""
 /V451D   
      0 ""
 /V451E   
      0 ""
 /V451F   
      0 ""
 /V451G   
      0 ""
 /V451H   
      0 ""
 /V451I   
      0 ""
 /V451J   
      0 ""
 /V451K   
      0 ""
 /V451X   
      0 ""
 /V451Z   
      0 ""
 /V501    
      0 "Never married"
      1 "Married"
      2 "Living together"
      3 "Widowed"
      4 "Divorced"
      5 "Not living together"
 /V502    
      0 "Never married"
      1 "Currently married"
      2 "Formerly married"
 /V503    
      1 "Once"
      2 "More than once"
 /V504    
      1 "Living with her"
      2 "Staying elsewhere"
 /V505    
     98 ""
 /V506    
     98 ""
 /V510    
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 ""
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
 /V513    
      0 "Never married"
      1 "0-4"
      2 "5-9"
      3 "10-14"
      4 "15-19"
      5 "20-24"
      6 "25-29"
      7 "30+"
 /V527    
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
 /V528    
     31 "31+ days"
     95 "Within last 4 weeks"
     96 "Before last birth"
     97 "Inconsistent"
     98 "Don't know"
 /V529    
    995 "Within last 4 weeks"
    996 "Before last birth"
    997 "Inconsistent"
    998 "Don't know"
 /V530    
      0 "No flag"
      1 "N > int. since birth"
      2 "N + abst. > interval"
      3 "N, but sex not res."
      4 "96, but no birth"
      5 "96, but curr.preg."
      6 "96, but resumed sex"
      7 "N, last sex bef preg"
      8 "N, inconsis 4 weeks"
      9 "N, sex bef last birt"
 /V532    
      0 ""
 /V535    
      0 "No"
      1 "Formerly married"
      2 "Lived with a man"
 /V602    
      1 "Have another"
      2 "Undecided"
      3 "No more"
      4 "Sterilized"
      5 "Declared infecund"
      6 "Never had sex"
 /V603    
    993 "After marriage"
    994 "Soon, now"
    995 ""
    996 "Other, Non-numeric"
    997 "Inconsistent"
    998 "Don't know"
 /V604    
      0 "<12 months"
      1 "1 year"
      2 "2 years"
      3 "3 years"
      4 "4 years"
      5 "5 years"
      6 "6+ years"
      7 "Non-numeric"
      8 "Don't know"
 /V605    
      1 "Wants within 2 years"
      2 "Wants after 2+ years"
      3 "Wants, unsure timing"
      4 "Undecided"
      5 "Wants no more"
      6 "Sterilized"
      7 "Declared infecund"
      8 "Never had sex"
 /V606    
      1 "Happy"
      2 "Unhappy"
      3 "Would not matter"
      8 "DK"
 /V610    
      0 "Disapproves"
      1 "Approves"
      8 "Don't know"
 /V611    
      0 "Never"
      1 "Once or twice"
      2 "More often"
 /V612    
      0 "Disapproves"
      1 "Approves"
      8 "Don't know"
 /V613    
     95 "Up to God"
     96 "Other"
     98 "DK"
 /V614    
      6 "6+"
      7 "Non-numeric response"
 /V616    
    993 "After marriage"
    994 "Soon/now"
    995 "Can't get pregnant"
    996 "Other"
    998 "DK"
 /V618    
      0 "No regret"
      1 "Resp. wants another"
      2 "Part. wants another"
      3 "Side effects"
      4 "Child died"
      5 ""
      6 "Other reason"
 /V621    
      1 "Both want same"
      2 "Husband wants more"
      3 "Husband wants fewer"
      8 "DK"
 /V623    
      0 "Fecund"
      1 "Pregnant"
      2 "Amenorrheic"
      3 "Infecund, menopausal"
 /V624    
      0 "Never had sex"
      1 "Unmet need to space"
      2 "Unmet need to limit"
      3 "Using to space"
      4 "Using to limit"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "Desire birth < 2 yrs"
      8 "No sex, want to wait"
      9 "Infecund, menopausal"
 /V625    
      0 "Fecund"
      1 "Pregnant"
      2 "Amenorrheic"
      3 "Infecund, menopausal"
 /V626    
      0 "Never had sex"
      1 "Unmet need to space"
      2 "Unmet need to limit"
      3 "Using to space"
      4 "Using to limit"
      5 "Spacing failure"
      6 "Limiting failure"
      7 "Desire birth < 2 yrs"
      8 "No sex, want to wait"
      9 "Infecund, menopausal"
 /V627    
     95 "Up to God"
     96 "Other"
     97 ""
     98 "DK"
 /V628    
     95 "Up to God"
     96 "Other"
     97 ""
     98 "DK"
 /V629    
     95 "Up to God"
     96 "Other"
     97 ""
     98 "DK"
 /V701    
      0 "No education"
      1 "Primary"
      2 "Secondary"
      3 "Higher"
      8 "Don't know"
 /V702    
     98 "Don't know"
 /V704    
     11 "Land owner"
     12 "Farmer"
     13 "Agricultural worker"
     14 "Fisherman"
     21 "Unskilled labourers"
     22 "Domestic servant"
     23 "Non-agricultural wkr"
     31 "Semi-skilled labour"
     41 "Professional worker"
     51 "Business"
     52 "Small business/tradr"
     61 "Unemployed"
     62 "Retired"
     96 "Others"
     97 ""
     98 "Don't know"
 /V705    
      0 "Did not work"
      1 "Prof., Tech., Manag."
      2 "Clerical"
      3 "Sales"
      4 "Agric-self employed"
      5 "Agric-employee"
      6 "Household & domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     98 "Don't know"
 /V707    
      0 "His land"
      1 "Family land"
      2 "Someone else's land"
      3 "Rented land"
      8 "Don't know"
 /V714    
      0 "No"
      1 "Yes"
 /V715    
     97 "Inconsistent"
     98 "Don't know"
 /V716    
      0 "Not working"
     11 "Land owner"
     12 "Farmer"
     13 "Agricultural worker"
     14 "Fisherman"
     21 "Unskilled labourers"
     22 "Domestic servant"
     23 "Non-agricultural wkr"
     31 "Semi-skilled labour"
     41 "Professional worker"
     51 "Business"
     52 "Small business/tradr"
     61 "Unemployed"
     62 "Retired"
     96 "Others"
     97 ""
     98 "Don't know"
 /V717    
      0 "Not working"
      1 "Prof., Tech., Manag."
      2 "Clerical"
      3 "Sales"
      4 "Agric-self employed"
      5 "Agric-employee"
      6 "Household & domestic"
      7 "Services"
      8 "Skilled manual"
      9 "Unskilled manual"
     98 "Don't know"
 /V718    
      0 "Did not work"
      1 "Paid employee, away"
      2 "Paid employee, home"
      3 "Self-employed, away"
      4 "Self-employed, home"
      5 "Unpaid worker, away"
      6 "Unpaid worker, home"
 /V719    
      1 "For family member"
      2 "For someone else"
      3 "Self-employed"
 /V720    
      0 "No"
      1 "Yes"
 /V721    
      1 "At home"
      2 "Away"
 /V723    
      0 "Respondent"
      1 "Husband/partner"
      2 "Other child"
      3 "Other relatives"
      4 "Neighbors"
      5 "Friends"
      6 "Servants/hired help"
      7 "Child is in school"
      8 "Institutional care"
      9 ""
     10 "Other female child"
     11 "Other male child"
     95 "Not worked since bth"
     96 "Other"
 /V729    
      0 "No education"
      1 "Incomplete primary"
      2 "Complete primary"
      3 "Incomplete secondary"
      4 "Complete secondary"
      5 "Higher"
      8 "Don't know"
 /V730    
      0 ""
 /V732    
      1 "All year"
      2 "Seasonal"
      3 "Occasional"
 /V736    
 99999996 ""
 /V739    
      1 "Respondent"
      2 "Partner"
      3 "Jointly with partner"
      4 "Someone else"
      5 "Jointly with someone"
 /V740    
      0 "Own land"
      1 "Family land"
      2 "Someone else's land"
      3 "Rented land"
      8 "Don't know"
 /B0      
      0 "Single birth"
      1 "1st of multiple"
      2 "2nd of multiple"
      3 "3rd of multiple"
      4 "4th of multiple"
      5 "5th of multiple"
 /B4      
      1 "Male"
      2 "Female"
 /B5      
      0 "No"
      1 "Yes"
 /B6      
    997 "Inconsistent"
    998 "Don't know"
 /B9      
      0 "Respondent"
      1 "Father"
      2 "Other relative"
      3 "Someone else"
      4 "Lives elsewhere"
 /B10     
      1 "Month and year"
      2 "Month and age -y imp"
      3 "Year and age - m imp"
      4 "Y & age - y ignored"
      5 "Year - a, m imp"
      6 "Age - y, m imp"
      7 "Month - a, y imp"
      8 "None - all imp"
 /B13     
      0 "No flag"
      1 "> interview"
      2 "< breastfeeding"
      3 "< age supplemented"
      4 "< first breastfed"
      5 "< last vaccination"
      6 "Outside range"
      7 "Imputed, units given"
      8 "Imputed, no units"
 /B14     
      0 ""
 /B15     
      0 ""
 /M1      
      0 "Received no inject."
      7 "7+"
      8 "Don't know"
 /M2A     
      0 "No"
      1 "Yes: doctor"
 /M2B     
      0 "No"
      1 "Yes: nurse/midwife"
 /M2C     
      0 ""
 /M2D     
      0 "No"
      1 "Yes: FW Visitor ."
 /M2E     
      0 ""
 /M2F     
      0 "No"
      1 "Yes: trained birth A"
 /M2G     
      0 "No"
      1 "Yes: trad.birth att."
 /M2H     
      0 ""
 /M2I     
      0 ""
 /M2J     
      0 ""
 /M2K     
      0 "No"
      1 "Yes: other responses"
 /M2L     
      0 ""
 /M2M     
      0 ""
 /M2N     
      0 "No: some care"
      1 "Yes: no one"
 /M3A     
      0 "No"
      1 "Yes: doctor"
 /M3B     
      0 "No"
      1 "Yes: nurse/midwife"
 /M3C     
      0 ""
 /M3D     
      0 "No"
      1 "Yes: FW Visitor ."
 /M3E     
      0 ""
 /M3F     
      0 "No"
      1 "Yes: trained birth A"
 /M3G     
      0 "No"
      1 "Yes: trad.birth att."
 /M3H     
      0 "No"
      1 "Yes: relative,friend"
 /M3I     
      0 ""
 /M3J     
      0 ""
 /M3K     
      0 "No"
      1 "Yes: other responses"
 /M3L     
      0 ""
 /M3M     
      0 "No"
      1 "Yes: CS other"
 /M3N     
      0 "No: some assistance"
      1 "Yes: no one"
 /M4      
     94 "Never breastfed"
     95 "Still breastfeeding"
     96 "Breastfed until died"
     97 "Inconsistent"
     98 "DK"
 /M5      
     94 "Never breastfed"
     97 "Inconsistent"
     98 "DK"
 /M6      
     96 "Period not returned"
     97 "Inconsistent"
     98 "DK"
 /M7      
     97 "Inconsistent"
     98 "DK"
 /M8      
     96 "Still abstaining"
     97 "Inconsistent"
     98 "DK"
 /M9      
     97 "Inconsistent"
     98 "DK"
 /M10     
      1 "Then"
      2 "Later"
      3 "No more"
 /M11     
      0 ""
 /M13     
     98 "DK"
 /M14     
      0 "No antenatal visits"
     98 "DK"
 /M15     
     10 "HOMES"
     11 "Respondents home"
     12 "Other home"
     20 "PUBLIC SECTOR"
     21 "Govt. hospital"
     22 "Govt. health center"
     23 "Govt. health post"
     26 "Other public"
     30 "PRIVATE SECTOR"
     31 "Private hosp/clinic"
     36 "Other private medica"
     96 "OTHER"
 /M17     
      0 ""
 /M18     
      0 ""
 /M19     
      0 ""
 /M19A    
      0 ""
 /M21     
      1 "Mother ill, weak"
      2 "Child ill, weak"
      3 "Child died"
      4 "Nipple, breast prob."
      5 "Insufficient milk"
      6 "Working"
      7 "Child refused"
      8 "Weaning age"
      9 "Became pregnant"
     10 "Started using method"
     96 "Other"
     97 "Missing ever breastf"
 /M27     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 mnth"
      3 "> age at death"
      4 "During preg in cal."
 /M28     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 mnth"
      3 ""
      4 "During preg in cal."
 /M29     
      0 "No flag"
      1 "> interval"
      2 "> interval by 1 mnth"
      3 ""
      4 "During preg in cal."
 /M30     
      0 ""
 /M31     
      0 ""
 /M32     
      0 ""
 /M33     
      0 ""
 /M34     
      0 "Immediately"
    100 ""
    101 "Hours: 1"
    201 "Days: 1"
 /M35     
     96 "On demand"
 /M36     
     96 "On demand"
 /M37A    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37B    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37C    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37D    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37E    
      0 ""
 /M37F    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37G    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37H    
      0 ""
 /M37I    
      0 ""
 /M37J    
      0 ""
 /M37K    
      0 ""
 /M37L    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37M    
      0 ""
 /M37N    
      0 ""
 /M37O    
      0 ""
 /M37P    
      0 "No"
      1 "Yes"
      8 "DK"
 /M37Q    
      0 ""
 /M37R    
      0 ""
 /M37S    
      0 ""
 /M37T    
      0 "No"
      1 "Yes"
      8 "DK"
 /M38     
      0 ""
 /M39     
      0 ""
 /M40A    
      0 ""
 /M40B    
      0 ""
 /M40C    
      0 ""
 /M40D    
      0 ""
 /M40E    
      0 ""
 /M40F    
      0 ""
 /M40G    
      0 ""
 /M40H    
      0 ""
 /M40I    
      0 ""
 /M40J    
      0 ""
 /M40K    
      0 ""
 /M40L    
      0 ""
 /M40M    
      0 ""
 /M40N    
      0 ""
 /M40O    
      0 ""
 /H1      
      0 "No card"
      1 "Yes, seen"
      2 "Yes, not seen"
      3 "No longer has card"
 /H2      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H2D     
     97 "Inconsistent"
     98 "DK"
 /H2M     
     97 "Inconsistent"
     98 "DK"
 /H2Y     
     97 "Inconsistent"
     98 "DK"
 /H3      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H3D     
     97 "Inconsistent"
     98 "DK"
 /H3M     
     97 "Inconsistent"
     98 "DK"
 /H3Y     
     97 "Inconsistent"
     98 "DK"
 /H4      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H4D     
     97 "Inconsistent"
     98 "DK"
 /H4M     
     97 "Inconsistent"
     98 "DK"
 /H4Y     
     97 "Inconsistent"
     98 "DK"
 /H5      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H5D     
     97 "Inconsistent"
     98 "DK"
 /H5M     
     97 "Inconsistent"
     98 "DK"
 /H5Y     
     97 "Inconsistent"
     98 "DK"
 /H6      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H6D     
     97 "Inconsistent"
     98 "DK"
 /H6M     
     97 "Inconsistent"
     98 "DK"
 /H6Y     
     97 "Inconsistent"
     98 "DK"
 /H7      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H7D     
     97 "Inconsistent"
     98 "DK"
 /H7M     
     97 "Inconsistent"
     98 "DK"
 /H7Y     
     97 "Inconsistent"
     98 "DK"
 /H8      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H8D     
     97 "Inconsistent"
     98 "DK"
 /H8M     
     97 "Inconsistent"
     98 "DK"
 /H8Y     
     97 "Inconsistent"
     98 "DK"
 /H9      
      0 "No"
      1 "Vacc. date on card"
      2 "Reported by mother"
      3 "Vacc. marked on card"
      8 "DK"
 /H9D     
     97 "Inconsistent"
     98 "DK"
 /H9M     
     97 "Inconsistent"
     98 "DK"
 /H9Y     
     97 "Inconsistent"
     98 "DK"
 /H0      
      0 ""
 /H0D     
     97 "Inconsistent"
     98 "DK"
 /H0M     
     97 "Inconsistent"
     98 "DK"
 /H0Y     
     97 "Inconsistent"
     98 "DK"
 /H10     
      0 "No"
      1 "Yes"
      8 "Don't know"
 /H11     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
 /H11B    
      0 "No"
      1 "Yes"
      8 "DK"
 /H11C    
      0 ""
 /H12A    
      0 "No"
      1 "Government hospital"
 /H12B    
      0 "No"
      1 "Govt. health center"
 /H12C    
      0 ""
 /H12D    
      0 ""
 /H12E    
      0 "No"
      1 "Comm.health worker"
 /H12F    
      0 "No"
      1 "Satellite clinic"
 /H12G    
      0 ""
 /H12H    
      0 ""
 /H12I    
      0 ""
 /H12J    
      0 "No"
      1 "Private hosp/clinic"
 /H12K    
      0 "No"
      1 "Private pharmacy"
 /H12L    
      0 "No"
      1 "Private doctor"
 /H12M    
      0 ""
 /H12N    
      0 ""
 /H12O    
      0 ""
 /H12P    
      0 ""
 /H12Q    
      0 ""
 /H12R    
      0 ""
 /H12S    
      0 "No"
      1 "Shop"
 /H12T    
      0 "No"
      1 "Traditional pract."
 /H12U    
      0 ""
 /H12V    
      0 ""
 /H12W    
      0 ""
 /H12X    
      0 "No"
      1 "Other"
 /H12Y    
      0 "No: received treatm."
      1 "Yes: no treatment"
 /H12Z    
      0 "No"
      1 "Yes: medical treatm."
 /H13     
      0 "No"
      1 "Yes: ORS - spontan."
      2 "Yes: ORS - probed"
      8 "Don't know"
 /H14     
      0 "No"
      1 "Yes: RHS - spontan."
      2 "Yes: RHS - probed"
      8 "Don't know"
 /H15     
      0 "No"
      1 "Yes: oth pill, syrup"
 /H15A    
      0 ""
 /H15B    
      0 "No"
      1 "Yes: injection"
 /H15C    
      0 "No"
      1 "Yes: intravenous (IV"
 /H15D    
      0 "No"
      1 "Yes: home rem, herb."
 /H15E    
      0 ""
 /H15F    
      0 ""
 /H15G    
      0 ""
 /H15H    
      0 ""
 /H16     
      0 "Same"
      1 "Increase"
      2 "Decrease"
      8 "DK"
 /H18     
      0 ""
 /H20     
      0 "No"
      1 "Yes"
 /H21A    
      0 "No: received treatm."
      1 "Yes: no treatment"
      8 "DK"
 /H21     
      0 "No"
      1 "Yes"
 /H22     
      0 ""
 /H31     
      0 "No"
      1 "Yes, last 24 hours"
      2 "Yes, last two weeks"
      8 "Don't know"
 /H31B    
      0 "No"
      1 "Yes"
      8 "DK"
 /H32A    
      0 "No"
      1 "Government hospital"
 /H32B    
      0 "No"
      1 "Govt. health center"
 /H32C    
      0 ""
 /H32D    
      0 ""
 /H32E    
      0 "No"
      1 "Community health wrk"
 /H32F    
      0 "No"
      1 "Satellite clinic"
 /H32G    
      0 ""
 /H32H    
      0 ""
 /H32I    
      0 ""
 /H32J    
      0 "No"
      1 "Private hosp./clinic"
 /H32K    
      0 "No"
      1 "Private pharmacy"
 /H32L    
      0 "No"
      1 "Private doctor"
 /H32M    
      0 ""
 /H32N    
      0 ""
 /H32O    
      0 ""
 /H32P    
      0 ""
 /H32Q    
      0 ""
 /H32R    
      0 ""
 /H32S    
      0 "No"
      1 "Shop"
 /H32T    
      0 "No"
      1 "Traditional pract."
 /H32U    
      0 ""
 /H32V    
      0 ""
 /H32W    
      0 ""
 /H32X    
      0 "No"
      1 "Other"
 /H32Y    
      0 "No: received treatm."
      1 "Yes: no treatment"
 /H32Z    
      0 "No"
      1 "Yes: medical treatm."
 /SDFORMAT
      1 "Bengali"
      2 "English"
 /SADJUST 
      0 "Not adjusted"
      1 "Adjusted"
 /SDIV    
      1 "Barishal"
      2 "Chittagong"
      3 "Dhaka"
      4 "Khulna"
      5 "Rajshani"
 /S114A   
      0 "No"
      1 "Yes"
 /S114B   
      0 "No"
      1 "Yes"
 /S114C   
      0 "No"
      1 "Yes"
 /S114D   
      0 "No"
      1 "Yes"
 /S114E   
      0 "No"
      1 "Yes"
 /S119    
    996 "On premises"
 /S123    
      0 "No children"
     11 "Sep.tank/modern tlet"
     21 "Water sld/Slab latr."
     22 "Pit latrine"
     23 "Open latrine"
     24 "Hanging latrine"
     31 "No facility,bush"
     96 "Other"
 /S124A   
      0 "No"
      1 "Yes"
 /S124B   
      0 "No"
      1 "Yes"
 /S124C   
      0 "No"
      1 "Yes"
 /S124D   
      0 "No"
      1 "Yes"
 /S124I   
      0 "No"
      1 "Yes"
 /S229M   
     97 "Inconsistent"
     98 "DK"
 /S229Y   
   9997 "Inconsistent"
   9998 "DK"
 /S233A   
      0 "No"
      1 "Yes"
 /S233B   
      0 "No"
      1 "Yes"
 /S233C   
      1 "Menstrual regulation"
      2 "Induced abortion/D&C"
      3 "Other"
 /S233DY  
   1300 "Bengali (Start)"
   1401 "Bengali (end)"
   1900 "English (Start)"
   1994 "English(end)"
   9997 "Inconsistent"
   9998 "Don't Know"
 .
 EXECUTE.
execute.
save outfile='BDBR31FL.SAV'.
