infix using BDKR31FL.dct

label variable caseid   "Case Identification"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Sample weight"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Current age - respondent"
label variable v013     "Age 5-year groups"
label variable v014     "Completeness of information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "CMC start of calendar"
label variable v018     "Row of month of interview"
label variable v019     "Length of calendar"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample stratum number"
label variable v023     "Sample domain"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "Keyer identification"
label variable v030     "Field supervisor -NA"
label variable v031     "Field editor -NA"
label variable v032     "Office editor -NA"
label variable v033     "Ultimate area selection prob."
label variable v034     "Line number of husband"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "Childhood place of residen -NA"
label variable v104     "Years lived in place of res."
label variable v105     "Type of place of previous res."
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v108     "Literacy"
label variable v109     "Reads newspaper once a week"
label variable v110     "Watches TV every week"
label variable v111     "Listens to radio every day -NA"
label variable v112     "Listens to radio every week"
label variable v113     "Source of drinking water"
label variable v114     "Source of non-drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Has electricity"
label variable v120     "Has radio"
label variable v121     "Has television"
label variable v122     "Has refrigerator -NA"
label variable v123     "Has bicycle"
label variable v124     "Has motorcycle -NA"
label variable v125     "Has car -NA"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity -NA"
label variable v133     "Education in single years"
label variable v134     "De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members"
label variable v137     "Number of children 5 and under"
label variable v138     "Number of eligible women in HH"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of res."
label variable v141     "De jure place of residence"
label variable v142     "Same source of water"
label variable v144     "Communities lived in >Jan.8-NA"
label variable v148     "Respondent still in school"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Has telephone -NA"
label variable v154     "Reason stop attending schoo-NA"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "Date of first birth (CMC)"
label variable v212     "Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v215     "Time since last menstrual perd"
label variable v216     "Menstruated in last six weeks"
label variable v217     "Knowledge of ovulatory cycl-NA"
label variable v218     "Number of living children"
label variable v219     "Living children + current preg"
label variable v220     "Living children + curr preg 6+"
label variable v221     "Marriage to first birth int."
label variable v222     "Last birth to interview"
label variable v223     "Completeness of curr preg. inf"
label variable v224     "Entries in birth history"
label variable v225     "Current pregnancy wanted"
label variable v226     "Time since last period (comp)"
label variable v227     "Flag for last period"
label variable v228     "Ever had a terminated preg."
label variable v229     "Month pregnancy ended"
label variable v230     "Year pregnancy ended"
label variable v231     "CMC pregnancy ended"
label variable v232     "Completeness of last term. inf"
label variable v233     "Months when pregnancy ended"
label variable v234     "Other such pregnancies"
label variable v235     "Index last child prior to cal."
label variable v236     "Last birth interval >= 4 ye-NA"
label variable v237     "Birth between last & interv-NA"
label variable v238     "Births in last three years"
label variable v310     "Living children at first use"
label variable v311     "Children at first use (grpd)"
label variable v312     "Current contraceptive method"
label variable v313     "Current use by method type"
label variable v314     "Method of periodic abstinen-NA"
label variable v315     "Month of sterilization"
label variable v316     "Year of sterilization"
label variable v317     "Date of sterilization (CMC)"
label variable v318     "Completeness of information"
label variable v319     "Years since sterilization"
label variable v320     "Age at sterilization"
label variable v321     "Marital duration at steriliz."
label variable v322     "Parity at sterilization"
label variable v323     "Brand of pill used"
label variable v325     "Cost of pills"
label variable v326     "Last source for current users"
label variable v327     "Last source for users by type"
label variable v328     "Main reason use current sou-NA"
label variable v337     "Months of use of current meth"
label variable v359     "Last method disc. last 5 years"
label variable v360     "Reason of last discontinuation"
label variable v361     "Pattern of use"
label variable v362     "Intention to use"
label variable v363     "Preferred future method"
label variable v364     "Contraceptive use & intention"
label variable v366a    "Acceptability of radio message"
label variable v366b    "Acceptability of TV message-NA"
label variable v367     "Wanted last child"
label variable v369     "First method used"
label variable v369b    "First use to space or limit-NA"
label variable v372     "Shown pill package"
label variable v375a    "Main reason not using a method"
label variable v376     "Main reason not to use a meth."
label variable v376a    "Would ever use method if ma-NA"
label variable v379     "Source known for any method"
label variable v380     "Source known for any method"
label variable v384a    "Heard FP on radio last months"
label variable v384b    "Heard FP on TV last months"
label variable v384c    "Heard FP newspaper last mon-NA"
label variable v384d    "Heard FP on poster last months"
label variable v384e    "Heard FP brochures last mon-NA"
label variable v393     "Visited by FP worker last 6m"
label variable v394     "Visited health facil. last 12m"
label variable v395     "At health facility, told of FP"
label variable v396     "Breastfeeding affect pregnancy"
label variable v397     "Pregnancy risk of breastfee-NA"
label variable v398     "Relied breastfeed. avoid pr-NA"
label variable v399     "Currently rely on breastfee-NA"
label variable v401     "Last birth ceasarean sectio-NA"
label variable v404     "Currently breastfeeding"
label variable v405     "Currently amenorrheic"
label variable v406     "Currently abstaining"
label variable v407     "Times breastfed during night"
label variable v408     "Times breastfed during day"
label variable v409     "Gave child plain water"
label variable v409a    "Gave child sugar water"
label variable v410     "Gave child juice"
label variable v410a    "Gave child herbal tea"
label variable v411     "Gave child powder/tinned mi-NA"
label variable v411a    "Gave child baby formula"
label variable v412     "Gave child fresh milk"
label variable v413a    "Country specific other liqu-NA"
label variable v413b    "Country specific other liqu-NA"
label variable v413c    "Country specific other liqu-NA"
label variable v413d    "Country specific other liqu-NA"
label variable v413     "Gave child other liquid"
label variable v414a    "Country specific other food-NA"
label variable v414b    "Country specific other food-NA"
label variable v414c    "Country specific other food-NA"
label variable v414d    "Other solid, semi-solid foods"
label variable v414e    "Food made from local grain -NA"
label variable v414f    "Food made from local tuber -NA"
label variable v414g    "Gave child eggs, fish, poul-NA"
label variable v414h    "Gave child meat"
label variable v415     "Drank from bottle with nipp-NA"
label variable v416     "Heard of oral rehydration"
label variable v417     "Entries in maternity table"
label variable v418     "Entries in health table"
label variable v419     "Entries in height/weight ta-NA"
label variable v420     "Measurer's code -NA"
label variable v421     "Assistant measurer's code -NA"
label variable v426     "When child put to breast"
label variable v436     "Arm circumference (cms-1d) -NA"
label variable v437     "Respondent's weight (kilos--NA"
label variable v438     "Respondent's height (cms-1d-NA"
label variable v439     "Ht/A Percentile (resp.) -NA"
label variable v440     "Ht/A Standard deviations (r-NA"
label variable v441     "Ht/A Percent ref. median (r-NA"
label variable v442     "Wt/Ht Percent ref. median (-NA"
label variable v443     "Wt/Ht Percent ref. median (-NA"
label variable v444     "Wt/Ht Percent ref. median (-NA"
label variable v444a    "Wt/Ht Std deviations(resp) -NA"
label variable v445     "Body mass index for respond-NA"
label variable v446     "Rohrer's index for responde-NA"
label variable v447     "Result of measurement of re-NA"
label variable v448     "Drinking pattern with diarr-NA"
label variable v449     "Eating pattern with diarrhe-NA"
label variable v450a    "Diarrhea: repeat watery sto-NA"
label variable v450b    "Diarrhea: Any watery stools-NA"
label variable v450c    "Diarrhea: Repeated vomiting-NA"
label variable v450d    "Diarrhea: Any vomiting -NA"
label variable v450e    "Diarrhea: Blood in stools -NA"
label variable v450f    "Diarrhea: Fever -NA"
label variable v450g    "Diarrhea: Marked thirst -NA"
label variable v450h    "Diarrhea: Not eating/drinki-NA"
label variable v450i    "Diarrhea: Getting sicker -NA"
label variable v450j    "Diarrhea: Not getting bette-NA"
label variable v450k    "Diarrhea: Country specific -NA"
label variable v450l    "Diarrhea: Country specific -NA"
label variable v450m    "Diarrhea: Country specific -NA"
label variable v450x    "Diarrhea: Other responses -NA"
label variable v450z    "Diarrhea: Does not know -NA"
label variable v451a    "Cough: Fast breathing -NA"
label variable v451b    "Cough: Difficult breathing -NA"
label variable v451c    "Cough: Noisy breathing -NA"
label variable v451d    "Cough: Fever -NA"
label variable v451e    "Cough: Unable to drink -NA"
label variable v451f    "Cough: Not eating/drinking -NA"
label variable v451g    "Cough: Getting sicker -NA"
label variable v451h    "Cough: Not getting better -NA"
label variable v451i    "Cough: Country specific -NA"
label variable v451j    "Cough: Country specific -NA"
label variable v451k    "Cough: Country specific -NA"
label variable v451x    "Cough: Other responses -NA"
label variable v451z    "Knows no sign of illness -NA"
label variable v501     "Current marital status"
label variable v502     "Currently/formerly/never marr."
label variable v503     "Number of unions"
label variable v504     "Husband lives in house"
label variable v505     "Number of other wives - NA"
label variable v506     "Wife rank number - NA"
label variable v507     "Month of first marriage"
label variable v508     "Year of first marriage"
label variable v509     "Date of first marriage (CMC)"
label variable v510     "Completeness of date inform."
label variable v511     "Age at first marriage"
label variable v512     "Years since first marriage"
label variable v513     "Marital duration (grouped)"
label variable v525     "Age at first intercourse - NA"
label variable v527     "Time since last intercourse"
label variable v528     "Time since last intercourse(g)"
label variable v529     "Time since last intercourse(im"
label variable v530     "Flag for V529"
label variable v531     "Age at first intercourse - NA"
label variable v532     "Flag for V531 -NA"
label variable v534     "Have a regular sex partne - NA"
label variable v535     "Have ever been married"
label variable v602     "Fertility preference"
label variable v603     "Preferred waiting time"
label variable v604     "Preferred waiting time (grpd)"
label variable v605     "Desire for more children"
label variable v606     "Attitude toward becoming preg."
label variable v610     "Husband approves FP"
label variable v611     "Discussed FP with partner"
label variable v612     "Respondent approves FP"
label variable v613     "Ideal number of children"
label variable v614     "Ideal number of children (grp)"
label variable v616     "Time for future birth"
label variable v618     "Reason regrets sterilization"
label variable v621     "Husbands desire for children"
label variable v623     "Exposure"
label variable v624     "Unmet need"
label variable v625     "Exposure (definition 2)"
label variable v626     "Unmet need (definition 2)"
label variable v627     "Ideal number of boys"
label variable v628     "Ideal number of girls"
label variable v629     "Ideal number of either sex"
label variable v630a    "Discussed FP with partner - NA"
label variable v630b    "Discussed FP with mother - NA"
label variable v630c    "Discussed FP with father - NA"
label variable v630d    "Discussed FP with sister( - NA"
label variable v630e    "Discussed FP with brother - NA"
label variable v630f    "Discussed FP with daughte - NA"
label variable v630g    "Discussed FP with mother- - NA"
label variable v630h    "Discussed FP with friends - NA"
label variable v630i    "Discussed FP -country spe - NA"
label variable v630j    "Discussed FP -country spe - NA"
label variable v630k    "Discussed FP -country spe - NA"
label variable v630l    "Discussed FP -country spe - NA"
label variable v630x    "Discussed FP with others - NA"
label variable v701     "Partner's education level"
label variable v702     "Highest year of education"
label variable v704     "Partner's occupation"
label variable v705     "Partner's occupation"
label variable v707     "Type of land where works"
label variable v714     "Respondent currently working"
label variable v715     "Husbands education-single yrs"
label variable v716     "Respondent's occupation"
label variable v717     "Respondent's occupation"
label variable v718     "Current type of employment"
label variable v719     "Work for family, others, self"
label variable v720     "Earns cash for work"
label variable v721     "Works at home or away"
label variable v723     "Child minder"
label variable v729     "Partner's educational attainm."
label variable v730     "Partners age -NA"
label variable v731     "Worked in last 12 months - NA"
label variable v732     "Employment all year/seasonal"
label variable v733     "Months worked in last 12 - NA"
label variable v734     "Days in a week normally w - NA"
label variable v735     "Days worked in last 12 mo - NA"
label variable v736     "Earnings for work - NA"
label variable v737     "Daily earnings for work - NA"
label variable v738     "Yearly earnings for work - NA"
label variable v739     "Who decides how to spend money"
label variable v740     "Type of land where resp. works"
label variable bidx     "Birth column number"
label variable bord     "Birth order number"
label variable b0       "Child is twin"
label variable b1       "Month of birth"
label variable b2       "Year of birth"
label variable b3       "Date of birth (CMC)"
label variable b4       "Sex of child"
label variable b5       "Child is alive"
label variable b6       "Age at death"
label variable b7       "Age at death (months-imputed)"
label variable b8       "Current age of child"
label variable b9       "Who child lives with"
label variable b10      "Completeness of information"
label variable b11      "Preceding birth interval"
label variable b12      "Succeeding birth interval"
label variable b13      "Flag for age at death"
label variable b14      "Birth interval >= 4 years -NA"
label variable b15      "Live birth between births -NA"
label variable midx     "Index to birth history"
label variable m1       "Tetanus injections bef. birth"
label variable m2a      "Prenatal: doctor"
label variable m2b      "Prenatal: nurse/midwife"
label variable m2c      "Prenatal: auxiliary midwife-NA"
label variable m2d      "Prenatal: Family Welf.Visitor"
label variable m2e      "Prenatal: CS health profess-NA"
label variable m2f      "Prenatal: trained birth att."
label variable m2g      "Prenatal: trad.birth attendant"
label variable m2h      "Prenatal: relative -NA"
label variable m2i      "Prenatal: CS other person -NA"
label variable m2j      "Prenatal: CS other person -NA"
label variable m2k      "Prenatal: other resp (uncoded)"
label variable m2l      "Prenatal: CS other -NA"
label variable m2m      "Prenatal: CS other -NA"
label variable m2n      "Prenatal: no one"
label variable m3a      "Assistance: doctor"
label variable m3b      "Assistance: nurse/midwife"
label variable m3c      "Delivery: auxiliary midwife-NA"
label variable m3d      "Delivery: Family Welf.Visitor"
label variable m3e      "Assistance: CS health profe-NA"
label variable m3f      "Assistance: trained birth att."
label variable m3g      "Assistance: trad.birth attend."
label variable m3h      "Assistance: relative, friend"
label variable m3i      "Assistance: CS other person-NA"
label variable m3j      "Assistance: CS other person-NA"
label variable m3k      "Assistance: other resp (uncod)"
label variable m3l      "Assistance: CS other -NA"
label variable m3m      "Assistance: CS other"
label variable m3n      "Assistance: no one"
label variable m4       "Duration of breastfeeding"
label variable m5       "Months of breastfeeding"
label variable m6       "Duration of amenorrhea"
label variable m7       "Months of amenorrhea"
label variable m8       "Duration of abstinence"
label variable m9       "Months of abstinence"
label variable m10      "Time wanted pregnancy"
label variable m11      "Time would have waited -NA"
label variable m13      "Timing of 1st antenatal check"
label variable m14      "Antenatal visits for pregnancy"
label variable m15      "Place of delivery"
label variable m17      "Delivery by caesarian secti-NA"
label variable m18      "Size of child at birth -NA"
label variable m19      "Birth weight (kilos - 3 dec-NA"
label variable m19a     "Weight at birth recall -NA"
label variable m21      "Reason stopped breastfeeding"
label variable m27      "Flag for breastfeeding"
label variable m28      "Flag for amenorrhea"
label variable m29      "Flag for abstinence"
label variable m30      "At birth - prolonged labor -NA"
label variable m31      "At birth - excessive bleedi-NA"
label variable m32      "At birth - high fever/disch-NA"
label variable m33      "At birth - convulsions -NA"
label variable m34      "When child put to breast"
label variable m35      "Times breastfed during night"
label variable m36      "Times breastfed during day"
label variable m37a     "Gave child plain water"
label variable m37b     "Gave child sugar water"
label variable m37c     "Gave child juice"
label variable m37d     "Gave child herbal tea"
label variable m37e     "Gave child powder/tinned mi-NA"
label variable m37f     "Gave child baby formula"
label variable m37g     "Gave child fresh milk"
label variable m37h     "Country specific other liqu-NA"
label variable m37i     "Country specific other liqu-NA"
label variable m37j     "Country specific other liqu-NA"
label variable m37k     "Country specific other liqu-NA"
label variable m37l     "Gave child other liquid"
label variable m37m     "Country specific other food-NA"
label variable m37n     "Country specific other food-NA"
label variable m37o     "Country specific other food-NA"
label variable m37p     "Other solid, semi-solid foods"
label variable m37q     "Food made from local grain -NA"
label variable m37r     "Food made from local tuber -NA"
label variable m37s     "Gave child eggs, fish, poul-NA"
label variable m37t     "Gave child meat"
label variable m38      "Drank from bottle with nipp-NA"
label variable m39      "Times ate other food yester-NA"
label variable m40a     "Last 7 days - plain water -NA"
label variable m40b     "Last 7 days - milk -NA"
label variable m40c     "Last 7 days - other liquids-NA"
label variable m40d     "Last 7 days - local grain f-NA"
label variable m40e     "Last 7 days - local tuber f-NA"
label variable m40f     "Last 7 days - egg/fish/poul-NA"
label variable m40g     "Last 7 days - meat -NA"
label variable m40h     "Last 7 days - other solid f-NA"
label variable m40i     "Last 7 days - country speci-NA"
label variable m40j     "Last 7 days - country speci-NA"
label variable m40k     "Last 7 days - country speci-NA"
label variable m40l     "Last 7 days - country speci-NA"
label variable m40m     "Last 7 days - country speci-NA"
label variable m40n     "Last 7 days - country speci-NA"
label variable m40o     "Last 7 days - country speci-NA"
label variable hidx     "Index to birth history"
label variable h1       "Has health card"
label variable h2       "Received BCG"
label variable h2d      "BCG day"
label variable h2m      "BCG month"
label variable h2y      "BCG year"
label variable h3       "Received DPT 1"
label variable h3d      "DPT 1 day"
label variable h3m      "DPT 1 month"
label variable h3y      "DPT 1 year"
label variable h4       "Received POLIO 1"
label variable h4d      "POLIO 1 day"
label variable h4m      "POLIO 1 month"
label variable h4y      "POLIO 1 year"
label variable h5       "Received DPT 2"
label variable h5d      "DPT 2 day"
label variable h5m      "DPT 2 month"
label variable h5y      "DPT 2 year"
label variable h6       "Received POLIO 2"
label variable h6d      "POLIO 2 day"
label variable h6m      "POLIO 2 month"
label variable h6y      "POLIO 2 year"
label variable h7       "Received DPT 3"
label variable h7d      "DPT 3 day"
label variable h7m      "DPT 3 month"
label variable h7y      "DPT 3 year"
label variable h8       "Received POLIO 3"
label variable h8d      "POLIO 3 day"
label variable h8m      "POLIO 3 month"
label variable h8y      "POLIO 3 year"
label variable h9       "Received MEASLES"
label variable h9d      "MEASLES day"
label variable h9m      "MEASLES month"
label variable h9y      "MEASLES year"
label variable h0       "Polio 0 -NA"
label variable h0d      "Polio 0 day"
label variable h0m      "POLIO 0 month"
label variable h0y      "POLIO 0 year"
label variable h10      "Ever had vaccination"
label variable h11      "Had diarrhea recently"
label variable h11b     "Blood in the stools"
label variable h11c     "Bowel movements in worst da-NA"
label variable h12a     "Diarrhea: government hosp."
label variable h12b     "Diarrhea: govt health center"
label variable h12c     "Diarrhea: govt health post -NA"
label variable h12d     "Diarrhea: mobile clinic -NA"
label variable h12e     "Diarrhea: comm.health worker"
label variable h12f     "Diarrhea: Satellite clinic -CS"
label variable h12g     "Diarrhea: CS public sector -NA"
label variable h12h     "Diarrhea: CS public sector -NA"
label variable h12i     "Diarrhea: CS public sector -NA"
label variable h12j     "Diarrhea: private hosp/clinic"
label variable h12k     "Diarrhea: private pharmacy"
label variable h12l     "Diarrhea: private doctor"
label variable h12m     "Diarrhea: private mobile cl-NA"
label variable h12n     "Diarrhea: comm.health worke-NA"
label variable h12o     "Diarrhea: CS med.priv secto-NA"
label variable h12p     "Diarrhea: CS med.priv secto-NA"
label variable h12q     "Diarrhea: CS med.priv secto-NA"
label variable h12r     "Diarrhea: CS med.priv secto-NA"
label variable h12s     "Diarrhea: shop"
label variable h12t     "Diarrhea: traditional pract."
label variable h12u     "Diarrhea: CS oth.priv secto-NA"
label variable h12v     "Diarrhea: CS oth.priv secto-NA"
label variable h12w     "Diarrhea: CS oth.priv secto-NA"
label variable h12x     "Diarrhea: Other"
label variable h12y     "Diarrhea: no treatment"
label variable h12z     "Diarrhea: medical treatment"
label variable h13      "Given oral rehydration"
label variable h14      "Given recommend. home solution"
label variable h15      "Given other pills or syrups"
label variable h15a     "Given antibiotics (CS) -NA"
label variable h15b     "Given an injection"
label variable h15c     "Given an intravenous (IV)"
label variable h15d     "Given home remedy, herbal med."
label variable h15e     "Given CS other treatment -NA"
label variable h15f     "Given CS other treatment -NA"
label variable h15g     "Given CS other treatment -NA"
label variable h15h     "Given CS other treatment -NA"
label variable h16      "Increase or decrease fluids"
label variable h18      "Increase or decrease in foo-NA"
label variable h20      "Given other treatment"
label variable h21a     "Given no treatment"
label variable h21      "Received any treatment"
label variable h22      "Had fever in last two weeks-NA"
label variable h31      "Had cough in last two weeks"
label variable h31b     "Short, rapid breaths"
label variable h32a     "Fever/cough: government hosp."
label variable h32b     "Fever/cough: govt health cntr"
label variable h32c     "Fever/cough: govt health po-NA"
label variable h32d     "Fever/cough: mobile clinic -NA"
label variable h32e     "Fever/cough: comm.health wrkr"
label variable h32f     "Fever/cough: Satellite clinic"
label variable h32g     "Fever/cough: CS public sect-NA"
label variable h32h     "Fever/cough: CS public sect-NA"
label variable h32i     "Fever/cough: CS public sect-NA"
label variable h32j     "Fever/cough: private hosp/clin"
label variable h32k     "Fever/cough: private pharmacy"
label variable h32l     "Fever/cough: private doctor"
label variable h32m     "Fever/cough: private mobile-NA"
label variable h32n     "Fever/cough: comm.health wr-NA"
label variable h32o     "Fever/cough: CS med.priv se-NA"
label variable h32p     "Fever/cough: CS med.priv se-NA"
label variable h32q     "Fever/cough: CS med.priv se-NA"
label variable h32r     "Fever/cough: CS med.priv se-NA"
label variable h32s     "Fever/cough: shop"
label variable h32t     "Fever/cough: traditional pract"
label variable h32u     "Fever/cough: CS oth.priv se-NA"
label variable h32v     "Fever/cough: CS oth.priv se-NA"
label variable h32w     "Fever/cough: CS oth.priv se-NA"
label variable h32x     "Fever/cough: Other"
label variable h32y     "Fever/cough: no treatment"
label variable h32z     "Fever/cough: medical treatment"
label variable hwidx    "Index to birth history - NA"
label variable hw1      "Age in months - NA"
label variable hw2      "Weight in kilograms (1 de - NA"
label variable hw3      "Height in centimeters (1 - NA"
label variable hw4      "Ht/A Percentile - NA"
label variable hw5      "Ht/A Standard deviations - NA"
label variable hw6      "Ht/A Percent of ref. medi - NA"
label variable hw7      "Wt/A Percentile - NA"
label variable hw8      "Wt/A Standard deviations - NA"
label variable hw9      "Wt/A Percent of ref. medi - NA"
label variable hw10     "Wt/Ht Percentile - NA"
label variable hw11     "Wt/Ht Standard deviations - NA"
label variable hw12     "Wt/Ht Percent of ref. med - NA"
label variable hw13     "Reason not measured"
label variable hw14     "BCG scar on arm or should - NA"
label variable hw15     "Height: lying or standing - NA"
label variable hw16     "Day of birth of child - NA"
label variable hw17     "Date measured (day) - NA"
label variable hw18     "Date measured (month) - NA"
label variable hw19     "Date measured (year) - NA"
label variable hw20     "Arm circumference (cms - - NA"
label variable hw21     "Arm circ/A Percentile - NA"
label variable hw22     "Arm circ/A Standard devia - NA"
label variable hw23     "Arm c/A Percent of ref. m - NA"
label variable hw24     "Arm circ/Ht Percentile - NA"
label variable hw25     "Arm cir/Ht Standard devia - NA"
label variable hw26     "Arm cir/Ht Percent ref. m - NA"
label variable sdformat "Date format of questionnaire"
label variable sadjust  "Month of interview adjusted 1m"
label variable sintm    "Month of interview(unadjusted)"
label variable sinty    "Year of interview(unadjusted)"
label variable sdiv     "Division"
label variable sdistr   "District of residence"
label variable s114a    "Grameen Bank"
label variable s114b    "BRAC"
label variable s114c    "BRDP"
label variable s114d    "Mothers club"
label variable s114e    "Other"
label variable s119     "Time to get to water (mins)"
label variable s119a    "Time to wait to get water:mins"
label variable s123     "Toilet facility : children"
label variable s124a    "Almirah"
label variable s124b    "Table/chair/bench"
label variable s124c    "Watch/clock"
label variable s124d    "Cot/bed"
label variable s124i    "Agricultural land"
label variable s229m    "Month pregnancy ended"
label variable s229y    "Year pregnancy ended"
label variable s233a    "Ever had unwanted pregnancy"
label variable s233b    "Pregancy aborted/menst.reg'ltn"
label variable s233c    "Pregnancy ended by MR/D&C"
label variable s233dm   "When pr. ended : Month"
label variable s233dy   "When pregnancy ended :Year"

#delimit ;
label define V013    
     0 "10-14"
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
     9 "Missing"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V023    
     0 "National"
     1 "Country specific"
;
label define V024    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define V034    
     0 "Husband not in HH"
    99 "Missing"
;
label define V101    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     9 "Missing"
;
label define V108    
     1 "Reads easily"
     2 "Reads with difficult"
     3 "Cannot read"
     9 "Missing"
;
label define V109    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V110    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V112    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
    99 "Missing"
;
label define V114    
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
    99 "Missing"
;
label define V115    
   996 "On premises"
   999 "Missing"
;
label define V116    
    10 "FLUSH TOILET"
    20 "PIT TOILET LATRINE"
    30 "NO FACILITY"
    96 "OTHER"
    99 "Missing"
;
label define V119    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V120    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V121    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V123    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V127    
    10 "NATURAL"
    11 "Earth"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
    99 "Missing"
;
label define V128    
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Brick/cement"
    32 "Tin"
    96 "OTHER"
    99 "Missing"
;
label define V129    
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Tin"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
    99 "Missing"
;
label define V130    
     1 "Islam"
     2 "Christianity"
     3 "Hinduism"
     4 "Buddhism"
     5 "Other"
     9 "Missing"
;
label define V133    
    97 "Inconsistent"
    99 "Missing"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
     9 "Missing"
;
label define V139    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
    99 "Missing"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     9 "Missing"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define V142    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V148    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     9 "Missing"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Grand-daughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
    99 "Missing"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    96 "96+"
    99 "Missing"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
     9 "Missing"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V227    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + amen. > interval"
     3 "N, but per. not ret."
     4 "95, but no birth"
     5 "96, but per.returned"
     6 "95, but per.returned"
     7 "N, last per. in preg"
     8 "96, had children"
     9 "N, per.bef.last birt"
;
label define V228    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V229    
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define V230    
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define V231    
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V234    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V235    
     0 "No prior child"
;
label define V311    
     4 "4+"
     5 "Never used"
     9 "Missing"
;
label define V312    
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define V313    
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     9 "Missing"
;
label define V318    
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
;
label define V319    
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
;
label define V320    
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45-49"
;
label define V321    
     0 "Single,before marr."
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
;
label define V322    
     5 "5+"
;
label define V323    
     1 "Maya"
     2 "Ovacon"
     3 "Norquest"
     4 "Noriday"
     5 "Ovral"
     6 "Combination-5"
     7 "Ovostat"
     8 "Restovar-NA"
     9 "Lyndiol"
    10 "Nordette"
    11 "Marvelou"
    96 "Other pill brand"
    99 "Missing"
;
label define V326    
    10 "PUBLIC"
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    20 "PRIVATE MEDICAL"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    30 "OTHER PRIVATE"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "OTHER"
    98 "DK"
    99 "Missing"
;
label define V327    
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
     9 "Missing"
;
label define V337    
    95 "All cal. {A core}"
    96 "96+ {B core}"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V359    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define V360    
     1 "Became pregnant"
     2 "Wanted to become prg"
     3 "Husband disapproved"
     4 "Side effects"
     5 "Health concerns"
     6 "Access, availability"
     7 "Wanted more eff.meth"
     8 "Inconvenient to use"
     9 "Infreq.sex,husb away"
    10 "Cost"
    11 "Fatalistic"
    12 "Diff.preg.,menopause"
    13 "Marital dissolution"
    14 "Other"
    98 "Don't know"
    99 "Missing"
;
label define V361    
     1 "Currently using"
     2 "Used since last brth"
     3 "Used before last brt"
     4 "Never used"
;
label define V362    
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
     9 "Missing"
;
label define V363    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    98 "Don't know"
    99 "Missing"
;
label define V364    
     1 "Using modern method"
     2 "Using tradit. method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
;
label define V366A   
     0 "Not acceptable"
     1 "Acceptable"
     8 "Don't know"
     9 "Missing"
;
label define V367    
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
     9 "Missing"
;
label define V369    
     0 "Never used"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define V372    
     0 "Package not seen"
     1 "Package seen"
     9 "Missing"
;
label define V375A   
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V376    
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V379    
    10 "PUBLIC"
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    20 "PRIVATE MEDICAL"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    30 "OTHER PRIVATE"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "OTHER"
    98 "DK"
    99 "Missing"
;
label define V380    
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
     9 "Missing"
;
label define V384A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V384B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V384D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V393    
     0 "No"
     1 "Yes - 6 months"
     8 "Don't know"
     9 "Missing"
;
label define V394    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V395    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V396    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define V401    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V404    
     0 "No"
     1 "Yes"
;
label define V405    
     0 "No"
     1 "Yes"
;
label define V406    
     0 "No"
     1 "Yes"
;
label define V407    
    96 "On demand"
    99 "Missing"
;
label define V408    
    96 "On demand"
    99 "Missing"
;
label define V409    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V409A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V410    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V410A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V411A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V412    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V413    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414E   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414F   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414G   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414H   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V416    
     0 "Never heard of"
     1 "Used ORS"
     2 "Heard of ORS"
     9 "Missing"
;
label define V426    
     0 "Immediately"
   999 "Missing"
;
label define V501    
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
     9 "Missing"
;
label define V502    
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
     9 "Missing"
;
label define V503    
     1 "Once"
     2 "More than once"
     9 "Missing"
;
label define V504    
     1 "Living with her"
     2 "Staying elsewhere"
     9 "Missing"
;
label define V510    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V513    
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define V527    
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V528    
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V529    
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V530    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + abst. > interval"
     3 "N, but sex not res."
     4 "96, but no birth"
     5 "96, but curr.preg."
     6 "96, but resumed sex"
     7 "N, last sex bef preg"
     8 "N, inconsis 4 weeks"
     9 "N, sex bef last birt"
;
label define V535    
     0 "No"
     1 "Formerly married"
     2 "Lived with a man"
     9 "Missing"
;
label define V602    
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Declared infecund"
     6 "Never had sex"
     9 "Missing"
;
label define V603    
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V604    
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
     9 "Missing"
;
label define V605    
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
     9 "Missing"
;
label define V606    
     1 "Happy"
     2 "Unhappy"
     3 "Would not matter"
     8 "DK"
     9 "Missing"
;
label define V610    
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define V611    
     0 "Never"
     1 "Once or twice"
     2 "More often"
     9 "Missing"
;
label define V612    
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define V613    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V614    
     6 "6+"
     7 "Non-numeric response"
;
label define V616    
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
   999 "Missing"
;
label define V618    
     0 "No regret"
     1 "Resp. wants another"
     2 "Part. wants another"
     3 "Side effects"
     4 "Child died"
     6 "Other reason"
     9 "Missing"
;
label define V621    
     1 "Both want same"
     2 "Husband wants more"
     3 "Husband wants fewer"
     8 "DK"
     9 "Missing"
;
label define V623    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
     9 "Missing"
;
label define V624    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
    99 "Missing"
;
label define V625    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
     9 "Missing"
;
label define V626    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
    99 "Missing"
;
label define V627    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V628    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V629    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V701    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
     9 "Missing"
;
label define V702    
    98 "Don't know"
    99 "Missing"
;
label define V704    
    11 "Land owner"
    12 "Farmer"
    13 "Agricultural worker"
    14 "Fisherman"
    21 "Unskilled labourers"
    22 "Domestic servant"
    23 "Non-agricultural wkr"
    31 "Semi-skilled labour"
    41 "Professional worker"
    51 "Business"
    52 "Small business/tradr"
    61 "Unemployed"
    62 "Retired"
    96 "Others"
    98 "Don't know"
   999 "Missing"
;
label define V705    
     0 "Did not work"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
    99 "Missing"
;
label define V707    
     0 "His land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
     9 "Missing"
;
label define V714    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V715    
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V716    
     0 "Not working"
    11 "Land owner"
    12 "Farmer"
    13 "Agricultural worker"
    14 "Fisherman"
    21 "Unskilled labourers"
    22 "Domestic servant"
    23 "Non-agricultural wkr"
    31 "Semi-skilled labour"
    41 "Professional worker"
    51 "Business"
    52 "Small business/tradr"
    61 "Unemployed"
    62 "Retired"
    96 "Others"
    98 "Don't know"
   999 "Missing"
;
label define V717    
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
    99 "Missing"
;
label define V718    
     0 "Did not work"
     1 "Paid employee, away"
     2 "Paid employee, home"
     3 "Self-employed, away"
     4 "Self-employed, home"
     5 "Unpaid worker, away"
     6 "Unpaid worker, home"
     9 "Missing"
;
label define V719    
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
     9 "Missing"
;
label define V720    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V721    
     1 "At home"
     2 "Away"
     9 "Missing"
;
label define V723    
     0 "Respondent"
     1 "Husband/partner"
     2 "Other child"
     3 "Other relatives"
     4 "Neighbors"
     5 "Friends"
     6 "Servants/hired help"
     7 "Child is in school"
     8 "Institutional care"
    10 "Other female child"
    11 "Other male child"
    95 "Not worked since bth"
    96 "Other"
    99 "Missing"
;
label define V729    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
     9 "Missing"
;
label define V732    
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
     9 "Missing"
;
label define V739    
     1 "Respondent"
     2 "Partner"
     3 "Jointly with partner"
     4 "Someone else"
     5 "Jointly with someone"
     9 "Missing"
;
label define V740    
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
     9 "Missing"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
     9 "Missing"
;
label define B10     
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define M1      
     0 "Received no inject."
     7 "7+"
     8 "Don't know"
     9 "Missing"
;
label define M2A     
     0 "No"
     1 "Yes: doctor"
     9 "Missing"
;
label define M2B     
     0 "No"
     1 "Yes: nurse/midwife"
     9 "Missing"
;
label define M2D     
     0 "No"
     1 "Yes: FW Visitor ."
     9 "Missing"
;
label define M2F     
     0 "No"
     1 "Yes: trained birth A"
     9 "Missing"
;
label define M2G     
     0 "No"
     1 "Yes: trad.birth att."
     9 "Missing"
;
label define M2K     
     0 "No"
     1 "Yes: other responses"
     9 "Missing"
;
label define M2N     
     0 "No: some care"
     1 "Yes: no one"
     9 "Missing"
;
label define M3A     
     0 "No"
     1 "Yes: doctor"
     9 "Missing"
;
label define M3B     
     0 "No"
     1 "Yes: nurse/midwife"
     9 "Missing"
;
label define M3D     
     0 "No"
     1 "Yes: FW Visitor ."
     9 "Missing"
;
label define M3F     
     0 "No"
     1 "Yes: trained birth A"
     9 "Missing"
;
label define M3G     
     0 "No"
     1 "Yes: trad.birth att."
     9 "Missing"
;
label define M3H     
     0 "No"
     1 "Yes: relative,friend"
     9 "Missing"
;
label define M3K     
     0 "No"
     1 "Yes: other responses"
     9 "Missing"
;
label define M3M     
     0 "No"
     1 "Yes: CS other"
     9 "Missing"
;
label define M3N     
     0 "No: some assistance"
     1 "Yes: no one"
     9 "Missing"
;
label define M4      
    94 "Never breastfed"
    95 "Still breastfeeding"
    96 "Breastfed until died"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define M5      
    94 "Never breastfed"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define M6      
    96 "Period not returned"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define M7      
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define M8      
    96 "Still abstaining"
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define M9      
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define M10     
     1 "Then"
     2 "Later"
     3 "No more"
     9 "Missing"
;
label define M13     
    98 "DK"
    99 "Missing"
;
label define M14     
     0 "No antenatal visits"
    98 "DK"
    99 "Missing"
;
label define M15     
    10 "HOMES"
    11 "Respondents home"
    12 "Other home"
    20 "PUBLIC SECTOR"
    21 "Govt. hospital"
    22 "Govt. health center"
    23 "Govt. health post"
    26 "Other public"
    30 "PRIVATE SECTOR"
    31 "Private hosp/clinic"
    36 "Other private medica"
    96 "OTHER"
    99 "Missing"
;
label define M21     
     1 "Mother ill, weak"
     2 "Child ill, weak"
     3 "Child died"
     4 "Nipple, breast prob."
     5 "Insufficient milk"
     6 "Working"
     7 "Child refused"
     8 "Weaning age"
     9 "Became pregnant"
    10 "Started using method"
    96 "Other"
    97 "Missing ever breastf"
    99 "Missing"
;
label define M27     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     3 "> age at death"
     4 "During preg in cal."
;
label define M28     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     4 "During preg in cal."
;
label define M29     
     0 "No flag"
     1 "> interval"
     2 "> interval by 1 mnth"
     4 "During preg in cal."
;
label define M34     
     0 "Immediately"
   101 "Hours: 1"
   201 "Days: 1"
   999 "Missing"
;
label define M35     
    96 "On demand"
    99 "Missing"
;
label define M36     
    96 "On demand"
    99 "Missing"
;
label define M37A    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37B    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37C    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37D    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37F    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37G    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37L    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37P    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define M37T    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define H1      
     0 "No card"
     1 "Yes, seen"
     2 "Yes, not seen"
     3 "No longer has card"
     9 "Missing"
;
label define H2      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H2D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H2M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H2Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H3      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H3D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H3M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H3Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H4      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H4D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H4M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H4Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H5      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H5D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H5M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H5Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H6      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H6D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H6M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H6Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H7      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H7D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H7M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H7Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H8      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H8D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H8M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H8Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H9      
     0 "No"
     1 "Vacc. date on card"
     2 "Reported by mother"
     3 "Vacc. marked on card"
     8 "DK"
     9 "Missing"
;
label define H9D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H9M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H9Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H0D     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H0M     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H0Y     
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define H10     
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define H11     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
     9 "Missing"
;
label define H11B    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define H12A    
     0 "No"
     1 "Government hospital"
     9 "Missing"
;
label define H12B    
     0 "No"
     1 "Govt. health center"
     9 "Missing"
;
label define H12E    
     0 "No"
     1 "Comm.health worker"
     9 "Missing"
;
label define H12F    
     0 "No"
     1 "Satellite clinic"
     9 "Missing"
;
label define H12J    
     0 "No"
     1 "Private hosp/clinic"
     9 "Missing"
;
label define H12K    
     0 "No"
     1 "Private pharmacy"
     9 "Missing"
;
label define H12L    
     0 "No"
     1 "Private doctor"
     9 "Missing"
;
label define H12S    
     0 "No"
     1 "Shop"
     9 "Missing"
;
label define H12T    
     0 "No"
     1 "Traditional pract."
     9 "Missing"
;
label define H12X    
     0 "No"
     1 "Other"
     9 "Missing"
;
label define H12Y    
     0 "No: received treatm."
     1 "Yes: no treatment"
     9 "Missing"
;
label define H12Z    
     0 "No"
     1 "Yes: medical treatm."
     9 "Missing"
;
label define H13     
     0 "No"
     1 "Yes: ORS - spontan."
     2 "Yes: ORS - probed"
     8 "Don't know"
     9 "Missing"
;
label define H14     
     0 "No"
     1 "Yes: RHS - spontan."
     2 "Yes: RHS - probed"
     8 "Don't know"
     9 "Missing"
;
label define H15     
     0 "No"
     1 "Yes: oth pill, syrup"
     9 "Missing"
;
label define H15B    
     0 "No"
     1 "Yes: injection"
     9 "Missing"
;
label define H15C    
     0 "No"
     1 "Yes: intravenous (IV"
     9 "Missing"
;
label define H15D    
     0 "No"
     1 "Yes: home rem, herb."
     9 "Missing"
;
label define H16     
     0 "Same"
     1 "Increase"
     2 "Decrease"
     8 "DK"
     9 "Missing"
;
label define H20     
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define H21A    
     0 "No: received treatm."
     1 "Yes: no treatment"
     8 "DK"
     9 "Missing"
;
label define H21     
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define H31     
     0 "No"
     1 "Yes, last 24 hours"
     2 "Yes, last two weeks"
     8 "Don't know"
     9 "Missing"
;
label define H31B    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define H32A    
     0 "No"
     1 "Government hospital"
     9 "Missing"
;
label define H32B    
     0 "No"
     1 "Govt. health center"
     9 "Missing"
;
label define H32E    
     0 "No"
     1 "Community health wrk"
     9 "Missing"
;
label define H32F    
     0 "No"
     1 "Satellite clinic"
     9 "Missing"
;
label define H32J    
     0 "No"
     1 "Private hosp./clinic"
     9 "Missing"
;
label define H32K    
     0 "No"
     1 "Private pharmacy"
     9 "Missing"
;
label define H32L    
     0 "No"
     1 "Private doctor"
     9 "Missing"
;
label define H32S    
     0 "No"
     1 "Shop"
     9 "Missing"
;
label define H32T    
     0 "No"
     1 "Traditional pract."
     9 "Missing"
;
label define H32X    
     0 "No"
     1 "Other"
     9 "Missing"
;
label define H32Y    
     0 "No: received treatm."
     1 "Yes: no treatment"
     9 "Missing"
;
label define H32Z    
     0 "No"
     1 "Yes: medical treatm."
     9 "Missing"
;
label define SDFORMAT
     1 "Bengali"
     2 "English"
;
label define SADJUST 
     0 "Not adjusted"
     1 "Adjusted"
;
label define SDIV    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define S114A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114E   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S119    
   996 "On premises"
   999 "Missing"
;
label define S123    
     0 "No children"
    11 "Sep.tank/modern tlet"
    21 "Water sld/Slab latr."
    22 "Pit latrine"
    23 "Open latrine"
    24 "Hanging latrine"
    31 "No facility,bush"
    96 "Other"
    99 "Missing"
;
label define S124A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124I   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S229M   
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define S229Y   
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define S233A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S233B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S233C   
     1 "Menstrual regulation"
     2 "Induced abortion/D&C"
     3 "Other"
     9 "Missing"
;
label define S233DY  
  1300 "Bengali (Start)"
  1401 "Bengali (end)"
  1900 "English (Start)"
  1994 "English(end)"
  9997 "Inconsistent"
  9998 "Don't Know"
  9999 "Missing"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v020     V020    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v101     V101    
label values v102     V102    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v108     V108    
label values v109     V109    
label values v110     V110    
label values v112     V112    
label values v113     V113    
label values v114     V114    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v123     V123    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v142     V142    
label values v148     V148    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v311     V311    
label values v312     V312    
label values v313     V313    
label values v318     V318    
label values v319     V319    
label values v320     V320    
label values v321     V321    
label values v322     V322    
label values v323     V323    
label values v326     V326    
label values v327     V327    
label values v337     V337    
label values v359     V359    
label values v360     V360    
label values v361     V361    
label values v362     V362    
label values v363     V363    
label values v364     V364    
label values v366a    V366A   
label values v367     V367    
label values v369     V369    
label values v372     V372    
label values v375a    V375A   
label values v376     V376    
label values v379     V379    
label values v380     V380    
label values v384a    V384A   
label values v384b    V384B   
label values v384d    V384D   
label values v393     V393    
label values v394     V394    
label values v395     V395    
label values v396     V396    
label values v401     V401    
label values v404     V404    
label values v405     V405    
label values v406     V406    
label values v407     V407    
label values v408     V408    
label values v409     V409    
label values v409a    V409A   
label values v410     V410    
label values v410a    V410A   
label values v411a    V411A   
label values v412     V412    
label values v413     V413    
label values v414d    V414D   
label values v414e    V414E   
label values v414f    V414F   
label values v414g    V414G   
label values v414h    V414H   
label values v416     V416    
label values v426     V426    
label values v501     V501    
label values v502     V502    
label values v503     V503    
label values v504     V504    
label values v510     V510    
label values v513     V513    
label values v527     V527    
label values v528     V528    
label values v529     V529    
label values v530     V530    
label values v535     V535    
label values v602     V602    
label values v603     V603    
label values v604     V604    
label values v605     V605    
label values v606     V606    
label values v610     V610    
label values v611     V611    
label values v612     V612    
label values v613     V613    
label values v614     V614    
label values v616     V616    
label values v618     V618    
label values v621     V621    
label values v623     V623    
label values v624     V624    
label values v625     V625    
label values v626     V626    
label values v627     V627    
label values v628     V628    
label values v629     V629    
label values v701     V701    
label values v702     V702    
label values v704     V704    
label values v705     V705    
label values v707     V707    
label values v714     V714    
label values v715     V715    
label values v716     V716    
label values v717     V717    
label values v718     V718    
label values v719     V719    
label values v720     V720    
label values v721     V721    
label values v723     V723    
label values v729     V729    
label values v732     V732    
label values v739     V739    
label values v740     V740    
label values b0       B0      
label values b4       B4      
label values b5       B5      
label values b6       B6      
label values b9       B9      
label values b10      B10     
label values b13      B13     
label values m1       M1      
label values m2a      M2A     
label values m2b      M2B     
label values m2d      M2D     
label values m2f      M2F     
label values m2g      M2G     
label values m2k      M2K     
label values m2n      M2N     
label values m3a      M3A     
label values m3b      M3B     
label values m3d      M3D     
label values m3f      M3F     
label values m3g      M3G     
label values m3h      M3H     
label values m3k      M3K     
label values m3m      M3M     
label values m3n      M3N     
label values m4       M4      
label values m5       M5      
label values m6       M6      
label values m7       M7      
label values m8       M8      
label values m9       M9      
label values m10      M10     
label values m13      M13     
label values m14      M14     
label values m15      M15     
label values m21      M21     
label values m27      M27     
label values m28      M28     
label values m29      M29     
label values m34      M34     
label values m35      M35     
label values m36      M36     
label values m37a     M37A    
label values m37b     M37B    
label values m37c     M37C    
label values m37d     M37D    
label values m37f     M37F    
label values m37g     M37G    
label values m37l     M37L    
label values m37p     M37P    
label values m37t     M37T    
label values h1       H1      
label values h2       H2      
label values h2d      H2D     
label values h2m      H2M     
label values h2y      H2Y     
label values h3       H3      
label values h3d      H3D     
label values h3m      H3M     
label values h3y      H3Y     
label values h4       H4      
label values h4d      H4D     
label values h4m      H4M     
label values h4y      H4Y     
label values h5       H5      
label values h5d      H5D     
label values h5m      H5M     
label values h5y      H5Y     
label values h6       H6      
label values h6d      H6D     
label values h6m      H6M     
label values h6y      H6Y     
label values h7       H7      
label values h7d      H7D     
label values h7m      H7M     
label values h7y      H7Y     
label values h8       H8      
label values h8d      H8D     
label values h8m      H8M     
label values h8y      H8Y     
label values h9       H9      
label values h9d      H9D     
label values h9m      H9M     
label values h9y      H9Y     
label values h0d      H0D     
label values h0m      H0M     
label values h0y      H0Y     
label values h10      H10     
label values h11      H11     
label values h11b     H11B    
label values h12a     H12A    
label values h12b     H12B    
label values h12e     H12E    
label values h12f     H12F    
label values h12j     H12J    
label values h12k     H12K    
label values h12l     H12L    
label values h12s     H12S    
label values h12t     H12T    
label values h12x     H12X    
label values h12y     H12Y    
label values h12z     H12Z    
label values h13      H13     
label values h14      H14     
label values h15      H15     
label values h15b     H15B    
label values h15c     H15C    
label values h15d     H15D    
label values h16      H16     
label values h20      H20     
label values h21a     H21A    
label values h21      H21     
label values h31      H31     
label values h31b     H31B    
label values h32a     H32A    
label values h32b     H32B    
label values h32e     H32E    
label values h32f     H32F    
label values h32j     H32J    
label values h32k     H32K    
label values h32l     H32L    
label values h32s     H32S    
label values h32t     H32T    
label values h32x     H32X    
label values h32y     H32Y    
label values h32z     H32Z    
label values sdformat SDFORMAT
label values sadjust  SADJUST 
label values sdiv     SDIV    
label values s114a    S114A   
label values s114b    S114B   
label values s114c    S114C   
label values s114d    S114D   
label values s114e    S114E   
label values s119     S119    
label values s123     S123    
label values s124a    S124A   
label values s124b    S124B   
label values s124c    S124C   
label values s124d    S124D   
label values s124i    S124I   
label values s229m    S229M   
label values s229y    S229Y   
label values s233a    S233A   
label values s233b    S233B   
label values s233c    S233C   
label values s233dy   S233DY  
