DATA LIST FILE='BDCR31FL.DAT' RECORDS=1
/
 CASEID      1-15   (A)
 V000       16-18   (A)
 V001       19-26
 V002       27-30
 V003       31-33
 V004       34-37
 V005       38-45
 V006       46-47
 V007       48-49
 V008       50-53
 V009       54-55
 V010       56-57
 V011       58-61
 V012       62-63
 V013       64-64
 V014       65-65
 V015       66-66
 V016       67-68
 V017       69-72
 V018       73-74
 V019       75-76
 V020       77-77
 V021       78-81
 V022       82-85
 V023       86-87
 V024       88-89
 V025       90-90
 V026       91-91
 V027       92-92
 V028       93-95
 V029       96-97
 V030       98-99
 V031      100-101
 V032      102-103
 V033      104-111
 V034      112-113
 V101      114-115
 V102      116-116
 V103      117-117
 V104      118-119
 V105      120-120
 V106      121-121
 V107      122-123
 V108      124-124
 V109      125-125
 V110      126-126
 V111      127-127
 V112      128-128
 V113      129-130
 V114      131-132
 V115      133-135
 V116      136-137
 V119      138-138
 V120      139-139
 V121      140-140
 V122      141-141
 V123      142-142
 V124      143-143
 V125      144-144
 V127      145-146
 V128      147-148
 V129      149-150
 V130      151-151
 V131      152-153
 V133      154-155
 V134      156-156
 V135      157-157
 V136      158-159
 V137      160-161
 V138      162-163
 V139      164-165
 V140      166-166
 V141      167-167
 V142      168-168
 V144      169-169
 V148      170-170
 V149      171-171
 V150      172-173
 V151      174-174
 V152      175-176
 V153      177-177
 V154      178-179
 AWFACTT   180-184
 AWFACTU   185-189
 AWFACTR   190-194
 AWFACTE   195-199
 BIDX$01   200-201
 BORD$01   202-203
 B0$01     204-204
 B1$01     205-206
 B2$01     207-208
 B3$01     209-212
 B4$01     213-213
 B5$01     214-214
 B6$01     215-217
 B7$01     218-220
 B8$01     221-222
 B9$01     223-223
 B10$01    224-224
 B11$01    225-227
 B12$01    228-230
 B13$01    231-231
 B14$01    232-232
 B15$01    233-233
 BIDX$02   234-235
 BORD$02   236-237
 B0$02     238-238
 B1$02     239-240
 B2$02     241-242
 B3$02     243-246
 B4$02     247-247
 B5$02     248-248
 B6$02     249-251
 B7$02     252-254
 B8$02     255-256
 B9$02     257-257
 B10$02    258-258
 B11$02    259-261
 B12$02    262-264
 B13$02    265-265
 B14$02    266-266
 B15$02    267-267
 BIDX$03   268-269
 BORD$03   270-271
 B0$03     272-272
 B1$03     273-274
 B2$03     275-276
 B3$03     277-280
 B4$03     281-281
 B5$03     282-282
 B6$03     283-285
 B7$03     286-288
 B8$03     289-290
 B9$03     291-291
 B10$03    292-292
 B11$03    293-295
 B12$03    296-298
 B13$03    299-299
 B14$03    300-300
 B15$03    301-301
 BIDX$04   302-303
 BORD$04   304-305
 B0$04     306-306
 B1$04     307-308
 B2$04     309-310
 B3$04     311-314
 B4$04     315-315
 B5$04     316-316
 B6$04     317-319
 B7$04     320-322
 B8$04     323-324
 B9$04     325-325
 B10$04    326-326
 B11$04    327-329
 B12$04    330-332
 B13$04    333-333
 B14$04    334-334
 B15$04    335-335
 BIDX$05   336-337
 BORD$05   338-339
 B0$05     340-340
 B1$05     341-342
 B2$05     343-344
 B3$05     345-348
 B4$05     349-349
 B5$05     350-350
 B6$05     351-353
 B7$05     354-356
 B8$05     357-358
 B9$05     359-359
 B10$05    360-360
 B11$05    361-363
 B12$05    364-366
 B13$05    367-367
 B14$05    368-368
 B15$05    369-369
 BIDX$06   370-371
 BORD$06   372-373
 B0$06     374-374
 B1$06     375-376
 B2$06     377-378
 B3$06     379-382
 B4$06     383-383
 B5$06     384-384
 B6$06     385-387
 B7$06     388-390
 B8$06     391-392
 B9$06     393-393
 B10$06    394-394
 B11$06    395-397
 B12$06    398-400
 B13$06    401-401
 B14$06    402-402
 B15$06    403-403
 BIDX$07   404-405
 BORD$07   406-407
 B0$07     408-408
 B1$07     409-410
 B2$07     411-412
 B3$07     413-416
 B4$07     417-417
 B5$07     418-418
 B6$07     419-421
 B7$07     422-424
 B8$07     425-426
 B9$07     427-427
 B10$07    428-428
 B11$07    429-431
 B12$07    432-434
 B13$07    435-435
 B14$07    436-436
 B15$07    437-437
 BIDX$08   438-439
 BORD$08   440-441
 B0$08     442-442
 B1$08     443-444
 B2$08     445-446
 B3$08     447-450
 B4$08     451-451
 B5$08     452-452
 B6$08     453-455
 B7$08     456-458
 B8$08     459-460
 B9$08     461-461
 B10$08    462-462
 B11$08    463-465
 B12$08    466-468
 B13$08    469-469
 B14$08    470-470
 B15$08    471-471
 BIDX$09   472-473
 BORD$09   474-475
 B0$09     476-476
 B1$09     477-478
 B2$09     479-480
 B3$09     481-484
 B4$09     485-485
 B5$09     486-486
 B6$09     487-489
 B7$09     490-492
 B8$09     493-494
 B9$09     495-495
 B10$09    496-496
 B11$09    497-499
 B12$09    500-502
 B13$09    503-503
 B14$09    504-504
 B15$09    505-505
 BIDX$10   506-507
 BORD$10   508-509
 B0$10     510-510
 B1$10     511-512
 B2$10     513-514
 B3$10     515-518
 B4$10     519-519
 B5$10     520-520
 B6$10     521-523
 B7$10     524-526
 B8$10     527-528
 B9$10     529-529
 B10$10    530-530
 B11$10    531-533
 B12$10    534-536
 B13$10    537-537
 B14$10    538-538
 B15$10    539-539
 BIDX$11   540-541
 BORD$11   542-543
 B0$11     544-544
 B1$11     545-546
 B2$11     547-548
 B3$11     549-552
 B4$11     553-553
 B5$11     554-554
 B6$11     555-557
 B7$11     558-560
 B8$11     561-562
 B9$11     563-563
 B10$11    564-564
 B11$11    565-567
 B12$11    568-570
 B13$11    571-571
 B14$11    572-572
 B15$11    573-573
 BIDX$12   574-575
 BORD$12   576-577
 B0$12     578-578
 B1$12     579-580
 B2$12     581-582
 B3$12     583-586
 B4$12     587-587
 B5$12     588-588
 B6$12     589-591
 B7$12     592-594
 B8$12     595-596
 B9$12     597-597
 B10$12    598-598
 B11$12    599-601
 B12$12    602-604
 B13$12    605-605
 B14$12    606-606
 B15$12    607-607
 BIDX$13   608-609
 BORD$13   610-611
 B0$13     612-612
 B1$13     613-614
 B2$13     615-616
 B3$13     617-620
 B4$13     621-621
 B5$13     622-622
 B6$13     623-625
 B7$13     626-628
 B8$13     629-630
 B9$13     631-631
 B10$13    632-632
 B11$13    633-635
 B12$13    636-638
 B13$13    639-639
 B14$13    640-640
 B15$13    641-641
 BIDX$14   642-643
 BORD$14   644-645
 B0$14     646-646
 B1$14     647-648
 B2$14     649-650
 B3$14     651-654
 B4$14     655-655
 B5$14     656-656
 B6$14     657-659
 B7$14     660-662
 B8$14     663-664
 B9$14     665-665
 B10$14    666-666
 B11$14    667-669
 B12$14    670-672
 B13$14    673-673
 B14$14    674-674
 B15$14    675-675
 BIDX$15   676-677
 BORD$15   678-679
 B0$15     680-680
 B1$15     681-682
 B2$15     683-684
 B3$15     685-688
 B4$15     689-689
 B5$15     690-690
 B6$15     691-693
 B7$15     694-696
 B8$15     697-698
 B9$15     699-699
 B10$15    700-700
 B11$15    701-703
 B12$15    704-706
 B13$15    707-707
 B14$15    708-708
 B15$15    709-709
 BIDX$16   710-711
 BORD$16   712-713
 B0$16     714-714
 B1$16     715-716
 B2$16     717-718
 B3$16     719-722
 B4$16     723-723
 B5$16     724-724
 B6$16     725-727
 B7$16     728-730
 B8$16     731-732
 B9$16     733-733
 B10$16    734-734
 B11$16    735-737
 B12$16    738-740
 B13$16    741-741
 B14$16    742-742
 B15$16    743-743
 BIDX$17   744-745
 BORD$17   746-747
 B0$17     748-748
 B1$17     749-750
 B2$17     751-752
 B3$17     753-756
 B4$17     757-757
 B5$17     758-758
 B6$17     759-761
 B7$17     762-764
 B8$17     765-766
 B9$17     767-767
 B10$17    768-768
 B11$17    769-771
 B12$17    772-774
 B13$17    775-775
 B14$17    776-776
 B15$17    777-777
 BIDX$18   778-779
 BORD$18   780-781
 B0$18     782-782
 B1$18     783-784
 B2$18     785-786
 B3$18     787-790
 B4$18     791-791
 B5$18     792-792
 B6$18     793-795
 B7$18     796-798
 B8$18     799-800
 B9$18     801-801
 B10$18    802-802
 B11$18    803-805
 B12$18    806-808
 B13$18    809-809
 B14$18    810-810
 B15$18    811-811
 BIDX$19   812-813
 BORD$19   814-815
 B0$19     816-816
 B1$19     817-818
 B2$19     819-820
 B3$19     821-824
 B4$19     825-825
 B5$19     826-826
 B6$19     827-829
 B7$19     830-832
 B8$19     833-834
 B9$19     835-835
 B10$19    836-836
 B11$19    837-839
 B12$19    840-842
 B13$19    843-843
 B14$19    844-844
 B15$19    845-845
 BIDX$20   846-847
 BORD$20   848-849
 B0$20     850-850
 B1$20     851-852
 B2$20     853-854
 B3$20     855-858
 B4$20     859-859
 B5$20     860-860
 B6$20     861-863
 B7$20     864-866
 B8$20     867-868
 B9$20     869-869
 B10$20    870-870
 B11$20    871-873
 B12$20    874-876
 B13$20    877-877
 B14$20    878-878
 B15$20    879-879
 V201      880-881
 V202      882-883
 V203      884-885
 V204      886-887
 V205      888-889
 V206      890-891
 V207      892-893
 V208      894-894
 V209      895-895
 V210      896-896
 V211      897-900
 V212      901-902
 V213      903-903
 V214      904-905
 V215      906-908
 V216      909-909
 V217      910-910
 V218      911-912
 V219      913-914
 V220      915-915
 V221      916-918
 V222      919-921
 V223      922-922
 V224      923-924
 V225      925-925
 V226      926-928
 V227      929-929
 V228      930-930
 V229      931-932
 V230      933-934
 V231      935-938
 V232      939-939
 V233      940-941
 V234      942-942
 V235      943-944
 V236      945-945
 V237      946-946
 V238      947-947
 V301      948-948
 V302      949-949
 V304A$01  950-950
 V304$01   951-951
 V305$01   952-952
 V304A$02  953-953
 V304$02   954-954
 V305$02   955-955
 V304A$03  956-956
 V304$03   957-957
 V305$03   958-958
 V304A$04  959-959
 V304$04   960-960
 V305$04   961-961
 V304A$05  962-962
 V304$05   963-963
 V305$05   964-964
 V304A$06  965-965
 V304$06   966-966
 V305$06   967-967
 V304A$07  968-968
 V304$07   969-969
 V305$07   970-970
 V304A$08  971-971
 V304$08   972-972
 V305$08   973-973
 V304A$09  974-974
 V304$09   975-975
 V305$09   976-976
 V304A$10  977-977
 V304$10   978-978
 V305$10   979-979
 V304A$11  980-980
 V304$11   981-981
 V305$11   982-982
 V304A$12  983-983
 V304$12   984-984
 V305$12   985-985
 V304A$13  986-986
 V304$13   987-987
 V305$13   988-988
 V304A$14  989-989
 V304$14   990-990
 V305$14   991-991
 V304A$15  992-992
 V304$15   993-993
 V305$15   994-994
 V310      995-996
 V311      997-997
 V312      998-999
 V313     1000-1000
 V314     1001-1001
 V315     1002-1003
 V316     1004-1005
 V317     1006-1009
 V318     1010-1010
 V319     1011-1011
 V320     1012-1012
 V321     1013-1013
 V322     1014-1014
 V323     1015-1016
 V325     1017-1022
 V326     1023-1024
 V327     1025-1025
 V328     1026-1027
 V337     1028-1030
 V359     1031-1032
 V360     1033-1034
 V361     1035-1035
 V362     1036-1036
 V363     1037-1038
 V364     1039-1039
 V366A    1040-1040
 V366B    1041-1041
 V367     1042-1042
 V369     1043-1044
 V369B    1045-1045
 V372     1046-1046
 V375A    1047-1048
 V376     1049-1050
 V376A    1051-1051
 V379     1052-1053
 V380     1054-1054
 V384A    1055-1055
 V384B    1056-1056
 V384C    1057-1057
 V384D    1058-1058
 V384E    1059-1059
 V393     1060-1060
 V394     1061-1061
 V395     1062-1062
 V396     1063-1063
 V397     1064-1064
 V398     1065-1065
 V399     1066-1066
 V401     1067-1067
 V404     1068-1068
 V405     1069-1069
 V406     1070-1070
 V407     1071-1072
 V408     1073-1074
 V409     1075-1075
 V409A    1076-1076
 V410     1077-1077
 V410A    1078-1078
 V411     1079-1079
 V411A    1080-1080
 V412     1081-1081
 V413A    1082-1082
 V413B    1083-1083
 V413C    1084-1084
 V413D    1085-1085
 V413     1086-1086
 V414A    1087-1087
 V414B    1088-1088
 V414C    1089-1089
 V414D    1090-1090
 V414E    1091-1091
 V414F    1092-1092
 V414G    1093-1093
 V414H    1094-1094
 V415     1095-1095
 V416     1096-1096
 V417     1097-1097
 V418     1098-1098
 V419     1099-1099
 V420     1100-1101
 V421     1102-1103
 V426     1104-1106
 V436     1107-1109
 V437     1110-1113
 V438     1114-1117
 V439     1118-1121
 V440     1122-1125
 V441     1126-1130
 V442     1131-1135
 V443     1136-1140
 V444     1141-1145
 V444A    1146-1149
 V445     1150-1153
 V446     1154-1157
 V447     1158-1158
 V448     1159-1159
 V449     1160-1160
 V450A    1161-1161
 V450B    1162-1162
 V450C    1163-1163
 V450D    1164-1164
 V450E    1165-1165
 V450F    1166-1166
 V450G    1167-1167
 V450H    1168-1168
 V450I    1169-1169
 V450J    1170-1170
 V450K    1171-1171
 V450L    1172-1172
 V450M    1173-1173
 V450X    1174-1174
 V450Z    1175-1175
 V451A    1176-1176
 V451B    1177-1177
 V451C    1178-1178
 V451D    1179-1179
 V451E    1180-1180
 V451F    1181-1181
 V451G    1182-1182
 V451H    1183-1183
 V451I    1184-1184
 V451J    1185-1185
 V451K    1186-1186
 V451X    1187-1187
 V451Z    1188-1188
 V501     1189-1189
 V502     1190-1190
 V503     1191-1191
 V504     1192-1192
 V505     1193-1194
 V506     1195-1196
 V507     1197-1198
 V508     1199-1200
 V509     1201-1204
 V510     1205-1205
 V511     1206-1207
 V512     1208-1209
 V513     1210-1210
 V525     1211-1212
 V527     1213-1215
 V528     1216-1217
 V529     1218-1220
 V530     1221-1221
 V531     1222-1223
 V532     1224-1224
 V534     1225-1225
 V535     1226-1226
 V602     1227-1227
 V603     1228-1230
 V604     1231-1231
 V605     1232-1232
 V606     1233-1233
 V610     1234-1234
 V611     1235-1235
 V612     1236-1236
 V613     1237-1238
 V614     1239-1239
 V616     1240-1242
 V618     1243-1243
 V621     1244-1244
 V623     1245-1245
 V624     1246-1247
 V625     1248-1248
 V626     1249-1250
 V627     1251-1252
 V628     1253-1254
 V629     1255-1256
 V630A    1257-1257
 V630B    1258-1258
 V630C    1259-1259
 V630D    1260-1260
 V630E    1261-1261
 V630F    1262-1262
 V630G    1263-1263
 V630H    1264-1264
 V630I    1265-1265
 V630J    1266-1266
 V630K    1267-1267
 V630L    1268-1268
 V630X    1269-1269
 V701     1270-1270
 V702     1271-1272
 V704     1273-1275
 V705     1276-1277
 V707     1278-1278
 V714     1279-1279
 V715     1280-1281
 V716     1282-1284
 V717     1285-1286
 V718     1287-1287
 V719     1288-1288
 V720     1289-1289
 V721     1290-1290
 V723     1291-1292
 V729     1293-1293
 V730     1294-1295
 V731     1296-1296
 V732     1297-1297
 V733     1298-1299
 V734     1300-1300
 V735     1301-1303
 V736     1304-1311
 V737     1312-1318
 V738     1319-1325
 V739     1326-1326
 V740     1327-1327
 V751     1328-1328
 V752A    1329-1329
 V752B    1330-1330
 V752C    1331-1331
 V752D    1332-1332
 V752E    1333-1333
 V752F    1334-1334
 V752G    1335-1335
 V752H    1336-1336
 V752I    1337-1337
 V752J    1338-1338
 V752K    1339-1339
 V752L    1340-1340
 V752M    1341-1341
 V752N    1342-1342
 V752O    1343-1343
 V752X    1344-1344
 V753     1345-1345
 V754A    1346-1346
 V754B    1347-1347
 V754C    1348-1348
 V754D    1349-1349
 V754E    1350-1350
 V754F    1351-1351
 V754G    1352-1352
 V754H    1353-1353
 V754I    1354-1354
 V754J    1355-1355
 V754K    1356-1356
 V754L    1357-1357
 V754M    1358-1358
 V754N    1359-1359
 V754O    1360-1360
 V754X    1361-1361
 V754Z    1362-1362
 V755B    1363-1363
 V755C    1364-1364
 V755D    1365-1365
 V755E    1366-1366
 V755F    1367-1367
 V755L    1368-1368
 V755M    1369-1369
 V755N    1370-1370
 V755O    1371-1371
 V755X    1372-1372
 V755Z    1373-1373
 V756     1374-1374
 V757     1375-1375
 V758     1376-1376
 V760A    1377-1377
 V760B    1378-1378
 V760C    1379-1379
 V760D    1380-1380
 V760E    1381-1381
 V760F    1382-1382
 V760G    1383-1383
 V760I    1384-1384
 V760L    1385-1385
 V760M    1386-1386
 V760N    1387-1387
 V760O    1388-1388
 V760P    1389-1389
 V760V    1390-1390
 V760W    1391-1391
 V760X    1392-1392
 V760Y    1393-1393
 V760Z    1394-1394
 V761     1395-1395
 V762     1396-1397
 V764     1398-1398
 V765     1399-1399
 V801     1400-1403
 V802     1404-1407
 V803     1408-1409
 V804     1410-1410
 V805     1411-1413
 V806     1414-1415
 V811     1416-1416
 V812     1417-1417
 V813     1418-1418
 V814     1419-1419
 MCASEID  1420-1434 (A)
 MV000    1435-1437 (A)
 MV001    1438-1445
 MV002    1446-1449
 MV003    1450-1452
 MV004    1453-1456
 MV005    1457-1464
 MV006    1465-1466
 MV007    1467-1468
 MV008    1469-1472
 MV009    1473-1474
 MV010    1475-1476
 MV011    1477-1480
 MV012    1481-1482
 MV013    1483-1484
 MV014    1485-1485
 MV015    1486-1486
 MV016    1487-1488
 MV021    1489-1492
 MV022    1493-1496
 MV023    1497-1498
 MV024    1499-1500
 MV025    1501-1501
 MV026    1502-1502
 MV027    1503-1503
 MV028    1504-1506
 MV029    1507-1508
 MV030    1509-1510
 MV031    1511-1512
 MV032    1513-1514
 MV033    1515-1522
 MV034$1  1523-1524
 MV034$2  1525-1526
 MV034$3  1527-1528
 MV034$4  1529-1530
 MV034$5  1531-1532
 MV034$6  1533-1534
 MV034$7  1535-1536
 MV034$8  1537-1538
 MV035    1539-1539
 MV801    1540-1543
 MV802    1544-1547
 MV803    1548-1549
 MV101    1550-1551
 MV102    1552-1552
 MV103    1553-1553
 MV104    1554-1555
 MV105    1556-1556
 MV106    1557-1557
 MV107    1558-1559
 MV108    1560-1560
 MV109    1561-1561
 MV110    1562-1562
 MV111    1563-1563
 MV112    1564-1564
 MV130    1565-1565
 MV131    1566-1567
 MV133    1568-1569
 MV134    1570-1570
 MV135    1571-1571
 MV136    1572-1573
 MV138    1574-1575
 MV148    1576-1576
 MV149    1577-1577
 MV150    1578-1579
 MV151    1580-1580
 MV152    1581-1582
 MV201    1583-1584
 MV202    1585-1586
 MV203    1587-1588
 MV204    1589-1590
 MV205    1591-1592
 MV206    1593-1594
 MV207    1595-1596
 MV213    1597-1597
 MV218    1598-1599
 MV225    1600-1600
 MV301    1601-1601
 MV302    1602-1602
 MV304A01 1603-1603
 MV304$01 1604-1604
 MV305$01 1605-1605
 MV304A02 1606-1606
 MV304$02 1607-1607
 MV305$02 1608-1608
 MV304A03 1609-1609
 MV304$03 1610-1610
 MV305$03 1611-1611
 MV304A04 1612-1612
 MV304$04 1613-1613
 MV305$04 1614-1614
 MV304A05 1615-1615
 MV304$05 1616-1616
 MV305$05 1617-1617
 MV304A06 1618-1618
 MV304$06 1619-1619
 MV305$06 1620-1620
 MV304A07 1621-1621
 MV304$07 1622-1622
 MV305$07 1623-1623
 MV304A08 1624-1624
 MV304$08 1625-1625
 MV305$08 1626-1626
 MV304A09 1627-1627
 MV304$09 1628-1628
 MV305$09 1629-1629
 MV304A10 1630-1630
 MV304$10 1631-1631
 MV305$10 1632-1632
 MV304A11 1633-1633
 MV304$11 1634-1634
 MV305$11 1635-1635
 MV304A12 1636-1636
 MV304$12 1637-1637
 MV305$12 1638-1638
 MV304A13 1639-1639
 MV304$13 1640-1640
 MV305$13 1641-1641
 MV304A14 1642-1642
 MV304$14 1643-1643
 MV305$14 1644-1644
 MV304A15 1645-1645
 MV304$15 1646-1646
 MV305$15 1647-1647
 MV312    1648-1649
 MV313    1650-1650
 MV361    1651-1651
 MV362    1652-1652
 MV363    1653-1654
 MV364    1655-1655
 MV366A   1656-1656
 MV366B   1657-1657
 MV367    1658-1658
 MV375A   1659-1660
 MV376    1661-1662
 MV384A   1663-1663
 MV384B   1664-1664
 MV384C   1665-1665
 MV384D   1666-1666
 MV384E   1667-1667
 MV501    1668-1668
 MV502    1669-1669
 MV503    1670-1670
 MV505    1671-1672
 MV507    1673-1674
 MV508    1675-1676
 MV509    1677-1680
 MV510    1681-1681
 MV511    1682-1683
 MV512    1684-1685
 MV513    1686-1686
 MV525    1687-1688
 MV527    1689-1691
 MV531    1692-1693
 MV532    1694-1694
 MV534    1695-1695
 MV535    1696-1696
 MV602    1697-1697
 MV603    1698-1700
 MV604    1701-1701
 MV605    1702-1702
 MV610    1703-1703
 MV611    1704-1704
 MV612    1705-1705
 MV613    1706-1707
 MV614    1708-1708
 MV616    1709-1711
 MV621    1712-1712
 MV627    1713-1714
 MV628    1715-1716
 MV629    1717-1718
 MV630A   1719-1719
 MV630B   1720-1720
 MV630C   1721-1721
 MV630D   1722-1722
 MV630E   1723-1723
 MV630F   1724-1724
 MV630G   1725-1725
 MV630H   1726-1726
 MV630I   1727-1727
 MV630J   1728-1728
 MV630K   1729-1729
 MV630L   1730-1730
 MV630X   1731-1731
 MV714    1732-1732
 MV716    1733-1735
 MV717    1736-1737
 MV719    1738-1738
 MV731    1739-1739
 MV732    1740-1740
 MV733    1741-1742
 MV736    1743-1750
 MV740    1751-1751
 MV751    1752-1752
 MV752A   1753-1753
 MV752B   1754-1754
 MV752C   1755-1755
 MV752D   1756-1756
 MV752E   1757-1757
 MV752F   1758-1758
 MV752G   1759-1759
 MV752H   1760-1760
 MV752I   1761-1761
 MV752J   1762-1762
 MV752K   1763-1763
 MV752L   1764-1764
 MV752M   1765-1765
 MV752N   1766-1766
 MV752O   1767-1767
 MV752X   1768-1768
 MV753    1769-1769
 MV754A   1770-1770
 MV754B   1771-1771
 MV754C   1772-1772
 MV754D   1773-1773
 MV754E   1774-1774
 MV754F   1775-1775
 MV754G   1776-1776
 MV754H   1777-1777
 MV754I   1778-1778
 MV754J   1779-1779
 MV754K   1780-1780
 MV754L   1781-1781
 MV754M   1782-1782
 MV754N   1783-1783
 MV754O   1784-1784
 MV754X   1785-1785
 MV754Z   1786-1786
 MV755B   1787-1787
 MV755C   1788-1788
 MV755D   1789-1789
 MV755E   1790-1790
 MV755F   1791-1791
 MV755L   1792-1792
 MV755M   1793-1793
 MV755N   1794-1794
 MV755O   1795-1795
 MV755X   1796-1796
 MV755Z   1797-1797
 MV756    1798-1798
 MV757    1799-1799
 MV758    1800-1800
 MV760A   1801-1801
 MV760B   1802-1802
 MV760C   1803-1803
 MV760D   1804-1804
 MV760E   1805-1805
 MV760F   1806-1806
 MV760G   1807-1807
 MV760I   1808-1808
 MV760L   1809-1809
 MV760M   1810-1810
 MV760N   1811-1811
 MV760O   1812-1812
 MV760P   1813-1813
 MV760V   1814-1814
 MV760W   1815-1815
 MV760X   1816-1816
 MV760Y   1817-1817
 MV760Z   1818-1818
 MV761    1819-1819
 MV762    1820-1821
 MV763    1822-1823
 MV764    1824-1824
 MV765    1825-1825
 SDFORMAT 1826-1826
 SADJUST  1827-1827
 SINTM    1828-1829
 SINTY    1830-1831
 SDIV     1832-1832
 SDISTR   1833-1834
 S114A    1835-1835
 S114B    1836-1836
 S114C    1837-1837
 S114D    1838-1838
 S114E    1839-1839
 S119     1840-1842
 S119A    1843-1845
 S123     1846-1847
 S124A    1848-1848
 S124B    1849-1849
 S124C    1850-1850
 S124D    1851-1851
 S124I    1852-1852
 S229M    1853-1854
 S229Y    1855-1858
 S233A    1859-1859
 S233B    1860-1860
 S233C    1861-1861
 S233DM   1862-1863
 S233DY   1864-1867
 MSDISTR  1868-1869
 MSFORMAT 1870-1870
 MSADJUST 1871-1871
 MSINTY   1872-1873
 MSINTM   1874-1875
 MS304$01 1876-1876
 MS304$02 1877-1877
 MS304$03 1878-1878
 MS304$04 1879-1879
 MS304$05 1880-1880
 MS304$06 1881-1881
 MS304$07 1882-1882
 MS304$08 1883-1883
 MS304$09 1884-1884
 MS304$10 1885-1885
 MS304$11 1886-1886
 MS304$12 1887-1887
 MS304$13 1888-1888
 MS304$14 1889-1889
 MS304$15 1890-1890
 MS304$16 1891-1891
 MS304$17 1892-1892
 MS304$18 1893-1893
 MS304$19 1894-1894
 MS304$20 1895-1895
 MS309    1896-1897
 MS311    1898-1899
 MS316    1900-1900
 MS317    1901-1902
 MS320S   1903-1903
 MS320    1904-1905
 MS320A   1906-1906
 MS320C   1907-1910
 MS320E   1911-1912
 MS320D   1913-1913
 MS321M   1914-1915
 MS321Y   1916-1917
 MS321C   1918-1921
 MS321F   1922-1922
 MS321XA  1923-1923
 MS321XB  1924-1924
 MS321XC  1925-1925
 MS321XD  1926-1926
 MS321XE  1927-1928
 MS321XF  1929-1932
 MS322B   1933-1933
 MS322C   1934-1935
 MS323    1936-1937
 MS323B   1938-1938
 MS325    1939-1939
 MS325A   1940-1940
 MS325B   1941-1941
 MS325C   1942-1942
 MS325H   1943-1943
 MS325I   1944-1945
 MS325J   1946-1946
 MS326    1947-1948
 MS328HI  1949-1950
 MS347A   1951-1951
 MS347B   1952-1952
 MS347CA  1953-1953
 MS347CB  1954-1954
 MS347CC  1955-1955
 MS347CD  1956-1956
 MS347CE  1957-1957
 MS348C   1958-1958
 MS349A   1959-1959
 MS349B   1960-1960
 MS349C   1961-1961
 MS349D   1962-1962
 MS349E   1963-1963
 MS350    1964-1964
 MS352    1965-1966
 MS353    1967-1967
 MS354    1968-1968
 MS355    1969-1969
 MS356    1970-1971
 MS357A   1972-1972
 MS357B   1973-1973
 MS357C   1974-1974
 MS357D   1975-1975
 MS357E   1976-1976
 MS357F   1977-1977
 MS357G   1978-1978
 MS358    1979-1979
 MS359    1980-1980
 MS360    1981-1981
 MS361    1982-1982
 MS408A   1983-1983
 MS408B   1984-1984
 MS408C   1985-1985
 MS408D   1986-1986
 MS508    1987-1988
 MS512    1989-1989
 MS514    1990-1990
 S304$01  1991-1991
 S304$02  1992-1992
 S304$03  1993-1993
 S304$04  1994-1994
 S304$05  1995-1995
 S304$06  1996-1996
 S304$07  1997-1997
 S304$08  1998-1998
 S304$09  1999-1999
 S304$10  2000-2000
 S304$11  2001-2001
 S304$12  2002-2002
 S304$13  2003-2003
 S304$14  2004-2004
 S304$15  2005-2005
 S309     2006-2007
 S310     2008-2009
 S316     2010-2010
 S317     2011-2012
 S318B    2013-2013
 S318C    2014-2015
 S318EA   2016-2016
 S318EB   2017-2017
 S318EC   2018-2018
 S318ED   2019-2019
 S318EE   2020-2020
 S318EF   2021-2021
 S318EG   2022-2022
 S318F    2023-2024
 S318HA   2025-2025
 S318HB   2026-2026
 S318HC   2027-2027
 S318HD   2028-2028
 S318HE   2029-2029
 S318HF   2030-2030
 S318HG   2031-2031
 S318HH   2032-2032
 S318HI   2033-2033
 S318I    2034-2034
 S318K    2035-2035
 S319     2036-2037
 S319B    2038-2038
 S320S    2039-2039
 S320     2040-2041
 S320A    2042-2042
 S320C    2043-2043
 S322C    2044-2045
 S320D    2046-2047
 S322D    2048-2049
 S323B    2050-2050
 S325     2051-2051
 S325A    2052-2052
 S325B    2053-2053
 S325C    2054-2054
 S325E    2055-2055
 S325G    2056-2056
 S325H    2057-2057
 S325I    2058-2059
 S325J    2060-2060
 S326     2061-2062
 S327     2063-2063
 S328PA   2064-2064
 S328PB   2065-2065
 S328PC   2066-2066
 S328PD   2067-2067
 S328PE   2068-2068
 S328PF   2069-2069
 S328PG   2070-2070
 S328PH   2071-2071
 S328PI   2072-2072
 S328PJ   2073-2073
 S328PK   2074-2074
 S328A    2075-2075
 S328B    2076-2076
 S328C    2077-2077
 S328DA   2078-2078
 S328DB   2079-2079
 S328DC   2080-2080
 S328DD   2081-2081
 S328DE   2082-2082
 S328DF   2083-2083
 S328DG   2084-2084
 S328DH   2085-2085
 S328DI   2086-2086
 S347A    2087-2087
 S347B    2088-2088
 S347CA   2089-2089
 S347CB   2090-2090
 S347CC   2091-2091
 S347CD   2092-2092
 S347CE   2093-2093
 S348C    2094-2094
 S349A    2095-2095
 S349B    2096-2096
 S349C    2097-2097
 S349D    2098-2098
 S349E    2099-2099
 S352     2100-2101
 S353     2102-2102
 S354     2103-2103
 S355     2104-2104
 S356     2105-2106
 S357MA   2107-2107
 S357MB   2108-2108
 S357MC   2109-2109
 S357MD   2110-2110
 S357ME   2111-2111
 S357MF   2112-2112
 S357MG   2113-2113
 S357A    2114-2114
 S357B    2115-2115
 S358     2116-2116
 S359     2117-2117
 S361     2118-2118
 S439     2119-2119
 S440     2120-2121
 S441     2122-2123
 S442A    2124-2124
 S442B$1  2125-2126
 S442C$1  2127-2127
 S442DA$1 2128-2128
 S442DB$1 2129-2129
 S442DC$1 2130-2130
 S442DD$1 2131-2131
 S442DE$1 2132-2132
 S442DF$1 2133-2133
 S442DG$1 2134-2134
 S442DH$1 2135-2135
 S442DI$1 2136-2136
 S442DJ$1 2137-2137
 S442DK$1 2138-2138
 S442EMA1 2139-2140
 S442FMA1 2141-2142
 S442EMB1 2143-2144
 S442FMB1 2145-2146
 S442B$2  2147-2148
 S442C$2  2149-2149
 S442DA$2 2150-2150
 S442DB$2 2151-2151
 S442DC$2 2152-2152
 S442DD$2 2153-2153
 S442DE$2 2154-2154
 S442DF$2 2155-2155
 S442DG$2 2156-2156
 S442DH$2 2157-2157
 S442DI$2 2158-2158
 S442DJ$2 2159-2159
 S442DK$2 2160-2160
 S442EMA2 2161-2162
 S442FMA2 2163-2164
 S442EMB2 2165-2166
 S442FMB2 2167-2168
 S442H    2169-2170
 S442IA   2171-2171
 S442IB   2172-2172
 S442IC   2173-2173
 S442ID   2174-2174
 S442IE   2175-2175
 S442IF   2176-2176
 S442IG   2177-2177
 S442J    2178-2179
 S442KA   2180-2180
 S442KB   2181-2181
 S442KC   2182-2182
 S442KD   2183-2183
 S442KE   2184-2184
 S442KF   2185-2185
 S442L    2186-2186
 S442MA   2187-2187
 S442MB   2188-2188
 S442MC   2189-2189
 S442MD   2190-2190
 S442ME   2191-2191
 S442MF   2192-2192
 S442MG   2193-2193
 S442MH   2194-2194
 S442MI   2195-2195
 S442N    2196-2196
 S442O    2197-2198
 S609     2199-2200
 S613     2201-2201
 S615     2202-2202
 S616     2203-2203
 S617     2204-2204
 S618     2205-2205
.
VARIABLE LABELS
 CASEID   "Case Identification"
/V000     "Country code and phase"
/V001     "Cluster number"
/V002     "Household number"
/V003     "Respondent's line number"
/V004     "Ultimate area unit"
/V005     "Sample weight"
/V006     "Month of interview"
/V007     "Year of interview"
/V008     "Date of interview (CMC)"
/V009     "Respondent's month of birth"
/V010     "Respondent's year of birth"
/V011     "Date of birth (CMC)"
/V012     "Current age - respondent"
/V013     "Age 5-year groups"
/V014     "Completeness of information"
/V015     "Result of individual interview"
/V016     "Day of interview"
/V017     "CMC start of calendar"
/V018     "Row of month of interview"
/V019     "Length of calendar"
/V020     "Ever-married sample"
/V021     "Primary sampling unit"
/V022     "Sample stratum number"
/V023     "Sample domain"
/V024     "Region"
/V025     "Type of place of residence"
/V026     "De facto place of residence"
/V027     "Number of visits"
/V028     "Interviewer identification"
/V029     "Keyer identification"
/V030     "Field supervisor -NA"
/V031     "Field editor -NA"
/V032     "Office editor -NA"
/V033     "Ultimate area selection prob."
/V034     "Line number of husband"
/V101     "Region"
/V102     "Type of place of residence"
/V103     "Childhood place of residen -NA"
/V104     "Years lived in place of res."
/V105     "Type of place of previous res."
/V106     "Highest educational level"
/V107     "Highest year of education"
/V108     "Literacy"
/V109     "Reads newspaper once a week"
/V110     "Watches TV every week"
/V111     "Listens to radio every day -NA"
/V112     "Listens to radio every week"
/V113     "Source of drinking water"
/V114     "Source of non-drinking water"
/V115     "Time to get to water source"
/V116     "Type of toilet facility"
/V119     "Has electricity"
/V120     "Has radio"
/V121     "Has television"
/V122     "Has refrigerator -NA"
/V123     "Has bicycle"
/V124     "Has motorcycle -NA"
/V125     "Has car -NA"
/V127     "Main floor material"
/V128     "Main wall material"
/V129     "Main roof material"
/V130     "Religion"
/V131     "Ethnicity -NA"
/V133     "Education in single years"
/V134     "De facto place of residence"
/V135     "Usual resident or visitor"
/V136     "Number of household members"
/V137     "Number of children 5 and under"
/V138     "Number of eligible women in HH"
/V139     "De jure region of residence"
/V140     "De jure type of place of res."
/V141     "De jure place of residence"
/V142     "Same source of water"
/V144     "Communities lived in >Jan.8-NA"
/V148     "Respondent still in school"
/V149     "Educational attainment"
/V150     "Relationship to household head"
/V151     "Sex of household head"
/V152     "Age of household head"
/V153     "Has telephone -NA"
/V154     "Reason stop attending schoo-NA"
/AWFACTT  "All woman factor - total"
/AWFACTU  "All woman factor - urban/rural"
/AWFACTR  "All woman factor - regional"
/AWFACTE  "All woman factor - educational"
/BIDX$01  "Birth column number"
/BORD$01  "Birth order number"
/B0$01    "Child is twin"
/B1$01    "Month of birth"
/B2$01    "Year of birth"
/B3$01    "Date of birth (CMC)"
/B4$01    "Sex of child"
/B5$01    "Child is alive"
/B6$01    "Age at death"
/B7$01    "Age at death (months-imputed)"
/B8$01    "Current age of child"
/B9$01    "Who child lives with"
/B10$01   "Completeness of information"
/B11$01   "Preceding birth interval"
/B12$01   "Succeeding birth interval"
/B13$01   "Flag for age at death"
/B14$01   "Birth interval >= 4 years -NA"
/B15$01   "Live birth between births -NA"
/BIDX$02  "Birth column number"
/BORD$02  "Birth order number"
/B0$02    "Child is twin"
/B1$02    "Month of birth"
/B2$02    "Year of birth"
/B3$02    "Date of birth (CMC)"
/B4$02    "Sex of child"
/B5$02    "Child is alive"
/B6$02    "Age at death"
/B7$02    "Age at death (months-imputed)"
/B8$02    "Current age of child"
/B9$02    "Who child lives with"
/B10$02   "Completeness of information"
/B11$02   "Preceding birth interval"
/B12$02   "Succeeding birth interval"
/B13$02   "Flag for age at death"
/B14$02   "Birth interval >= 4 years -NA"
/B15$02   "Live birth between births -NA"
/BIDX$03  "Birth column number"
/BORD$03  "Birth order number"
/B0$03    "Child is twin"
/B1$03    "Month of birth"
/B2$03    "Year of birth"
/B3$03    "Date of birth (CMC)"
/B4$03    "Sex of child"
/B5$03    "Child is alive"
/B6$03    "Age at death"
/B7$03    "Age at death (months-imputed)"
/B8$03    "Current age of child"
/B9$03    "Who child lives with"
/B10$03   "Completeness of information"
/B11$03   "Preceding birth interval"
/B12$03   "Succeeding birth interval"
/B13$03   "Flag for age at death"
/B14$03   "Birth interval >= 4 years -NA"
/B15$03   "Live birth between births -NA"
/BIDX$04  "Birth column number"
/BORD$04  "Birth order number"
/B0$04    "Child is twin"
/B1$04    "Month of birth"
/B2$04    "Year of birth"
/B3$04    "Date of birth (CMC)"
/B4$04    "Sex of child"
/B5$04    "Child is alive"
/B6$04    "Age at death"
/B7$04    "Age at death (months-imputed)"
/B8$04    "Current age of child"
/B9$04    "Who child lives with"
/B10$04   "Completeness of information"
/B11$04   "Preceding birth interval"
/B12$04   "Succeeding birth interval"
/B13$04   "Flag for age at death"
/B14$04   "Birth interval >= 4 years -NA"
/B15$04   "Live birth between births -NA"
/BIDX$05  "Birth column number"
/BORD$05  "Birth order number"
/B0$05    "Child is twin"
/B1$05    "Month of birth"
/B2$05    "Year of birth"
/B3$05    "Date of birth (CMC)"
/B4$05    "Sex of child"
/B5$05    "Child is alive"
/B6$05    "Age at death"
/B7$05    "Age at death (months-imputed)"
/B8$05    "Current age of child"
/B9$05    "Who child lives with"
/B10$05   "Completeness of information"
/B11$05   "Preceding birth interval"
/B12$05   "Succeeding birth interval"
/B13$05   "Flag for age at death"
/B14$05   "Birth interval >= 4 years -NA"
/B15$05   "Live birth between births -NA"
/BIDX$06  "Birth column number"
/BORD$06  "Birth order number"
/B0$06    "Child is twin"
/B1$06    "Month of birth"
/B2$06    "Year of birth"
/B3$06    "Date of birth (CMC)"
/B4$06    "Sex of child"
/B5$06    "Child is alive"
/B6$06    "Age at death"
/B7$06    "Age at death (months-imputed)"
/B8$06    "Current age of child"
/B9$06    "Who child lives with"
/B10$06   "Completeness of information"
/B11$06   "Preceding birth interval"
/B12$06   "Succeeding birth interval"
/B13$06   "Flag for age at death"
/B14$06   "Birth interval >= 4 years -NA"
/B15$06   "Live birth between births -NA"
/BIDX$07  "Birth column number"
/BORD$07  "Birth order number"
/B0$07    "Child is twin"
/B1$07    "Month of birth"
/B2$07    "Year of birth"
/B3$07    "Date of birth (CMC)"
/B4$07    "Sex of child"
/B5$07    "Child is alive"
/B6$07    "Age at death"
/B7$07    "Age at death (months-imputed)"
/B8$07    "Current age of child"
/B9$07    "Who child lives with"
/B10$07   "Completeness of information"
/B11$07   "Preceding birth interval"
/B12$07   "Succeeding birth interval"
/B13$07   "Flag for age at death"
/B14$07   "Birth interval >= 4 years -NA"
/B15$07   "Live birth between births -NA"
/BIDX$08  "Birth column number"
/BORD$08  "Birth order number"
/B0$08    "Child is twin"
/B1$08    "Month of birth"
/B2$08    "Year of birth"
/B3$08    "Date of birth (CMC)"
/B4$08    "Sex of child"
/B5$08    "Child is alive"
/B6$08    "Age at death"
/B7$08    "Age at death (months-imputed)"
/B8$08    "Current age of child"
/B9$08    "Who child lives with"
/B10$08   "Completeness of information"
/B11$08   "Preceding birth interval"
/B12$08   "Succeeding birth interval"
/B13$08   "Flag for age at death"
/B14$08   "Birth interval >= 4 years -NA"
/B15$08   "Live birth between births -NA"
/BIDX$09  "Birth column number"
/BORD$09  "Birth order number"
/B0$09    "Child is twin"
/B1$09    "Month of birth"
/B2$09    "Year of birth"
/B3$09    "Date of birth (CMC)"
/B4$09    "Sex of child"
/B5$09    "Child is alive"
/B6$09    "Age at death"
/B7$09    "Age at death (months-imputed)"
/B8$09    "Current age of child"
/B9$09    "Who child lives with"
/B10$09   "Completeness of information"
/B11$09   "Preceding birth interval"
/B12$09   "Succeeding birth interval"
/B13$09   "Flag for age at death"
/B14$09   "Birth interval >= 4 years -NA"
/B15$09   "Live birth between births -NA"
/BIDX$10  "Birth column number"
/BORD$10  "Birth order number"
/B0$10    "Child is twin"
/B1$10    "Month of birth"
/B2$10    "Year of birth"
/B3$10    "Date of birth (CMC)"
/B4$10    "Sex of child"
/B5$10    "Child is alive"
/B6$10    "Age at death"
/B7$10    "Age at death (months-imputed)"
/B8$10    "Current age of child"
/B9$10    "Who child lives with"
/B10$10   "Completeness of information"
/B11$10   "Preceding birth interval"
/B12$10   "Succeeding birth interval"
/B13$10   "Flag for age at death"
/B14$10   "Birth interval >= 4 years -NA"
/B15$10   "Live birth between births -NA"
/BIDX$11  "Birth column number"
/BORD$11  "Birth order number"
/B0$11    "Child is twin"
/B1$11    "Month of birth"
/B2$11    "Year of birth"
/B3$11    "Date of birth (CMC)"
/B4$11    "Sex of child"
/B5$11    "Child is alive"
/B6$11    "Age at death"
/B7$11    "Age at death (months-imputed)"
/B8$11    "Current age of child"
/B9$11    "Who child lives with"
/B10$11   "Completeness of information"
/B11$11   "Preceding birth interval"
/B12$11   "Succeeding birth interval"
/B13$11   "Flag for age at death"
/B14$11   "Birth interval >= 4 years -NA"
/B15$11   "Live birth between births -NA"
/BIDX$12  "Birth column number"
/BORD$12  "Birth order number"
/B0$12    "Child is twin"
/B1$12    "Month of birth"
/B2$12    "Year of birth"
/B3$12    "Date of birth (CMC)"
/B4$12    "Sex of child"
/B5$12    "Child is alive"
/B6$12    "Age at death"
/B7$12    "Age at death (months-imputed)"
/B8$12    "Current age of child"
/B9$12    "Who child lives with"
/B10$12   "Completeness of information"
/B11$12   "Preceding birth interval"
/B12$12   "Succeeding birth interval"
/B13$12   "Flag for age at death"
/B14$12   "Birth interval >= 4 years -NA"
/B15$12   "Live birth between births -NA"
/BIDX$13  "Birth column number"
/BORD$13  "Birth order number"
/B0$13    "Child is twin"
/B1$13    "Month of birth"
/B2$13    "Year of birth"
/B3$13    "Date of birth (CMC)"
/B4$13    "Sex of child"
/B5$13    "Child is alive"
/B6$13    "Age at death"
/B7$13    "Age at death (months-imputed)"
/B8$13    "Current age of child"
/B9$13    "Who child lives with"
/B10$13   "Completeness of information"
/B11$13   "Preceding birth interval"
/B12$13   "Succeeding birth interval"
/B13$13   "Flag for age at death"
/B14$13   "Birth interval >= 4 years -NA"
/B15$13   "Live birth between births -NA"
/BIDX$14  "Birth column number"
/BORD$14  "Birth order number"
/B0$14    "Child is twin"
/B1$14    "Month of birth"
/B2$14    "Year of birth"
/B3$14    "Date of birth (CMC)"
/B4$14    "Sex of child"
/B5$14    "Child is alive"
/B6$14    "Age at death"
/B7$14    "Age at death (months-imputed)"
/B8$14    "Current age of child"
/B9$14    "Who child lives with"
/B10$14   "Completeness of information"
/B11$14   "Preceding birth interval"
/B12$14   "Succeeding birth interval"
/B13$14   "Flag for age at death"
/B14$14   "Birth interval >= 4 years -NA"
/B15$14   "Live birth between births -NA"
/BIDX$15  "Birth column number"
/BORD$15  "Birth order number"
/B0$15    "Child is twin"
/B1$15    "Month of birth"
/B2$15    "Year of birth"
/B3$15    "Date of birth (CMC)"
/B4$15    "Sex of child"
/B5$15    "Child is alive"
/B6$15    "Age at death"
/B7$15    "Age at death (months-imputed)"
/B8$15    "Current age of child"
/B9$15    "Who child lives with"
/B10$15   "Completeness of information"
/B11$15   "Preceding birth interval"
/B12$15   "Succeeding birth interval"
/B13$15   "Flag for age at death"
/B14$15   "Birth interval >= 4 years -NA"
/B15$15   "Live birth between births -NA"
/BIDX$16  "Birth column number"
/BORD$16  "Birth order number"
/B0$16    "Child is twin"
/B1$16    "Month of birth"
/B2$16    "Year of birth"
/B3$16    "Date of birth (CMC)"
/B4$16    "Sex of child"
/B5$16    "Child is alive"
/B6$16    "Age at death"
/B7$16    "Age at death (months-imputed)"
/B8$16    "Current age of child"
/B9$16    "Who child lives with"
/B10$16   "Completeness of information"
/B11$16   "Preceding birth interval"
/B12$16   "Succeeding birth interval"
/B13$16   "Flag for age at death"
/B14$16   "Birth interval >= 4 years -NA"
/B15$16   "Live birth between births -NA"
/BIDX$17  "Birth column number"
/BORD$17  "Birth order number"
/B0$17    "Child is twin"
/B1$17    "Month of birth"
/B2$17    "Year of birth"
/B3$17    "Date of birth (CMC)"
/B4$17    "Sex of child"
/B5$17    "Child is alive"
/B6$17    "Age at death"
/B7$17    "Age at death (months-imputed)"
/B8$17    "Current age of child"
/B9$17    "Who child lives with"
/B10$17   "Completeness of information"
/B11$17   "Preceding birth interval"
/B12$17   "Succeeding birth interval"
/B13$17   "Flag for age at death"
/B14$17   "Birth interval >= 4 years -NA"
/B15$17   "Live birth between births -NA"
/BIDX$18  "Birth column number"
/BORD$18  "Birth order number"
/B0$18    "Child is twin"
/B1$18    "Month of birth"
/B2$18    "Year of birth"
/B3$18    "Date of birth (CMC)"
/B4$18    "Sex of child"
/B5$18    "Child is alive"
/B6$18    "Age at death"
/B7$18    "Age at death (months-imputed)"
/B8$18    "Current age of child"
/B9$18    "Who child lives with"
/B10$18   "Completeness of information"
/B11$18   "Preceding birth interval"
/B12$18   "Succeeding birth interval"
/B13$18   "Flag for age at death"
/B14$18   "Birth interval >= 4 years -NA"
/B15$18   "Live birth between births -NA"
/BIDX$19  "Birth column number"
/BORD$19  "Birth order number"
/B0$19    "Child is twin"
/B1$19    "Month of birth"
/B2$19    "Year of birth"
/B3$19    "Date of birth (CMC)"
/B4$19    "Sex of child"
/B5$19    "Child is alive"
/B6$19    "Age at death"
/B7$19    "Age at death (months-imputed)"
/B8$19    "Current age of child"
/B9$19    "Who child lives with"
/B10$19   "Completeness of information"
/B11$19   "Preceding birth interval"
/B12$19   "Succeeding birth interval"
/B13$19   "Flag for age at death"
/B14$19   "Birth interval >= 4 years -NA"
/B15$19   "Live birth between births -NA"
/BIDX$20  "Birth column number"
/BORD$20  "Birth order number"
/B0$20    "Child is twin"
/B1$20    "Month of birth"
/B2$20    "Year of birth"
/B3$20    "Date of birth (CMC)"
/B4$20    "Sex of child"
/B5$20    "Child is alive"
/B6$20    "Age at death"
/B7$20    "Age at death (months-imputed)"
/B8$20    "Current age of child"
/B9$20    "Who child lives with"
/B10$20   "Completeness of information"
/B11$20   "Preceding birth interval"
/B12$20   "Succeeding birth interval"
/B13$20   "Flag for age at death"
/B14$20   "Birth interval >= 4 years -NA"
/B15$20   "Live birth between births -NA"
/V201     "Total children ever born"
/V202     "Sons at home"
/V203     "Daughters at home"
/V204     "Sons elsewhere"
/V205     "Daughters elsewhere"
/V206     "Sons who have died"
/V207     "Daughters who have died"
/V208     "Births in last five years"
/V209     "Births in past year"
/V210     "Births in month of interview"
/V211     "Date of first birth (CMC)"
/V212     "Age of respondent at 1st birth"
/V213     "Currently pregnant"
/V214     "Duration of current pregnancy"
/V215     "Time since last menstrual perd"
/V216     "Menstruated in last six weeks"
/V217     "Knowledge of ovulatory cycl-NA"
/V218     "Number of living children"
/V219     "Living children + current preg"
/V220     "Living children + curr preg 6+"
/V221     "Marriage to first birth int."
/V222     "Last birth to interview"
/V223     "Completeness of curr preg. inf"
/V224     "Entries in birth history"
/V225     "Current pregnancy wanted"
/V226     "Time since last period (comp)"
/V227     "Flag for last period"
/V228     "Ever had a terminated preg."
/V229     "Month pregnancy ended"
/V230     "Year pregnancy ended"
/V231     "CMC pregnancy ended"
/V232     "Completeness of last term. inf"
/V233     "Months when pregnancy ended"
/V234     "Other such pregnancies"
/V235     "Index last child prior to cal."
/V236     "Last birth interval >= 4 ye-NA"
/V237     "Birth between last & interv-NA"
/V238     "Births in last three years"
/V301     "Knowledge of any method"
/V302     "Ever use of any method"
/V304A$01 "Type of method"
/V304$01  "Knows method"
/V305$01  "Ever used method"
/V304A$02 "Type of method"
/V304$02  "Knows method"
/V305$02  "Ever used method"
/V304A$03 "Type of method"
/V304$03  "Knows method"
/V305$03  "Ever used method"
/V304A$04 "Type of method"
/V304$04  "Knows method"
/V305$04  "Ever used method"
/V304A$05 "Type of method"
/V304$05  "Knows method"
/V305$05  "Ever used method"
/V304A$06 "Type of method"
/V304$06  "Knows method"
/V305$06  "Ever used method"
/V304A$07 "Type of method"
/V304$07  "Knows method"
/V305$07  "Ever used method"
/V304A$08 "Type of method"
/V304$08  "Knows method"
/V305$08  "Ever used method"
/V304A$09 "Type of method"
/V304$09  "Knows method"
/V305$09  "Ever used method"
/V304A$10 "Type of method"
/V304$10  "Knows method"
/V305$10  "Ever used method"
/V304A$11 "Type of method"
/V304$11  "Knows method"
/V305$11  "Ever used method"
/V304A$12 "Type of method"
/V304$12  "Knows method"
/V305$12  "Ever used method"
/V304A$13 "Type of method"
/V304$13  "Knows method"
/V305$13  "Ever used method"
/V304A$14 "Type of method"
/V304$14  "Knows method"
/V305$14  "Ever used method"
/V304A$15 "Type of method"
/V304$15  "Knows method"
/V305$15  "Ever used method"
/V310     "Living children at first use"
/V311     "Children at first use (grpd)"
/V312     "Current contraceptive method"
/V313     "Current use by method type"
/V314     "Method of periodic abstinen-NA"
/V315     "Month of sterilization"
/V316     "Year of sterilization"
/V317     "Date of sterilization (CMC)"
/V318     "Completeness of information"
/V319     "Years since sterilization"
/V320     "Age at sterilization"
/V321     "Marital duration at steriliz."
/V322     "Parity at sterilization"
/V323     "Brand of pill used"
/V325     "Cost of pills"
/V326     "Last source for current users"
/V327     "Last source for users by type"
/V328     "Main reason use current sou-NA"
/V337     "Months of use of current meth"
/V359     "Last method disc. last 5 years"
/V360     "Reason of last discontinuation"
/V361     "Pattern of use"
/V362     "Intention to use"
/V363     "Preferred future method"
/V364     "Contraceptive use & intention"
/V366A    "Acceptability of radio message"
/V366B    "Acceptability of TV message-NA"
/V367     "Wanted last child"
/V369     "First method used"
/V369B    "First use to space or limit-NA"
/V372     "Shown pill package"
/V375A    "Main reason not using a method"
/V376     "Main reason not to use a meth."
/V376A    "Would ever use method if ma-NA"
/V379     "Source known for any method"
/V380     "Source known for any method"
/V384A    "Heard FP on radio last months"
/V384B    "Heard FP on TV last months"
/V384C    "Heard FP newspaper last mon-NA"
/V384D    "Heard FP on poster last months"
/V384E    "Heard FP brochures last mon-NA"
/V393     "Visited by FP worker last 6m"
/V394     "Visited health facil. last 12m"
/V395     "At health facility, told of FP"
/V396     "Breastfeeding affect pregnancy"
/V397     "Pregnancy risk of breastfee-NA"
/V398     "Relied breastfeed. avoid pr-NA"
/V399     "Currently rely on breastfee-NA"
/V401     "Last birth ceasarean sectio-NA"
/V404     "Currently breastfeeding"
/V405     "Currently amenorrheic"
/V406     "Currently abstaining"
/V407     "Times breastfed during night"
/V408     "Times breastfed during day"
/V409     "Gave child plain water"
/V409A    "Gave child sugar water"
/V410     "Gave child juice"
/V410A    "Gave child herbal tea"
/V411     "Gave child powder/tinned mi-NA"
/V411A    "Gave child baby formula"
/V412     "Gave child fresh milk"
/V413A    "Country specific other liqu-NA"
/V413B    "Country specific other liqu-NA"
/V413C    "Country specific other liqu-NA"
/V413D    "Country specific other liqu-NA"
/V413     "Gave child other liquid"
/V414A    "Country specific other food-NA"
/V414B    "Country specific other food-NA"
/V414C    "Country specific other food-NA"
/V414D    "Other solid, semi-solid foods"
/V414E    "Food made from local grain -NA"
/V414F    "Food made from local tuber -NA"
/V414G    "Gave child eggs, fish, poul-NA"
/V414H    "Gave child meat"
/V415     "Drank from bottle with nipp-NA"
/V416     "Heard of oral rehydration"
/V417     "Entries in maternity table"
/V418     "Entries in health table"
/V419     "Entries in height/weight ta-NA"
/V420     "Measurer's code -NA"
/V421     "Assistant measurer's code -NA"
/V426     "When child put to breast"
/V436     "Arm circumference (cms-1d) -NA"
/V437     "Respondent's weight (kilos--NA"
/V438     "Respondent's height (cms-1d-NA"
/V439     "Ht/A Percentile (resp.) -NA"
/V440     "Ht/A Standard deviations (r-NA"
/V441     "Ht/A Percent ref. median (r-NA"
/V442     "Wt/Ht Percent ref. median (-NA"
/V443     "Wt/Ht Percent ref. median (-NA"
/V444     "Wt/Ht Percent ref. median (-NA"
/V444A    "Wt/Ht Std deviations(resp) -NA"
/V445     "Body mass index for respond-NA"
/V446     "Rohrer's index for responde-NA"
/V447     "Result of measurement of re-NA"
/V448     "Drinking pattern with diarr-NA"
/V449     "Eating pattern with diarrhe-NA"
/V450A    "Diarrhea: repeat watery sto-NA"
/V450B    "Diarrhea: Any watery stools-NA"
/V450C    "Diarrhea: Repeated vomiting-NA"
/V450D    "Diarrhea: Any vomiting -NA"
/V450E    "Diarrhea: Blood in stools -NA"
/V450F    "Diarrhea: Fever -NA"
/V450G    "Diarrhea: Marked thirst -NA"
/V450H    "Diarrhea: Not eating/drinki-NA"
/V450I    "Diarrhea: Getting sicker -NA"
/V450J    "Diarrhea: Not getting bette-NA"
/V450K    "Diarrhea: Country specific -NA"
/V450L    "Diarrhea: Country specific -NA"
/V450M    "Diarrhea: Country specific -NA"
/V450X    "Diarrhea: Other responses -NA"
/V450Z    "Diarrhea: Does not know -NA"
/V451A    "Cough: Fast breathing -NA"
/V451B    "Cough: Difficult breathing -NA"
/V451C    "Cough: Noisy breathing -NA"
/V451D    "Cough: Fever -NA"
/V451E    "Cough: Unable to drink -NA"
/V451F    "Cough: Not eating/drinking -NA"
/V451G    "Cough: Getting sicker -NA"
/V451H    "Cough: Not getting better -NA"
/V451I    "Cough: Country specific -NA"
/V451J    "Cough: Country specific -NA"
/V451K    "Cough: Country specific -NA"
/V451X    "Cough: Other responses -NA"
/V451Z    "Knows no sign of illness -NA"
/V501     "Current marital status"
/V502     "Currently/formerly/never marr."
/V503     "Number of unions"
/V504     "Husband lives in house"
/V505     "Number of other wives - NA"
/V506     "Wife rank number - NA"
/V507     "Month of first marriage"
/V508     "Year of first marriage"
/V509     "Date of first marriage (CMC)"
/V510     "Completeness of date inform."
/V511     "Age at first marriage"
/V512     "Years since first marriage"
/V513     "Marital duration (grouped)"
/V525     "Age at first intercourse - NA"
/V527     "Time since last intercourse"
/V528     "Time since last intercourse(g)"
/V529     "Time since last intercourse(im"
/V530     "Flag for V529"
/V531     "Age at first intercourse - NA"
/V532     "Flag for V531 -NA"
/V534     "Have a regular sex partne - NA"
/V535     "Have ever been married"
/V602     "Fertility preference"
/V603     "Preferred waiting time"
/V604     "Preferred waiting time (grpd)"
/V605     "Desire for more children"
/V606     "Attitude toward becoming preg."
/V610     "Husband approves FP"
/V611     "Discussed FP with partner"
/V612     "Respondent approves FP"
/V613     "Ideal number of children"
/V614     "Ideal number of children (grp)"
/V616     "Time for future birth"
/V618     "Reason regrets sterilization"
/V621     "Husbands desire for children"
/V623     "Exposure"
/V624     "Unmet need"
/V625     "Exposure (definition 2)"
/V626     "Unmet need (definition 2)"
/V627     "Ideal number of boys"
/V628     "Ideal number of girls"
/V629     "Ideal number of either sex"
/V630A    "Discussed FP with partner - NA"
/V630B    "Discussed FP with mother - NA"
/V630C    "Discussed FP with father - NA"
/V630D    "Discussed FP with sister( - NA"
/V630E    "Discussed FP with brother - NA"
/V630F    "Discussed FP with daughte - NA"
/V630G    "Discussed FP with mother- - NA"
/V630H    "Discussed FP with friends - NA"
/V630I    "Discussed FP -country spe - NA"
/V630J    "Discussed FP -country spe - NA"
/V630K    "Discussed FP -country spe - NA"
/V630L    "Discussed FP -country spe - NA"
/V630X    "Discussed FP with others - NA"
/V701     "Partner's education level"
/V702     "Highest year of education"
/V704     "Partner's occupation"
/V705     "Partner's occupation"
/V707     "Type of land where works"
/V714     "Respondent currently working"
/V715     "Husbands education-single yrs"
/V716     "Respondent's occupation"
/V717     "Respondent's occupation"
/V718     "Current type of employment"
/V719     "Work for family, others, self"
/V720     "Earns cash for work"
/V721     "Works at home or away"
/V723     "Child minder"
/V729     "Partner's educational attainm."
/V730     "Partners age -NA"
/V731     "Worked in last 12 months - NA"
/V732     "Employment all year/seasonal"
/V733     "Months worked in last 12 - NA"
/V734     "Days in a week normally w - NA"
/V735     "Days worked in last 12 mo - NA"
/V736     "Earnings for work - NA"
/V737     "Daily earnings for work - NA"
/V738     "Yearly earnings for work - NA"
/V739     "Who decides how to spend money"
/V740     "Type of land where resp. works"
/V751     "Ever heard of AIDS -NA"
/V752A    "AIDS: radio - NA"
/V752B    "AIDS: television - NA"
/V752C    "AIDS: newspapers/magazine - NA"
/V752D    "AIDS: pamphlets/posters - NA"
/V752E    "AIDS: clinic/health worke - NA"
/V752F    "AIDS: churches/mosques - NA"
/V752G    "AIDS: schools/teachers - NA"
/V752H    "AIDS: community meetings - NA"
/V752I    "AIDS: friends/relatives - NA"
/V752J    "AIDS: work place - NA"
/V752K    "AIDS: country specific - NA"
/V752L    "AIDS: country specific - NA"
/V752M    "AIDS: country specific - NA"
/V752N    "AIDS: country specific - NA"
/V752O    "AIDS: country specific - NA"
/V752X    "AIDS: other responses - NA"
/V753     "Ways to avoid AIDS - NA"
/V754A    "AIDS: Safe sex - NA"
/V754B    "AIDS: abstain from sex - NA"
/V754C    "AIDS: use condoms during - NA"
/V754D    "AIDS: only one sex partne - NA"
/V754E    "AIDS: avoid sex prostitut - NA"
/V754F    "AIDS: avoid sex homosexua - NA"
/V754G    "AIDS: avoid blood transfu - NA"
/V754H    "AIDS: avoid injections - NA"
/V754I    "AIDS: avoid kissing - NA"
/V754J    "AIDS: avoid mosquito bite - NA"
/V754K    "AIDS: protection trad. he - NA"
/V754L    "AIDS: country specific - NA"
/V754M    "AIDS: country specific - NA"
/V754N    "AIDS: country specific - NA"
/V754O    "AIDS: country specific - NA"
/V754X    "AIDS: other responses - NA"
/V754Z    "AIDS: DK ways to avoid AI - NA"
/V755B    "Safe sex: abstain from se - NA"
/V755C    "Safe sex: use condoms dur - NA"
/V755D    "Safe sex: only one partne - NA"
/V755E    "Safe sex: avoid prostitut - NA"
/V755F    "Safe sex: avoid homosexua - NA"
/V755L    "Safe sex: country specifi - NA"
/V755M    "Safe sex: country specifi - NA"
/V755N    "Safe sex: country specifi - NA"
/V755O    "Safe sex: country specifi - NA"
/V755X    "Safe sex: other responses - NA"
/V755Z    "Safe sex: DK meaning - NA"
/V756     "Can a healthy person have - NA"
/V757     "Is AIDS a fatal disease - NA"
/V758     "Chances of getting AIDS - NA"
/V760A    "Behavior: Did not start s - NA"
/V760B    "Behavior: Stopped all sex - NA"
/V760C    "Behavior: Started using c - NA"
/V760D    "Behavior: Only one sex pa - NA"
/V760E    "Behavior: Reduced partner - NA"
/V760F    "Behavior: Ask spouse fait - NA"
/V760G    "Behavior: No homosexual c - NA"
/V760I    "Behavior: Stopped injecti - NA"
/V760L    "Behavior: Country specifi - NA"
/V760M    "Behavior: Country specifi - NA"
/V760N    "Behavior: Country specifi - NA"
/V760O    "Behavior: Country specifi - NA"
/V760P    "Behavior: Spouse avoid pro- NA"
/V760V    "Behavior: No nonsexual ch - NA"
/V760W    "Behavior: Other nonsexual - NA"
/V760X    "Behavior: Other responses - NA"
/V760Y    "Behavior: No change - NA"
/V760Z    "Behavior: Don't know - NA"
/V761     "Last intercourse used con - NA"
/V762     "Source for condoms -NA"
/V764     "Knowledge of condom -NA"
/V765     "Ever use of condom -NA"
/V801     "Time interview started"
/V802     "Time interview ended"
/V803     "Length of interview in minutes"
/V804     "Number of visits"
/V805     "Interviewer identification"
/V806     "Keyer identification"
/V811     "Pres. children < 10 (sec 5)"
/V812     "Pres. husband (sec 5)"
/V813     "Pres. other males (sec 5)"
/V814     "Pres. other females (sec 5)"
/MCASEID  "Case Identification"
/MV000    "Country code and phase"
/MV001    "Cluster number"
/MV002    "Household number"
/MV003    "Respondent's line number"
/MV004    "Ultimate area unit"
/MV005    "Sample weight"
/MV006    "Month of interview"
/MV007    "Year of interview"
/MV008    "Date of interview (CMC)"
/MV009    "Respondent's month of birth"
/MV010    "Respondent's year of birth"
/MV011    "Date of birth (CMC)"
/MV012    "Current age - respondent"
/MV013    "Age 5-year groups"
/MV014    "Completeness of information"
/MV015    "Result of individual interview"
/MV016    "Day of interview"
/MV021    "Primary sampling unit"
/MV022    "Sample stratum number"
/MV023    "Sample domain"
/MV024    "Region"
/MV025    "Type of place of residence"
/MV026    "De facto place of residence"
/MV027    "Number of visits"
/MV028    "Interviewer identification"
/MV029    "Keyer identification"
/MV030    "Field supervisor - NA"
/MV031    "Field editor - NA"
/MV032    "Office editor - NA"
/MV033    "Ultimate area selection prob."
/MV034$1  "Line numbers of wives"
/MV034$2  "Line numbers of wives"
/MV034$3  "Line numbers of wives"
/MV034$4  "Line numbers of wives"
/MV034$5  "Line numbers of wives"
/MV034$6  "Line numbers of wives"
/MV034$7  "Line numbers of wives"
/MV034$8  "Line numbers of wives"
/MV035    "Number of wives, partners"
/MV801    "Time interview started"
/MV802    "Time interview ended"
/MV803    "Length of interview in minutes"
/MV101    "Region"
/MV102    "Type of place of residence"
/MV103    "Childhood place of residen- NA"
/MV104    "Years lived in place of res."
/MV105    "Type of place of previous resi"
/MV106    "Highest educational level"
/MV107    "Highest year of education"
/MV108    "Literacy"
/MV109    "Reads newspaper once a week"
/MV110    "Watches TV every week"
/MV111    "Listens to radio every da - NA"
/MV112    "Listens to radio every week"
/MV130    "Religion"
/MV131    "Ethnicity - NA"
/MV133    "Education in single years"
/MV134    "De facto place of residence"
/MV135    "Usual resident or visitor"
/MV136    "Number of household members"
/MV138    "Number of eligible men in HH"
/MV148    "Respondent still in school"
/MV149    "Educational attainment"
/MV150    "Relationship to household head"
/MV151    "Sex of household head"
/MV152    "Age of household head"
/MV201    "Total children ever born"
/MV202    "Sons at home"
/MV203    "Daughters at home"
/MV204    "Sons elsewhere"
/MV205    "Daughters elsewhere"
/MV206    "Sons who have died"
/MV207    "Daughters who have died"
/MV213    "Partner currently pregnan - NA"
/MV218    "Number of living children"
/MV225    "Current pregnancy wanted - NA"
/MV301    "Knowledge of any method"
/MV302    "Ever use of any method"
/MV304A01 "Type of method"
/MV304$01 "Knows method"
/MV305$01 "Ever used method"
/MV304A02 "Type of method"
/MV304$02 "Knows method"
/MV305$02 "Ever used method"
/MV304A03 "Type of method"
/MV304$03 "Knows method"
/MV305$03 "Ever used method"
/MV304A04 "Type of method"
/MV304$04 "Knows method"
/MV305$04 "Ever used method"
/MV304A05 "Type of method"
/MV304$05 "Knows method"
/MV305$05 "Ever used method"
/MV304A06 "Type of method"
/MV304$06 "Knows method"
/MV305$06 "Ever used method"
/MV304A07 "Type of method"
/MV304$07 "Knows method"
/MV305$07 "Ever used method"
/MV304A08 "Type of method"
/MV304$08 "Knows method"
/MV305$08 "Ever used method"
/MV304A09 "Type of method"
/MV304$09 "Knows method"
/MV305$09 "Ever used method"
/MV304A10 "Type of method"
/MV304$10 "Knows method"
/MV305$10 "Ever used method"
/MV304A11 "Type of method"
/MV304$11 "Knows method"
/MV305$11 "Ever used method"
/MV304A12 "Type of method"
/MV304$12 "Knows method"
/MV305$12 "Ever used method"
/MV304A13 "Type of method"
/MV304$13 "Knows method"
/MV305$13 "Ever used method"
/MV304A14 "Type of method"
/MV304$14 "Knows method"
/MV305$14 "Ever used method"
/MV304A15 "Type of method"
/MV304$15 "Knows method"
/MV305$15 "Ever used method"
/MV312    "Current contraceptive method"
/MV313    "Current use by method type"
/MV361    "Pattern of use"
/MV362    "Intention to use"
/MV363    "Preferred future method"
/MV364    "Contraceptive use & intention"
/MV366A   "Acceptability of radio me - NA"
/MV366B   "Acceptability of TV messa - NA"
/MV367    "Wanted last child - NA"
/MV375A   "Main reason not using a method"
/MV376    "Main reason not to use a meth."
/MV384A   "Heard FP on radio last month"
/MV384B   "Heard FP on TV last month"
/MV384C   "Heard FP newspaper last mon-NA"
/MV384D   "Heard FP on poster last month"
/MV384E   "Heard FP brochures last m - NA"
/MV501    "Current marital status"
/MV502    "Currently/formerly/never marr."
/MV503    "Number of unions"
/MV505    "Number of wives, partners"
/MV507    "Month of first marriage"
/MV508    "Year of first marriage"
/MV509    "Date of first marriage (CMC)"
/MV510    "Completeness of date inform."
/MV511    "Age at first marriage"
/MV512    "Years since first marriage"
/MV513    "Marital duration (grouped)"
/MV525    "Age at first intercourse - NA"
/MV527    "Time since last intercourse"
/MV531    "Age at first intercourse - NA"
/MV532    "Flag for MV531"
/MV534    "Have a regular sex partne - NA"
/MV535    "Have ever been married - NA"
/MV602    "Fertility preference"
/MV603    "Preferred waiting time"
/MV604    "Preferred waiting time (grpd)"
/MV605    "Desire for more children"
/MV610    "Wife approves FP"
/MV611    "Discussed FP with partner"
/MV612    "Respondent approves FP"
/MV613    "Ideal number of children"
/MV614    "Ideal number of children (grp)"
/MV616    "Time for future birth"
/MV621    "Wifes desire for children"
/MV627    "Ideal number of boys"
/MV628    "Ideal number of girls"
/MV629    "Ideal number of either sex"
/MV630A   "Discussed FP with partner - NA"
/MV630B   "Discussed FP with mother - NA"
/MV630C   "Discussed FP with father - NA"
/MV630D   "Discussed FP with sister( - NA"
/MV630E   "Discussed FP with brother - NA"
/MV630F   "Discussed FP with daughte - NA"
/MV630G   "Discussed FP with mother- - NA"
/MV630H   "Discussed FP with friends - NA"
/MV630I   "Discussed FP -country spe - NA"
/MV630J   "Discussed FP -country spe - NA"
/MV630K   "Discussed FP -country spe - NA"
/MV630L   "Discussed FP -country spe - NA"
/MV630X   "Discussed FP with others - NA"
/MV714    "Respondent currently working"
/MV716    "Respondent's occupation"
/MV717    "Respondent's occupation"
/MV719    "Work for family, others, - NA"
/MV731    "Worked in last 12 months - NA"
/MV732    "Employment all year/seaso - NA"
/MV733    "Months worked in last 12 - NA"
/MV736    "Earnings for work - NA"
/MV740    "Type of land where resp. works"
/MV751    "Ever heard of AIDS - NA"
/MV752A   "AIDS: radio - NA"
/MV752B   "AIDS: television - NA"
/MV752C   "AIDS: newspapers/magazine - NA"
/MV752D   "AIDS: pamphlets/posters - NA"
/MV752E   "AIDS: clinic/health worke - NA"
/MV752F   "AIDS: churches/mosques - NA"
/MV752G   "AIDS: schools/teachers - NA"
/MV752H   "AIDS: community meetings - NA"
/MV752I   "AIDS: friends/relatives - NA"
/MV752J   "AIDS: work place - NA"
/MV752K   "AIDS: country specific - NA"
/MV752L   "AIDS: country specific - NA"
/MV752M   "AIDS: country specific - NA"
/MV752N   "AIDS: country specific - NA"
/MV752O   "AIDS: country specific - NA"
/MV752X   "AIDS: other responses - NA"
/MV753    "Ways to avoid AIDS - NA"
/MV754A   "AIDS: Safe sex - NA"
/MV754B   "AIDS: abstain from sex - NA"
/MV754C   "AIDS: use condoms during - NA"
/MV754D   "AIDS: only one sex partne - NA"
/MV754E   "AIDS: avoid sex prostitut - NA"
/MV754F   "AIDS: avoid sex homosexua - NA"
/MV754G   "AIDS: avoid blood transfu - NA"
/MV754H   "AIDS: avoid injections - NA"
/MV754I   "AIDS: avoid kissing - NA"
/MV754J   "AIDS: avoid mosquito bite - NA"
/MV754K   "AIDS: protection trad. he - NA"
/MV754L   "AIDS: country specific - NA"
/MV754M   "AIDS: country specific - NA"
/MV754N   "AIDS: country specific - NA"
/MV754O   "AIDS: country specific - NA"
/MV754X   "AIDS: other responses - NA"
/MV754Z   "AIDS: DK ways to avoid AI - NA"
/MV755B   "Safe sex: abstain from se - NA"
/MV755C   "Safe sex: use condoms dur - NA"
/MV755D   "Safe sex: only one partne - NA"
/MV755E   "Safe sex: avoid prostitut - NA"
/MV755F   "Safe sex: avoid homosexua - NA"
/MV755L   "Safe sex: country specifi - NA"
/MV755M   "Safe sex: country specifi - NA"
/MV755N   "Safe sex: country specifi - NA"
/MV755O   "Safe sex: country specifi - NA"
/MV755X   "Safe sex: other responses - NA"
/MV755Z   "Safe sex: DK meaning - NA"
/MV756    "Can a healthy person have - NA"
/MV757    "Is AIDS a fatal disease - NA"
/MV758    "Chances of getting AIDS - NA"
/MV760A   "Behavior: Did not start s - NA"
/MV760B   "Behavior: Stopped all sex - NA"
/MV760C   "Behavior: Started using c - NA"
/MV760D   "Behavior: Only one sex pa - NA"
/MV760E   "Behavior: Reduced partner - NA"
/MV760F   "Behavior: Ask spouse fait - NA"
/MV760G   "Behavior: No homosexual c - NA"
/MV760I   "Behavior: Stopped injecti - NA"
/MV760L   "Behavior: Country specifi - NA"
/MV760M   "Behavior: Country specifi - NA"
/MV760N   "Behavior: Country specifi - NA"
/MV760O   "Behavior: Country specifi - NA"
/MV760P   "Behavior: Avoid sex w. pr - NA"
/MV760V   "Behavior: No nonsexual ch - NA"
/MV760W   "Behavior: Other nonsexual - NA"
/MV760X   "Behavior: Other responses - NA"
/MV760Y   "Behavior: No change - NA"
/MV760Z   "Behavior: Don't know - NA"
/MV761    "Last intercourse used con - NA"
/MV762    "Source for condoms"
/MV763    "Partners in last 12 month - NA"
/MV764    "Knowledge of condom - NA"
/MV765    "Ever use of condom - NA"
/SDFORMAT "Date format of questionnaire"
/SADJUST  "Month of interview adjusted 1m"
/SINTM    "Month of interview(unadjusted)"
/SINTY    "Year of interview(unadjusted)"
/SDIV     "Division"
/SDISTR   "District of residence"
/S114A    "Grameen Bank"
/S114B    "BRAC"
/S114C    "BRDP"
/S114D    "Mothers club"
/S114E    "Other"
/S119     "Time to get to water (mins)"
/S119A    "Time to wait to get water:mins"
/S123     "Toilet facility : children"
/S124A    "Almirah"
/S124B    "Table/chair/bench"
/S124C    "Watch/clock"
/S124D    "Cot/bed"
/S124I    "Agricultural land"
/S229M    "Month pregnancy ended"
/S229Y    "Year pregnancy ended"
/S233A    "Ever had unwanted pregnancy"
/S233B    "Pregancy aborted/menst.reg'ltn"
/S233C    "Pregnancy ended by MR/D&C"
/S233DM   "When pr. ended : Month"
/S233DY   "When pregnancy ended :Year"
/MSDISTR  "District of residence"
/MSFORMAT "Type of date format used"
/MSADJUST "Month of interview adjusted 1m"
/MSINTY   "Year of interview(unadjusted)"
/MSINTM   "Month of interview(unadjusted)"
/MS304$01 "Knows source of method"
/MS304$02 "Knows source of method"
/MS304$03 "Knows source of method"
/MS304$04 "Knows source of method"
/MS304$05 "Knows source of method"
/MS304$06 "Knows source of method"
/MS304$07 "Knows source of method"
/MS304$08 "Knows source of method"
/MS304$09 "Knows source of method"
/MS304$10 "Knows source of method"
/MS304$11 "Knows source of method"
/MS304$12 "Knows source of method"
/MS304$13 "Knows source of method"
/MS304$14 "Knows source of method"
/MS304$15 "Knows source of method"
/MS304$16 "Knows source of method"
/MS304$17 "Knows source of method"
/MS304$18 "Knows source of method"
/MS304$19 "Knows source of method"
/MS304$20 "Knows source of method"
/MS309    "First method used"
/MS311    "Living children at first use"
/MS316    "Currently using second method"
/MS317    "Second method currently used"
/MS320S   "Condom package seen"
/MS320    "Brand of condoms shown"
/MS320A   "Reason can't show condom pack"
/MS320C   "Reason can't show condom pack"
/MS320E   "Times used condoms last month"
/MS320D   "Use condom every time have sex"
/MS321M   "Month of sterilization (imp.)"
/MS321Y   "Year of sterilization (imp.)"
/MS321C   "Date of sterilization (CMC)"
/MS321F   "Completeness of information"
/MS321XA  "Years since sterilization"
/MS321XB  "Age at sterilization"
/MS321XC  "Marital duration at steriliz."
/MS321XD  "Wife's sterilization:date form"
/MS321XE  "Wife's sterilization : month"
/MS321XF  "Wife's sterilization: year"
/MS322B   "Sterilization regret"
/MS322C   "Method used most recently"
/MS323    "Source of current method"
/MS323B   "Paid for use of contr.source"
/MS325    "Who obtained pills/condoms"
/MS325A   "Got pls,cndm at HF,doctor,shop"
/MS325B   "Informed of side effects/probs"
/MS325C   "Informed of other methods"
/MS325H   "Got method he wanted"
/MS325I   "Method wanted at HF."
/MS325J   "Who had most inflc. at 1st use"
/MS326    "Reason for current method"
/MS328HI  "Knows source for method"
/MS347A   "Satellite clinic last 3 months"
/MS347B   "Visited satellite clinic"
/MS347CA  "Sat.Clinic: Family Plng.Meths."
/MS347CB  "Sat.Clinic: Immunization"
/MS347CC  "Sat.Clinic: Ch.growth monitor."
/MS347CD  "Sat.Clinic: Other"
/MS347CE  "Sat.Clinic: Does not know"
/MS348C   "Read about FP on Billboard"
/MS349A   "Inf. on radio acceptable:pill"
/MS349B   "Inf. on radio acct'ble:condoms"
/MS349C   "Inf. on radio acct'ble:injctns"
/MS349D   "Inf. on radio acct'ble:IUD's"
/MS349E   "Inf. on radio acct'ble:sterlzn"
/MS350    "Visit by FPW in last 6 mnths"
/MS352    "No. visits by FPW last 6 mnths"
/MS353    "Months since last visit by FPW"
/MS354    "Received supplies from FPW"
/MS355    "Supplies received from FPW"
/MS356    "How many cycles/condoms rec'vd"
/MS357A   "Meths.disc.w FPW: Pills"
/MS357B   "Meths.disc.w FPW: IUD"
/MS357C   "Meths.disc.w FPW: Injection"
/MS357D   "Meths.disc.w FPW: Condom"
/MS357E   "Meths.disc.w FPW: Female Ster."
/MS357F   "Meths.disc.w FPW: Male Ster."
/MS357G   "Meths.disc.w FPW: Never disc."
/MS358    "Most men known by rsp use FP"
/MS359    "Has recommended FP to someone"
/MS360    "Visit Health Facility last 6m"
/MS361    "Spoke with psn at HF about FP"
/MS408A   "Children under 10"
/MS408B   "Presence of wife"
/MS408C   "Other males"
/MS408D   "Other females"
/MS508    "Source of preferred method"
/MS512    "Discussed children"
/MS514    "Wife allowed to go out alone"
/S304$01  "Knows source for method"
/S304$02  "Knows source for method"
/S304$03  "Knows source for method"
/S304$04  "Knows source for method"
/S304$05  "Knows source for method"
/S304$06  "Knows source for method"
/S304$07  "Knows source for method"
/S304$08  "Knows source for method"
/S304$09  "Knows source for method"
/S304$10  "Knows source for method"
/S304$11  "Knows source for method"
/S304$12  "Knows source for method"
/S304$13  "Knows source for method"
/S304$14  "Knows source for method"
/S304$15  "Knows source for method"
/S309     "First contraceptive method"
/S310     "Source of first method"
/S316     "Currently using second method"
/S317     "Second method currently used"
/S318B    "Pill usage"
/S318C    "Why not taken pills in order"
/S318EA   "No pill pack: Ran out"
/S318EB   "No pill pack: Cost too much"
/S318EC   "No pill pack: Husband away"
/S318ED   "No pill pack: Has menstrual pd"
/S318EE   "No pill pack:none at her s'rce"
/S318EF   "No pill pack:FWA didn't supply"
/S318EG   "No pill pack: Other reason"
/S318F    "Days since last took a pill"
/S318HA   "No curr.pill use:husband away"
/S318HB   "No curr.pill use:forgot"
/S318HC   "No curr.pill use:health reason"
/S318HD   "No curr.pill use:cost too much"
/S318HE   "No curr.pill use:daily use N/R"
/S318HF   "No curr.pill use:ran out"
/S318HG   "No curr.pill use:FWA not resup"
/S318HH   "No curr.pill use:menstruating"
/S318HI   "No curr.pill use:other reason"
/S318I    "Delays use between pill pk'age"
/S318K    "Action after forgetting pill"
/S319     "Months since last injection"
/S319B    "Reason why no recent injection"
/S320S    "Condom package seen"
/S320     "Brand of condoms used"
/S320A    "Reason can't show condom pack"
/S320C    "Use condom every time have sex"
/S322C    "Which days of cycle not safe"
/S320D    "Times used condoms last month"
/S322D    "Method used most recently"
/S323B    "Paid for use of contr.source"
/S325     "Who obtained pills/condoms"
/S325A    "Got pls,cndm at HF,doctor,shop"
/S325B    "Informed of side effects/probs"
/S325C    "Informed of other methods"
/S325E    "Inf. of side effs by FWA(ever)"
/S325G    "Inf. of oth.meths by FWA(ever)"
/S325H    "Got method she wanted"
/S325I    "Method wanted at hlth.facility"
/S325J    "Who had most inflc. at 1st use"
/S326     "Reason for current method"
/S327     "Problems with current method"
/S328PA   "Probs,curr.meth: weight gain"
/S328PB   "Probs,curr.meth: weight loss"
/S328PC   "Probs,curr.meth: excess bleed."
/S328PD   "Probs,curr.meth: hypertension"
/S328PE   "Probs,curr.meth: headache"
/S328PF   "Probs,curr.meth: nausea"
/S328PG   "Probs,curr.meth: no menstruatn"
/S328PH   "Probs,curr.meth: weak/tired"
/S328PI   "Probs,curr.meth: dizziness"
/S328PJ   "Probs,curr.meth: other"
/S328PK   "Probs,curr.meth: does not know"
/S328A    "Advice when 1st had problems"
/S328B    "Who gave advice when 1st probs"
/S328C    "Any other probs. using meth."
/S328DA   "Other probs: husb.disapproves"
/S328DB   "Other probs: Oth.rel. disappr."
/S328DC   "Other probs: relig.disapproves"
/S328DD   "Other probs: access/availab'ty"
/S328DE   "Other probs: cost too much"
/S328DF   "Other probs: inconvenient use"
/S328DG   "Other probs : ster.,wants ch."
/S328DH   "Other probs: Other"
/S328DI   "Other probs: does not know"
/S347A    "Satellite clinic last 3 months"
/S347B    "Visited satellite clinic"
/S347CA   "Sat.Clinic: Family Plng.Meths."
/S347CB   "Sat.Clinic: Immunization"
/S347CC   "Sat.Clinic: Ch.growth monitor."
/S347CD   "Sat.Clinic: Other"
/S347CE   "Sat.Clinic: Does not know"
/S348C    "Read about FP on Billboard"
/S349A    "Inf. on radio acceptable:pill"
/S349B    "Inf. on radio acct'ble:condoms"
/S349C    "Inf. on radio acct'ble:injctns"
/S349D    "Inf. on radio acct'ble:injctns"
/S349E    "Inf. on radio acct'ble:sterlzn"
/S352     "No. visits by FPW last 6 mnths"
/S353     "Months since last visit by FPW"
/S354     "Received supplies from FPW"
/S355     "Supplies received from FPW"
/S356     "How many cycles/condoms rec'vd"
/S357MA   "Meths.disc.w FPW: Pills"
/S357MB   "Meths.disc.w FPW: IUD"
/S357MC   "Meths.disc.w FPW: Injection"
/S357MD   "Meths.disc.w FPW: Condom"
/S357ME   "Meths.disc.w FPW: Female Ster."
/S357MF   "Meths.disc.w FPW: Male Ster."
/S357MG   "Meths.disc.w FPW: Never disc."
/S357A    "Referred to clinic by FPW"
/S357B    "Why FPW referred to clinic"
/S358     "Most women known by rsp use FP"
/S359     "Has recommended FP to someone"
/S361     "Spoke with psn at HF about FP"
/S439     "Rec.advice on duration of bfdg"
/S440     "Dec dur'tn BF:who helped most"
/S441     "No.months advised for BF"
/S442A    "Anyone give FP adv.after birth"
/S442B$1  "Who gave specific advice on FP"
/S442C$1  "Asked how planned to feed baby"
/S442DA$1 "Methods discussed: Pill"
/S442DB$1 "Methods discussed: IUD"
/S442DC$1 "Methods discussed: Injections"
/S442DD$1 "Methods discussed: Condom"
/S442DE$1 "Methods discussed: Female Ster"
/S442DF$1 "Methods discussed: Male Ster."
/S442DG$1 "Methods discussed: Calendar"
/S442DH$1 "Methods discussed: Withdrawal."
/S442DI$1 "Methods discussed: Prol.BrFeed"
/S442DJ$1 "Methods discussed: Other"
/S442DK$1 "Methods discussed: None"
/S442EMA1 "1st recommended method"
/S442FMA1 "Rec.interval before use mthd 1"
/S442EMB1 "2nd recommended method"
/S442FMB1 "Rec.interval before use mthd 2"
/S442B$2  "Who gave specific advice on FP"
/S442C$2  "Asked how planned to feed baby"
/S442DA$2 "Methods discussed: Pill"
/S442DB$2 "Methods discussed: IUD"
/S442DC$2 "Methods discussed: Injections"
/S442DD$2 "Methods discussed: Condom"
/S442DE$2 "Methods discussed: Female Ster"
/S442DF$2 "Methods discussed: Male Ster."
/S442DG$2 "Methods discussed: Calendar"
/S442DH$2 "Methods discussed: Withdrawal."
/S442DI$2 "Methods discussed: Prol.BrFeed"
/S442DJ$2 "Methods discussed: Other"
/S442DK$2 "Methods discussed: None"
/S442EMA2 "1st recommended method"
/S442FMA2 "Rec.interval before use mthd 1"
/S442EMB2 "2nd recommended method"
/S442FMB2 "Rec.interval before use mthd 2"
/S442H    "Dec to use FP :who helped most"
/S442IA   "Infl.to use FP: Resumed sex"
/S442IB   "Infl.to use FP: Resumed period"
/S442IC   "Infl.to use FP: Breastfeeding"
/S442ID   "Infl.to use FP:des.to have ch."
/S442IE   "Infl.to use FP: Radio/TV msges"
/S442IF   "Infl.to use FP: Other"
/S442IG   "Infl.to use FP: Nothing else"
/S442J    "Helped mst to decide which mth"
/S442KA   "Oth.infl.on meth:Effic.method"
/S442KB   "Oth.infl.on meth: Prev.experi."
/S442KC   "Oth.infl.on meth:Safeness meth"
/S442KD   "Oth.infl.on meth:Comfort/disc."
/S442KE   "Oth.infl.on meth: Radio/TV msg"
/S442KF   "Oth.infl.on meth: Other"
/S442L    "FP meths.not good while brstfg"
/S442MA   "Bad for Bfdg.Wom.: Pill"
/S442MB   "Bad for Bfdg.Wom.: IUD"
/S442MC   "Bad for Bfdg.Wom.: Injections"
/S442MD   "Bad for Bfdg.Wom.: Condom"
/S442ME   "Bad for Bfdg.Wom.: Female sTer"
/S442MF   "Bad for Bfdg.Wom.: Male Ster."
/S442MG   "Bad for Bfdg.Wom.: Safe period"
/S442MH   "Bad for Bfdg.Wom.: Withdrawal"
/S442MI   "Bad for Bfdg.Wom.: Other"
/S442N    "EFf. of BF/amen against prgncy"
/S442O    "How long protected by b.feedin"
/S609     "Source of preferred method"
/S613     "Discussed children"
/S615     "Resp.allowed to go out alone"
/S616     "Freq.visits to oth.pts localit"
/S617     "Freq.of shopping/marketing"
/S618     "Allowed to visit H.cntr,hosp."
.
MISSING VALUE
 V015     (9)
/V026     (9)
/V028     (999)
/V029     (99)
/V030     (99)
/V031     (99)
/V032     (99)
/V034     (99)
/V103     (9)
/V104     (99)
/V105     (9)
/V106     (9)
/V107     (99)
/V108     (9)
/V109     (9)
/V110     (9)
/V111     (9)
/V112     (9)
/V113     (99)
/V114     (99)
/V115     (999)
/V116     (99)
/V119     (9)
/V120     (9)
/V121     (9)
/V122     (9)
/V123     (9)
/V124     (9)
/V125     (9)
/V127     (99)
/V128     (99)
/V129     (99)
/V130     (9)
/V131     (99)
/V133     (99)
/V134     (9)
/V135     (9)
/V139     (99)
/V140     (9)
/V141     (9)
/V142     (9)
/V144     (9)
/V148     (9)
/V149     (9)
/V150     (99)
/V152     (99)
/V153     (9)
/V154     (99)
/B6$01    (999)
/B9$01    (9)
/B14$01   (9)
/B15$01   (9)
/B6$02    (999)
/B9$02    (9)
/B14$02   (9)
/B15$02   (9)
/B6$03    (999)
/B9$03    (9)
/B14$03   (9)
/B15$03   (9)
/B6$04    (999)
/B9$04    (9)
/B14$04   (9)
/B15$04   (9)
/B6$05    (999)
/B9$05    (9)
/B14$05   (9)
/B15$05   (9)
/B6$06    (999)
/B9$06    (9)
/B14$06   (9)
/B15$06   (9)
/B6$07    (999)
/B9$07    (9)
/B14$07   (9)
/B15$07   (9)
/B6$08    (999)
/B9$08    (9)
/B14$08   (9)
/B15$08   (9)
/B6$09    (999)
/B9$09    (9)
/B14$09   (9)
/B15$09   (9)
/B6$10    (999)
/B9$10    (9)
/B14$10   (9)
/B15$10   (9)
/B6$11    (999)
/B9$11    (9)
/B14$11   (9)
/B15$11   (9)
/B6$12    (999)
/B9$12    (9)
/B14$12   (9)
/B15$12   (9)
/B6$13    (999)
/B9$13    (9)
/B14$13   (9)
/B15$13   (9)
/B6$14    (999)
/B9$14    (9)
/B14$14   (9)
/B15$14   (9)
/B6$15    (999)
/B9$15    (9)
/B14$15   (9)
/B15$15   (9)
/B6$16    (999)
/B9$16    (9)
/B14$16   (9)
/B15$16   (9)
/B6$17    (999)
/B9$17    (9)
/B14$17   (9)
/B15$17   (9)
/B6$18    (999)
/B9$18    (9)
/B14$18   (9)
/B15$18   (9)
/B6$19    (999)
/B9$19    (9)
/B14$19   (9)
/B15$19   (9)
/B6$20    (999)
/B9$20    (9)
/B14$20   (9)
/B15$20   (9)
/V215     (999)
/V225     (9)
/V226     (999)
/V228     (9)
/V229     (99)
/V230     (99)
/V231     (9999)
/V233     (99)
/V234     (9)
/V304$01  (9)
/V305$01  (9)
/V304$02  (9)
/V305$02  (9)
/V304$03  (9)
/V305$03  (9)
/V304$04  (9)
/V305$04  (9)
/V304$05  (9)
/V305$05  (9)
/V304$06  (9)
/V305$06  (9)
/V304$07  (9)
/V305$07  (9)
/V304$08  (9)
/V305$08  (9)
/V304$09  (9)
/V305$09  (9)
/V304$10  (9)
/V305$10  (9)
/V304$11  (9)
/V305$11  (9)
/V304$12  (9)
/V305$12  (9)
/V304$13  (9)
/V305$13  (9)
/V304$14  (9)
/V305$14  (9)
/V304$15  (9)
/V305$15  (9)
/V310     (99)
/V311     (9)
/V312     (99)
/V313     (9)
/V314     (9)
/V323     (99)
/V325     (999999)
/V326     (99)
/V327     (9)
/V328     (99)
/V337     (999)
/V359     (99)
/V360     (99)
/V362     (9)
/V363     (99)
/V366A    (9)
/V367     (9)
/V369     (99)
/V372     (9)
/V375A    (99)
/V376     (99)
/V376A    (9)
/V379     (99)
/V380     (9)
/V384A    (9)
/V384B    (9)
/V384D    (9)
/V393     (9)
/V394     (9)
/V395     (9)
/V396     (9)
/V399     (9)
/V401     (9)
/V407     (99)
/V408     (99)
/V409     (9)
/V409A    (9)
/V410     (9)
/V410A    (9)
/V411     (9)
/V411A    (9)
/V412     (9)
/V413A    (9)
/V413B    (9)
/V413C    (9)
/V413D    (9)
/V413     (9)
/V414A    (9)
/V414B    (9)
/V414C    (9)
/V414D    (9)
/V414E    (9)
/V414F    (9)
/V414G    (9)
/V414H    (9)
/V416     (9)
/V426     (999)
/V450B    (9)
/V450E    (9)
/V450F    (9)
/V450G    (9)
/V501     (9)
/V502     (9)
/V503     (9)
/V504     (9)
/V527     (999)
/V528     (99)
/V529     (999)
/V535     (9)
/V602     (9)
/V603     (999)
/V604     (9)
/V605     (9)
/V606     (9)
/V610     (9)
/V611     (9)
/V612     (9)
/V613     (99)
/V616     (999)
/V618     (9)
/V621     (9)
/V623     (9)
/V624     (99)
/V625     (9)
/V626     (99)
/V627     (99)
/V628     (99)
/V629     (99)
/V701     (9)
/V702     (99)
/V704     (999)
/V705     (99)
/V707     (9)
/V714     (9)
/V715     (99)
/V716     (999)
/V717     (99)
/V718     (9)
/V719     (9)
/V720     (9)
/V721     (9)
/V723     (99)
/V729     (9)
/V730     (99)
/V732     (9)
/V739     (9)
/V740     (9)
/V751     (9)
/V764     (9)
/V765     (9)
/V801     (9999)
/V802     (9999)
/V803     (99)
/V805     (999)
/V806     (99)
/V811     (9)
/V812     (9)
/V813     (9)
/V814     (9)
/MV015    (9)
/MV026    (9)
/MV028    (999)
/MV029    (99)
/MV035    (9)
/MV801    (9999)
/MV802    (9999)
/MV803    (99)
/MV104    (99)
/MV105    (9)
/MV106    (9)
/MV107    (99)
/MV108    (9)
/MV109    (9)
/MV110    (9)
/MV112    (9)
/MV130    (9)
/MV133    (99)
/MV134    (9)
/MV135    (9)
/MV148    (9)
/MV149    (9)
/MV150    (99)
/MV152    (99)
/MV304$01 (9)
/MV305$01 (9)
/MV304$02 (9)
/MV305$02 (9)
/MV304$03 (9)
/MV305$03 (9)
/MV304$04 (9)
/MV305$04 (9)
/MV304$05 (9)
/MV305$05 (9)
/MV304$06 (9)
/MV305$06 (9)
/MV304$07 (9)
/MV305$07 (9)
/MV304$08 (9)
/MV305$08 (9)
/MV304$09 (9)
/MV305$09 (9)
/MV304$10 (9)
/MV305$10 (9)
/MV304$11 (9)
/MV305$11 (9)
/MV304$12 (9)
/MV305$12 (9)
/MV304$13 (9)
/MV305$13 (9)
/MV304$14 (9)
/MV305$14 (9)
/MV304$15 (9)
/MV305$15 (9)
/MV312    (99)
/MV313    (9)
/MV362    (9)
/MV363    (99)
/MV375A   (99)
/MV376    (99)
/MV384A   (9)
/MV384B   (9)
/MV384D   (9)
/MV501    (9)
/MV502    (9)
/MV503    (9)
/MV505    (99)
/MV527    (999)
/MV602    (9)
/MV603    (999)
/MV604    (9)
/MV605    (9)
/MV610    (9)
/MV611    (9)
/MV612    (9)
/MV613    (99)
/MV616    (999)
/MV621    (9)
/MV627    (99)
/MV628    (99)
/MV629    (99)
/MV714    (9)
/MV716    (999)
/MV717    (99)
/MV731    (9)
/MV740    (9)
/MV762    (99)
/S114A    (9)
/S114B    (9)
/S114C    (9)
/S114D    (9)
/S114E    (9)
/S119     (999)
/S119A    (999)
/S123     (99)
/S124A    (9)
/S124B    (9)
/S124C    (9)
/S124D    (9)
/S124I    (9)
/S229M    (99)
/S229Y    (9999)
/S233A    (9)
/S233B    (9)
/S233C    (9)
/S233DM   (99)
/S233DY   (9999)
/MS304$01 (9)
/MS304$02 (9)
/MS304$03 (9)
/MS304$04 (9)
/MS304$05 (9)
/MS304$06 (9)
/MS304$07 (9)
/MS304$08 (9)
/MS304$09 (9)
/MS304$10 (9)
/MS304$11 (9)
/MS304$12 (9)
/MS304$13 (9)
/MS304$14 (9)
/MS304$15 (9)
/MS304$16 (9)
/MS304$17 (9)
/MS304$18 (9)
/MS304$19 (9)
/MS304$20 (9)
/MS309    (99)
/MS311    (99)
/MS316    (9)
/MS317    (99)
/MS320S   (9)
/MS320    (99)
/MS320A   (9)
/MS320C   (9999)
/MS320E   (99)
/MS320D   (9)
/MS321XE  (99)
/MS321XF  (9999)
/MS322B   (9)
/MS322C   (99)
/MS323    (99)
/MS323B   (9)
/MS325    (9)
/MS325A   (9)
/MS325B   (9)
/MS325C   (9)
/MS325H   (9)
/MS325I   (99)
/MS325J   (9)
/MS326    (99)
/MS328HI  (99)
/MS347A   (9)
/MS347B   (9)
/MS347CA  (9)
/MS347CB  (9)
/MS347CC  (9)
/MS347CD  (9)
/MS347CE  (9)
/MS348C   (9)
/MS349A   (9)
/MS349B   (9)
/MS349C   (9)
/MS349D   (9)
/MS349E   (9)
/MS350    (9)
/MS352    (99)
/MS353    (9)
/MS354    (9)
/MS355    (9)
/MS356    (99)
/MS357A   (9)
/MS357B   (9)
/MS357C   (9)
/MS357D   (9)
/MS357E   (9)
/MS357F   (9)
/MS357G   (9)
/MS358    (9)
/MS359    (9)
/MS360    (9)
/MS361    (9)
/MS408A   (9)
/MS408B   (9)
/MS408C   (9)
/MS408D   (9)
/MS508    (99)
/MS512    (9)
/MS514    (9)
/S304$01  (9)
/S304$02  (9)
/S304$03  (9)
/S304$04  (9)
/S304$05  (9)
/S304$06  (9)
/S304$07  (9)
/S304$08  (9)
/S304$09  (9)
/S304$10  (9)
/S304$11  (9)
/S304$12  (9)
/S304$13  (9)
/S304$14  (9)
/S304$15  (9)
/S309     (99)
/S310     (99)
/S316     (9)
/S317     (99)
/S318B    (9)
/S318C    (99)
/S318EA   (9)
/S318EB   (9)
/S318EC   (9)
/S318ED   (9)
/S318EE   (9)
/S318EF   (9)
/S318EG   (9)
/S318F    (99)
/S318HA   (9)
/S318HB   (9)
/S318HC   (9)
/S318HD   (9)
/S318HE   (9)
/S318HF   (9)
/S318HG   (9)
/S318HH   (9)
/S318HI   (9)
/S318I    (9)
/S318K    (9)
/S319     (99)
/S319B    (9)
/S320S    (9)
/S320     (99)
/S320A    (9)
/S320C    (9)
/S322C    (99)
/S320D    (99)
/S322D    (99)
/S323B    (9)
/S325     (9)
/S325A    (9)
/S325B    (9)
/S325C    (9)
/S325E    (9)
/S325G    (9)
/S325H    (9)
/S325I    (99)
/S325J    (9)
/S326     (99)
/S327     (9)
/S328PA   (9)
/S328PB   (9)
/S328PC   (9)
/S328PD   (9)
/S328PE   (9)
/S328PF   (9)
/S328PG   (9)
/S328PH   (9)
/S328PI   (9)
/S328PJ   (9)
/S328PK   (9)
/S328A    (9)
/S328B    (9)
/S328C    (9)
/S328DA   (9)
/S328DB   (9)
/S328DC   (9)
/S328DD   (9)
/S328DE   (9)
/S328DF   (9)
/S328DG   (9)
/S328DH   (9)
/S328DI   (9)
/S347A    (9)
/S347B    (9)
/S347CA   (9)
/S347CB   (9)
/S347CC   (9)
/S347CD   (9)
/S347CE   (9)
/S348C    (9)
/S349A    (9)
/S349B    (9)
/S349C    (9)
/S349D    (9)
/S349E    (9)
/S352     (99)
/S353     (9)
/S354     (9)
/S355     (9)
/S356     (99)
/S357MA   (9)
/S357MB   (9)
/S357MC   (9)
/S357MD   (9)
/S357ME   (9)
/S357MF   (9)
/S357MG   (9)
/S357A    (9)
/S357B    (9)
/S358     (9)
/S359     (9)
/S361     (9)
/S439     (9)
/S440     (99)
/S441     (99)
/S442A    (9)
/S442B$1  (99)
/S442C$1  (9)
/S442DA$1 (9)
/S442DB$1 (9)
/S442DC$1 (9)
/S442DD$1 (9)
/S442DE$1 (9)
/S442DF$1 (9)
/S442DG$1 (9)
/S442DH$1 (9)
/S442DI$1 (9)
/S442DJ$1 (9)
/S442DK$1 (9)
/S442EMA1 (99)
/S442FMA1 (99)
/S442EMB1 (99)
/S442FMB1 (99)
/S442B$2  (99)
/S442C$2  (9)
/S442DA$2 (9)
/S442DB$2 (9)
/S442DC$2 (9)
/S442DD$2 (9)
/S442DE$2 (9)
/S442DF$2 (9)
/S442DG$2 (9)
/S442DH$2 (9)
/S442DI$2 (9)
/S442DJ$2 (9)
/S442DK$2 (9)
/S442EMA2 (99)
/S442FMA2 (99)
/S442EMB2 (99)
/S442FMB2 (99)
/S442H    (99)
/S442IA   (9)
/S442IB   (9)
/S442IC   (9)
/S442ID   (9)
/S442IE   (9)
/S442IF   (9)
/S442IG   (9)
/S442J    (99)
/S442KA   (9)
/S442KB   (9)
/S442KC   (9)
/S442KD   (9)
/S442KE   (9)
/S442KF   (9)
/S442L    (9)
/S442MA   (9)
/S442MB   (9)
/S442MC   (9)
/S442MD   (9)
/S442ME   (9)
/S442MF   (9)
/S442MG   (9)
/S442MH   (9)
/S442MI   (9)
/S442N    (9)
/S442O    (99)
/S609     (99)
/S613     (9)
/S615     (9)
/S616     (9)
/S617     (9)
/S618     (9)
.
VALUE LABELS
 V013
     0 "10-14"
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
/V014
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/V015
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
/V018
     0 "No calendar"
/V019
     0 "No calendar"
/V020
     0 "All woman sample"
     1 "Ever married sample"
/V023
     0 "National"
     1 "Country specific"
/V024
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/V025
     1 "Urban"
     2 "Rural"
/V026
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/V034
     0 "Husband not in HH"
/V101
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/V102
     1 "Urban"
     2 "Rural"
/V104
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
/V105
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
/V106
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/V108
     1 "Reads easily"
     2 "Reads with difficult"
     3 "Cannot read"
/V109
     0 "No"
     1 "Yes"
/V110
     0 "No"
     1 "Yes"
/V112
     0 "No"
     1 "Yes"
/V113
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
/V114
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
/V115
   996 "On premises"
/V116
    10 "FLUSH TOILET"
    20 "PIT TOILET LATRINE"
    30 "NO FACILITY"
    96 "OTHER"
/V119
     0 "No"
     1 "Yes"
/V120
     0 "No"
     1 "Yes"
/V121
     0 "No"
     1 "Yes"
/V123
     0 "No"
     1 "Yes"
/V127
    10 "NATURAL"
    11 "Earth"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
/V128
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Brick/cement"
    32 "Tin"
    96 "OTHER"
/V129
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Tin"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
/V130
     1 "Islam"
     2 "Christianity"
     3 "Hinduism"
     4 "Buddhism"
     5 "Other"
/V133
    97 "Inconsistent"
/V134
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/V135
     1 "Usual resident"
     2 "Visitor"
/V139
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/V140
     0 "Abroad"
     1 "Urban"
     2 "Rural"
/V141
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
/V142
     0 "No"
     1 "Yes"
/V148
     0 "No"
     1 "Yes"
/V149
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
/V150
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Grand-daughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/V151
     1 "Male"
     2 "Female"
/V152
    96 "96+"
/B0$01
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$01
     1 "Male"
     2 "Female"
/B5$01
     0 "No"
     1 "Yes"
/B6$01
   997 "Inconsistent"
   998 "Don't know"
/B9$01
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$01
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$01
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$02
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$02
     1 "Male"
     2 "Female"
/B5$02
     0 "No"
     1 "Yes"
/B6$02
   997 "Inconsistent"
   998 "Don't know"
/B9$02
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$02
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$02
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$03
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$03
     1 "Male"
     2 "Female"
/B5$03
     0 "No"
     1 "Yes"
/B6$03
   997 "Inconsistent"
   998 "Don't know"
/B9$03
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$03
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$03
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$04
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$04
     1 "Male"
     2 "Female"
/B5$04
     0 "No"
     1 "Yes"
/B6$04
   997 "Inconsistent"
   998 "Don't know"
/B9$04
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$04
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$04
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$05
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$05
     1 "Male"
     2 "Female"
/B5$05
     0 "No"
     1 "Yes"
/B6$05
   997 "Inconsistent"
   998 "Don't know"
/B9$05
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$05
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$05
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$06
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$06
     1 "Male"
     2 "Female"
/B5$06
     0 "No"
     1 "Yes"
/B6$06
   997 "Inconsistent"
   998 "Don't know"
/B9$06
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$06
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$06
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$07
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$07
     1 "Male"
     2 "Female"
/B5$07
     0 "No"
     1 "Yes"
/B6$07
   997 "Inconsistent"
   998 "Don't know"
/B9$07
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$07
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$07
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$08
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$08
     1 "Male"
     2 "Female"
/B5$08
     0 "No"
     1 "Yes"
/B6$08
   997 "Inconsistent"
   998 "Don't know"
/B9$08
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$08
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$08
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$09
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$09
     1 "Male"
     2 "Female"
/B5$09
     0 "No"
     1 "Yes"
/B6$09
   997 "Inconsistent"
   998 "Don't know"
/B9$09
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$09
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$09
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$10
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$10
     1 "Male"
     2 "Female"
/B5$10
     0 "No"
     1 "Yes"
/B6$10
   997 "Inconsistent"
   998 "Don't know"
/B9$10
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$10
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$10
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$11
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$11
     1 "Male"
     2 "Female"
/B5$11
     0 "No"
     1 "Yes"
/B6$11
   997 "Inconsistent"
   998 "Don't know"
/B9$11
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$11
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$11
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$12
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$12
     1 "Male"
     2 "Female"
/B5$12
     0 "No"
     1 "Yes"
/B6$12
   997 "Inconsistent"
   998 "Don't know"
/B9$12
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$12
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$12
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$13
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$13
     1 "Male"
     2 "Female"
/B5$13
     0 "No"
     1 "Yes"
/B6$13
   997 "Inconsistent"
   998 "Don't know"
/B9$13
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$13
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$13
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$14
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$14
     1 "Male"
     2 "Female"
/B5$14
     0 "No"
     1 "Yes"
/B6$14
   997 "Inconsistent"
   998 "Don't know"
/B9$14
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$14
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$14
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$15
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$15
     1 "Male"
     2 "Female"
/B5$15
     0 "No"
     1 "Yes"
/B6$15
   997 "Inconsistent"
   998 "Don't know"
/B9$15
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$15
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$15
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$16
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$16
     1 "Male"
     2 "Female"
/B5$16
     0 "No"
     1 "Yes"
/B6$16
   997 "Inconsistent"
   998 "Don't know"
/B9$16
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$16
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$16
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$17
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$17
     1 "Male"
     2 "Female"
/B5$17
     0 "No"
     1 "Yes"
/B6$17
   997 "Inconsistent"
   998 "Don't know"
/B9$17
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$17
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$17
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$18
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$18
     1 "Male"
     2 "Female"
/B5$18
     0 "No"
     1 "Yes"
/B6$18
   997 "Inconsistent"
   998 "Don't know"
/B9$18
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$18
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$18
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$19
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$19
     1 "Male"
     2 "Female"
/B5$19
     0 "No"
     1 "Yes"
/B6$19
   997 "Inconsistent"
   998 "Don't know"
/B9$19
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$19
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$19
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/B0$20
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
/B4$20
     1 "Male"
     2 "Female"
/B5$20
     0 "No"
     1 "Yes"
/B6$20
   997 "Inconsistent"
   998 "Don't know"
/B9$20
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
/B10$20
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/B13$20
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
/V213
     0 "No or unsure"
     1 "Yes"
/V215
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
/V216
     0 "No"
     1 "Yes"
/V220
     6 "6+"
/V221
   996 "Negative interval"
/V223
     7 "Month - exact date"
     8 "None - date placed"
/V225
     1 "Then"
     2 "Later"
     3 "Not at all"
/V226
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
/V227
     0 "No flag"
     1 "N > int. since birth"
     2 "N + amen. > interval"
     3 "N, but per. not ret."
     4 "95, but no birth"
     5 "96, but per.returned"
     6 "95, but per.returned"
     7 "N, last per. in preg"
     8 "96, had children"
     9 "N, per.bef.last birt"
/V228
     0 "No"
     1 "Yes"
/V229
    97 "Inconsistent"
    98 "DK"
/V230
    97 "Inconsistent"
    98 "DK"
/V231
  9997 "Inconsistent"
  9998 "DK"
/V232
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
/V233
    97 "Inconsistent"
    98 "Don't know"
/V234
     0 "No"
     1 "Yes"
/V235
     0 "No prior child"
/V301
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
/V302
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
/V304A$01
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$01
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$01
     0 "No"
     1 "Yes"
/V304A$02
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$02
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$02
     0 "No"
     1 "Yes"
/V304A$03
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$03
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$03
     0 "No"
     1 "Yes"
/V304A$04
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$04
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$04
     0 "No"
     1 "Yes"
/V304A$05
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$05
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$05
     0 "No"
     1 "Yes"
/V304A$06
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$06
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$06
     0 "No"
     1 "Yes"
/V304A$07
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$07
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$07
     0 "No"
     1 "Yes"
/V304A$08
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$08
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$08
     0 "No"
     1 "Yes"
/V304A$09
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$09
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$09
     0 "No"
     1 "Yes"
/V304A$10
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$10
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$10
     0 "No"
     1 "Yes"
/V304A$11
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$11
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$11
     0 "No"
     1 "Yes"
/V304A$12
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$12
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$12
     0 "No"
     1 "Yes"
/V304A$13
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$13
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$13
     0 "No"
     1 "Yes"
/V304A$14
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$14
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$14
     0 "No"
     1 "Yes"
/V304A$15
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/V304$15
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/V305$15
     0 "No"
     1 "Yes"
/V311
     4 "4+"
     5 "Never used"
/V312
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/V313
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
/V318
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
/V319
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
/V320
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45-49"
/V321
     0 "Single,before marr."
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
/V322
     5 "5+"
/V323
     1 "Maya"
     2 "Ovacon"
     3 "Norquest"
     4 "Noriday"
     5 "Ovral"
     6 "Combination-5"
     7 "Ovostat"
     8 "Restovar-NA"
     9 "Lyndiol"
    10 "Nordette"
    11 "Marvelou"
    96 "Other pill brand"
/V326
    10 "PUBLIC"
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    20 "PRIVATE MEDICAL"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    30 "OTHER PRIVATE"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "OTHER"
    98 "DK"
/V327
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
/V337
    95 "All cal. {A core}"
    96 "96+ {B core}"
   997 "Inconsistent"
   998 "Don't know"
/V359
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/V360
     1 "Became pregnant"
     2 "Wanted to become prg"
     3 "Husband disapproved"
     4 "Side effects"
     5 "Health concerns"
     6 "Access, availability"
     7 "Wanted more eff.meth"
     8 "Inconvenient to use"
     9 "Infreq.sex,husb away"
    10 "Cost"
    11 "Fatalistic"
    12 "Diff.preg.,menopause"
    13 "Marital dissolution"
    14 "Other"
    98 "Don't know"
/V361
     1 "Currently using"
     2 "Used since last brth"
     3 "Used before last brt"
     4 "Never used"
/V362
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
/V363
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    98 "Don't know"
/V364
     1 "Using modern method"
     2 "Using tradit. method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
/V366A
     0 "Not acceptable"
     1 "Acceptable"
     8 "Don't know"
/V367
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
/V369
     0 "Never used"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/V372
     0 "Package not seen"
     1 "Package seen"
/V375A
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
/V376
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
/V379
    10 "PUBLIC"
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    20 "PRIVATE MEDICAL"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    30 "OTHER PRIVATE"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "OTHER"
    98 "DK"
/V380
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
/V384A
     0 "No"
     1 "Yes"
/V384B
     0 "No"
     1 "Yes"
/V384D
     0 "No"
     1 "Yes"
/V393
     0 "No"
     1 "Yes - 6 months"
     8 "Don't know"
/V394
     0 "No"
     1 "Yes"
/V395
     0 "No"
     1 "Yes"
/V396
     0 "No"
     1 "Yes"
     8 "DK"
/V401
     0 "No"
     1 "Yes"
/V404
     0 "No"
     1 "Yes"
/V405
     0 "No"
     1 "Yes"
/V406
     0 "No"
     1 "Yes"
/V407
    96 "On demand"
/V408
    96 "On demand"
/V409
     0 "No"
     1 "Yes"
/V409A
     0 "No"
     1 "Yes"
/V410
     0 "No"
     1 "Yes"
/V410A
     0 "No"
     1 "Yes"
/V411A
     0 "No"
     1 "Yes"
/V412
     0 "No"
     1 "Yes"
/V413
     0 "No"
     1 "Yes"
/V414D
     0 "No"
     1 "Yes"
/V414E
     0 "No"
     1 "Yes"
/V414F
     0 "No"
     1 "Yes"
/V414G
     0 "No"
     1 "Yes"
/V414H
     0 "No"
     1 "Yes"
/V416
     0 "Never heard of"
     1 "Used ORS"
     2 "Heard of ORS"
/V426
     0 "Immediately"
/V501
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
/V502
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
/V503
     1 "Once"
     2 "More than once"
/V504
     1 "Living with her"
     2 "Staying elsewhere"
/V510
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/V513
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
/V527
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
/V528
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
/V529
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
/V530
     0 "No flag"
     1 "N > int. since birth"
     2 "N + abst. > interval"
     3 "N, but sex not res."
     4 "96, but no birth"
     5 "96, but curr.preg."
     6 "96, but resumed sex"
     7 "N, last sex bef preg"
     8 "N, inconsis 4 weeks"
     9 "N, sex bef last birt"
/V535
     0 "No"
     1 "Formerly married"
     2 "Lived with a man"
/V602
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Declared infecund"
     6 "Never had sex"
/V603
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
/V604
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
/V605
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
/V606
     1 "Happy"
     2 "Unhappy"
     3 "Would not matter"
     8 "DK"
/V610
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
/V611
     0 "Never"
     1 "Once or twice"
     2 "More often"
/V612
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
/V613
    95 "Up to God"
    96 "Other"
    98 "DK"
/V614
     6 "6+"
     7 "Non-numeric response"
/V616
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
/V618
     0 "No regret"
     1 "Resp. wants another"
     2 "Part. wants another"
     3 "Side effects"
     4 "Child died"
     6 "Other reason"
/V621
     1 "Both want same"
     2 "Husband wants more"
     3 "Husband wants fewer"
     8 "DK"
/V623
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
/V624
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
/V625
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
/V626
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
/V627
    95 "Up to God"
    96 "Other"
    98 "DK"
/V628
    95 "Up to God"
    96 "Other"
    98 "DK"
/V629
    95 "Up to God"
    96 "Other"
    98 "DK"
/V701
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
/V702
    98 "Don't know"
/V704
    11 "Land owner"
    12 "Farmer"
    13 "Agricultural worker"
    14 "Fisherman"
    21 "Unskilled labourers"
    22 "Domestic servant"
    23 "Non-agricultural wkr"
    31 "Semi-skilled labour"
    41 "Professional worker"
    51 "Business"
    52 "Small business/tradr"
    61 "Unemployed"
    62 "Retired"
    96 "Others"
    98 "Don't know"
/V705
     0 "Did not work"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
/V707
     0 "His land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
/V714
     0 "No"
     1 "Yes"
/V715
    97 "Inconsistent"
    98 "Don't know"
/V716
     0 "Not working"
    11 "Land owner"
    12 "Farmer"
    13 "Agricultural worker"
    14 "Fisherman"
    21 "Unskilled labourers"
    22 "Domestic servant"
    23 "Non-agricultural wkr"
    31 "Semi-skilled labour"
    41 "Professional worker"
    51 "Business"
    52 "Small business/tradr"
    61 "Unemployed"
    62 "Retired"
    96 "Others"
    98 "Don't know"
/V717
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
/V718
     0 "Did not work"
     1 "Paid employee, away"
     2 "Paid employee, home"
     3 "Self-employed, away"
     4 "Self-employed, home"
     5 "Unpaid worker, away"
     6 "Unpaid worker, home"
/V719
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
/V720
     0 "No"
     1 "Yes"
/V721
     1 "At home"
     2 "Away"
/V723
     0 "Respondent"
     1 "Husband/partner"
     2 "Other child"
     3 "Other relatives"
     4 "Neighbors"
     5 "Friends"
     6 "Servants/hired help"
     7 "Child is in school"
     8 "Institutional care"
    10 "Other female child"
    11 "Other male child"
    95 "Not worked since bth"
    96 "Other"
/V729
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
/V732
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
/V739
     1 "Respondent"
     2 "Partner"
     3 "Jointly with partner"
     4 "Someone else"
     5 "Jointly with someone"
/V740
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
/V803
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
/V811
     0 "No"
     1 "Yes"
/V812
     0 "No"
     1 "Yes"
/V813
     0 "No"
     1 "Yes"
/V814
     0 "No"
     1 "Yes"
/MV013
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60+"
/MV014
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/MV015
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
/MV023
     0 "National"
     1 "Country specific"
/MV024
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/MV025
     1 "Urban"
     2 "Rural"
/MV026
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/MV035
     0 "No wives/partners"
/MV803
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
/MV101
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/MV102
     1 "Urban"
     2 "Rural"
/MV104
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
/MV105
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
/MV106
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/MV108
     1 "Reads easily"
     2 "Reads with difficult"
     3 "Cannot read"
/MV109
     0 "No"
     1 "Yes"
/MV110
     0 "No"
     1 "Yes"
/MV112
     0 "No"
     1 "Yes"
/MV130
     1 "Islam"
     2 "Christianity"
     3 "Hinduism"
     4 "Buddhism"
     5 "Other"
/MV133
    97 "Inconsistent"
/MV134
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/MV135
     1 "Usual resident"
     2 "Visitor"
/MV148
     0 "No"
     1 "Yes"
/MV149
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
/MV150
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grand-son"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/MV151
     1 "Male"
     2 "Female"
/MV301
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
/MV302
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
/MV304A01
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$01
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$01
     0 "No"
     1 "Yes"
/MV304A02
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$02
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$02
     0 "No"
     1 "Yes"
/MV304A03
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$03
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$03
     0 "No"
     1 "Yes"
/MV304A04
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$04
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$04
     0 "No"
     1 "Yes"
/MV304A05
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$05
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$05
     0 "No"
     1 "Yes"
/MV304A06
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$06
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$06
     0 "No"
     1 "Yes"
/MV304A07
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$07
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$07
     0 "No"
     1 "Yes"
/MV304A08
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$08
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$08
     0 "No"
     1 "Yes"
/MV304A09
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$09
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$09
     0 "No"
     1 "Yes"
/MV304A10
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$10
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$10
     0 "No"
     1 "Yes"
/MV304A11
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$11
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$11
     0 "No"
     1 "Yes"
/MV304A12
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$12
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$12
     0 "No"
     1 "Yes"
/MV304A13
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$13
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$13
     0 "No"
     1 "Yes"
/MV304A14
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$14
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$14
     0 "No"
     1 "Yes"
/MV304A15
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$15
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$15
     0 "No"
     1 "Yes"
/MV312
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/MV313
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
/MV361
     1 "Currently using"
     3 "Ever used"
     4 "Never used"
/MV362
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
/MV363
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    98 "Don't know"
/MV364
     1 "Using modern method"
     2 "Using tradit. method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
/MV375A
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    95 "No reason"
    96 "Other"
    98 "DK"
/MV376
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    96 "Other"
    98 "DK"
/MV384A
     0 "No"
     1 "Yes"
/MV384B
     0 "No"
     1 "Yes"
/MV384D
     0 "No"
     1 "Yes"
/MV501
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
/MV502
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
/MV503
     1 "Once"
     2 "More than once"
/MV510
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/MV513
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
/MV527
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
/MV532
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
/MV602
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infec"
     6 "Never had sex"
     7 "Man declared infec."
/MV603
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
/MV604
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
/MV605
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
/MV610
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
/MV611
     0 "Never"
     1 "Once or twice"
     2 "More often"
/MV612
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
/MV613
    95 "Up to God"
    96 "Non-numeric response"
    98 "DK"
/MV614
     6 "6+"
     7 "Non-numeric response"
/MV616
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
/MV621
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "DK"
/MV627
    95 "Up to God"
    96 "Other"
/MV628
    95 "Up to God"
    96 "Other"
/MV629
    95 "Up to God"
    96 "Other"
/MV714
     0 "No"
     1 "Yes"
/MV716
     0 "Not working"
/MV717
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
/MV731
     0 "No"
     1 "In the past year"
     2 "Currently working"
/MV740
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
/MV762
    11 "Government hospital"
    12 "Government health c."
    13 "Family planning clin"
    14 "Mobile clinic"
    15 "Public field worker"
    16 "Other public"
    21 "Private hosp, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Private mobile clin"
    25 "Private field worker"
    26 "Other private"
    31 "Shop"
    32 "Church"
    33 "Friends, relatives"
    96 "Other"
    98 "DK source for condom"
/SDFORMAT
     1 "Bengali"
     2 "English"
/SADJUST
     0 "Not adjusted"
     1 "Adjusted"
/SDIV
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/S114A
     0 "No"
     1 "Yes"
/S114B
     0 "No"
     1 "Yes"
/S114C
     0 "No"
     1 "Yes"
/S114D
     0 "No"
     1 "Yes"
/S114E
     0 "No"
     1 "Yes"
/S119
   996 "On premises"
/S123
     0 "No children"
    11 "Sep.tank/modern tlet"
    21 "Water sld/Slab latr."
    22 "Pit latrine"
    23 "Open latrine"
    24 "Hanging latrine"
    31 "No facility,bush"
    96 "Other"
/S124A
     0 "No"
     1 "Yes"
/S124B
     0 "No"
     1 "Yes"
/S124C
     0 "No"
     1 "Yes"
/S124D
     0 "No"
     1 "Yes"
/S124I
     0 "No"
     1 "Yes"
/S229M
    97 "Inconsistent"
    98 "DK"
/S229Y
  9997 "Inconsistent"
  9998 "DK"
/S233A
     0 "No"
     1 "Yes"
/S233B
     0 "No"
     1 "Yes"
/S233C
     1 "Menstrual regulation"
     2 "Induced abortion/D&C"
     3 "Other"
/S233DY
  1300 "Bengali (Start)"
  1401 "Bengali (end)"
  1900 "English (Start)"
  1994 "English(end)"
  9997 "Inconsistent"
  9998 "Don't Know"
/MSFORMAT
     1 "Bengali"
     2 "English"
/MSADJUST
     0 "Not adjusted"
     1 "Adjusted"
/MS304$01
     0 "No"
     1 "Yes"
/MS304$02
     0 "No"
     1 "Yes"
/MS304$03
     0 "No"
     1 "Yes"
/MS304$04
     0 "No"
     1 "Yes"
/MS304$05
     0 "No"
     1 "Yes"
/MS304$06
     0 "No"
     1 "Yes"
/MS304$07
     0 "No"
     1 "Yes"
/MS304$08
     0 "No"
     1 "Yes"
/MS304$09
     0 "No"
     1 "Yes"
/MS304$10
     0 "No"
     1 "Yes"
/MS304$11
     0 "No"
     1 "Yes"
/MS304$12
     0 "No"
     1 "Yes"
/MS304$13
     0 "No"
     1 "Yes"
/MS304$14
     0 "No"
     1 "Yes"
/MS304$15
     0 "No"
     1 "Yes"
/MS304$16
     0 "No"
     1 "Yes"
/MS304$17
     0 "No"
     1 "Yes"
/MS304$18
     0 "No"
     1 "Yes"
/MS304$19
     0 "No"
     1 "Yes"
/MS304$20
     0 "No"
     1 "Yes"
/MS309
     0 "Never used"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/MS316
     0 "No"
     1 "Yes"
/MS317
     0 "Not using 2nd method"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
/MS320S
     0 "No"
     1 "Yes"
/MS320
     1 "Raja"
     2 "Panther"
     3 "Majestic"
     4 "Sensation"
     5 "Latex"
     6 "Tahiti"
     7 "Circle rubber"
     8 "Sultan"
     9 "Gent"
    10 "Durex"
    96 "Other condom brand"
    98 "Don't know brand"
/MS320A
     1 "Wife keeps"
     2 "Ran out"
     3 "Other"
/MS320C
  9995 "Partner obtained"
  9996 "Free"
  9998 "Don't know"
/MS320D
     0 "No"
     1 "Yes"
/MS321F
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
/MS321XA
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
/MS321XB
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45+"
/MS321XC
     0 "Single,before marr."
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
/MS321XD
     1 "Bengali"
     2 "English"
/MS321XE
    98 "DK month"
/MS321XF
  9997 "Inconsistent"
  9998 "DK year"
/MS322B
     0 "Does not regret"
     1 "Wants another child"
     2 "Partner wants child"
     3 "Side effects"
     4 "Other reason"
/MS322C
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/MS323
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/MS323B
     0 "No"
     1 "Yes"
     8 "Don't know"
/MS325
     1 "Respondent"
     2 "Wife"
     3 "Son/daughter"
     4 "Other relative"
     5 "Other"
/MS325A
     0 "No"
     1 "Yes"
/MS325B
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/MS325C
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/MS325H
     0 "No"
     1 "Yes"
/MS325I
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
/MS325J
     1 "Respondent had most"
     2 "Wife had most"
     3 "Husb. and wife equal"
     4 "Other relative"
     5 "Other"
/MS326
     1 "Recomm. FP worker"
     2 "Recomm. friend, rel."
     3 "Side effects others"
     4 "Method easy to use"
     5 "Access, availability"
     6 "Cost"
     7 "Wanted permanent m."
     8 "Wife preferred"
     9 "Wanted more effect."
    10 "Other"
    98 "DK"
/MS328HI
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/MS347A
     1 "Yes"
     0 "No"
     8 "DK"
/MS347B
     1 "Yes"
     0 "No"
/MS347CA
     0 "No"
     1 "Yes"
/MS347CB
     0 "No"
     1 "Yes"
/MS347CC
     0 "No"
     1 "Yes"
/MS347CD
     0 "No"
     1 "Yes"
/MS347CE
     0 "No"
     1 "Yes"
/MS348C
     0 "No"
     1 "Yes"
/MS349A
     0 "No"
     1 "Yes"
/MS349B
     0 "No"
     1 "Yes"
/MS349C
     0 "No"
     1 "Yes"
/MS349D
     0 "No"
     1 "Yes"
     8 "DK"
/MS349E
     0 "No"
     1 "Yes"
     8 "DK"
/MS350
     0 "No visit"
     1 "Yes, for Fmly Plng."
     2 "Yes, for other rsn."
     8 "DK"
/MS352
    98 "DK"
/MS353
     0 "Less than 1 mth ago"
     8 "DK"
/MS354
     0 "No"
     1 "Yes"
/MS355
     1 "Pills"
     2 "Condoms"
     3 "Injection"
     4 "Other"
/MS357A
     0 "Yes"
     1 "No"
/MS357B
     0 "Yes"
     1 "No"
/MS357C
     0 "Yes"
     1 "No"
/MS357D
     0 "Yes"
     1 "No"
/MS357E
     0 "Yes"
     1 "No"
/MS357F
     0 "Yes"
     1 "No"
/MS357G
     0 "Yes"
     1 "No"
/MS358
     0 "No"
     1 "Yes"
     8 "DK"
/MS359
     0 "No"
     1 "Yes"
/MS360
     0 "No"
     1 "Yes"
/MS361
     0 "No"
     1 "Yes"
/MS408A
     0 "No"
     1 "Yes"
/MS408B
     0 "No"
     1 "Yes"
/MS408C
     0 "No"
     1 "Yes"
/MS408D
     0 "No"
     1 "Yes"
/MS508
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Traditional doctor"
    22 "Qualified doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/MS512
     0 "No"
     1 "Yes"
/MS514
     0 "Not allowed to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
/S304$01
     0 "No"
     1 "Yes"
/S304$02
     0 "No"
     1 "Yes"
/S304$03
     0 "No"
     1 "Yes"
/S304$04
     0 "No"
     1 "Yes"
/S304$05
     0 "No"
     1 "Yes"
/S304$06
     0 "No"
     1 "Yes"
/S304$07
     0 "No"
     1 "Yes"
/S304$08
     0 "No"
     1 "Yes"
/S304$09
     0 "No"
     1 "Yes"
/S304$10
     0 "No"
     1 "Yes"
/S304$11
     0 "No"
     1 "Yes"
/S304$12
     0 "No"
     1 "Yes"
/S304$13
     0 "No"
     1 "Yes"
/S304$14
     0 "No"
     1 "Yes"
/S304$15
     0 "No"
     1 "Yes"
/S309
     0 "Never used a method"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/S310
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/S316
     0 "No"
     1 "Yes"
/S317
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/S318B
     1 "Missing in order"
     2 "Missing out of order"
     3 "No pills missing"
/S318C
     1 "DK what to do"
     2 "Health reasons"
     3 "Following instr'tns"
     4 "New packet"
     5 "Menstruating"
     6 "Other"
/S318EA
     0 "No"
     1 "Yes"
/S318EB
     0 "No"
     1 "Yes"
/S318EC
     0 "No"
     1 "Yes"
/S318ED
     0 "No"
     1 "Yes"
/S318EE
     0 "No"
     1 "Yes"
/S318EF
     0 "No"
     1 "Yes"
/S318EG
     0 "No"
     1 "Yes"
/S318F
    97 "More than 1 mnth.ago"
/S318HA
     0 "No"
     1 "Yes"
/S318HB
     0 "No"
     1 "Yes"
/S318HC
     0 "No"
     1 "Yes"
/S318HD
     0 "No"
     1 "Yes"
/S318HE
     0 "No"
     1 "Yes"
/S318HF
     0 "No"
     1 "Yes"
/S318HG
     0 "No"
     1 "Yes"
/S318HH
     0 "No"
     1 "Yes"
/S318HI
     0 "No"
     1 "Yes"
/S318I
     0 "No"
     1 "Yes"
/S318K
     1 "Start taking again"
     2 "Use extra/missed pll"
     3 "Use another method"
     4 "Extra pill+anoth.mth"
     5 "Other"
     6 "Never forgot"
/S319B
     1 "Husband away"
     2 "Forgot"
     3 "Health reasons"
     4 "Cost too much"
     5 "Not available at pr."
     6 "Other"
/S320S
     0 "No"
     1 "Yes"
/S320
     1 "Raja"
     2 "Panther"
     3 "Majestic"
     4 "Sensation"
     5 "Latex"
     6 "Tahiti"
     7 "Circle rubber"
     8 "Sultan"
     9 "Gent"
    10 "Durex"
    96 "Other condom brand"
    98 "Don't know brand"
/S320A
     1 "Husband keeps"
     2 "Ran out"
     3 "Other"
/S320C
     0 "No"
     1 "Yes"
/S322C
     1 "During period"
     2 "Imm.after per'd ends"
     3 "Middle of cycle"
     4 "Imm.bef. per'd ends"
    96 "Other"
    98 "Don't know"
/S322D
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/S323B
     0 "No"
     1 "Yes"
     8 "Don't know"
/S325
     1 "Respondent"
     2 "Husband"
     3 "Son/daughter"
     4 "Other relative"
     5 "Other"
/S325A
     0 "No"
     1 "Yes"
/S325B
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/S325C
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/S325E
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/S325G
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/S325H
     0 "No"
     1 "Yes"
/S325I
     1 "Pill, Maya"
     2 "IUD, Copper T"
     3 "Injections"
     4 "Condom, Raja"
     5 "Female Sterilization"
     6 "Male Sterilization"
     7 "Safe period,calendar"
     8 "Withdrawal"
     9 "Other"
/S325J
     1 "Respondent had most"
     2 "Husband had most"
     3 "Husb. and wife equal"
     4 "Other relative"
     5 "Other"
/S326
     1 "Recomm. FP worker"
     2 "Recomm. friend, rel."
     3 "Side effects others"
     4 "Method easy to use"
     5 "Access, availability"
     6 "Cost"
     7 "Wanted permanent m."
     8 "Husband preferred"
     9 "Wanted more effect."
    10 "Other"
    98 "DK"
/S327
     0 "No"
     1 "Yes"
/S328PA
     0 "No"
     1 "Yes"
/S328PB
     0 "No"
     1 "Yes"
/S328PC
     0 "No"
     1 "Yes"
/S328PD
     0 "No"
     1 "Yes"
/S328PE
     0 "No"
     1 "Yes"
/S328PF
     0 "No"
     1 "Yes"
/S328PG
     0 "No"
     1 "Yes"
/S328PH
     0 "No"
     1 "Yes"
/S328PI
     0 "No"
     1 "Yes"
/S328PJ
     0 "No"
     1 "Yes"
/S328PK
     0 "No"
     1 "Yes"
/S328A
     0 "No"
     1 "Yes"
/S328B
     1 "Fieldworker, FWA"
     2 "Staff satellite cl."
     3 "Staff Family Welf.Cl"
     4 "Relative, friend"
     5 "Other"
/S328C
     0 "No"
     1 "Yes"
/S328DA
     0 "No"
     1 "Yes"
/S328DB
     0 "No"
     1 "Yes"
/S328DC
     0 "No"
     1 "Yes"
/S328DD
     0 "No"
     1 "Yes"
/S328DE
     0 "No"
     1 "Yes"
/S328DF
     0 "No"
     1 "Yes"
/S328DG
     0 "No"
     1 "Yes"
/S328DH
     0 "No"
     1 "Yes"
/S328DI
     0 "No"
     1 "Yes"
/S347A
     0 "No"
     1 "Yes"
     8 "DK"
/S347B
     0 "No"
     1 "Yes"
/S347CA
     0 "No"
     1 "Yes"
/S347CB
     0 "No"
     1 "Yes"
/S347CC
     0 "No"
     1 "Yes"
/S347CD
     0 "No"
     1 "Yes"
/S347CE
     0 "No"
     1 "Yes"
/S348C
     0 "No"
     1 "Yes"
/S349A
     0 "No"
     1 "Yes"
/S349B
     0 "No"
     1 "Yes"
/S349C
     0 "No"
     1 "Yes"
/S349D
     0 "No"
     1 "Yes"
/S349E
     0 "No"
     1 "Yes"
/S352
    98 "DK"
/S353
     0 "Less than 1 mth ago"
     8 "DK"
/S354
     0 "No"
     1 "Yes"
/S355
     1 "Pills"
     2 "Condoms"
     3 "Injection"
     4 "Other"
/S357MA
     0 "Yes"
     1 "No"
/S357MB
     0 "Yes"
     1 "No"
/S357MC
     0 "Yes"
     1 "No"
/S357MD
     0 "Yes"
     1 "No"
/S357ME
     0 "Yes"
     1 "No"
/S357MF
     0 "Yes"
     1 "No"
/S357MG
     0 "Yes"
     1 "No"
/S357A
     0 "No"
     1 "Yes"
     8 "DK"
/S357B
     1 "For sterilisation"
     2 "IUD insertion"
     3 "For an Injection"
     4 "Get other FP methods"
     5 "Treatment side effs."
     6 "Other health reasons"
     7 "Other"
/S358
     0 "No"
     1 "Yes"
     8 "DK"
/S359
     0 "No"
     1 "Yes"
/S361
     0 "No"
     1 "Yes"
/S439
     0 "No"
     1 "Yes"
/S440
     1 "Doctor"
     2 "Nurse/midwife"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    12 "Other"
/S441
    96 "Did not discuss"
    98 "DK/Can't remember"
/S442A
     0 "No"
     1 "Yes"
/S442B$1
     0 "No one else"
     1 "Doctor"
     2 "Nurse/midwife/FWV"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    96 "Other"
/S442C$1
     0 "No"
     1 "Yes"
     8 "DK"
/S442DA$1
     0 "No"
     1 "Yes"
/S442DB$1
     0 "No"
     1 "Yes"
/S442DC$1
     0 "No"
     1 "Yes"
/S442DD$1
     0 "No"
     1 "Yes"
/S442DE$1
     0 "No"
     1 "Yes"
/S442DF$1
     0 "No"
     1 "Yes"
/S442DG$1
     0 "No"
     1 "Yes"
/S442DH$1
     0 "No"
     1 "Yes"
/S442DI$1
     0 "No"
     1 "Yes"
/S442DJ$1
     0 "No"
     1 "Yes"
/S442DK$1
     0 "No"
     1 "Yes"
/S442EMA1
     0 "No method rec'd."
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Prolonged Bfdng."
/S442FMA1
    95 "After menst.begins"
    96 "Not discussed"
    98 "Forgot/DK"
/S442EMB1
     0 "No method rec'd."
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Prolonged Bfdng."
/S442FMB1
    95 "After menst.begins"
    96 "Not discussed"
    98 "Forgot/DK"
/S442B$2
     0 "No one else"
     1 "Doctor"
     2 "Nurse/midwife/FWV"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    96 "Other"
/S442C$2
     0 "No"
     1 "Yes"
     8 "DK"
/S442DA$2
     0 "No"
     1 "Yes"
/S442DB$2
     0 "No"
     1 "Yes"
/S442DC$2
     0 "No"
     1 "Yes"
/S442DD$2
     0 "No"
     1 "Yes"
/S442DE$2
     0 "No"
     1 "Yes"
/S442DF$2
     0 "No"
     1 "Yes"
/S442DG$2
     0 "No"
     1 "Yes"
/S442DH$2
     0 "No"
     1 "Yes"
/S442DI$2
     0 "No"
     1 "Yes"
/S442DJ$2
     0 "No"
     1 "Yes"
/S442DK$2
     0 "No"
     1 "Yes"
/S442EMA2
     0 "No method rec'd."
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Prolonged Bfdng."
/S442FMA2
    95 "After menst.begins"
    96 "Not discussed"
    98 "Forgot/DK"
/S442EMB2
     0 "No method rec'd."
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Prolonged Bfdng."
/S442FMB2
    95 "After menst.begins"
    96 "Not discussed"
    98 "Forgot/DK"
/S442H
     1 "Doctor"
     2 "Nurse/midwife"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    12 "Other"
/S442IA
     0 "No"
     1 "Yes"
/S442IB
     0 "No"
     1 "Yes"
/S442IC
     0 "No"
     1 "Yes"
/S442ID
     0 "No"
     1 "Yes"
/S442IE
     0 "No"
     1 "Yes"
/S442IF
     0 "No"
     1 "Yes"
/S442IG
     0 "No"
     1 "Yes"
/S442J
     1 "Doctor"
     2 "Nurse/midwife"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    12 "Other"
/S442KA
     0 "No"
     1 "Yes"
/S442KB
     0 "No"
     1 "Yes"
/S442KC
     0 "No"
     1 "Yes"
/S442KD
     0 "No"
     1 "Yes"
/S442KE
     0 "No"
     1 "Yes"
/S442KF
     0 "No"
     1 "Yes"
/S442L
     0 "No"
     1 "Yes"
     8 "DK"
/S442MA
     0 "No"
     1 "Yes"
/S442MB
     0 "No"
     1 "Yes"
/S442MC
     0 "No"
     1 "Yes"
/S442MD
     0 "No"
     1 "Yes"
/S442ME
     0 "No"
     1 "Yes"
/S442MF
     0 "No"
     1 "Yes"
/S442MG
     0 "No"
     1 "Yes"
/S442MH
     0 "No"
     1 "Yes"
/S442MI
     0 "No"
     1 "Yes"
/S442N
     0 "No"
     1 "Yes"
     8 "DK"
/S442O
    96 "Until next period"
    98 "DK"
/S609
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Traditional doctor"
    22 "Qualified doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/S613
     0 "No"
     1 "Yes"
/S615
     0 "Not allowd to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
/S616
     1 "1x month or more"
     2 "Several times a year"
     3 "Less than 1x a year"
     4 "Never"
/S617
     1 "1x month or more"
     2 "Several times a year"
     3 "Less than 1x a year"
     4 "Never"
/S618
     0 "Not allowd to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
.
