infix using BDCR31FL.dct

label variable caseid   "Case Identification"
label variable v000     "Country code and phase"
label variable v001     "Cluster number"
label variable v002     "Household number"
label variable v003     "Respondent's line number"
label variable v004     "Ultimate area unit"
label variable v005     "Sample weight"
label variable v006     "Month of interview"
label variable v007     "Year of interview"
label variable v008     "Date of interview (CMC)"
label variable v009     "Respondent's month of birth"
label variable v010     "Respondent's year of birth"
label variable v011     "Date of birth (CMC)"
label variable v012     "Current age - respondent"
label variable v013     "Age 5-year groups"
label variable v014     "Completeness of information"
label variable v015     "Result of individual interview"
label variable v016     "Day of interview"
label variable v017     "CMC start of calendar"
label variable v018     "Row of month of interview"
label variable v019     "Length of calendar"
label variable v020     "Ever-married sample"
label variable v021     "Primary sampling unit"
label variable v022     "Sample stratum number"
label variable v023     "Sample domain"
label variable v024     "Region"
label variable v025     "Type of place of residence"
label variable v026     "De facto place of residence"
label variable v027     "Number of visits"
label variable v028     "Interviewer identification"
label variable v029     "Keyer identification"
label variable v030     "Field supervisor -NA"
label variable v031     "Field editor -NA"
label variable v032     "Office editor -NA"
label variable v033     "Ultimate area selection prob."
label variable v034     "Line number of husband"
label variable v101     "Region"
label variable v102     "Type of place of residence"
label variable v103     "Childhood place of residen -NA"
label variable v104     "Years lived in place of res."
label variable v105     "Type of place of previous res."
label variable v106     "Highest educational level"
label variable v107     "Highest year of education"
label variable v108     "Literacy"
label variable v109     "Reads newspaper once a week"
label variable v110     "Watches TV every week"
label variable v111     "Listens to radio every day -NA"
label variable v112     "Listens to radio every week"
label variable v113     "Source of drinking water"
label variable v114     "Source of non-drinking water"
label variable v115     "Time to get to water source"
label variable v116     "Type of toilet facility"
label variable v119     "Has electricity"
label variable v120     "Has radio"
label variable v121     "Has television"
label variable v122     "Has refrigerator -NA"
label variable v123     "Has bicycle"
label variable v124     "Has motorcycle -NA"
label variable v125     "Has car -NA"
label variable v127     "Main floor material"
label variable v128     "Main wall material"
label variable v129     "Main roof material"
label variable v130     "Religion"
label variable v131     "Ethnicity -NA"
label variable v133     "Education in single years"
label variable v134     "De facto place of residence"
label variable v135     "Usual resident or visitor"
label variable v136     "Number of household members"
label variable v137     "Number of children 5 and under"
label variable v138     "Number of eligible women in HH"
label variable v139     "De jure region of residence"
label variable v140     "De jure type of place of res."
label variable v141     "De jure place of residence"
label variable v142     "Same source of water"
label variable v144     "Communities lived in >Jan.8-NA"
label variable v148     "Respondent still in school"
label variable v149     "Educational attainment"
label variable v150     "Relationship to household head"
label variable v151     "Sex of household head"
label variable v152     "Age of household head"
label variable v153     "Has telephone -NA"
label variable v154     "Reason stop attending schoo-NA"
label variable awfactt  "All woman factor - total"
label variable awfactu  "All woman factor - urban/rural"
label variable awfactr  "All woman factor - regional"
label variable awfacte  "All woman factor - educational"
label variable bidx_01  "Birth column number"
label variable bord_01  "Birth order number"
label variable b0_01    "Child is twin"
label variable b1_01    "Month of birth"
label variable b2_01    "Year of birth"
label variable b3_01    "Date of birth (CMC)"
label variable b4_01    "Sex of child"
label variable b5_01    "Child is alive"
label variable b6_01    "Age at death"
label variable b7_01    "Age at death (months-imputed)"
label variable b8_01    "Current age of child"
label variable b9_01    "Who child lives with"
label variable b10_01   "Completeness of information"
label variable b11_01   "Preceding birth interval"
label variable b12_01   "Succeeding birth interval"
label variable b13_01   "Flag for age at death"
label variable b14_01   "Birth interval >= 4 years -NA"
label variable b15_01   "Live birth between births -NA"
label variable bidx_02  "Birth column number"
label variable bord_02  "Birth order number"
label variable b0_02    "Child is twin"
label variable b1_02    "Month of birth"
label variable b2_02    "Year of birth"
label variable b3_02    "Date of birth (CMC)"
label variable b4_02    "Sex of child"
label variable b5_02    "Child is alive"
label variable b6_02    "Age at death"
label variable b7_02    "Age at death (months-imputed)"
label variable b8_02    "Current age of child"
label variable b9_02    "Who child lives with"
label variable b10_02   "Completeness of information"
label variable b11_02   "Preceding birth interval"
label variable b12_02   "Succeeding birth interval"
label variable b13_02   "Flag for age at death"
label variable b14_02   "Birth interval >= 4 years -NA"
label variable b15_02   "Live birth between births -NA"
label variable bidx_03  "Birth column number"
label variable bord_03  "Birth order number"
label variable b0_03    "Child is twin"
label variable b1_03    "Month of birth"
label variable b2_03    "Year of birth"
label variable b3_03    "Date of birth (CMC)"
label variable b4_03    "Sex of child"
label variable b5_03    "Child is alive"
label variable b6_03    "Age at death"
label variable b7_03    "Age at death (months-imputed)"
label variable b8_03    "Current age of child"
label variable b9_03    "Who child lives with"
label variable b10_03   "Completeness of information"
label variable b11_03   "Preceding birth interval"
label variable b12_03   "Succeeding birth interval"
label variable b13_03   "Flag for age at death"
label variable b14_03   "Birth interval >= 4 years -NA"
label variable b15_03   "Live birth between births -NA"
label variable bidx_04  "Birth column number"
label variable bord_04  "Birth order number"
label variable b0_04    "Child is twin"
label variable b1_04    "Month of birth"
label variable b2_04    "Year of birth"
label variable b3_04    "Date of birth (CMC)"
label variable b4_04    "Sex of child"
label variable b5_04    "Child is alive"
label variable b6_04    "Age at death"
label variable b7_04    "Age at death (months-imputed)"
label variable b8_04    "Current age of child"
label variable b9_04    "Who child lives with"
label variable b10_04   "Completeness of information"
label variable b11_04   "Preceding birth interval"
label variable b12_04   "Succeeding birth interval"
label variable b13_04   "Flag for age at death"
label variable b14_04   "Birth interval >= 4 years -NA"
label variable b15_04   "Live birth between births -NA"
label variable bidx_05  "Birth column number"
label variable bord_05  "Birth order number"
label variable b0_05    "Child is twin"
label variable b1_05    "Month of birth"
label variable b2_05    "Year of birth"
label variable b3_05    "Date of birth (CMC)"
label variable b4_05    "Sex of child"
label variable b5_05    "Child is alive"
label variable b6_05    "Age at death"
label variable b7_05    "Age at death (months-imputed)"
label variable b8_05    "Current age of child"
label variable b9_05    "Who child lives with"
label variable b10_05   "Completeness of information"
label variable b11_05   "Preceding birth interval"
label variable b12_05   "Succeeding birth interval"
label variable b13_05   "Flag for age at death"
label variable b14_05   "Birth interval >= 4 years -NA"
label variable b15_05   "Live birth between births -NA"
label variable bidx_06  "Birth column number"
label variable bord_06  "Birth order number"
label variable b0_06    "Child is twin"
label variable b1_06    "Month of birth"
label variable b2_06    "Year of birth"
label variable b3_06    "Date of birth (CMC)"
label variable b4_06    "Sex of child"
label variable b5_06    "Child is alive"
label variable b6_06    "Age at death"
label variable b7_06    "Age at death (months-imputed)"
label variable b8_06    "Current age of child"
label variable b9_06    "Who child lives with"
label variable b10_06   "Completeness of information"
label variable b11_06   "Preceding birth interval"
label variable b12_06   "Succeeding birth interval"
label variable b13_06   "Flag for age at death"
label variable b14_06   "Birth interval >= 4 years -NA"
label variable b15_06   "Live birth between births -NA"
label variable bidx_07  "Birth column number"
label variable bord_07  "Birth order number"
label variable b0_07    "Child is twin"
label variable b1_07    "Month of birth"
label variable b2_07    "Year of birth"
label variable b3_07    "Date of birth (CMC)"
label variable b4_07    "Sex of child"
label variable b5_07    "Child is alive"
label variable b6_07    "Age at death"
label variable b7_07    "Age at death (months-imputed)"
label variable b8_07    "Current age of child"
label variable b9_07    "Who child lives with"
label variable b10_07   "Completeness of information"
label variable b11_07   "Preceding birth interval"
label variable b12_07   "Succeeding birth interval"
label variable b13_07   "Flag for age at death"
label variable b14_07   "Birth interval >= 4 years -NA"
label variable b15_07   "Live birth between births -NA"
label variable bidx_08  "Birth column number"
label variable bord_08  "Birth order number"
label variable b0_08    "Child is twin"
label variable b1_08    "Month of birth"
label variable b2_08    "Year of birth"
label variable b3_08    "Date of birth (CMC)"
label variable b4_08    "Sex of child"
label variable b5_08    "Child is alive"
label variable b6_08    "Age at death"
label variable b7_08    "Age at death (months-imputed)"
label variable b8_08    "Current age of child"
label variable b9_08    "Who child lives with"
label variable b10_08   "Completeness of information"
label variable b11_08   "Preceding birth interval"
label variable b12_08   "Succeeding birth interval"
label variable b13_08   "Flag for age at death"
label variable b14_08   "Birth interval >= 4 years -NA"
label variable b15_08   "Live birth between births -NA"
label variable bidx_09  "Birth column number"
label variable bord_09  "Birth order number"
label variable b0_09    "Child is twin"
label variable b1_09    "Month of birth"
label variable b2_09    "Year of birth"
label variable b3_09    "Date of birth (CMC)"
label variable b4_09    "Sex of child"
label variable b5_09    "Child is alive"
label variable b6_09    "Age at death"
label variable b7_09    "Age at death (months-imputed)"
label variable b8_09    "Current age of child"
label variable b9_09    "Who child lives with"
label variable b10_09   "Completeness of information"
label variable b11_09   "Preceding birth interval"
label variable b12_09   "Succeeding birth interval"
label variable b13_09   "Flag for age at death"
label variable b14_09   "Birth interval >= 4 years -NA"
label variable b15_09   "Live birth between births -NA"
label variable bidx_10  "Birth column number"
label variable bord_10  "Birth order number"
label variable b0_10    "Child is twin"
label variable b1_10    "Month of birth"
label variable b2_10    "Year of birth"
label variable b3_10    "Date of birth (CMC)"
label variable b4_10    "Sex of child"
label variable b5_10    "Child is alive"
label variable b6_10    "Age at death"
label variable b7_10    "Age at death (months-imputed)"
label variable b8_10    "Current age of child"
label variable b9_10    "Who child lives with"
label variable b10_10   "Completeness of information"
label variable b11_10   "Preceding birth interval"
label variable b12_10   "Succeeding birth interval"
label variable b13_10   "Flag for age at death"
label variable b14_10   "Birth interval >= 4 years -NA"
label variable b15_10   "Live birth between births -NA"
label variable bidx_11  "Birth column number"
label variable bord_11  "Birth order number"
label variable b0_11    "Child is twin"
label variable b1_11    "Month of birth"
label variable b2_11    "Year of birth"
label variable b3_11    "Date of birth (CMC)"
label variable b4_11    "Sex of child"
label variable b5_11    "Child is alive"
label variable b6_11    "Age at death"
label variable b7_11    "Age at death (months-imputed)"
label variable b8_11    "Current age of child"
label variable b9_11    "Who child lives with"
label variable b10_11   "Completeness of information"
label variable b11_11   "Preceding birth interval"
label variable b12_11   "Succeeding birth interval"
label variable b13_11   "Flag for age at death"
label variable b14_11   "Birth interval >= 4 years -NA"
label variable b15_11   "Live birth between births -NA"
label variable bidx_12  "Birth column number"
label variable bord_12  "Birth order number"
label variable b0_12    "Child is twin"
label variable b1_12    "Month of birth"
label variable b2_12    "Year of birth"
label variable b3_12    "Date of birth (CMC)"
label variable b4_12    "Sex of child"
label variable b5_12    "Child is alive"
label variable b6_12    "Age at death"
label variable b7_12    "Age at death (months-imputed)"
label variable b8_12    "Current age of child"
label variable b9_12    "Who child lives with"
label variable b10_12   "Completeness of information"
label variable b11_12   "Preceding birth interval"
label variable b12_12   "Succeeding birth interval"
label variable b13_12   "Flag for age at death"
label variable b14_12   "Birth interval >= 4 years -NA"
label variable b15_12   "Live birth between births -NA"
label variable bidx_13  "Birth column number"
label variable bord_13  "Birth order number"
label variable b0_13    "Child is twin"
label variable b1_13    "Month of birth"
label variable b2_13    "Year of birth"
label variable b3_13    "Date of birth (CMC)"
label variable b4_13    "Sex of child"
label variable b5_13    "Child is alive"
label variable b6_13    "Age at death"
label variable b7_13    "Age at death (months-imputed)"
label variable b8_13    "Current age of child"
label variable b9_13    "Who child lives with"
label variable b10_13   "Completeness of information"
label variable b11_13   "Preceding birth interval"
label variable b12_13   "Succeeding birth interval"
label variable b13_13   "Flag for age at death"
label variable b14_13   "Birth interval >= 4 years -NA"
label variable b15_13   "Live birth between births -NA"
label variable bidx_14  "Birth column number"
label variable bord_14  "Birth order number"
label variable b0_14    "Child is twin"
label variable b1_14    "Month of birth"
label variable b2_14    "Year of birth"
label variable b3_14    "Date of birth (CMC)"
label variable b4_14    "Sex of child"
label variable b5_14    "Child is alive"
label variable b6_14    "Age at death"
label variable b7_14    "Age at death (months-imputed)"
label variable b8_14    "Current age of child"
label variable b9_14    "Who child lives with"
label variable b10_14   "Completeness of information"
label variable b11_14   "Preceding birth interval"
label variable b12_14   "Succeeding birth interval"
label variable b13_14   "Flag for age at death"
label variable b14_14   "Birth interval >= 4 years -NA"
label variable b15_14   "Live birth between births -NA"
label variable bidx_15  "Birth column number"
label variable bord_15  "Birth order number"
label variable b0_15    "Child is twin"
label variable b1_15    "Month of birth"
label variable b2_15    "Year of birth"
label variable b3_15    "Date of birth (CMC)"
label variable b4_15    "Sex of child"
label variable b5_15    "Child is alive"
label variable b6_15    "Age at death"
label variable b7_15    "Age at death (months-imputed)"
label variable b8_15    "Current age of child"
label variable b9_15    "Who child lives with"
label variable b10_15   "Completeness of information"
label variable b11_15   "Preceding birth interval"
label variable b12_15   "Succeeding birth interval"
label variable b13_15   "Flag for age at death"
label variable b14_15   "Birth interval >= 4 years -NA"
label variable b15_15   "Live birth between births -NA"
label variable bidx_16  "Birth column number"
label variable bord_16  "Birth order number"
label variable b0_16    "Child is twin"
label variable b1_16    "Month of birth"
label variable b2_16    "Year of birth"
label variable b3_16    "Date of birth (CMC)"
label variable b4_16    "Sex of child"
label variable b5_16    "Child is alive"
label variable b6_16    "Age at death"
label variable b7_16    "Age at death (months-imputed)"
label variable b8_16    "Current age of child"
label variable b9_16    "Who child lives with"
label variable b10_16   "Completeness of information"
label variable b11_16   "Preceding birth interval"
label variable b12_16   "Succeeding birth interval"
label variable b13_16   "Flag for age at death"
label variable b14_16   "Birth interval >= 4 years -NA"
label variable b15_16   "Live birth between births -NA"
label variable bidx_17  "Birth column number"
label variable bord_17  "Birth order number"
label variable b0_17    "Child is twin"
label variable b1_17    "Month of birth"
label variable b2_17    "Year of birth"
label variable b3_17    "Date of birth (CMC)"
label variable b4_17    "Sex of child"
label variable b5_17    "Child is alive"
label variable b6_17    "Age at death"
label variable b7_17    "Age at death (months-imputed)"
label variable b8_17    "Current age of child"
label variable b9_17    "Who child lives with"
label variable b10_17   "Completeness of information"
label variable b11_17   "Preceding birth interval"
label variable b12_17   "Succeeding birth interval"
label variable b13_17   "Flag for age at death"
label variable b14_17   "Birth interval >= 4 years -NA"
label variable b15_17   "Live birth between births -NA"
label variable bidx_18  "Birth column number"
label variable bord_18  "Birth order number"
label variable b0_18    "Child is twin"
label variable b1_18    "Month of birth"
label variable b2_18    "Year of birth"
label variable b3_18    "Date of birth (CMC)"
label variable b4_18    "Sex of child"
label variable b5_18    "Child is alive"
label variable b6_18    "Age at death"
label variable b7_18    "Age at death (months-imputed)"
label variable b8_18    "Current age of child"
label variable b9_18    "Who child lives with"
label variable b10_18   "Completeness of information"
label variable b11_18   "Preceding birth interval"
label variable b12_18   "Succeeding birth interval"
label variable b13_18   "Flag for age at death"
label variable b14_18   "Birth interval >= 4 years -NA"
label variable b15_18   "Live birth between births -NA"
label variable bidx_19  "Birth column number"
label variable bord_19  "Birth order number"
label variable b0_19    "Child is twin"
label variable b1_19    "Month of birth"
label variable b2_19    "Year of birth"
label variable b3_19    "Date of birth (CMC)"
label variable b4_19    "Sex of child"
label variable b5_19    "Child is alive"
label variable b6_19    "Age at death"
label variable b7_19    "Age at death (months-imputed)"
label variable b8_19    "Current age of child"
label variable b9_19    "Who child lives with"
label variable b10_19   "Completeness of information"
label variable b11_19   "Preceding birth interval"
label variable b12_19   "Succeeding birth interval"
label variable b13_19   "Flag for age at death"
label variable b14_19   "Birth interval >= 4 years -NA"
label variable b15_19   "Live birth between births -NA"
label variable bidx_20  "Birth column number"
label variable bord_20  "Birth order number"
label variable b0_20    "Child is twin"
label variable b1_20    "Month of birth"
label variable b2_20    "Year of birth"
label variable b3_20    "Date of birth (CMC)"
label variable b4_20    "Sex of child"
label variable b5_20    "Child is alive"
label variable b6_20    "Age at death"
label variable b7_20    "Age at death (months-imputed)"
label variable b8_20    "Current age of child"
label variable b9_20    "Who child lives with"
label variable b10_20   "Completeness of information"
label variable b11_20   "Preceding birth interval"
label variable b12_20   "Succeeding birth interval"
label variable b13_20   "Flag for age at death"
label variable b14_20   "Birth interval >= 4 years -NA"
label variable b15_20   "Live birth between births -NA"
label variable v201     "Total children ever born"
label variable v202     "Sons at home"
label variable v203     "Daughters at home"
label variable v204     "Sons elsewhere"
label variable v205     "Daughters elsewhere"
label variable v206     "Sons who have died"
label variable v207     "Daughters who have died"
label variable v208     "Births in last five years"
label variable v209     "Births in past year"
label variable v210     "Births in month of interview"
label variable v211     "Date of first birth (CMC)"
label variable v212     "Age of respondent at 1st birth"
label variable v213     "Currently pregnant"
label variable v214     "Duration of current pregnancy"
label variable v215     "Time since last menstrual perd"
label variable v216     "Menstruated in last six weeks"
label variable v217     "Knowledge of ovulatory cycl-NA"
label variable v218     "Number of living children"
label variable v219     "Living children + current preg"
label variable v220     "Living children + curr preg 6+"
label variable v221     "Marriage to first birth int."
label variable v222     "Last birth to interview"
label variable v223     "Completeness of curr preg. inf"
label variable v224     "Entries in birth history"
label variable v225     "Current pregnancy wanted"
label variable v226     "Time since last period (comp)"
label variable v227     "Flag for last period"
label variable v228     "Ever had a terminated preg."
label variable v229     "Month pregnancy ended"
label variable v230     "Year pregnancy ended"
label variable v231     "CMC pregnancy ended"
label variable v232     "Completeness of last term. inf"
label variable v233     "Months when pregnancy ended"
label variable v234     "Other such pregnancies"
label variable v235     "Index last child prior to cal."
label variable v236     "Last birth interval >= 4 ye-NA"
label variable v237     "Birth between last & interv-NA"
label variable v238     "Births in last three years"
label variable v301     "Knowledge of any method"
label variable v302     "Ever use of any method"
label variable v304a_01 "Type of method"
label variable v304_01  "Knows method"
label variable v305_01  "Ever used method"
label variable v304a_02 "Type of method"
label variable v304_02  "Knows method"
label variable v305_02  "Ever used method"
label variable v304a_03 "Type of method"
label variable v304_03  "Knows method"
label variable v305_03  "Ever used method"
label variable v304a_04 "Type of method"
label variable v304_04  "Knows method"
label variable v305_04  "Ever used method"
label variable v304a_05 "Type of method"
label variable v304_05  "Knows method"
label variable v305_05  "Ever used method"
label variable v304a_06 "Type of method"
label variable v304_06  "Knows method"
label variable v305_06  "Ever used method"
label variable v304a_07 "Type of method"
label variable v304_07  "Knows method"
label variable v305_07  "Ever used method"
label variable v304a_08 "Type of method"
label variable v304_08  "Knows method"
label variable v305_08  "Ever used method"
label variable v304a_09 "Type of method"
label variable v304_09  "Knows method"
label variable v305_09  "Ever used method"
label variable v304a_10 "Type of method"
label variable v304_10  "Knows method"
label variable v305_10  "Ever used method"
label variable v304a_11 "Type of method"
label variable v304_11  "Knows method"
label variable v305_11  "Ever used method"
label variable v304a_12 "Type of method"
label variable v304_12  "Knows method"
label variable v305_12  "Ever used method"
label variable v304a_13 "Type of method"
label variable v304_13  "Knows method"
label variable v305_13  "Ever used method"
label variable v304a_14 "Type of method"
label variable v304_14  "Knows method"
label variable v305_14  "Ever used method"
label variable v304a_15 "Type of method"
label variable v304_15  "Knows method"
label variable v305_15  "Ever used method"
label variable v310     "Living children at first use"
label variable v311     "Children at first use (grpd)"
label variable v312     "Current contraceptive method"
label variable v313     "Current use by method type"
label variable v314     "Method of periodic abstinen-NA"
label variable v315     "Month of sterilization"
label variable v316     "Year of sterilization"
label variable v317     "Date of sterilization (CMC)"
label variable v318     "Completeness of information"
label variable v319     "Years since sterilization"
label variable v320     "Age at sterilization"
label variable v321     "Marital duration at steriliz."
label variable v322     "Parity at sterilization"
label variable v323     "Brand of pill used"
label variable v325     "Cost of pills"
label variable v326     "Last source for current users"
label variable v327     "Last source for users by type"
label variable v328     "Main reason use current sou-NA"
label variable v337     "Months of use of current meth"
label variable v359     "Last method disc. last 5 years"
label variable v360     "Reason of last discontinuation"
label variable v361     "Pattern of use"
label variable v362     "Intention to use"
label variable v363     "Preferred future method"
label variable v364     "Contraceptive use & intention"
label variable v366a    "Acceptability of radio message"
label variable v366b    "Acceptability of TV message-NA"
label variable v367     "Wanted last child"
label variable v369     "First method used"
label variable v369b    "First use to space or limit-NA"
label variable v372     "Shown pill package"
label variable v375a    "Main reason not using a method"
label variable v376     "Main reason not to use a meth."
label variable v376a    "Would ever use method if ma-NA"
label variable v379     "Source known for any method"
label variable v380     "Source known for any method"
label variable v384a    "Heard FP on radio last months"
label variable v384b    "Heard FP on TV last months"
label variable v384c    "Heard FP newspaper last mon-NA"
label variable v384d    "Heard FP on poster last months"
label variable v384e    "Heard FP brochures last mon-NA"
label variable v393     "Visited by FP worker last 6m"
label variable v394     "Visited health facil. last 12m"
label variable v395     "At health facility, told of FP"
label variable v396     "Breastfeeding affect pregnancy"
label variable v397     "Pregnancy risk of breastfee-NA"
label variable v398     "Relied breastfeed. avoid pr-NA"
label variable v399     "Currently rely on breastfee-NA"
label variable v401     "Last birth ceasarean sectio-NA"
label variable v404     "Currently breastfeeding"
label variable v405     "Currently amenorrheic"
label variable v406     "Currently abstaining"
label variable v407     "Times breastfed during night"
label variable v408     "Times breastfed during day"
label variable v409     "Gave child plain water"
label variable v409a    "Gave child sugar water"
label variable v410     "Gave child juice"
label variable v410a    "Gave child herbal tea"
label variable v411     "Gave child powder/tinned mi-NA"
label variable v411a    "Gave child baby formula"
label variable v412     "Gave child fresh milk"
label variable v413a    "Country specific other liqu-NA"
label variable v413b    "Country specific other liqu-NA"
label variable v413c    "Country specific other liqu-NA"
label variable v413d    "Country specific other liqu-NA"
label variable v413     "Gave child other liquid"
label variable v414a    "Country specific other food-NA"
label variable v414b    "Country specific other food-NA"
label variable v414c    "Country specific other food-NA"
label variable v414d    "Other solid, semi-solid foods"
label variable v414e    "Food made from local grain -NA"
label variable v414f    "Food made from local tuber -NA"
label variable v414g    "Gave child eggs, fish, poul-NA"
label variable v414h    "Gave child meat"
label variable v415     "Drank from bottle with nipp-NA"
label variable v416     "Heard of oral rehydration"
label variable v417     "Entries in maternity table"
label variable v418     "Entries in health table"
label variable v419     "Entries in height/weight ta-NA"
label variable v420     "Measurer's code -NA"
label variable v421     "Assistant measurer's code -NA"
label variable v426     "When child put to breast"
label variable v436     "Arm circumference (cms-1d) -NA"
label variable v437     "Respondent's weight (kilos--NA"
label variable v438     "Respondent's height (cms-1d-NA"
label variable v439     "Ht/A Percentile (resp.) -NA"
label variable v440     "Ht/A Standard deviations (r-NA"
label variable v441     "Ht/A Percent ref. median (r-NA"
label variable v442     "Wt/Ht Percent ref. median (-NA"
label variable v443     "Wt/Ht Percent ref. median (-NA"
label variable v444     "Wt/Ht Percent ref. median (-NA"
label variable v444a    "Wt/Ht Std deviations(resp) -NA"
label variable v445     "Body mass index for respond-NA"
label variable v446     "Rohrer's index for responde-NA"
label variable v447     "Result of measurement of re-NA"
label variable v448     "Drinking pattern with diarr-NA"
label variable v449     "Eating pattern with diarrhe-NA"
label variable v450a    "Diarrhea: repeat watery sto-NA"
label variable v450b    "Diarrhea: Any watery stools-NA"
label variable v450c    "Diarrhea: Repeated vomiting-NA"
label variable v450d    "Diarrhea: Any vomiting -NA"
label variable v450e    "Diarrhea: Blood in stools -NA"
label variable v450f    "Diarrhea: Fever -NA"
label variable v450g    "Diarrhea: Marked thirst -NA"
label variable v450h    "Diarrhea: Not eating/drinki-NA"
label variable v450i    "Diarrhea: Getting sicker -NA"
label variable v450j    "Diarrhea: Not getting bette-NA"
label variable v450k    "Diarrhea: Country specific -NA"
label variable v450l    "Diarrhea: Country specific -NA"
label variable v450m    "Diarrhea: Country specific -NA"
label variable v450x    "Diarrhea: Other responses -NA"
label variable v450z    "Diarrhea: Does not know -NA"
label variable v451a    "Cough: Fast breathing -NA"
label variable v451b    "Cough: Difficult breathing -NA"
label variable v451c    "Cough: Noisy breathing -NA"
label variable v451d    "Cough: Fever -NA"
label variable v451e    "Cough: Unable to drink -NA"
label variable v451f    "Cough: Not eating/drinking -NA"
label variable v451g    "Cough: Getting sicker -NA"
label variable v451h    "Cough: Not getting better -NA"
label variable v451i    "Cough: Country specific -NA"
label variable v451j    "Cough: Country specific -NA"
label variable v451k    "Cough: Country specific -NA"
label variable v451x    "Cough: Other responses -NA"
label variable v451z    "Knows no sign of illness -NA"
label variable v501     "Current marital status"
label variable v502     "Currently/formerly/never marr."
label variable v503     "Number of unions"
label variable v504     "Husband lives in house"
label variable v505     "Number of other wives - NA"
label variable v506     "Wife rank number - NA"
label variable v507     "Month of first marriage"
label variable v508     "Year of first marriage"
label variable v509     "Date of first marriage (CMC)"
label variable v510     "Completeness of date inform."
label variable v511     "Age at first marriage"
label variable v512     "Years since first marriage"
label variable v513     "Marital duration (grouped)"
label variable v525     "Age at first intercourse - NA"
label variable v527     "Time since last intercourse"
label variable v528     "Time since last intercourse(g)"
label variable v529     "Time since last intercourse(im"
label variable v530     "Flag for V529"
label variable v531     "Age at first intercourse - NA"
label variable v532     "Flag for V531 -NA"
label variable v534     "Have a regular sex partne - NA"
label variable v535     "Have ever been married"
label variable v602     "Fertility preference"
label variable v603     "Preferred waiting time"
label variable v604     "Preferred waiting time (grpd)"
label variable v605     "Desire for more children"
label variable v606     "Attitude toward becoming preg."
label variable v610     "Husband approves FP"
label variable v611     "Discussed FP with partner"
label variable v612     "Respondent approves FP"
label variable v613     "Ideal number of children"
label variable v614     "Ideal number of children (grp)"
label variable v616     "Time for future birth"
label variable v618     "Reason regrets sterilization"
label variable v621     "Husbands desire for children"
label variable v623     "Exposure"
label variable v624     "Unmet need"
label variable v625     "Exposure (definition 2)"
label variable v626     "Unmet need (definition 2)"
label variable v627     "Ideal number of boys"
label variable v628     "Ideal number of girls"
label variable v629     "Ideal number of either sex"
label variable v630a    "Discussed FP with partner - NA"
label variable v630b    "Discussed FP with mother - NA"
label variable v630c    "Discussed FP with father - NA"
label variable v630d    "Discussed FP with sister( - NA"
label variable v630e    "Discussed FP with brother - NA"
label variable v630f    "Discussed FP with daughte - NA"
label variable v630g    "Discussed FP with mother- - NA"
label variable v630h    "Discussed FP with friends - NA"
label variable v630i    "Discussed FP -country spe - NA"
label variable v630j    "Discussed FP -country spe - NA"
label variable v630k    "Discussed FP -country spe - NA"
label variable v630l    "Discussed FP -country spe - NA"
label variable v630x    "Discussed FP with others - NA"
label variable v701     "Partner's education level"
label variable v702     "Highest year of education"
label variable v704     "Partner's occupation"
label variable v705     "Partner's occupation"
label variable v707     "Type of land where works"
label variable v714     "Respondent currently working"
label variable v715     "Husbands education-single yrs"
label variable v716     "Respondent's occupation"
label variable v717     "Respondent's occupation"
label variable v718     "Current type of employment"
label variable v719     "Work for family, others, self"
label variable v720     "Earns cash for work"
label variable v721     "Works at home or away"
label variable v723     "Child minder"
label variable v729     "Partner's educational attainm."
label variable v730     "Partners age -NA"
label variable v731     "Worked in last 12 months - NA"
label variable v732     "Employment all year/seasonal"
label variable v733     "Months worked in last 12 - NA"
label variable v734     "Days in a week normally w - NA"
label variable v735     "Days worked in last 12 mo - NA"
label variable v736     "Earnings for work - NA"
label variable v737     "Daily earnings for work - NA"
label variable v738     "Yearly earnings for work - NA"
label variable v739     "Who decides how to spend money"
label variable v740     "Type of land where resp. works"
label variable v751     "Ever heard of AIDS -NA"
label variable v752a    "AIDS: radio - NA"
label variable v752b    "AIDS: television - NA"
label variable v752c    "AIDS: newspapers/magazine - NA"
label variable v752d    "AIDS: pamphlets/posters - NA"
label variable v752e    "AIDS: clinic/health worke - NA"
label variable v752f    "AIDS: churches/mosques - NA"
label variable v752g    "AIDS: schools/teachers - NA"
label variable v752h    "AIDS: community meetings - NA"
label variable v752i    "AIDS: friends/relatives - NA"
label variable v752j    "AIDS: work place - NA"
label variable v752k    "AIDS: country specific - NA"
label variable v752l    "AIDS: country specific - NA"
label variable v752m    "AIDS: country specific - NA"
label variable v752n    "AIDS: country specific - NA"
label variable v752o    "AIDS: country specific - NA"
label variable v752x    "AIDS: other responses - NA"
label variable v753     "Ways to avoid AIDS - NA"
label variable v754a    "AIDS: Safe sex - NA"
label variable v754b    "AIDS: abstain from sex - NA"
label variable v754c    "AIDS: use condoms during - NA"
label variable v754d    "AIDS: only one sex partne - NA"
label variable v754e    "AIDS: avoid sex prostitut - NA"
label variable v754f    "AIDS: avoid sex homosexua - NA"
label variable v754g    "AIDS: avoid blood transfu - NA"
label variable v754h    "AIDS: avoid injections - NA"
label variable v754i    "AIDS: avoid kissing - NA"
label variable v754j    "AIDS: avoid mosquito bite - NA"
label variable v754k    "AIDS: protection trad. he - NA"
label variable v754l    "AIDS: country specific - NA"
label variable v754m    "AIDS: country specific - NA"
label variable v754n    "AIDS: country specific - NA"
label variable v754o    "AIDS: country specific - NA"
label variable v754x    "AIDS: other responses - NA"
label variable v754z    "AIDS: DK ways to avoid AI - NA"
label variable v755b    "Safe sex: abstain from se - NA"
label variable v755c    "Safe sex: use condoms dur - NA"
label variable v755d    "Safe sex: only one partne - NA"
label variable v755e    "Safe sex: avoid prostitut - NA"
label variable v755f    "Safe sex: avoid homosexua - NA"
label variable v755l    "Safe sex: country specifi - NA"
label variable v755m    "Safe sex: country specifi - NA"
label variable v755n    "Safe sex: country specifi - NA"
label variable v755o    "Safe sex: country specifi - NA"
label variable v755x    "Safe sex: other responses - NA"
label variable v755z    "Safe sex: DK meaning - NA"
label variable v756     "Can a healthy person have - NA"
label variable v757     "Is AIDS a fatal disease - NA"
label variable v758     "Chances of getting AIDS - NA"
label variable v760a    "Behavior: Did not start s - NA"
label variable v760b    "Behavior: Stopped all sex - NA"
label variable v760c    "Behavior: Started using c - NA"
label variable v760d    "Behavior: Only one sex pa - NA"
label variable v760e    "Behavior: Reduced partner - NA"
label variable v760f    "Behavior: Ask spouse fait - NA"
label variable v760g    "Behavior: No homosexual c - NA"
label variable v760i    "Behavior: Stopped injecti - NA"
label variable v760l    "Behavior: Country specifi - NA"
label variable v760m    "Behavior: Country specifi - NA"
label variable v760n    "Behavior: Country specifi - NA"
label variable v760o    "Behavior: Country specifi - NA"
label variable v760p    "Behavior: Spouse avoid pro- NA"
label variable v760v    "Behavior: No nonsexual ch - NA"
label variable v760w    "Behavior: Other nonsexual - NA"
label variable v760x    "Behavior: Other responses - NA"
label variable v760y    "Behavior: No change - NA"
label variable v760z    "Behavior: Don't know - NA"
label variable v761     "Last intercourse used con - NA"
label variable v762     "Source for condoms -NA"
label variable v764     "Knowledge of condom -NA"
label variable v765     "Ever use of condom -NA"
label variable v801     "Time interview started"
label variable v802     "Time interview ended"
label variable v803     "Length of interview in minutes"
label variable v804     "Number of visits"
label variable v805     "Interviewer identification"
label variable v806     "Keyer identification"
label variable v811     "Pres. children < 10 (sec 5)"
label variable v812     "Pres. husband (sec 5)"
label variable v813     "Pres. other males (sec 5)"
label variable v814     "Pres. other females (sec 5)"
label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Sample weight"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Respondent's month of birth"
label variable mv010    "Respondent's year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age - respondent"
label variable mv013    "Age 5-year groups"
label variable mv014    "Completeness of information"
label variable mv015    "Result of individual interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor - NA"
label variable mv031    "Field editor - NA"
label variable mv032    "Office editor - NA"
label variable mv033    "Ultimate area selection prob."
label variable mv034_1  "Line numbers of wives"
label variable mv034_2  "Line numbers of wives"
label variable mv034_3  "Line numbers of wives"
label variable mv034_4  "Line numbers of wives"
label variable mv034_5  "Line numbers of wives"
label variable mv034_6  "Line numbers of wives"
label variable mv034_7  "Line numbers of wives"
label variable mv034_8  "Line numbers of wives"
label variable mv035    "Number of wives, partners"
label variable mv801    "Time interview started"
label variable mv802    "Time interview ended"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "Childhood place of residen- NA"
label variable mv104    "Years lived in place of res."
label variable mv105    "Type of place of previous residence"
label variable mv106    "Highest educational level"
label variable mv107    "Highest year of education"
label variable mv108    "Literacy"
label variable mv109    "Reads newspaper once a week"
label variable mv110    "Watches TV every week"
label variable mv111    "Listens to radio every da - NA"
label variable mv112    "Listens to radio every week"
label variable mv130    "Religion"
label variable mv131    "Ethnicity - NA"
label variable mv133    "Education in single years"
label variable mv134    "De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members"
label variable mv138    "Number of eligible men in HH"
label variable mv148    "Respondent still in school"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv213    "Partner currently pregnan - NA"
label variable mv218    "Number of living children"
label variable mv225    "Current pregnancy wanted - NA"
label variable mv301    "Knowledge of any method"
label variable mv302    "Ever use of any method"
label variable m304a_01 "Type of method"
label variable mv304_01 "Knows method"
label variable mv305_01 "Ever used method"
label variable m304a_02 "Type of method"
label variable mv304_02 "Knows method"
label variable mv305_02 "Ever used method"
label variable m304a_03 "Type of method"
label variable mv304_03 "Knows method"
label variable mv305_03 "Ever used method"
label variable m304a_04 "Type of method"
label variable mv304_04 "Knows method"
label variable mv305_04 "Ever used method"
label variable m304a_05 "Type of method"
label variable mv304_05 "Knows method"
label variable mv305_05 "Ever used method"
label variable m304a_06 "Type of method"
label variable mv304_06 "Knows method"
label variable mv305_06 "Ever used method"
label variable m304a_07 "Type of method"
label variable mv304_07 "Knows method"
label variable mv305_07 "Ever used method"
label variable m304a_08 "Type of method"
label variable mv304_08 "Knows method"
label variable mv305_08 "Ever used method"
label variable m304a_09 "Type of method"
label variable mv304_09 "Knows method"
label variable mv305_09 "Ever used method"
label variable m304a_10 "Type of method"
label variable mv304_10 "Knows method"
label variable mv305_10 "Ever used method"
label variable m304a_11 "Type of method"
label variable mv304_11 "Knows method"
label variable mv305_11 "Ever used method"
label variable m304a_12 "Type of method"
label variable mv304_12 "Knows method"
label variable mv305_12 "Ever used method"
label variable m304a_13 "Type of method"
label variable mv304_13 "Knows method"
label variable mv305_13 "Ever used method"
label variable m304a_14 "Type of method"
label variable mv304_14 "Knows method"
label variable mv305_14 "Ever used method"
label variable m304a_15 "Type of method"
label variable mv304_15 "Knows method"
label variable mv305_15 "Ever used method"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current use by method type"
label variable mv361    "Pattern of use"
label variable mv362    "Intention to use"
label variable mv363    "Preferred future method"
label variable mv364    "Contraceptive use & intention"
label variable mv366a   "Acceptability of radio me - NA"
label variable mv366b   "Acceptability of TV messa - NA"
label variable mv367    "Wanted last child - NA"
label variable mv375a   "Main reason not using a method"
label variable mv376    "Main reason not to use a meth."
label variable mv384a   "Heard FP on radio last month"
label variable mv384b   "Heard FP on TV last month"
label variable mv384c   "Heard FP newspaper last mon-NA"
label variable mv384d   "Heard FP on poster last month"
label variable mv384e   "Heard FP brochures last m - NA"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never marr."
label variable mv503    "Number of unions"
label variable mv505    "Number of wives, partners"
label variable mv507    "Month of first marriage"
label variable mv508    "Year of first marriage"
label variable mv509    "Date of first marriage (CMC)"
label variable mv510    "Completeness of date inform."
label variable mv511    "Age at first marriage"
label variable mv512    "Years since first marriage"
label variable mv513    "Marital duration (grouped)"
label variable mv525    "Age at first intercourse - NA"
label variable mv527    "Time since last intercourse"
label variable mv531    "Age at first intercourse - NA"
label variable mv532    "Flag for MV531"
label variable mv534    "Have a regular sex partne - NA"
label variable mv535    "Have ever been married - NA"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time"
label variable mv604    "Preferred waiting time (grpd)"
label variable mv605    "Desire for more children"
label variable mv610    "Wife approves FP"
label variable mv611    "Discussed FP with partner"
label variable mv612    "Respondent approves FP"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grp)"
label variable mv616    "Time for future birth"
label variable mv621    "Wifes desire for children"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv630a   "Discussed FP with partner - NA"
label variable mv630b   "Discussed FP with mother - NA"
label variable mv630c   "Discussed FP with father - NA"
label variable mv630d   "Discussed FP with sister( - NA"
label variable mv630e   "Discussed FP with brother - NA"
label variable mv630f   "Discussed FP with daughte - NA"
label variable mv630g   "Discussed FP with mother- - NA"
label variable mv630h   "Discussed FP with friends - NA"
label variable mv630i   "Discussed FP -country spe - NA"
label variable mv630j   "Discussed FP -country spe - NA"
label variable mv630k   "Discussed FP -country spe - NA"
label variable mv630l   "Discussed FP -country spe - NA"
label variable mv630x   "Discussed FP with others - NA"
label variable mv714    "Respondent currently working"
label variable mv716    "Respondent's occupation"
label variable mv717    "Respondent's occupation"
label variable mv719    "Work for family, others, - NA"
label variable mv731    "Worked in last 12 months - NA"
label variable mv732    "Employment all year/seaso - NA"
label variable mv733    "Months worked in last 12 - NA"
label variable mv736    "Earnings for work - NA"
label variable mv740    "Type of land where resp. works"
label variable mv751    "Ever heard of AIDS - NA"
label variable mv752a   "AIDS: radio - NA"
label variable mv752b   "AIDS: television - NA"
label variable mv752c   "AIDS: newspapers/magazine - NA"
label variable mv752d   "AIDS: pamphlets/posters - NA"
label variable mv752e   "AIDS: clinic/health worke - NA"
label variable mv752f   "AIDS: churches/mosques - NA"
label variable mv752g   "AIDS: schools/teachers - NA"
label variable mv752h   "AIDS: community meetings - NA"
label variable mv752i   "AIDS: friends/relatives - NA"
label variable mv752j   "AIDS: work place - NA"
label variable mv752k   "AIDS: country specific - NA"
label variable mv752l   "AIDS: country specific - NA"
label variable mv752m   "AIDS: country specific - NA"
label variable mv752n   "AIDS: country specific - NA"
label variable mv752o   "AIDS: country specific - NA"
label variable mv752x   "AIDS: other responses - NA"
label variable mv753    "Ways to avoid AIDS - NA"
label variable mv754a   "AIDS: Safe sex - NA"
label variable mv754b   "AIDS: abstain from sex - NA"
label variable mv754c   "AIDS: use condoms during - NA"
label variable mv754d   "AIDS: only one sex partne - NA"
label variable mv754e   "AIDS: avoid sex prostitut - NA"
label variable mv754f   "AIDS: avoid sex homosexua - NA"
label variable mv754g   "AIDS: avoid blood transfu - NA"
label variable mv754h   "AIDS: avoid injections - NA"
label variable mv754i   "AIDS: avoid kissing - NA"
label variable mv754j   "AIDS: avoid mosquito bite - NA"
label variable mv754k   "AIDS: protection trad. he - NA"
label variable mv754l   "AIDS: country specific - NA"
label variable mv754m   "AIDS: country specific - NA"
label variable mv754n   "AIDS: country specific - NA"
label variable mv754o   "AIDS: country specific - NA"
label variable mv754x   "AIDS: other responses - NA"
label variable mv754z   "AIDS: DK ways to avoid AI - NA"
label variable mv755b   "Safe sex: abstain from se - NA"
label variable mv755c   "Safe sex: use condoms dur - NA"
label variable mv755d   "Safe sex: only one partne - NA"
label variable mv755e   "Safe sex: avoid prostitut - NA"
label variable mv755f   "Safe sex: avoid homosexua - NA"
label variable mv755l   "Safe sex: country specifi - NA"
label variable mv755m   "Safe sex: country specifi - NA"
label variable mv755n   "Safe sex: country specifi - NA"
label variable mv755o   "Safe sex: country specifi - NA"
label variable mv755x   "Safe sex: other responses - NA"
label variable mv755z   "Safe sex: DK meaning - NA"
label variable mv756    "Can a healthy person have - NA"
label variable mv757    "Is AIDS a fatal disease - NA"
label variable mv758    "Chances of getting AIDS - NA"
label variable mv760a   "Behavior: Did not start s - NA"
label variable mv760b   "Behavior: Stopped all sex - NA"
label variable mv760c   "Behavior: Started using c - NA"
label variable mv760d   "Behavior: Only one sex pa - NA"
label variable mv760e   "Behavior: Reduced partner - NA"
label variable mv760f   "Behavior: Ask spouse fait - NA"
label variable mv760g   "Behavior: No homosexual c - NA"
label variable mv760i   "Behavior: Stopped injecti - NA"
label variable mv760l   "Behavior: Country specifi - NA"
label variable mv760m   "Behavior: Country specifi - NA"
label variable mv760n   "Behavior: Country specifi - NA"
label variable mv760o   "Behavior: Country specifi - NA"
label variable mv760p   "Behavior: Avoid sex w. pr - NA"
label variable mv760v   "Behavior: No nonsexual ch - NA"
label variable mv760w   "Behavior: Other nonsexual - NA"
label variable mv760x   "Behavior: Other responses - NA"
label variable mv760y   "Behavior: No change - NA"
label variable mv760z   "Behavior: Don't know - NA"
label variable mv761    "Last intercourse used con - NA"
label variable mv762    "Source for condoms"
label variable mv763    "Partners in last 12 month - NA"
label variable mv764    "Knowledge of condom - NA"
label variable mv765    "Ever use of condom - NA"
label variable sdformat "Date format of questionnaire"
label variable sadjust  "Month of interview adjusted 1m"
label variable sintm    "Month of interview(unadjusted)"
label variable sinty    "Year of interview(unadjusted)"
label variable sdiv     "Division"
label variable sdistr   "District of residence"
label variable s114a    "Grameen Bank"
label variable s114b    "BRAC"
label variable s114c    "BRDP"
label variable s114d    "Mothers club"
label variable s114e    "Other"
label variable s119     "Time to get to water (mins)"
label variable s119a    "Time to wait to get water:mins"
label variable s123     "Toilet facility : children"
label variable s124a    "Almirah"
label variable s124b    "Table/chair/bench"
label variable s124c    "Watch/clock"
label variable s124d    "Cot/bed"
label variable s124i    "Agricultural land"
label variable s229m    "Month pregnancy ended"
label variable s229y    "Year pregnancy ended"
label variable s233a    "Ever had unwanted pregnancy"
label variable s233b    "Pregancy aborted/menst.reg'ltn"
label variable s233c    "Pregnancy ended by MR/D&C"
label variable s233dm   "When pr. ended : Month"
label variable s233dy   "When pregnancy ended :Year"
label variable msdistr  "District of residence"
label variable msformat "Type of date format used"
label variable msadjust "Month of interview adjusted 1m"
label variable msinty   "Year of interview(unadjusted)"
label variable msintm   "Month of interview(unadjusted)"
label variable ms304_01 "Knows source of method"
label variable ms304_02 "Knows source of method"
label variable ms304_03 "Knows source of method"
label variable ms304_04 "Knows source of method"
label variable ms304_05 "Knows source of method"
label variable ms304_06 "Knows source of method"
label variable ms304_07 "Knows source of method"
label variable ms304_08 "Knows source of method"
label variable ms304_09 "Knows source of method"
label variable ms304_10 "Knows source of method"
label variable ms304_11 "Knows source of method"
label variable ms304_12 "Knows source of method"
label variable ms304_13 "Knows source of method"
label variable ms304_14 "Knows source of method"
label variable ms304_15 "Knows source of method"
label variable ms304_16 "Knows source of method"
label variable ms304_17 "Knows source of method"
label variable ms304_18 "Knows source of method"
label variable ms304_19 "Knows source of method"
label variable ms304_20 "Knows source of method"
label variable ms309    "First method used"
label variable ms311    "Living children at first use"
label variable ms316    "Currently using second method"
label variable ms317    "Second method currently used"
label variable ms320s   "Condom package seen"
label variable ms320    "Brand of condoms shown"
label variable ms320a   "Reason can't show condom pack"
label variable ms320c   "Reason can't show condom pack"
label variable ms320e   "Times used condoms last month"
label variable ms320d   "Use condom every time have sex"
label variable ms321m   "Month of sterilization (imp.)"
label variable ms321y   "Year of sterilization (imp.)"
label variable ms321c   "Date of sterilization (CMC)"
label variable ms321f   "Completeness of information"
label variable ms321xa  "Years since sterilization"
label variable ms321xb  "Age at sterilization"
label variable ms321xc  "Marital duration at steriliz."
label variable ms321xd  "Wife's sterilization:date form"
label variable ms321xe  "Wife's sterilization : month"
label variable ms321xf  "Wife's sterilization: year"
label variable ms322b   "Sterilization regret"
label variable ms322c   "Method used most recently"
label variable ms323    "Source of current method"
label variable ms323b   "Paid for use of contr.source"
label variable ms325    "Who obtained pills/condoms"
label variable ms325a   "Got pls,cndm at HF,doctor,shop"
label variable ms325b   "Informed of side effects/probs"
label variable ms325c   "Informed of other methods"
label variable ms325h   "Got method he wanted"
label variable ms325i   "Method wanted at HF."
label variable ms325j   "Who had most inflc. at 1st use"
label variable ms326    "Reason for current method"
label variable ms328hi  "Knows source for method"
label variable ms347a   "Satellite clinic last 3 months"
label variable ms347b   "Visited satellite clinic"
label variable ms347ca  "Sat.Clinic: Family Plng.Meths."
label variable ms347cb  "Sat.Clinic: Immunization"
label variable ms347cc  "Sat.Clinic: Ch.growth monitor."
label variable ms347cd  "Sat.Clinic: Other"
label variable ms347ce  "Sat.Clinic: Does not know"
label variable ms348c   "Read about FP on Billboard"
label variable ms349a   "Inf. on radio acceptable:pill"
label variable ms349b   "Inf. on radio acct'ble:condoms"
label variable ms349c   "Inf. on radio acct'ble:injctns"
label variable ms349d   "Inf. on radio acct'ble:IUD's"
label variable ms349e   "Inf. on radio acct'ble:sterlzn"
label variable ms350    "Visit by FPW in last 6 mnths"
label variable ms352    "No. visits by FPW last 6 mnths"
label variable ms353    "Months since last visit by FPW"
label variable ms354    "Received supplies from FPW"
label variable ms355    "Supplies received from FPW"
label variable ms356    "How many cycles/condoms rec'vd"
label variable ms357a   "Meths.disc.w FPW: Pills"
label variable ms357b   "Meths.disc.w FPW: IUD"
label variable ms357c   "Meths.disc.w FPW: Injection"
label variable ms357d   "Meths.disc.w FPW: Condom"
label variable ms357e   "Meths.disc.w FPW: Female Ster."
label variable ms357f   "Meths.disc.w FPW: Male Ster."
label variable ms357g   "Meths.disc.w FPW: Never disc."
label variable ms358    "Most men known by rsp use FP"
label variable ms359    "Has recommended FP to someone"
label variable ms360    "Visit Health Facility last 6m"
label variable ms361    "Spoke with psn at HF about FP"
label variable ms408a   "Children under 10"
label variable ms408b   "Presence of wife"
label variable ms408c   "Other males"
label variable ms408d   "Other females"
label variable ms508    "Source of preferred method"
label variable ms512    "Discussed children"
label variable ms514    "Wife allowed to go out alone"
label variable s304_01  "Knows source for method"
label variable s304_02  "Knows source for method"
label variable s304_03  "Knows source for method"
label variable s304_04  "Knows source for method"
label variable s304_05  "Knows source for method"
label variable s304_06  "Knows source for method"
label variable s304_07  "Knows source for method"
label variable s304_08  "Knows source for method"
label variable s304_09  "Knows source for method"
label variable s304_10  "Knows source for method"
label variable s304_11  "Knows source for method"
label variable s304_12  "Knows source for method"
label variable s304_13  "Knows source for method"
label variable s304_14  "Knows source for method"
label variable s304_15  "Knows source for method"
label variable s309     "First contraceptive method"
label variable s310     "Source of first method"
label variable s316     "Currently using second method"
label variable s317     "Second method currently used"
label variable s318b    "Pill usage"
label variable s318c    "Why not taken pills in order"
label variable s318ea   "No pill pack: Ran out"
label variable s318eb   "No pill pack: Cost too much"
label variable s318ec   "No pill pack: Husband away"
label variable s318ed   "No pill pack: Has menstrual pd"
label variable s318ee   "No pill pack:none at her s'rce"
label variable s318ef   "No pill pack:FWA didn't supply"
label variable s318eg   "No pill pack: Other reason"
label variable s318f    "Days since last took a pill"
label variable s318ha   "No curr.pill use:husband away"
label variable s318hb   "No curr.pill use:forgot"
label variable s318hc   "No curr.pill use:health reason"
label variable s318hd   "No curr.pill use:cost too much"
label variable s318he   "No curr.pill use:daily use N/R"
label variable s318hf   "No curr.pill use:ran out"
label variable s318hg   "No curr.pill use:FWA not resup"
label variable s318hh   "No curr.pill use:menstruating"
label variable s318hi   "No curr.pill use:other reason"
label variable s318i    "Delays use between pill pk'age"
label variable s318k    "Action after forgetting pill"
label variable s319     "Months since last injection"
label variable s319b    "Reason why no recent injection"
label variable s320s    "Condom package seen"
label variable s320     "Brand of condoms used"
label variable s320a    "Reason can't show condom pack"
label variable s320c    "Use condom every time have sex"
label variable s322c    "Which days of cycle not safe"
label variable s320d    "Times used condoms last month"
label variable s322d    "Method used most recently"
label variable s323b    "Paid for use of contr.source"
label variable s325     "Who obtained pills/condoms"
label variable s325a    "Got pls,cndm at HF,doctor,shop"
label variable s325b    "Informed of side effects/probs"
label variable s325c    "Informed of other methods"
label variable s325e    "Inf. of side effs by FWA(ever)"
label variable s325g    "Inf. of oth.meths by FWA(ever)"
label variable s325h    "Got method she wanted"
label variable s325i    "Method wanted at hlth.facility"
label variable s325j    "Who had most inflc. at 1st use"
label variable s326     "Reason for current method"
label variable s327     "Problems with current method"
label variable s328pa   "Probs,curr.meth: weight gain"
label variable s328pb   "Probs,curr.meth: weight loss"
label variable s328pc   "Probs,curr.meth: excess bleed."
label variable s328pd   "Probs,curr.meth: hypertension"
label variable s328pe   "Probs,curr.meth: headache"
label variable s328pf   "Probs,curr.meth: nausea"
label variable s328pg   "Probs,curr.meth: no menstruatn"
label variable s328ph   "Probs,curr.meth: weak/tired"
label variable s328pi   "Probs,curr.meth: dizziness"
label variable s328pj   "Probs,curr.meth: other"
label variable s328pk   "Probs,curr.meth: does not know"
label variable s328a    "Advice when 1st had problems"
label variable s328b    "Who gave advice when 1st probs"
label variable s328c    "Any other probs. using meth."
label variable s328da   "Other probs: husb.disapproves"
label variable s328db   "Other probs: Oth.rel. disappr."
label variable s328dc   "Other probs: relig.disapproves"
label variable s328dd   "Other probs: access/availab'ty"
label variable s328de   "Other probs: cost too much"
label variable s328df   "Other probs: inconvenient use"
label variable s328dg   "Other probs : ster.,wants ch."
label variable s328dh   "Other probs: Other"
label variable s328di   "Other probs: does not know"
label variable s347a    "Satellite clinic last 3 months"
label variable s347b    "Visited satellite clinic"
label variable s347ca   "Sat.Clinic: Family Plng.Meths."
label variable s347cb   "Sat.Clinic: Immunization"
label variable s347cc   "Sat.Clinic: Ch.growth monitor."
label variable s347cd   "Sat.Clinic: Other"
label variable s347ce   "Sat.Clinic: Does not know"
label variable s348c    "Read about FP on Billboard"
label variable s349a    "Inf. on radio acceptable:pill"
label variable s349b    "Inf. on radio acct'ble:condoms"
label variable s349c    "Inf. on radio acct'ble:injctns"
label variable s349d    "Inf. on radio acct'ble:injctns"
label variable s349e    "Inf. on radio acct'ble:sterlzn"
label variable s352     "No. visits by FPW last 6 mnths"
label variable s353     "Months since last visit by FPW"
label variable s354     "Received supplies from FPW"
label variable s355     "Supplies received from FPW"
label variable s356     "How many cycles/condoms rec'vd"
label variable s357ma   "Meths.disc.w FPW: Pills"
label variable s357mb   "Meths.disc.w FPW: IUD"
label variable s357mc   "Meths.disc.w FPW: Injection"
label variable s357md   "Meths.disc.w FPW: Condom"
label variable s357me   "Meths.disc.w FPW: Female Ster."
label variable s357mf   "Meths.disc.w FPW: Male Ster."
label variable s357mg   "Meths.disc.w FPW: Never disc."
label variable s357a    "Referred to clinic by FPW"
label variable s357b    "Why FPW referred to clinic"
label variable s358     "Most women known by rsp use FP"
label variable s359     "Has recommended FP to someone"
label variable s361     "Spoke with psn at HF about FP"
label variable s439     "Rec.advice on duration of bfdg"
label variable s440     "Dec dur'tn BF:who helped most"
label variable s441     "No.months advised for BF"
label variable s442a    "Anyone give FP adv.after birth"
label variable s442b_1  "Who gave specific advice on FP"
label variable s442c_1  "Asked how planned to feed baby"
label variable s442da_1 "Methods discussed: Pill"
label variable s442db_1 "Methods discussed: IUD"
label variable s442dc_1 "Methods discussed: Injections"
label variable s442dd_1 "Methods discussed: Condom"
label variable s442de_1 "Methods discussed: Female Ster"
label variable s442df_1 "Methods discussed: Male Ster."
label variable s442dg_1 "Methods discussed: Calendar"
label variable s442dh_1 "Methods discussed: Withdrawal."
label variable s442di_1 "Methods discussed: Prol.BrFeed"
label variable s442dj_1 "Methods discussed: Other"
label variable s442dk_1 "Methods discussed: None"
label variable s442r1_1 "1st recommended method"
label variable s442i1_1 "Rec.interval before use mthd 1"
label variable s442r2_1 "2nd recommended method"
label variable s442i2_1 "Rec.interval before use mthd 2"
label variable s442b_2  "Who gave specific advice on FP"
label variable s442c_2  "Asked how planned to feed baby"
label variable s442da_2 "Methods discussed: Pill"
label variable s442db_2 "Methods discussed: IUD"
label variable s442dc_2 "Methods discussed: Injections"
label variable s442dd_2 "Methods discussed: Condom"
label variable s442de_2 "Methods discussed: Female Ster"
label variable s442df_2 "Methods discussed: Male Ster."
label variable s442dg_2 "Methods discussed: Calendar"
label variable s442dh_2 "Methods discussed: Withdrawal."
label variable s442di_2 "Methods discussed: Prol.BrFeed"
label variable s442dj_2 "Methods discussed: Other"
label variable s442dk_2 "Methods discussed: None"
label variable s442r1_2 "1st recommended method"
label variable s442i1_2 "Rec.interval before use mthd 1"
label variable s442r2_2 "2nd recommended method"
label variable s442i2_2 "Rec.interval before use mthd 2"
label variable s442h    "Dec to use FP :who helped most"
label variable s442ia   "Infl.to use FP: Resumed sex"
label variable s442ib   "Infl.to use FP: Resumed period"
label variable s442ic   "Infl.to use FP: Breastfeeding"
label variable s442id   "Infl.to use FP:des.to have ch."
label variable s442ie   "Infl.to use FP: Radio/TV msges"
label variable s442if   "Infl.to use FP: Other"
label variable s442ig   "Infl.to use FP: Nothing else"
label variable s442j    "Helped mst to decide which mth"
label variable s442ka   "Oth.infl.on meth:Effic.method"
label variable s442kb   "Oth.infl.on meth: Prev.experi."
label variable s442kc   "Oth.infl.on meth:Safeness meth"
label variable s442kd   "Oth.infl.on meth:Comfort/disc."
label variable s442ke   "Oth.infl.on meth: Radio/TV msg"
label variable s442kf   "Oth.infl.on meth: Other"
label variable s442l    "FP meths.not good while brstfg"
label variable s442ma   "Bad for Bfdg.Wom.: Pill"
label variable s442mb   "Bad for Bfdg.Wom.: IUD"
label variable s442mc   "Bad for Bfdg.Wom.: Injections"
label variable s442md   "Bad for Bfdg.Wom.: Condom"
label variable s442me   "Bad for Bfdg.Wom.: Female sTer"
label variable s442mf   "Bad for Bfdg.Wom.: Male Ster."
label variable s442mg   "Bad for Bfdg.Wom.: Safe period"
label variable s442mh   "Bad for Bfdg.Wom.: Withdrawal"
label variable s442mi   "Bad for Bfdg.Wom.: Other"
label variable s442n    "EFf. of BF/amen against prgncy"
label variable s442o    "How long protected by b.feedin"
label variable s609     "Source of preferred method"
label variable s613     "Discussed children"
label variable s615     "Resp.allowed to go out alone"
label variable s616     "Freq.visits to oth.pts localit"
label variable s617     "Freq.of shopping/marketing"
label variable s618     "Allowed to visit H.cntr,hosp."

#delimit ;
label define V013    
     0 "10-14"
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
;
label define V014    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V015    
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
     9 "Missing"
;
label define V018    
     0 "No calendar"
;
label define V019    
     0 "No calendar"
;
label define V020    
     0 "All woman sample"
     1 "Ever married sample"
;
label define V023    
     0 "National"
     1 "Country specific"
;
label define V024    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define V025    
     1 "Urban"
     2 "Rural"
;
label define V026    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define V034    
     0 "Husband not in HH"
    99 "Missing"
;
label define V101    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define V102    
     1 "Urban"
     2 "Rural"
;
label define V104    
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V105    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define V106    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     9 "Missing"
;
label define V108    
     1 "Reads easily"
     2 "Reads with difficult"
     3 "Cannot read"
     9 "Missing"
;
label define V109    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V110    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V112    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V113    
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
    99 "Missing"
;
label define V114    
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
    99 "Missing"
;
label define V115    
   996 "On premises"
   999 "Missing"
;
label define V116    
    10 "FLUSH TOILET"
    20 "PIT TOILET LATRINE"
    30 "NO FACILITY"
    96 "OTHER"
    99 "Missing"
;
label define V119    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V120    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V121    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V123    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V127    
    10 "NATURAL"
    11 "Earth"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
    99 "Missing"
;
label define V128    
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Brick/cement"
    32 "Tin"
    96 "OTHER"
    99 "Missing"
;
label define V129    
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Tin"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
    99 "Missing"
;
label define V130    
     1 "Islam"
     2 "Christianity"
     3 "Hinduism"
     4 "Buddhism"
     5 "Other"
     9 "Missing"
;
label define V133    
    97 "Inconsistent"
    99 "Missing"
;
label define V134    
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define V135    
     1 "Usual resident"
     2 "Visitor"
     9 "Missing"
;
label define V139    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
    99 "Missing"
;
label define V140    
     0 "Abroad"
     1 "Urban"
     2 "Rural"
     9 "Missing"
;
label define V141    
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define V142    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V148    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V149    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     9 "Missing"
;
label define V150    
     1 "Head"
     2 "Wife"
     3 "Daughter"
     4 "Daughter-in-law"
     5 "Grand-daughter"
     6 "Mother"
     7 "Mother-in-law"
     8 "Sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
    99 "Missing"
;
label define V151    
     1 "Male"
     2 "Female"
;
label define V152    
    96 "96+"
    99 "Missing"
;
label define B0      
     0 "Single birth"
     1 "1st of multiple"
     2 "2nd of multiple"
     3 "3rd of multiple"
     4 "4th of multiple"
     5 "5th of multiple"
;
label define B4      
     1 "Male"
     2 "Female"
;
label define B5      
     0 "No"
     1 "Yes"
;
label define B6      
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define B9      
     0 "Respondent"
     1 "Father"
     2 "Other relative"
     3 "Someone else"
     4 "Lives elsewhere"
     9 "Missing"
;
label define B10     
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define B13     
     0 "No flag"
     1 "> interview"
     2 "< breastfeeding"
     3 "< age supplemented"
     4 "< first breastfed"
     5 "< last vaccination"
     6 "Outside range"
     7 "Imputed, units given"
     8 "Imputed, no units"
;
label define V213    
     0 "No or unsure"
     1 "Yes"
;
label define V215    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V216    
     0 "No"
     1 "Yes"
;
label define V220    
     6 "6+"
;
label define V221    
   996 "Negative interval"
;
label define V223    
     7 "Month - exact date"
     8 "None - date placed"
;
label define V225    
     1 "Then"
     2 "Later"
     3 "Not at all"
     9 "Missing"
;
label define V226    
   994 "In menopause"
   995 "Before last birth"
   996 "Never menstruated"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V227    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + amen. > interval"
     3 "N, but per. not ret."
     4 "95, but no birth"
     5 "96, but per.returned"
     6 "95, but per.returned"
     7 "N, last per. in preg"
     8 "96, had children"
     9 "N, per.bef.last birt"
;
label define V228    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V229    
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define V230    
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define V231    
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define V232    
     1 "Month and year"
     2 "From calendar"
     5 "Year"
     7 "Month"
     8 "None"
;
label define V233    
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V234    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V235    
     0 "No prior child"
;
label define V301    
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
;
label define V302    
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
;
label define V304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define V304    
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
     9 "Missing"
;
label define V305    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V311    
     4 "4+"
     5 "Never used"
     9 "Missing"
;
label define V312    
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define V313    
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     9 "Missing"
;
label define V318    
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
;
label define V319    
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
;
label define V320    
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45-49"
;
label define V321    
     0 "Single,before marr."
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
;
label define V322    
     5 "5+"
;
label define V323    
     1 "Maya"
     2 "Ovacon"
     3 "Norquest"
     4 "Noriday"
     5 "Ovral"
     6 "Combination-5"
     7 "Ovostat"
     8 "Restovar-NA"
     9 "Lyndiol"
    10 "Nordette"
    11 "Marvelou"
    96 "Other pill brand"
    99 "Missing"
;
label define V326    
    10 "PUBLIC"
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    20 "PRIVATE MEDICAL"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    30 "OTHER PRIVATE"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "OTHER"
    98 "DK"
    99 "Missing"
;
label define V327    
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
     9 "Missing"
;
label define V337    
    95 "All cal. {A core}"
    96 "96+ {B core}"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V359    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define V360    
     1 "Became pregnant"
     2 "Wanted to become prg"
     3 "Husband disapproved"
     4 "Side effects"
     5 "Health concerns"
     6 "Access, availability"
     7 "Wanted more eff.meth"
     8 "Inconvenient to use"
     9 "Infreq.sex,husb away"
    10 "Cost"
    11 "Fatalistic"
    12 "Diff.preg.,menopause"
    13 "Marital dissolution"
    14 "Other"
    98 "Don't know"
    99 "Missing"
;
label define V361    
     1 "Currently using"
     2 "Used since last brth"
     3 "Used before last brt"
     4 "Never used"
;
label define V362    
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
     9 "Missing"
;
label define V363    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    98 "Don't know"
    99 "Missing"
;
label define V364    
     1 "Using modern method"
     2 "Using tradit. method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
;
label define V366A   
     0 "Not acceptable"
     1 "Acceptable"
     8 "Don't know"
     9 "Missing"
;
label define V367    
     1 "Wanted then"
     2 "Wanted later"
     3 "Wanted no more"
     9 "Missing"
;
label define V369    
     0 "Never used"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define V372    
     0 "Package not seen"
     1 "Package seen"
     9 "Missing"
;
label define V375A   
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V376    
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Husband opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V379    
    10 "PUBLIC"
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    20 "PRIVATE MEDICAL"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    30 "OTHER PRIVATE"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "OTHER"
    98 "DK"
    99 "Missing"
;
label define V380    
     1 "Govt Clinical/Pharm"
     2 "Govt Home/Comm deliv"
     3 "NGO"
     4 "Private Clin/Deliv"
     5 "Private Pharmacy"
     6 "Shop, church, friend"
     7 "Other"
     8 "Don't know"
     9 "Missing"
;
label define V384A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V384B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V384D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V393    
     0 "No"
     1 "Yes - 6 months"
     8 "Don't know"
     9 "Missing"
;
label define V394    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V395    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V396    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define V401    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V404    
     0 "No"
     1 "Yes"
;
label define V405    
     0 "No"
     1 "Yes"
;
label define V406    
     0 "No"
     1 "Yes"
;
label define V407    
    96 "On demand"
    99 "Missing"
;
label define V408    
    96 "On demand"
    99 "Missing"
;
label define V409    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V409A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V410    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V410A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V411A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V412    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V413    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414E   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414F   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414G   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V414H   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V416    
     0 "Never heard of"
     1 "Used ORS"
     2 "Heard of ORS"
     9 "Missing"
;
label define V426    
     0 "Immediately"
   999 "Missing"
;
label define V501    
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
     9 "Missing"
;
label define V502    
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
     9 "Missing"
;
label define V503    
     1 "Once"
     2 "More than once"
     9 "Missing"
;
label define V504    
     1 "Living with her"
     2 "Staying elsewhere"
     9 "Missing"
;
label define V510    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define V513    
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define V527    
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V528    
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V529    
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V530    
     0 "No flag"
     1 "N > int. since birth"
     2 "N + abst. > interval"
     3 "N, but sex not res."
     4 "96, but no birth"
     5 "96, but curr.preg."
     6 "96, but resumed sex"
     7 "N, last sex bef preg"
     8 "N, inconsis 4 weeks"
     9 "N, sex bef last birt"
;
label define V535    
     0 "No"
     1 "Formerly married"
     2 "Lived with a man"
     9 "Missing"
;
label define V602    
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Declared infecund"
     6 "Never had sex"
     9 "Missing"
;
label define V603    
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define V604    
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
     9 "Missing"
;
label define V605    
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
     9 "Missing"
;
label define V606    
     1 "Happy"
     2 "Unhappy"
     3 "Would not matter"
     8 "DK"
     9 "Missing"
;
label define V610    
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define V611    
     0 "Never"
     1 "Once or twice"
     2 "More often"
     9 "Missing"
;
label define V612    
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define V613    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V614    
     6 "6+"
     7 "Non-numeric response"
;
label define V616    
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
   999 "Missing"
;
label define V618    
     0 "No regret"
     1 "Resp. wants another"
     2 "Part. wants another"
     3 "Side effects"
     4 "Child died"
     6 "Other reason"
     9 "Missing"
;
label define V621    
     1 "Both want same"
     2 "Husband wants more"
     3 "Husband wants fewer"
     8 "DK"
     9 "Missing"
;
label define V623    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
     9 "Missing"
;
label define V624    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
    99 "Missing"
;
label define V625    
     0 "Fecund"
     1 "Pregnant"
     2 "Amenorrheic"
     3 "Infecund, menopausal"
     9 "Missing"
;
label define V626    
     0 "Never had sex"
     1 "Unmet need to space"
     2 "Unmet need to limit"
     3 "Using to space"
     4 "Using to limit"
     5 "Spacing failure"
     6 "Limiting failure"
     7 "Desire birth < 2 yrs"
     8 "No sex, want to wait"
     9 "Infecund, menopausal"
    99 "Missing"
;
label define V627    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V628    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V629    
    95 "Up to God"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define V701    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "Don't know"
     9 "Missing"
;
label define V702    
    98 "Don't know"
    99 "Missing"
;
label define V704    
    11 "Land owner"
    12 "Farmer"
    13 "Agricultural worker"
    14 "Fisherman"
    21 "Unskilled labourers"
    22 "Domestic servant"
    23 "Non-agricultural wkr"
    31 "Semi-skilled labour"
    41 "Professional worker"
    51 "Business"
    52 "Small business/tradr"
    61 "Unemployed"
    62 "Retired"
    96 "Others"
    98 "Don't know"
   999 "Missing"
;
label define V705    
     0 "Did not work"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
    99 "Missing"
;
label define V707    
     0 "His land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
     9 "Missing"
;
label define V714    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V715    
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define V716    
     0 "Not working"
    11 "Land owner"
    12 "Farmer"
    13 "Agricultural worker"
    14 "Fisherman"
    21 "Unskilled labourers"
    22 "Domestic servant"
    23 "Non-agricultural wkr"
    31 "Semi-skilled labour"
    41 "Professional worker"
    51 "Business"
    52 "Small business/tradr"
    61 "Unemployed"
    62 "Retired"
    96 "Others"
    98 "Don't know"
   999 "Missing"
;
label define V717    
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
    99 "Missing"
;
label define V718    
     0 "Did not work"
     1 "Paid employee, away"
     2 "Paid employee, home"
     3 "Self-employed, away"
     4 "Self-employed, home"
     5 "Unpaid worker, away"
     6 "Unpaid worker, home"
     9 "Missing"
;
label define V719    
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
     9 "Missing"
;
label define V720    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V721    
     1 "At home"
     2 "Away"
     9 "Missing"
;
label define V723    
     0 "Respondent"
     1 "Husband/partner"
     2 "Other child"
     3 "Other relatives"
     4 "Neighbors"
     5 "Friends"
     6 "Servants/hired help"
     7 "Child is in school"
     8 "Institutional care"
    10 "Other female child"
    11 "Other male child"
    95 "Not worked since bth"
    96 "Other"
    99 "Missing"
;
label define V729    
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "Don't know"
     9 "Missing"
;
label define V732    
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
     9 "Missing"
;
label define V739    
     1 "Respondent"
     2 "Partner"
     3 "Jointly with partner"
     4 "Someone else"
     5 "Jointly with someone"
     9 "Missing"
;
label define V740    
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
     9 "Missing"
;
label define V803    
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
    99 "Missing"
;
label define V811    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V812    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V813    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define V814    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60+"
;
label define MV014   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
     9 "Missing"
;
label define MV023   
     0 "National"
     1 "Country specific"
;
label define MV024   
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define MV035   
     0 "No wives/partners"
     9 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
    99 "Missing"
;
label define MV101   
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     9 "Missing"
;
label define MV108   
     1 "Reads easily"
     2 "Reads with difficult"
     3 "Cannot read"
     9 "Missing"
;
label define MV109   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV110   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV112   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV130   
     1 "Islam"
     2 "Christianity"
     3 "Hinduism"
     4 "Buddhism"
     5 "Other"
     9 "Missing"
;
label define MV133   
    97 "Inconsistent"
    99 "Missing"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
     9 "Missing"
;
label define MV148   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     9 "Missing"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grand-son"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
    99 "Missing"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
     9 "Missing"
;
label define MV305   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     9 "Missing"
;
label define MV361   
     1 "Currently using"
     3 "Ever used"
     4 "Never used"
;
label define MV362   
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
     9 "Missing"
;
label define MV363   
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    98 "Don't know"
    99 "Missing"
;
label define MV364   
     1 "Using modern method"
     2 "Using tradit. method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
;
label define MV375A  
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    95 "No reason"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV376   
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV384A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV384B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV384D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV501   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
     9 "Missing"
;
label define MV502   
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
     9 "Missing"
;
label define MV503   
     1 "Once"
     2 "More than once"
     9 "Missing"
;
label define MV510   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV527   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infec"
     6 "Never had sex"
     7 "Man declared infec."
     9 "Missing"
;
label define MV603   
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
     9 "Missing"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
     9 "Missing"
;
label define MV610   
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define MV611   
     0 "Never"
     1 "Once or twice"
     2 "More often"
     9 "Missing"
;
label define MV612   
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define MV613   
    95 "Up to God"
    96 "Non-numeric response"
    98 "DK"
    99 "Missing"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
   999 "Missing"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "DK"
     9 "Missing"
;
label define MV627   
    95 "Up to God"
    96 "Other"
    99 "Missing"
;
label define MV628   
    95 "Up to God"
    96 "Other"
    99 "Missing"
;
label define MV629   
    95 "Up to God"
    96 "Other"
    99 "Missing"
;
label define MV714   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV716   
     0 "Not working"
   999 "Missing"
;
label define MV717   
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
    99 "Missing"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
     9 "Missing"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
     9 "Missing"
;
label define MV762   
    11 "Government hospital"
    12 "Government health c."
    13 "Family planning clin"
    14 "Mobile clinic"
    15 "Public field worker"
    16 "Other public"
    21 "Private hosp, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Private mobile clin"
    25 "Private field worker"
    26 "Other private"
    31 "Shop"
    32 "Church"
    33 "Friends, relatives"
    96 "Other"
    98 "DK source for condom"
    99 "Missing"
;
label define SDFORMAT
     1 "Bengali"
     2 "English"
;
label define SADJUST 
     0 "Not adjusted"
     1 "Adjusted"
;
label define SDIV    
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define S114A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S114E   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S119    
   996 "On premises"
   999 "Missing"
;
label define S123    
     0 "No children"
    11 "Sep.tank/modern tlet"
    21 "Water sld/Slab latr."
    22 "Pit latrine"
    23 "Open latrine"
    24 "Hanging latrine"
    31 "No facility,bush"
    96 "Other"
    99 "Missing"
;
label define S124A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S124I   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S229M   
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define S229Y   
  9997 "Inconsistent"
  9998 "DK"
  9999 "Missing"
;
label define S233A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S233B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S233C   
     1 "Menstrual regulation"
     2 "Induced abortion/D&C"
     3 "Other"
     9 "Missing"
;
label define S233DY  
  1300 "Bengali (Start)"
  1401 "Bengali (end)"
  1900 "English (Start)"
  1994 "English(end)"
  9997 "Inconsistent"
  9998 "Don't Know"
  9999 "Missing"
;
label define MSFORMAT
     1 "Bengali"
     2 "English"
;
label define MSADJUST
     0 "Not adjusted"
     1 "Adjusted"
;
label define MS304   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS309   
     0 "Never used"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define MS316   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS317   
     0 "Not using 2nd method"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    99 "Missing"
;
label define MS320S  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS320   
     1 "Raja"
     2 "Panther"
     3 "Majestic"
     4 "Sensation"
     5 "Latex"
     6 "Tahiti"
     7 "Circle rubber"
     8 "Sultan"
     9 "Gent"
    10 "Durex"
    96 "Other condom brand"
    98 "Don't know brand"
    99 "Missing"
;
label define MS320A  
     1 "Wife keeps"
     2 "Ran out"
     3 "Other"
     9 "Missing"
;
label define MS320C  
  9995 "Partner obtained"
  9996 "Free"
  9998 "Don't know"
  9999 "Missing"
;
label define MS320D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS321F  
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
;
label define MS321XA 
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
;
label define MS321XB 
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45+"
;
label define MS321XC 
     0 "Single,before marr."
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
;
label define MS321XD 
     1 "Bengali"
     2 "English"
;
label define MS321XE 
    98 "DK month"
    99 "Missing"
;
label define MS321XF 
  9997 "Inconsistent"
  9998 "DK year"
  9999 "Missing"
;
label define MS322B  
     0 "Does not regret"
     1 "Wants another child"
     2 "Partner wants child"
     3 "Side effects"
     4 "Other reason"
     9 "Missing"
;
label define MS322C  
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define MS323   
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MS323B  
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define MS325   
     1 "Respondent"
     2 "Wife"
     3 "Son/daughter"
     4 "Other relative"
     5 "Other"
     9 "Missing"
;
label define MS325A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS325B  
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define MS325C  
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define MS325H  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS325I  
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    99 "Missing"
;
label define MS325J  
     1 "Respondent had most"
     2 "Wife had most"
     3 "Husb. and wife equal"
     4 "Other relative"
     5 "Other"
     9 "Missing"
;
label define MS326   
     1 "Recomm. FP worker"
     2 "Recomm. friend, rel."
     3 "Side effects others"
     4 "Method easy to use"
     5 "Access, availability"
     6 "Cost"
     7 "Wanted permanent m."
     8 "Wife preferred"
     9 "Wanted more effect."
    10 "Other"
    98 "DK"
    99 "Missing"
;
label define MS328HI 
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MS347A  
     1 "Yes"
     0 "No"
     8 "DK"
     9 "Missing"
;
label define MS347B  
     1 "Yes"
     0 "No"
     9 "Missing"
;
label define MS347CA 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CB 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CC 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CD 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CE 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS348C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349D  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MS349E  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MS350   
     0 "No visit"
     1 "Yes, for Fmly Plng."
     2 "Yes, for other rsn."
     8 "DK"
     9 "Missing"
;
label define MS352   
    98 "DK"
    99 "Missing"
;
label define MS353   
     0 "Less than 1 mth ago"
     8 "DK"
     9 "Missing"
;
label define MS354   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS355   
     1 "Pills"
     2 "Condoms"
     3 "Injection"
     4 "Other"
     9 "Missing"
;
label define MS357A  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357B  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357C  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357D  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357E  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357F  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357G  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS358   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MS359   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS360   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS361   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS508   
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Traditional doctor"
    22 "Qualified doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MS512   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS514   
     0 "Not allowed to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
     9 "Missing"
;
label define S304    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S309    
     0 "Never used a method"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define S310    
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define S316    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S317    
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define S318B   
     1 "Missing in order"
     2 "Missing out of order"
     3 "No pills missing"
     9 "Missing"
;
label define S318C   
     1 "DK what to do"
     2 "Health reasons"
     3 "Following instr'tns"
     4 "New packet"
     5 "Menstruating"
     6 "Other"
    99 "Missing"
;
label define S318EA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318EB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318EC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318ED  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318EE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318EF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318EG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318F   
    97 "More than 1 mnth.ago"
    99 "Missing"
;
label define S318HA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HH  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318HI  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318I   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S318K   
     1 "Start taking again"
     2 "Use extra/missed pll"
     3 "Use another method"
     4 "Extra pill+anoth.mth"
     5 "Other"
     6 "Never forgot"
     9 "Missing"
;
label define S319B   
     1 "Husband away"
     2 "Forgot"
     3 "Health reasons"
     4 "Cost too much"
     5 "Not available at pr."
     6 "Other"
     9 "Missing"
;
label define S320S   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S320    
     1 "Raja"
     2 "Panther"
     3 "Majestic"
     4 "Sensation"
     5 "Latex"
     6 "Tahiti"
     7 "Circle rubber"
     8 "Sultan"
     9 "Gent"
    10 "Durex"
    96 "Other condom brand"
    98 "Don't know brand"
    99 "Missing"
;
label define S320A   
     1 "Husband keeps"
     2 "Ran out"
     3 "Other"
     9 "Missing"
;
label define S320C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S322C   
     1 "During period"
     2 "Imm.after per'd ends"
     3 "Middle of cycle"
     4 "Imm.bef. per'd ends"
    96 "Other"
    98 "Don't know"
    99 "Missing"
;
label define S322D   
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define S323B   
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define S325    
     1 "Respondent"
     2 "Husband"
     3 "Son/daughter"
     4 "Other relative"
     5 "Other"
     9 "Missing"
;
label define S325A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S325B   
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define S325C   
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define S325E   
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define S325G   
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define S325H   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S325I   
     1 "Pill, Maya"
     2 "IUD, Copper T"
     3 "Injections"
     4 "Condom, Raja"
     5 "Female Sterilization"
     6 "Male Sterilization"
     7 "Safe period,calendar"
     8 "Withdrawal"
     9 "Other"
    99 "Missing"
;
label define S325J   
     1 "Respondent had most"
     2 "Husband had most"
     3 "Husb. and wife equal"
     4 "Other relative"
     5 "Other"
     9 "Missing"
;
label define S326    
     1 "Recomm. FP worker"
     2 "Recomm. friend, rel."
     3 "Side effects others"
     4 "Method easy to use"
     5 "Access, availability"
     6 "Cost"
     7 "Wanted permanent m."
     8 "Husband preferred"
     9 "Wanted more effect."
    10 "Other"
    98 "DK"
    99 "Missing"
;
label define S327    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PH  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PI  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PJ  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328PK  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328B   
     1 "Fieldworker, FWA"
     2 "Staff satellite cl."
     3 "Staff Family Welf.Cl"
     4 "Relative, friend"
     5 "Other"
     9 "Missing"
;
label define S328C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DH  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S328DI  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S347A   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define S347B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S347CA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S347CB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S347CC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S347CD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S347CE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S348C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S349A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S349B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S349C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S349D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S349E   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S352    
    98 "DK"
    99 "Missing"
;
label define S353    
     0 "Less than 1 mth ago"
     8 "DK"
     9 "Missing"
;
label define S354    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S355    
     1 "Pills"
     2 "Condoms"
     3 "Injection"
     4 "Other"
     9 "Missing"
;
label define S357MA  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define S357MB  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define S357MC  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define S357MD  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define S357ME  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define S357MF  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define S357MG  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define S357A   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define S357B   
     1 "For sterilisation"
     2 "IUD insertion"
     3 "For an Injection"
     4 "Get other FP methods"
     5 "Treatment side effs."
     6 "Other health reasons"
     7 "Other"
     9 "Missing"
;
label define S358    
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define S359    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S361    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S439    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S440    
     1 "Doctor"
     2 "Nurse/midwife"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    12 "Other"
    99 "Missing"
;
label define S441    
    96 "Did not discuss"
    98 "DK/Can't remember"
    99 "Missing"
;
label define S442A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442B   
     0 "No one else"
     1 "Doctor"
     2 "Nurse/midwife/FWV"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    96 "Other"
    99 "Missing"
;
label define S442C   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define S442DA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DH  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DI  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DJ  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442DK  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442R1  
     0 "No method rec'd."
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Prolonged Bfdng."
    99 "Missing"
;
label define S442I1  
    95 "After menst.begins"
    96 "Not discussed"
    98 "Forgot/DK"
    99 "Missing"
;
label define S442R2  
     0 "No method rec'd."
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Prolonged Bfdng."
    99 "Missing"
;
label define S442I2  
    95 "After menst.begins"
    96 "Not discussed"
    98 "Forgot/DK"
    99 "Missing"
;
label define S442H   
     1 "Doctor"
     2 "Nurse/midwife"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    12 "Other"
    99 "Missing"
;
label define S442IA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442IB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442IC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442ID  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442IE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442IF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442IG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442J   
     1 "Doctor"
     2 "Nurse/midwife"
     3 "Pharmacist"
     4 "Trad.birth attendant"
     5 "Fieldworker,FWA"
     6 "Husband"
     7 "Mother"
     8 "Sister"
     9 "Mother-in-law"
    10 "Sister-in-law"
    11 "Other relative"
    12 "Other"
    99 "Missing"
;
label define S442KA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442KB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442KC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442KD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442KE  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442KF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442L   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define S442MA  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442MB  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442MC  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442MD  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442ME  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442MF  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442MG  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442MH  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442MI  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S442N   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define S442O   
    96 "Until next period"
    98 "DK"
    99 "Missing"
;
label define S609    
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Traditional doctor"
    22 "Qualified doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define S613    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define S615    
     0 "Not allowd to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
     9 "Missing"
;
label define S616    
     1 "1x month or more"
     2 "Several times a year"
     3 "Less than 1x a year"
     4 "Never"
     9 "Missing"
;
label define S617    
     1 "1x month or more"
     2 "Several times a year"
     3 "Less than 1x a year"
     4 "Never"
     9 "Missing"
;
label define S618    
     0 "Not allowd to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
     9 "Missing"
;

#delimit cr
label values v013     V013    
label values v014     V014    
label values v015     V015    
label values v018     V018    
label values v019     V019    
label values v020     V020    
label values v023     V023    
label values v024     V024    
label values v025     V025    
label values v026     V026    
label values v034     V034    
label values v101     V101    
label values v102     V102    
label values v104     V104    
label values v105     V105    
label values v106     V106    
label values v108     V108    
label values v109     V109    
label values v110     V110    
label values v112     V112    
label values v113     V113    
label values v114     V114    
label values v115     V115    
label values v116     V116    
label values v119     V119    
label values v120     V120    
label values v121     V121    
label values v123     V123    
label values v127     V127    
label values v128     V128    
label values v129     V129    
label values v130     V130    
label values v133     V133    
label values v134     V134    
label values v135     V135    
label values v139     V139    
label values v140     V140    
label values v141     V141    
label values v142     V142    
label values v148     V148    
label values v149     V149    
label values v150     V150    
label values v151     V151    
label values v152     V152    
label values b0_01    B0      
label values b4_01    B4      
label values b5_01    B5      
label values b6_01    B6      
label values b9_01    B9      
label values b10_01   B10     
label values b13_01   B13     
label values b0_02    B0      
label values b4_02    B4      
label values b5_02    B5      
label values b6_02    B6      
label values b9_02    B9      
label values b10_02   B10     
label values b13_02   B13     
label values b0_03    B0      
label values b4_03    B4      
label values b5_03    B5      
label values b6_03    B6      
label values b9_03    B9      
label values b10_03   B10     
label values b13_03   B13     
label values b0_04    B0      
label values b4_04    B4      
label values b5_04    B5      
label values b6_04    B6      
label values b9_04    B9      
label values b10_04   B10     
label values b13_04   B13     
label values b0_05    B0      
label values b4_05    B4      
label values b5_05    B5      
label values b6_05    B6      
label values b9_05    B9      
label values b10_05   B10     
label values b13_05   B13     
label values b0_06    B0      
label values b4_06    B4      
label values b5_06    B5      
label values b6_06    B6      
label values b9_06    B9      
label values b10_06   B10     
label values b13_06   B13     
label values b0_07    B0      
label values b4_07    B4      
label values b5_07    B5      
label values b6_07    B6      
label values b9_07    B9      
label values b10_07   B10     
label values b13_07   B13     
label values b0_08    B0      
label values b4_08    B4      
label values b5_08    B5      
label values b6_08    B6      
label values b9_08    B9      
label values b10_08   B10     
label values b13_08   B13     
label values b0_09    B0      
label values b4_09    B4      
label values b5_09    B5      
label values b6_09    B6      
label values b9_09    B9      
label values b10_09   B10     
label values b13_09   B13     
label values b0_10    B0      
label values b4_10    B4      
label values b5_10    B5      
label values b6_10    B6      
label values b9_10    B9      
label values b10_10   B10     
label values b13_10   B13     
label values b0_11    B0      
label values b4_11    B4      
label values b5_11    B5      
label values b6_11    B6      
label values b9_11    B9      
label values b10_11   B10     
label values b13_11   B13     
label values b0_12    B0      
label values b4_12    B4      
label values b5_12    B5      
label values b6_12    B6      
label values b9_12    B9      
label values b10_12   B10     
label values b13_12   B13     
label values b0_13    B0      
label values b4_13    B4      
label values b5_13    B5      
label values b6_13    B6      
label values b9_13    B9      
label values b10_13   B10     
label values b13_13   B13     
label values b0_14    B0      
label values b4_14    B4      
label values b5_14    B5      
label values b6_14    B6      
label values b9_14    B9      
label values b10_14   B10     
label values b13_14   B13     
label values b0_15    B0      
label values b4_15    B4      
label values b5_15    B5      
label values b6_15    B6      
label values b9_15    B9      
label values b10_15   B10     
label values b13_15   B13     
label values b0_16    B0      
label values b4_16    B4      
label values b5_16    B5      
label values b6_16    B6      
label values b9_16    B9      
label values b10_16   B10     
label values b13_16   B13     
label values b0_17    B0      
label values b4_17    B4      
label values b5_17    B5      
label values b6_17    B6      
label values b9_17    B9      
label values b10_17   B10     
label values b13_17   B13     
label values b0_18    B0      
label values b4_18    B4      
label values b5_18    B5      
label values b6_18    B6      
label values b9_18    B9      
label values b10_18   B10     
label values b13_18   B13     
label values b0_19    B0      
label values b4_19    B4      
label values b5_19    B5      
label values b6_19    B6      
label values b9_19    B9      
label values b10_19   B10     
label values b13_19   B13     
label values b0_20    B0      
label values b4_20    B4      
label values b5_20    B5      
label values b6_20    B6      
label values b9_20    B9      
label values b10_20   B10     
label values b13_20   B13     
label values v213     V213    
label values v215     V215    
label values v216     V216    
label values v220     V220    
label values v221     V221    
label values v223     V223    
label values v225     V225    
label values v226     V226    
label values v227     V227    
label values v228     V228    
label values v229     V229    
label values v230     V230    
label values v231     V231    
label values v232     V232    
label values v233     V233    
label values v234     V234    
label values v235     V235    
label values v301     V301    
label values v302     V302    
label values v304a_01 V304A   
label values v304_01  V304    
label values v305_01  V305    
label values v304a_02 V304A   
label values v304_02  V304    
label values v305_02  V305    
label values v304a_03 V304A   
label values v304_03  V304    
label values v305_03  V305    
label values v304a_04 V304A   
label values v304_04  V304    
label values v305_04  V305    
label values v304a_05 V304A   
label values v304_05  V304    
label values v305_05  V305    
label values v304a_06 V304A   
label values v304_06  V304    
label values v305_06  V305    
label values v304a_07 V304A   
label values v304_07  V304    
label values v305_07  V305    
label values v304a_08 V304A   
label values v304_08  V304    
label values v305_08  V305    
label values v304a_09 V304A   
label values v304_09  V304    
label values v305_09  V305    
label values v304a_10 V304A   
label values v304_10  V304    
label values v305_10  V305    
label values v304a_11 V304A   
label values v304_11  V304    
label values v305_11  V305    
label values v304a_12 V304A   
label values v304_12  V304    
label values v305_12  V305    
label values v304a_13 V304A   
label values v304_13  V304    
label values v305_13  V305    
label values v304a_14 V304A   
label values v304_14  V304    
label values v305_14  V305    
label values v304a_15 V304A   
label values v304_15  V304    
label values v305_15  V305    
label values v311     V311    
label values v312     V312    
label values v313     V313    
label values v318     V318    
label values v319     V319    
label values v320     V320    
label values v321     V321    
label values v322     V322    
label values v323     V323    
label values v326     V326    
label values v327     V327    
label values v337     V337    
label values v359     V359    
label values v360     V360    
label values v361     V361    
label values v362     V362    
label values v363     V363    
label values v364     V364    
label values v366a    V366A   
label values v367     V367    
label values v369     V369    
label values v372     V372    
label values v375a    V375A   
label values v376     V376    
label values v379     V379    
label values v380     V380    
label values v384a    V384A   
label values v384b    V384B   
label values v384d    V384D   
label values v393     V393    
label values v394     V394    
label values v395     V395    
label values v396     V396    
label values v401     V401    
label values v404     V404    
label values v405     V405    
label values v406     V406    
label values v407     V407    
label values v408     V408    
label values v409     V409    
label values v409a    V409A   
label values v410     V410    
label values v410a    V410A   
label values v411a    V411A   
label values v412     V412    
label values v413     V413    
label values v414d    V414D   
label values v414e    V414E   
label values v414f    V414F   
label values v414g    V414G   
label values v414h    V414H   
label values v416     V416    
label values v426     V426    
label values v501     V501    
label values v502     V502    
label values v503     V503    
label values v504     V504    
label values v510     V510    
label values v513     V513    
label values v527     V527    
label values v528     V528    
label values v529     V529    
label values v530     V530    
label values v535     V535    
label values v602     V602    
label values v603     V603    
label values v604     V604    
label values v605     V605    
label values v606     V606    
label values v610     V610    
label values v611     V611    
label values v612     V612    
label values v613     V613    
label values v614     V614    
label values v616     V616    
label values v618     V618    
label values v621     V621    
label values v623     V623    
label values v624     V624    
label values v625     V625    
label values v626     V626    
label values v627     V627    
label values v628     V628    
label values v629     V629    
label values v701     V701    
label values v702     V702    
label values v704     V704    
label values v705     V705    
label values v707     V707    
label values v714     V714    
label values v715     V715    
label values v716     V716    
label values v717     V717    
label values v718     V718    
label values v719     V719    
label values v720     V720    
label values v721     V721    
label values v723     V723    
label values v729     V729    
label values v732     V732    
label values v739     V739    
label values v740     V740    
label values v803     V803    
label values v811     V811    
label values v812     V812    
label values v813     V813    
label values v814     V814    
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv108    MV108   
label values mv109    MV109   
label values mv110    MV110   
label values mv112    MV112   
label values mv130    MV130   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv148    MV148   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values mv304_01 MV304   
label values mv305_01 MV305   
label values m304a_02 M304A   
label values mv304_02 MV304   
label values mv305_02 MV305   
label values m304a_03 M304A   
label values mv304_03 MV304   
label values mv305_03 MV305   
label values m304a_04 M304A   
label values mv304_04 MV304   
label values mv305_04 MV305   
label values m304a_05 M304A   
label values mv304_05 MV304   
label values mv305_05 MV305   
label values m304a_06 M304A   
label values mv304_06 MV304   
label values mv305_06 MV305   
label values m304a_07 M304A   
label values mv304_07 MV304   
label values mv305_07 MV305   
label values m304a_08 M304A   
label values mv304_08 MV304   
label values mv305_08 MV305   
label values m304a_09 M304A   
label values mv304_09 MV304   
label values mv305_09 MV305   
label values m304a_10 M304A   
label values mv304_10 MV304   
label values mv305_10 MV305   
label values m304a_11 M304A   
label values mv304_11 MV304   
label values mv305_11 MV305   
label values m304a_12 M304A   
label values mv304_12 MV304   
label values mv305_12 MV305   
label values m304a_13 M304A   
label values mv304_13 MV304   
label values mv305_13 MV305   
label values m304a_14 M304A   
label values mv304_14 MV304   
label values mv305_14 MV305   
label values m304a_15 M304A   
label values mv304_15 MV304   
label values mv305_15 MV305   
label values mv312    MV312   
label values mv313    MV313   
label values mv361    MV361   
label values mv362    MV362   
label values mv363    MV363   
label values mv364    MV364   
label values mv375a   MV375A  
label values mv376    MV376   
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384d   MV384D  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv510    MV510   
label values mv513    MV513   
label values mv527    MV527   
label values mv532    MV532   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv610    MV610   
label values mv611    MV611   
label values mv612    MV612   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv714    MV714   
label values mv716    MV716   
label values mv717    MV717   
label values mv731    MV731   
label values mv740    MV740   
label values mv762    MV762   
label values sdformat SDFORMAT
label values sadjust  SADJUST 
label values sdiv     SDIV    
label values s114a    S114A   
label values s114b    S114B   
label values s114c    S114C   
label values s114d    S114D   
label values s114e    S114E   
label values s119     S119    
label values s123     S123    
label values s124a    S124A   
label values s124b    S124B   
label values s124c    S124C   
label values s124d    S124D   
label values s124i    S124I   
label values s229m    S229M   
label values s229y    S229Y   
label values s233a    S233A   
label values s233b    S233B   
label values s233c    S233C   
label values s233dy   S233DY  
label values msformat MSFORMAT
label values msadjust MSADJUST
label values ms304_01 MS304   
label values ms304_02 MS304   
label values ms304_03 MS304   
label values ms304_04 MS304   
label values ms304_05 MS304   
label values ms304_06 MS304   
label values ms304_07 MS304   
label values ms304_08 MS304   
label values ms304_09 MS304   
label values ms304_10 MS304   
label values ms304_11 MS304   
label values ms304_12 MS304   
label values ms304_13 MS304   
label values ms304_14 MS304   
label values ms304_15 MS304   
label values ms304_16 MS304   
label values ms304_17 MS304   
label values ms304_18 MS304   
label values ms304_19 MS304   
label values ms304_20 MS304   
label values ms309    MS309   
label values ms316    MS316   
label values ms317    MS317   
label values ms320s   MS320S  
label values ms320    MS320   
label values ms320a   MS320A  
label values ms320c   MS320C  
label values ms320d   MS320D  
label values ms321f   MS321F  
label values ms321xa  MS321XA 
label values ms321xb  MS321XB 
label values ms321xc  MS321XC 
label values ms321xd  MS321XD 
label values ms321xe  MS321XE 
label values ms321xf  MS321XF 
label values ms322b   MS322B  
label values ms322c   MS322C  
label values ms323    MS323   
label values ms323b   MS323B  
label values ms325    MS325   
label values ms325a   MS325A  
label values ms325b   MS325B  
label values ms325c   MS325C  
label values ms325h   MS325H  
label values ms325i   MS325I  
label values ms325j   MS325J  
label values ms326    MS326   
label values ms328hi  MS328HI 
label values ms347a   MS347A  
label values ms347b   MS347B  
label values ms347ca  MS347CA 
label values ms347cb  MS347CB 
label values ms347cc  MS347CC 
label values ms347cd  MS347CD 
label values ms347ce  MS347CE 
label values ms348c   MS348C  
label values ms349a   MS349A  
label values ms349b   MS349B  
label values ms349c   MS349C  
label values ms349d   MS349D  
label values ms349e   MS349E  
label values ms350    MS350   
label values ms352    MS352   
label values ms353    MS353   
label values ms354    MS354   
label values ms355    MS355   
label values ms357a   MS357A  
label values ms357b   MS357B  
label values ms357c   MS357C  
label values ms357d   MS357D  
label values ms357e   MS357E  
label values ms357f   MS357F  
label values ms357g   MS357G  
label values ms358    MS358   
label values ms359    MS359   
label values ms360    MS360   
label values ms361    MS361   
label values ms408a   MS408A  
label values ms408b   MS408B  
label values ms408c   MS408C  
label values ms408d   MS408D  
label values ms508    MS508   
label values ms512    MS512   
label values ms514    MS514   
label values s304_01  S304    
label values s304_02  S304    
label values s304_03  S304    
label values s304_04  S304    
label values s304_05  S304    
label values s304_06  S304    
label values s304_07  S304    
label values s304_08  S304    
label values s304_09  S304    
label values s304_10  S304    
label values s304_11  S304    
label values s304_12  S304    
label values s304_13  S304    
label values s304_14  S304    
label values s304_15  S304    
label values s309     S309    
label values s310     S310    
label values s316     S316    
label values s317     S317    
label values s318b    S318B   
label values s318c    S318C   
label values s318ea   S318EA  
label values s318eb   S318EB  
label values s318ec   S318EC  
label values s318ed   S318ED  
label values s318ee   S318EE  
label values s318ef   S318EF  
label values s318eg   S318EG  
label values s318f    S318F   
label values s318ha   S318HA  
label values s318hb   S318HB  
label values s318hc   S318HC  
label values s318hd   S318HD  
label values s318he   S318HE  
label values s318hf   S318HF  
label values s318hg   S318HG  
label values s318hh   S318HH  
label values s318hi   S318HI  
label values s318i    S318I   
label values s318k    S318K   
label values s319b    S319B   
label values s320s    S320S   
label values s320     S320    
label values s320a    S320A   
label values s320c    S320C   
label values s322c    S322C   
label values s322d    S322D   
label values s323b    S323B   
label values s325     S325    
label values s325a    S325A   
label values s325b    S325B   
label values s325c    S325C   
label values s325e    S325E   
label values s325g    S325G   
label values s325h    S325H   
label values s325i    S325I   
label values s325j    S325J   
label values s326     S326    
label values s327     S327    
label values s328pa   S328PA  
label values s328pb   S328PB  
label values s328pc   S328PC  
label values s328pd   S328PD  
label values s328pe   S328PE  
label values s328pf   S328PF  
label values s328pg   S328PG  
label values s328ph   S328PH  
label values s328pi   S328PI  
label values s328pj   S328PJ  
label values s328pk   S328PK  
label values s328a    S328A   
label values s328b    S328B   
label values s328c    S328C   
label values s328da   S328DA  
label values s328db   S328DB  
label values s328dc   S328DC  
label values s328dd   S328DD  
label values s328de   S328DE  
label values s328df   S328DF  
label values s328dg   S328DG  
label values s328dh   S328DH  
label values s328di   S328DI  
label values s347a    S347A   
label values s347b    S347B   
label values s347ca   S347CA  
label values s347cb   S347CB  
label values s347cc   S347CC  
label values s347cd   S347CD  
label values s347ce   S347CE  
label values s348c    S348C   
label values s349a    S349A   
label values s349b    S349B   
label values s349c    S349C   
label values s349d    S349D   
label values s349e    S349E   
label values s352     S352    
label values s353     S353    
label values s354     S354    
label values s355     S355    
label values s357ma   S357MA  
label values s357mb   S357MB  
label values s357mc   S357MC  
label values s357md   S357MD  
label values s357me   S357ME  
label values s357mf   S357MF  
label values s357mg   S357MG  
label values s357a    S357A   
label values s357b    S357B   
label values s358     S358    
label values s359     S359    
label values s361     S361    
label values s439     S439    
label values s440     S440    
label values s441     S441    
label values s442a    S442A   
label values s442b_1  S442B   
label values s442c_1  S442C   
label values s442da_1 S442DA  
label values s442db_1 S442DB  
label values s442dc_1 S442DC  
label values s442dd_1 S442DD  
label values s442de_1 S442DE  
label values s442df_1 S442DF  
label values s442dg_1 S442DG  
label values s442dh_1 S442DH  
label values s442di_1 S442DI  
label values s442dj_1 S442DJ  
label values s442dk_1 S442DK  
label values s442r1_1 S442R1  
label values s442i1_1 S442I1  
label values s442r2_1 S442R2  
label values s442i2_1 S442I2  
label values s442b_2  S442B   
label values s442c_2  S442C   
label values s442da_2 S442DA  
label values s442db_2 S442DB  
label values s442dc_2 S442DC  
label values s442dd_2 S442DD  
label values s442de_2 S442DE  
label values s442df_2 S442DF  
label values s442dg_2 S442DG  
label values s442dh_2 S442DH  
label values s442di_2 S442DI  
label values s442dj_2 S442DJ  
label values s442dk_2 S442DK  
label values s442r1_2 S442R1  
label values s442i1_2 S442I1  
label values s442r2_2 S442R2  
label values s442i2_2 S442I2  
label values s442h    S442H   
label values s442ia   S442IA  
label values s442ib   S442IB  
label values s442ic   S442IC  
label values s442id   S442ID  
label values s442ie   S442IE  
label values s442if   S442IF  
label values s442ig   S442IG  
label values s442j    S442J   
label values s442ka   S442KA  
label values s442kb   S442KB  
label values s442kc   S442KC  
label values s442kd   S442KD  
label values s442ke   S442KE  
label values s442kf   S442KF  
label values s442l    S442L   
label values s442ma   S442MA  
label values s442mb   S442MB  
label values s442mc   S442MC  
label values s442md   S442MD  
label values s442me   S442ME  
label values s442mf   S442MF  
label values s442mg   S442MG  
label values s442mh   S442MH  
label values s442mi   S442MI  
label values s442n    S442N   
label values s442o    S442O   
label values s609     S609    
label values s613     S613    
label values s615     S615    
label values s616     S616    
label values s617     S617    
label values s618     S618    
