infix using BDHR31FL.dct

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor -NA"
label variable hv031    "Field editor -NA"
label variable hv032    "Office editor -NA"
label variable hv033    "Ultimate area selection prob."
label variable hv201    "Source of drinking water"
label variable hv202    "Source of non-drinking water"
label variable hv203    "Same source of water"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator -NA"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle -NA"
label variable hv212    "Has car -NA"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material"
label variable hv215    "Main roof material"
label variable hv216    "Rooms for sleeping"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone -NA"
label variable hv222    "Type of salt used for cook -NA"
label variable hvidx_01 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv106_01 "Highest educational level"
label variable hv107_01 "Highest year of education"
label variable hv108_01 "Education in single years"
label variable hv109_01 "Educational attainment"
label variable hv110_01 "Member still in school"
label variable hv111_01 "Mother alive -NA"
label variable hv112_01 "Mother's line number -NA"
label variable hv113_01 "Father alive -NA"
label variable hv114_01 "Father's line number -NA"
label variable hv115_01 "Current marital status -NA"
label variable hv116_01 "Currently, formerly, never m."
label variable hv117_01 "Eligibility for female intview"
label variable hv118_01 "Eligibility for male interview"
label variable hvidx_02 "Line number"
label variable hv101_02 "Relationship to head"
label variable hv102_02 "Usual resident"
label variable hv103_02 "Slept last night"
label variable hv104_02 "Sex of household member"
label variable hv105_02 "Age of household members"
label variable hv106_02 "Highest educational level"
label variable hv107_02 "Highest year of education"
label variable hv108_02 "Education in single years"
label variable hv109_02 "Educational attainment"
label variable hv110_02 "Member still in school"
label variable hv111_02 "Mother alive -NA"
label variable hv112_02 "Mother's line number -NA"
label variable hv113_02 "Father alive -NA"
label variable hv114_02 "Father's line number -NA"
label variable hv115_02 "Current marital status -NA"
label variable hv116_02 "Currently, formerly, never m."
label variable hv117_02 "Eligibility for female intview"
label variable hv118_02 "Eligibility for male interview"
label variable hvidx_03 "Line number"
label variable hv101_03 "Relationship to head"
label variable hv102_03 "Usual resident"
label variable hv103_03 "Slept last night"
label variable hv104_03 "Sex of household member"
label variable hv105_03 "Age of household members"
label variable hv106_03 "Highest educational level"
label variable hv107_03 "Highest year of education"
label variable hv108_03 "Education in single years"
label variable hv109_03 "Educational attainment"
label variable hv110_03 "Member still in school"
label variable hv111_03 "Mother alive -NA"
label variable hv112_03 "Mother's line number -NA"
label variable hv113_03 "Father alive -NA"
label variable hv114_03 "Father's line number -NA"
label variable hv115_03 "Current marital status -NA"
label variable hv116_03 "Currently, formerly, never m."
label variable hv117_03 "Eligibility for female intview"
label variable hv118_03 "Eligibility for male interview"
label variable hvidx_04 "Line number"
label variable hv101_04 "Relationship to head"
label variable hv102_04 "Usual resident"
label variable hv103_04 "Slept last night"
label variable hv104_04 "Sex of household member"
label variable hv105_04 "Age of household members"
label variable hv106_04 "Highest educational level"
label variable hv107_04 "Highest year of education"
label variable hv108_04 "Education in single years"
label variable hv109_04 "Educational attainment"
label variable hv110_04 "Member still in school"
label variable hv111_04 "Mother alive -NA"
label variable hv112_04 "Mother's line number -NA"
label variable hv113_04 "Father alive -NA"
label variable hv114_04 "Father's line number -NA"
label variable hv115_04 "Current marital status -NA"
label variable hv116_04 "Currently, formerly, never m."
label variable hv117_04 "Eligibility for female intview"
label variable hv118_04 "Eligibility for male interview"
label variable hvidx_05 "Line number"
label variable hv101_05 "Relationship to head"
label variable hv102_05 "Usual resident"
label variable hv103_05 "Slept last night"
label variable hv104_05 "Sex of household member"
label variable hv105_05 "Age of household members"
label variable hv106_05 "Highest educational level"
label variable hv107_05 "Highest year of education"
label variable hv108_05 "Education in single years"
label variable hv109_05 "Educational attainment"
label variable hv110_05 "Member still in school"
label variable hv111_05 "Mother alive -NA"
label variable hv112_05 "Mother's line number -NA"
label variable hv113_05 "Father alive -NA"
label variable hv114_05 "Father's line number -NA"
label variable hv115_05 "Current marital status -NA"
label variable hv116_05 "Currently, formerly, never m."
label variable hv117_05 "Eligibility for female intview"
label variable hv118_05 "Eligibility for male interview"
label variable hvidx_06 "Line number"
label variable hv101_06 "Relationship to head"
label variable hv102_06 "Usual resident"
label variable hv103_06 "Slept last night"
label variable hv104_06 "Sex of household member"
label variable hv105_06 "Age of household members"
label variable hv106_06 "Highest educational level"
label variable hv107_06 "Highest year of education"
label variable hv108_06 "Education in single years"
label variable hv109_06 "Educational attainment"
label variable hv110_06 "Member still in school"
label variable hv111_06 "Mother alive -NA"
label variable hv112_06 "Mother's line number -NA"
label variable hv113_06 "Father alive -NA"
label variable hv114_06 "Father's line number -NA"
label variable hv115_06 "Current marital status -NA"
label variable hv116_06 "Currently, formerly, never m."
label variable hv117_06 "Eligibility for female intview"
label variable hv118_06 "Eligibility for male interview"
label variable hvidx_07 "Line number"
label variable hv101_07 "Relationship to head"
label variable hv102_07 "Usual resident"
label variable hv103_07 "Slept last night"
label variable hv104_07 "Sex of household member"
label variable hv105_07 "Age of household members"
label variable hv106_07 "Highest educational level"
label variable hv107_07 "Highest year of education"
label variable hv108_07 "Education in single years"
label variable hv109_07 "Educational attainment"
label variable hv110_07 "Member still in school"
label variable hv111_07 "Mother alive -NA"
label variable hv112_07 "Mother's line number -NA"
label variable hv113_07 "Father alive -NA"
label variable hv114_07 "Father's line number -NA"
label variable hv115_07 "Current marital status -NA"
label variable hv116_07 "Currently, formerly, never m."
label variable hv117_07 "Eligibility for female intview"
label variable hv118_07 "Eligibility for male interview"
label variable hvidx_08 "Line number"
label variable hv101_08 "Relationship to head"
label variable hv102_08 "Usual resident"
label variable hv103_08 "Slept last night"
label variable hv104_08 "Sex of household member"
label variable hv105_08 "Age of household members"
label variable hv106_08 "Highest educational level"
label variable hv107_08 "Highest year of education"
label variable hv108_08 "Education in single years"
label variable hv109_08 "Educational attainment"
label variable hv110_08 "Member still in school"
label variable hv111_08 "Mother alive -NA"
label variable hv112_08 "Mother's line number -NA"
label variable hv113_08 "Father alive -NA"
label variable hv114_08 "Father's line number -NA"
label variable hv115_08 "Current marital status -NA"
label variable hv116_08 "Currently, formerly, never m."
label variable hv117_08 "Eligibility for female intview"
label variable hv118_08 "Eligibility for male interview"
label variable hvidx_09 "Line number"
label variable hv101_09 "Relationship to head"
label variable hv102_09 "Usual resident"
label variable hv103_09 "Slept last night"
label variable hv104_09 "Sex of household member"
label variable hv105_09 "Age of household members"
label variable hv106_09 "Highest educational level"
label variable hv107_09 "Highest year of education"
label variable hv108_09 "Education in single years"
label variable hv109_09 "Educational attainment"
label variable hv110_09 "Member still in school"
label variable hv111_09 "Mother alive -NA"
label variable hv112_09 "Mother's line number -NA"
label variable hv113_09 "Father alive -NA"
label variable hv114_09 "Father's line number -NA"
label variable hv115_09 "Current marital status -NA"
label variable hv116_09 "Currently, formerly, never m."
label variable hv117_09 "Eligibility for female intview"
label variable hv118_09 "Eligibility for male interview"
label variable hvidx_10 "Line number"
label variable hv101_10 "Relationship to head"
label variable hv102_10 "Usual resident"
label variable hv103_10 "Slept last night"
label variable hv104_10 "Sex of household member"
label variable hv105_10 "Age of household members"
label variable hv106_10 "Highest educational level"
label variable hv107_10 "Highest year of education"
label variable hv108_10 "Education in single years"
label variable hv109_10 "Educational attainment"
label variable hv110_10 "Member still in school"
label variable hv111_10 "Mother alive -NA"
label variable hv112_10 "Mother's line number -NA"
label variable hv113_10 "Father alive -NA"
label variable hv114_10 "Father's line number -NA"
label variable hv115_10 "Current marital status -NA"
label variable hv116_10 "Currently, formerly, never m."
label variable hv117_10 "Eligibility for female intview"
label variable hv118_10 "Eligibility for male interview"
label variable hvidx_11 "Line number"
label variable hv101_11 "Relationship to head"
label variable hv102_11 "Usual resident"
label variable hv103_11 "Slept last night"
label variable hv104_11 "Sex of household member"
label variable hv105_11 "Age of household members"
label variable hv106_11 "Highest educational level"
label variable hv107_11 "Highest year of education"
label variable hv108_11 "Education in single years"
label variable hv109_11 "Educational attainment"
label variable hv110_11 "Member still in school"
label variable hv111_11 "Mother alive -NA"
label variable hv112_11 "Mother's line number -NA"
label variable hv113_11 "Father alive -NA"
label variable hv114_11 "Father's line number -NA"
label variable hv115_11 "Current marital status -NA"
label variable hv116_11 "Currently, formerly, never m."
label variable hv117_11 "Eligibility for female intview"
label variable hv118_11 "Eligibility for male interview"
label variable hvidx_12 "Line number"
label variable hv101_12 "Relationship to head"
label variable hv102_12 "Usual resident"
label variable hv103_12 "Slept last night"
label variable hv104_12 "Sex of household member"
label variable hv105_12 "Age of household members"
label variable hv106_12 "Highest educational level"
label variable hv107_12 "Highest year of education"
label variable hv108_12 "Education in single years"
label variable hv109_12 "Educational attainment"
label variable hv110_12 "Member still in school"
label variable hv111_12 "Mother alive -NA"
label variable hv112_12 "Mother's line number -NA"
label variable hv113_12 "Father alive -NA"
label variable hv114_12 "Father's line number -NA"
label variable hv115_12 "Current marital status -NA"
label variable hv116_12 "Currently, formerly, never m."
label variable hv117_12 "Eligibility for female intview"
label variable hv118_12 "Eligibility for male interview"
label variable hvidx_13 "Line number"
label variable hv101_13 "Relationship to head"
label variable hv102_13 "Usual resident"
label variable hv103_13 "Slept last night"
label variable hv104_13 "Sex of household member"
label variable hv105_13 "Age of household members"
label variable hv106_13 "Highest educational level"
label variable hv107_13 "Highest year of education"
label variable hv108_13 "Education in single years"
label variable hv109_13 "Educational attainment"
label variable hv110_13 "Member still in school"
label variable hv111_13 "Mother alive -NA"
label variable hv112_13 "Mother's line number -NA"
label variable hv113_13 "Father alive -NA"
label variable hv114_13 "Father's line number -NA"
label variable hv115_13 "Current marital status -NA"
label variable hv116_13 "Currently, formerly, never m."
label variable hv117_13 "Eligibility for female intview"
label variable hv118_13 "Eligibility for male interview"
label variable hvidx_14 "Line number"
label variable hv101_14 "Relationship to head"
label variable hv102_14 "Usual resident"
label variable hv103_14 "Slept last night"
label variable hv104_14 "Sex of household member"
label variable hv105_14 "Age of household members"
label variable hv106_14 "Highest educational level"
label variable hv107_14 "Highest year of education"
label variable hv108_14 "Education in single years"
label variable hv109_14 "Educational attainment"
label variable hv110_14 "Member still in school"
label variable hv111_14 "Mother alive -NA"
label variable hv112_14 "Mother's line number -NA"
label variable hv113_14 "Father alive -NA"
label variable hv114_14 "Father's line number -NA"
label variable hv115_14 "Current marital status -NA"
label variable hv116_14 "Currently, formerly, never m."
label variable hv117_14 "Eligibility for female intview"
label variable hv118_14 "Eligibility for male interview"
label variable hvidx_15 "Line number"
label variable hv101_15 "Relationship to head"
label variable hv102_15 "Usual resident"
label variable hv103_15 "Slept last night"
label variable hv104_15 "Sex of household member"
label variable hv105_15 "Age of household members"
label variable hv106_15 "Highest educational level"
label variable hv107_15 "Highest year of education"
label variable hv108_15 "Education in single years"
label variable hv109_15 "Educational attainment"
label variable hv110_15 "Member still in school"
label variable hv111_15 "Mother alive -NA"
label variable hv112_15 "Mother's line number -NA"
label variable hv113_15 "Father alive -NA"
label variable hv114_15 "Father's line number -NA"
label variable hv115_15 "Current marital status -NA"
label variable hv116_15 "Currently, formerly, never m."
label variable hv117_15 "Eligibility for female intview"
label variable hv118_15 "Eligibility for male interview"
label variable hvidx_16 "Line number"
label variable hv101_16 "Relationship to head"
label variable hv102_16 "Usual resident"
label variable hv103_16 "Slept last night"
label variable hv104_16 "Sex of household member"
label variable hv105_16 "Age of household members"
label variable hv106_16 "Highest educational level"
label variable hv107_16 "Highest year of education"
label variable hv108_16 "Education in single years"
label variable hv109_16 "Educational attainment"
label variable hv110_16 "Member still in school"
label variable hv111_16 "Mother alive -NA"
label variable hv112_16 "Mother's line number -NA"
label variable hv113_16 "Father alive -NA"
label variable hv114_16 "Father's line number -NA"
label variable hv115_16 "Current marital status -NA"
label variable hv116_16 "Currently, formerly, never m."
label variable hv117_16 "Eligibility for female intview"
label variable hv118_16 "Eligibility for male interview"
label variable hvidx_17 "Line number"
label variable hv101_17 "Relationship to head"
label variable hv102_17 "Usual resident"
label variable hv103_17 "Slept last night"
label variable hv104_17 "Sex of household member"
label variable hv105_17 "Age of household members"
label variable hv106_17 "Highest educational level"
label variable hv107_17 "Highest year of education"
label variable hv108_17 "Education in single years"
label variable hv109_17 "Educational attainment"
label variable hv110_17 "Member still in school"
label variable hv111_17 "Mother alive -NA"
label variable hv112_17 "Mother's line number -NA"
label variable hv113_17 "Father alive -NA"
label variable hv114_17 "Father's line number -NA"
label variable hv115_17 "Current marital status -NA"
label variable hv116_17 "Currently, formerly, never m."
label variable hv117_17 "Eligibility for female intview"
label variable hv118_17 "Eligibility for male interview"
label variable hvidx_18 "Line number"
label variable hv101_18 "Relationship to head"
label variable hv102_18 "Usual resident"
label variable hv103_18 "Slept last night"
label variable hv104_18 "Sex of household member"
label variable hv105_18 "Age of household members"
label variable hv106_18 "Highest educational level"
label variable hv107_18 "Highest year of education"
label variable hv108_18 "Education in single years"
label variable hv109_18 "Educational attainment"
label variable hv110_18 "Member still in school"
label variable hv111_18 "Mother alive -NA"
label variable hv112_18 "Mother's line number -NA"
label variable hv113_18 "Father alive -NA"
label variable hv114_18 "Father's line number -NA"
label variable hv115_18 "Current marital status -NA"
label variable hv116_18 "Currently, formerly, never m."
label variable hv117_18 "Eligibility for female intview"
label variable hv118_18 "Eligibility for male interview"
label variable hvidx_19 "Line number"
label variable hv101_19 "Relationship to head"
label variable hv102_19 "Usual resident"
label variable hv103_19 "Slept last night"
label variable hv104_19 "Sex of household member"
label variable hv105_19 "Age of household members"
label variable hv106_19 "Highest educational level"
label variable hv107_19 "Highest year of education"
label variable hv108_19 "Education in single years"
label variable hv109_19 "Educational attainment"
label variable hv110_19 "Member still in school"
label variable hv111_19 "Mother alive -NA"
label variable hv112_19 "Mother's line number -NA"
label variable hv113_19 "Father alive -NA"
label variable hv114_19 "Father's line number -NA"
label variable hv115_19 "Current marital status -NA"
label variable hv116_19 "Currently, formerly, never m."
label variable hv117_19 "Eligibility for female intview"
label variable hv118_19 "Eligibility for male interview"
label variable hvidx_20 "Line number"
label variable hv101_20 "Relationship to head"
label variable hv102_20 "Usual resident"
label variable hv103_20 "Slept last night"
label variable hv104_20 "Sex of household member"
label variable hv105_20 "Age of household members"
label variable hv106_20 "Highest educational level"
label variable hv107_20 "Highest year of education"
label variable hv108_20 "Education in single years"
label variable hv109_20 "Educational attainment"
label variable hv110_20 "Member still in school"
label variable hv111_20 "Mother alive -NA"
label variable hv112_20 "Mother's line number -NA"
label variable hv113_20 "Father alive -NA"
label variable hv114_20 "Father's line number -NA"
label variable hv115_20 "Current marital status -NA"
label variable hv116_20 "Currently, formerly, never m."
label variable hv117_20 "Eligibility for female intview"
label variable hv118_20 "Eligibility for male interview"
label variable hvidx_21 "Line number"
label variable hv101_21 "Relationship to head"
label variable hv102_21 "Usual resident"
label variable hv103_21 "Slept last night"
label variable hv104_21 "Sex of household member"
label variable hv105_21 "Age of household members"
label variable hv106_21 "Highest educational level"
label variable hv107_21 "Highest year of education"
label variable hv108_21 "Education in single years"
label variable hv109_21 "Educational attainment"
label variable hv110_21 "Member still in school"
label variable hv111_21 "Mother alive -NA"
label variable hv112_21 "Mother's line number -NA"
label variable hv113_21 "Father alive -NA"
label variable hv114_21 "Father's line number -NA"
label variable hv115_21 "Current marital status -NA"
label variable hv116_21 "Currently, formerly, never m."
label variable hv117_21 "Eligibility for female intview"
label variable hv118_21 "Eligibility for male interview"
label variable hvidx_22 "Line number"
label variable hv101_22 "Relationship to head"
label variable hv102_22 "Usual resident"
label variable hv103_22 "Slept last night"
label variable hv104_22 "Sex of household member"
label variable hv105_22 "Age of household members"
label variable hv106_22 "Highest educational level"
label variable hv107_22 "Highest year of education"
label variable hv108_22 "Education in single years"
label variable hv109_22 "Educational attainment"
label variable hv110_22 "Member still in school"
label variable hv111_22 "Mother alive -NA"
label variable hv112_22 "Mother's line number -NA"
label variable hv113_22 "Father alive -NA"
label variable hv114_22 "Father's line number -NA"
label variable hv115_22 "Current marital status -NA"
label variable hv116_22 "Currently, formerly, never m."
label variable hv117_22 "Eligibility for female intview"
label variable hv118_22 "Eligibility for male interview"
label variable hvidx_23 "Line number"
label variable hv101_23 "Relationship to head"
label variable hv102_23 "Usual resident"
label variable hv103_23 "Slept last night"
label variable hv104_23 "Sex of household member"
label variable hv105_23 "Age of household members"
label variable hv106_23 "Highest educational level"
label variable hv107_23 "Highest year of education"
label variable hv108_23 "Education in single years"
label variable hv109_23 "Educational attainment"
label variable hv110_23 "Member still in school"
label variable hv111_23 "Mother alive -NA"
label variable hv112_23 "Mother's line number -NA"
label variable hv113_23 "Father alive -NA"
label variable hv114_23 "Father's line number -NA"
label variable hv115_23 "Current marital status -NA"
label variable hv116_23 "Currently, formerly, never m."
label variable hv117_23 "Eligibility for female intview"
label variable hv118_23 "Eligibility for male interview"
label variable hvidx_24 "Line number"
label variable hv101_24 "Relationship to head"
label variable hv102_24 "Usual resident"
label variable hv103_24 "Slept last night"
label variable hv104_24 "Sex of household member"
label variable hv105_24 "Age of household members"
label variable hv106_24 "Highest educational level"
label variable hv107_24 "Highest year of education"
label variable hv108_24 "Education in single years"
label variable hv109_24 "Educational attainment"
label variable hv110_24 "Member still in school"
label variable hv111_24 "Mother alive -NA"
label variable hv112_24 "Mother's line number -NA"
label variable hv113_24 "Father alive -NA"
label variable hv114_24 "Father's line number -NA"
label variable hv115_24 "Current marital status -NA"
label variable hv116_24 "Currently, formerly, never m."
label variable hv117_24 "Eligibility for female intview"
label variable hv118_24 "Eligibility for male interview"
label variable hvidx_25 "Line number"
label variable hv101_25 "Relationship to head"
label variable hv102_25 "Usual resident"
label variable hv103_25 "Slept last night"
label variable hv104_25 "Sex of household member"
label variable hv105_25 "Age of household members"
label variable hv106_25 "Highest educational level"
label variable hv107_25 "Highest year of education"
label variable hv108_25 "Education in single years"
label variable hv109_25 "Educational attainment"
label variable hv110_25 "Member still in school"
label variable hv111_25 "Mother alive -NA"
label variable hv112_25 "Mother's line number -NA"
label variable hv113_25 "Father alive -NA"
label variable hv114_25 "Father's line number -NA"
label variable hv115_25 "Current marital status -NA"
label variable hv116_25 "Currently, formerly, never m."
label variable hv117_25 "Eligibility for female intview"
label variable hv118_25 "Eligibility for male interview"
label variable hvidx_26 "Line number"
label variable hv101_26 "Relationship to head"
label variable hv102_26 "Usual resident"
label variable hv103_26 "Slept last night"
label variable hv104_26 "Sex of household member"
label variable hv105_26 "Age of household members"
label variable hv106_26 "Highest educational level"
label variable hv107_26 "Highest year of education"
label variable hv108_26 "Education in single years"
label variable hv109_26 "Educational attainment"
label variable hv110_26 "Member still in school"
label variable hv111_26 "Mother alive -NA"
label variable hv112_26 "Mother's line number -NA"
label variable hv113_26 "Father alive -NA"
label variable hv114_26 "Father's line number -NA"
label variable hv115_26 "Current marital status -NA"
label variable hv116_26 "Currently, formerly, never m."
label variable hv117_26 "Eligibility for female intview"
label variable hv118_26 "Eligibility for male interview"
label variable hvidx_27 "Line number"
label variable hv101_27 "Relationship to head"
label variable hv102_27 "Usual resident"
label variable hv103_27 "Slept last night"
label variable hv104_27 "Sex of household member"
label variable hv105_27 "Age of household members"
label variable hv106_27 "Highest educational level"
label variable hv107_27 "Highest year of education"
label variable hv108_27 "Education in single years"
label variable hv109_27 "Educational attainment"
label variable hv110_27 "Member still in school"
label variable hv111_27 "Mother alive -NA"
label variable hv112_27 "Mother's line number -NA"
label variable hv113_27 "Father alive -NA"
label variable hv114_27 "Father's line number -NA"
label variable hv115_27 "Current marital status -NA"
label variable hv116_27 "Currently, formerly, never m."
label variable hv117_27 "Eligibility for female intview"
label variable hv118_27 "Eligibility for male interview"
label variable hvidx_28 "Line number"
label variable hv101_28 "Relationship to head"
label variable hv102_28 "Usual resident"
label variable hv103_28 "Slept last night"
label variable hv104_28 "Sex of household member"
label variable hv105_28 "Age of household members"
label variable hv106_28 "Highest educational level"
label variable hv107_28 "Highest year of education"
label variable hv108_28 "Education in single years"
label variable hv109_28 "Educational attainment"
label variable hv110_28 "Member still in school"
label variable hv111_28 "Mother alive -NA"
label variable hv112_28 "Mother's line number -NA"
label variable hv113_28 "Father alive -NA"
label variable hv114_28 "Father's line number -NA"
label variable hv115_28 "Current marital status -NA"
label variable hv116_28 "Currently, formerly, never m."
label variable hv117_28 "Eligibility for female intview"
label variable hv118_28 "Eligibility for male interview"
label variable shdistr  "District of residence"
label variable sh20     "Time to get to water source"
label variable sh20a    "Time to wait to get water:mins"
label variable sh25     "Toilet facility : children"
label variable sh26a    "Almirah"
label variable sh26b    "Table/chair/bench"
label variable sh26c    "Watch/clock"
label variable sh26d    "Cot/bed"
label variable sh26i    "Agricultural land"
label variable sh31     "Urban slum"
label variable idxh4_01 "Index to household schedule"
label variable sh14_01  "Works for money"
label variable sh17_01  "Husbands line number"
label variable idxh4_02 "Index to household schedule"
label variable sh14_02  "Works for money"
label variable sh17_02  "Husbands line number"
label variable idxh4_03 "Index to household schedule"
label variable sh14_03  "Works for money"
label variable sh17_03  "Husbands line number"
label variable idxh4_04 "Index to household schedule"
label variable sh14_04  "Works for money"
label variable sh17_04  "Husbands line number"
label variable idxh4_05 "Index to household schedule"
label variable sh14_05  "Works for money"
label variable sh17_05  "Husbands line number"
label variable idxh4_06 "Index to household schedule"
label variable sh14_06  "Works for money"
label variable sh17_06  "Husbands line number"
label variable idxh4_07 "Index to household schedule"
label variable sh14_07  "Works for money"
label variable sh17_07  "Husbands line number"
label variable idxh4_08 "Index to household schedule"
label variable sh14_08  "Works for money"
label variable sh17_08  "Husbands line number"
label variable idxh4_09 "Index to household schedule"
label variable sh14_09  "Works for money"
label variable sh17_09  "Husbands line number"
label variable idxh4_10 "Index to household schedule"
label variable sh14_10  "Works for money"
label variable sh17_10  "Husbands line number"
label variable idxh4_11 "Index to household schedule"
label variable sh14_11  "Works for money"
label variable sh17_11  "Husbands line number"
label variable idxh4_12 "Index to household schedule"
label variable sh14_12  "Works for money"
label variable sh17_12  "Husbands line number"
label variable idxh4_13 "Index to household schedule"
label variable sh14_13  "Works for money"
label variable sh17_13  "Husbands line number"
label variable idxh4_14 "Index to household schedule"
label variable sh14_14  "Works for money"
label variable sh17_14  "Husbands line number"
label variable idxh4_15 "Index to household schedule"
label variable sh14_15  "Works for money"
label variable sh17_15  "Husbands line number"
label variable idxh4_16 "Index to household schedule"
label variable sh14_16  "Works for money"
label variable sh17_16  "Husbands line number"
label variable idxh4_17 "Index to household schedule"
label variable sh14_17  "Works for money"
label variable sh17_17  "Husbands line number"
label variable idxh4_18 "Index to household schedule"
label variable sh14_18  "Works for money"
label variable sh17_18  "Husbands line number"
label variable idxh4_19 "Index to household schedule"
label variable sh14_19  "Works for money"
label variable sh17_19  "Husbands line number"
label variable idxh4_20 "Index to household schedule"
label variable sh14_20  "Works for money"
label variable sh17_20  "Husbands line number"
label variable idxh4_21 "Index to household schedule"
label variable sh14_21  "Works for money"
label variable sh17_21  "Husbands line number"
label variable idxh4_22 "Index to household schedule"
label variable sh14_22  "Works for money"
label variable sh17_22  "Husbands line number"
label variable idxh4_23 "Index to household schedule"
label variable sh14_23  "Works for money"
label variable sh17_23  "Husbands line number"
label variable idxh4_24 "Index to household schedule"
label variable sh14_24  "Works for money"
label variable sh17_24  "Husbands line number"
label variable idxh4_25 "Index to household schedule"
label variable sh14_25  "Works for money"
label variable sh17_25  "Husbands line number"
label variable idxh4_26 "Index to household schedule"
label variable sh14_26  "Works for money"
label variable sh17_26  "Husbands line number"
label variable idxh4_27 "Index to household schedule"
label variable sh14_27  "Works for money"
label variable sh17_27  "Husbands line number"
label variable idxh4_28 "Index to household schedule"
label variable sh14_28  "Works for money"
label variable sh17_28  "Husbands line number"

#delimit ;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     0 "National"
     1 "Country specific"
;
label define HV024   
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Dhaka/Chittagong"
     1 "Small city"
     2 "Town"
     3 "Village"
     9 "Missing"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
    99 "Missing"
;
label define HV202   
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
    99 "Missing"
;
label define HV203   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV204   
   996 "On premises"
   999 "Missing"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Septic tank/modern"
    20 "PIT TOILET LATRINE"
    21 "Water sealed/slab"
    22 "Pit latrine"
    23 "Open latrine"
    24 "Hanging latrine"
    30 "NO FACILITY"
    31 "No facility/bush"
    96 "OTHER"
    99 "Missing"
;
label define HV206   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV207   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV208   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV210   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV213   
    10 "NATURAL"
    11 "Earth"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
    99 "Missing"
;
label define HV214   
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Brick/cement"
    32 "Tin"
    96 "OTHER"
    99 "Missing"
;
label define HV215   
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Tin"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
    99 "Missing"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
     9 "Missing"
;
label define HV220   
    97 "97+"
    98 "DK"
    99 "Missing"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
    99 "Missing"
;
label define HV102   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV103   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV104   
     1 "Male"
     2 "Female"
     9 "Missing"
;
label define HV105   
    96 "96 or older"
    98 "DK"
    99 "Missing"
;
label define HV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
     9 "Missing"
;
label define HV107   
    98 "DK"
    99 "Missing"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
    99 "Missing"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
     9 "Missing"
;
label define HV110   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define HV116   
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
     9 "Missing"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define SH20    
   996 "On premises"
   999 "Missing"
;
label define SH25    
     0 "No children"
    10 "FLUSH TOILET"
    11 "Septic tank/modern"
    20 "PIT TOILET LATRINE"
    21 "Water sealed/slab"
    22 "Pit latrine"
    23 "Open latrine"
    24 "Hanging latrine"
    30 "NO FACILITY"
    31 "No facility/bush"
    96 "OTHER"
    99 "Missing"
;
label define SH26A   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH26B   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH26C   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH26D   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH26I   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH31    
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define SH14    
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define SH17    
     0 "Not marr./husb away"
;

#delimit cr
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv201    HV201   
label values hv202    HV202   
label values hv203    HV203   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv210    HV210   
label values hv213    HV213   
label values hv214    HV214   
label values hv215    HV215   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv101_01 HV101   
label values hv102_01 HV102   
label values hv103_01 HV103   
label values hv104_01 HV104   
label values hv105_01 HV105   
label values hv106_01 HV106   
label values hv107_01 HV107   
label values hv108_01 HV108   
label values hv109_01 HV109   
label values hv110_01 HV110   
label values hv116_01 HV116   
label values hv117_01 HV117   
label values hv118_01 HV118   
label values hv101_02 HV101   
label values hv102_02 HV102   
label values hv103_02 HV103   
label values hv104_02 HV104   
label values hv105_02 HV105   
label values hv106_02 HV106   
label values hv107_02 HV107   
label values hv108_02 HV108   
label values hv109_02 HV109   
label values hv110_02 HV110   
label values hv116_02 HV116   
label values hv117_02 HV117   
label values hv118_02 HV118   
label values hv101_03 HV101   
label values hv102_03 HV102   
label values hv103_03 HV103   
label values hv104_03 HV104   
label values hv105_03 HV105   
label values hv106_03 HV106   
label values hv107_03 HV107   
label values hv108_03 HV108   
label values hv109_03 HV109   
label values hv110_03 HV110   
label values hv116_03 HV116   
label values hv117_03 HV117   
label values hv118_03 HV118   
label values hv101_04 HV101   
label values hv102_04 HV102   
label values hv103_04 HV103   
label values hv104_04 HV104   
label values hv105_04 HV105   
label values hv106_04 HV106   
label values hv107_04 HV107   
label values hv108_04 HV108   
label values hv109_04 HV109   
label values hv110_04 HV110   
label values hv116_04 HV116   
label values hv117_04 HV117   
label values hv118_04 HV118   
label values hv101_05 HV101   
label values hv102_05 HV102   
label values hv103_05 HV103   
label values hv104_05 HV104   
label values hv105_05 HV105   
label values hv106_05 HV106   
label values hv107_05 HV107   
label values hv108_05 HV108   
label values hv109_05 HV109   
label values hv110_05 HV110   
label values hv116_05 HV116   
label values hv117_05 HV117   
label values hv118_05 HV118   
label values hv101_06 HV101   
label values hv102_06 HV102   
label values hv103_06 HV103   
label values hv104_06 HV104   
label values hv105_06 HV105   
label values hv106_06 HV106   
label values hv107_06 HV107   
label values hv108_06 HV108   
label values hv109_06 HV109   
label values hv110_06 HV110   
label values hv116_06 HV116   
label values hv117_06 HV117   
label values hv118_06 HV118   
label values hv101_07 HV101   
label values hv102_07 HV102   
label values hv103_07 HV103   
label values hv104_07 HV104   
label values hv105_07 HV105   
label values hv106_07 HV106   
label values hv107_07 HV107   
label values hv108_07 HV108   
label values hv109_07 HV109   
label values hv110_07 HV110   
label values hv116_07 HV116   
label values hv117_07 HV117   
label values hv118_07 HV118   
label values hv101_08 HV101   
label values hv102_08 HV102   
label values hv103_08 HV103   
label values hv104_08 HV104   
label values hv105_08 HV105   
label values hv106_08 HV106   
label values hv107_08 HV107   
label values hv108_08 HV108   
label values hv109_08 HV109   
label values hv110_08 HV110   
label values hv116_08 HV116   
label values hv117_08 HV117   
label values hv118_08 HV118   
label values hv101_09 HV101   
label values hv102_09 HV102   
label values hv103_09 HV103   
label values hv104_09 HV104   
label values hv105_09 HV105   
label values hv106_09 HV106   
label values hv107_09 HV107   
label values hv108_09 HV108   
label values hv109_09 HV109   
label values hv110_09 HV110   
label values hv116_09 HV116   
label values hv117_09 HV117   
label values hv118_09 HV118   
label values hv101_10 HV101   
label values hv102_10 HV102   
label values hv103_10 HV103   
label values hv104_10 HV104   
label values hv105_10 HV105   
label values hv106_10 HV106   
label values hv107_10 HV107   
label values hv108_10 HV108   
label values hv109_10 HV109   
label values hv110_10 HV110   
label values hv116_10 HV116   
label values hv117_10 HV117   
label values hv118_10 HV118   
label values hv101_11 HV101   
label values hv102_11 HV102   
label values hv103_11 HV103   
label values hv104_11 HV104   
label values hv105_11 HV105   
label values hv106_11 HV106   
label values hv107_11 HV107   
label values hv108_11 HV108   
label values hv109_11 HV109   
label values hv110_11 HV110   
label values hv116_11 HV116   
label values hv117_11 HV117   
label values hv118_11 HV118   
label values hv101_12 HV101   
label values hv102_12 HV102   
label values hv103_12 HV103   
label values hv104_12 HV104   
label values hv105_12 HV105   
label values hv106_12 HV106   
label values hv107_12 HV107   
label values hv108_12 HV108   
label values hv109_12 HV109   
label values hv110_12 HV110   
label values hv116_12 HV116   
label values hv117_12 HV117   
label values hv118_12 HV118   
label values hv101_13 HV101   
label values hv102_13 HV102   
label values hv103_13 HV103   
label values hv104_13 HV104   
label values hv105_13 HV105   
label values hv106_13 HV106   
label values hv107_13 HV107   
label values hv108_13 HV108   
label values hv109_13 HV109   
label values hv110_13 HV110   
label values hv116_13 HV116   
label values hv117_13 HV117   
label values hv118_13 HV118   
label values hv101_14 HV101   
label values hv102_14 HV102   
label values hv103_14 HV103   
label values hv104_14 HV104   
label values hv105_14 HV105   
label values hv106_14 HV106   
label values hv107_14 HV107   
label values hv108_14 HV108   
label values hv109_14 HV109   
label values hv110_14 HV110   
label values hv116_14 HV116   
label values hv117_14 HV117   
label values hv118_14 HV118   
label values hv101_15 HV101   
label values hv102_15 HV102   
label values hv103_15 HV103   
label values hv104_15 HV104   
label values hv105_15 HV105   
label values hv106_15 HV106   
label values hv107_15 HV107   
label values hv108_15 HV108   
label values hv109_15 HV109   
label values hv110_15 HV110   
label values hv116_15 HV116   
label values hv117_15 HV117   
label values hv118_15 HV118   
label values hv101_16 HV101   
label values hv102_16 HV102   
label values hv103_16 HV103   
label values hv104_16 HV104   
label values hv105_16 HV105   
label values hv106_16 HV106   
label values hv107_16 HV107   
label values hv108_16 HV108   
label values hv109_16 HV109   
label values hv110_16 HV110   
label values hv116_16 HV116   
label values hv117_16 HV117   
label values hv118_16 HV118   
label values hv101_17 HV101   
label values hv102_17 HV102   
label values hv103_17 HV103   
label values hv104_17 HV104   
label values hv105_17 HV105   
label values hv106_17 HV106   
label values hv107_17 HV107   
label values hv108_17 HV108   
label values hv109_17 HV109   
label values hv110_17 HV110   
label values hv116_17 HV116   
label values hv117_17 HV117   
label values hv118_17 HV118   
label values hv101_18 HV101   
label values hv102_18 HV102   
label values hv103_18 HV103   
label values hv104_18 HV104   
label values hv105_18 HV105   
label values hv106_18 HV106   
label values hv107_18 HV107   
label values hv108_18 HV108   
label values hv109_18 HV109   
label values hv110_18 HV110   
label values hv116_18 HV116   
label values hv117_18 HV117   
label values hv118_18 HV118   
label values hv101_19 HV101   
label values hv102_19 HV102   
label values hv103_19 HV103   
label values hv104_19 HV104   
label values hv105_19 HV105   
label values hv106_19 HV106   
label values hv107_19 HV107   
label values hv108_19 HV108   
label values hv109_19 HV109   
label values hv110_19 HV110   
label values hv116_19 HV116   
label values hv117_19 HV117   
label values hv118_19 HV118   
label values hv101_20 HV101   
label values hv102_20 HV102   
label values hv103_20 HV103   
label values hv104_20 HV104   
label values hv105_20 HV105   
label values hv106_20 HV106   
label values hv107_20 HV107   
label values hv108_20 HV108   
label values hv109_20 HV109   
label values hv110_20 HV110   
label values hv116_20 HV116   
label values hv117_20 HV117   
label values hv118_20 HV118   
label values hv101_21 HV101   
label values hv102_21 HV102   
label values hv103_21 HV103   
label values hv104_21 HV104   
label values hv105_21 HV105   
label values hv106_21 HV106   
label values hv107_21 HV107   
label values hv108_21 HV108   
label values hv109_21 HV109   
label values hv110_21 HV110   
label values hv116_21 HV116   
label values hv117_21 HV117   
label values hv118_21 HV118   
label values hv101_22 HV101   
label values hv102_22 HV102   
label values hv103_22 HV103   
label values hv104_22 HV104   
label values hv105_22 HV105   
label values hv106_22 HV106   
label values hv107_22 HV107   
label values hv108_22 HV108   
label values hv109_22 HV109   
label values hv110_22 HV110   
label values hv116_22 HV116   
label values hv117_22 HV117   
label values hv118_22 HV118   
label values hv101_23 HV101   
label values hv102_23 HV102   
label values hv103_23 HV103   
label values hv104_23 HV104   
label values hv105_23 HV105   
label values hv106_23 HV106   
label values hv107_23 HV107   
label values hv108_23 HV108   
label values hv109_23 HV109   
label values hv110_23 HV110   
label values hv116_23 HV116   
label values hv117_23 HV117   
label values hv118_23 HV118   
label values hv101_24 HV101   
label values hv102_24 HV102   
label values hv103_24 HV103   
label values hv104_24 HV104   
label values hv105_24 HV105   
label values hv106_24 HV106   
label values hv107_24 HV107   
label values hv108_24 HV108   
label values hv109_24 HV109   
label values hv110_24 HV110   
label values hv116_24 HV116   
label values hv117_24 HV117   
label values hv118_24 HV118   
label values hv101_25 HV101   
label values hv102_25 HV102   
label values hv103_25 HV103   
label values hv104_25 HV104   
label values hv105_25 HV105   
label values hv106_25 HV106   
label values hv107_25 HV107   
label values hv108_25 HV108   
label values hv109_25 HV109   
label values hv110_25 HV110   
label values hv116_25 HV116   
label values hv117_25 HV117   
label values hv118_25 HV118   
label values hv101_26 HV101   
label values hv102_26 HV102   
label values hv103_26 HV103   
label values hv104_26 HV104   
label values hv105_26 HV105   
label values hv106_26 HV106   
label values hv107_26 HV107   
label values hv108_26 HV108   
label values hv109_26 HV109   
label values hv110_26 HV110   
label values hv116_26 HV116   
label values hv117_26 HV117   
label values hv118_26 HV118   
label values hv101_27 HV101   
label values hv102_27 HV102   
label values hv103_27 HV103   
label values hv104_27 HV104   
label values hv105_27 HV105   
label values hv106_27 HV106   
label values hv107_27 HV107   
label values hv108_27 HV108   
label values hv109_27 HV109   
label values hv110_27 HV110   
label values hv116_27 HV116   
label values hv117_27 HV117   
label values hv118_27 HV118   
label values hv101_28 HV101   
label values hv102_28 HV102   
label values hv103_28 HV103   
label values hv104_28 HV104   
label values hv105_28 HV105   
label values hv106_28 HV106   
label values hv107_28 HV107   
label values hv108_28 HV108   
label values hv109_28 HV109   
label values hv110_28 HV110   
label values hv116_28 HV116   
label values hv117_28 HV117   
label values hv118_28 HV118   
label values sh20     SH20    
label values sh25     SH25    
label values sh26a    SH26A   
label values sh26b    SH26B   
label values sh26c    SH26C   
label values sh26d    SH26D   
label values sh26i    SH26I   
label values sh31     SH31    
label values sh14_01  SH14    
label values sh17_01  SH17    
label values sh14_02  SH14    
label values sh17_02  SH17    
label values sh14_03  SH14    
label values sh17_03  SH17    
label values sh14_04  SH14    
label values sh17_04  SH17    
label values sh14_05  SH14    
label values sh17_05  SH17    
label values sh14_06  SH14    
label values sh17_06  SH17    
label values sh14_07  SH14    
label values sh17_07  SH17    
label values sh14_08  SH14    
label values sh17_08  SH17    
label values sh14_09  SH14    
label values sh17_09  SH17    
label values sh14_10  SH14    
label values sh17_10  SH17    
label values sh14_11  SH14    
label values sh17_11  SH17    
label values sh14_12  SH14    
label values sh17_12  SH17    
label values sh14_13  SH14    
label values sh17_13  SH17    
label values sh14_14  SH14    
label values sh17_14  SH17    
label values sh14_15  SH14    
label values sh17_15  SH17    
label values sh14_16  SH14    
label values sh17_16  SH17    
label values sh14_17  SH14    
label values sh17_17  SH17    
label values sh14_18  SH14    
label values sh17_18  SH17    
label values sh14_19  SH14    
label values sh17_19  SH17    
label values sh14_20  SH14    
label values sh17_20  SH17    
label values sh14_21  SH14    
label values sh17_21  SH17    
label values sh14_22  SH14    
label values sh17_22  SH17    
label values sh14_23  SH14    
label values sh17_23  SH17    
label values sh14_24  SH14    
label values sh17_24  SH17    
label values sh14_25  SH14    
label values sh17_25  SH17    
label values sh14_26  SH14    
label values sh17_26  SH17    
label values sh14_27  SH14    
label values sh17_27  SH17    
label values sh14_28  SH14    
label values sh17_28  SH17    
