DATA LIST FILE='BDHR31FL.DAT' RECORDS=1
/
 HHID        1-12   (A)
 HV000      13-15   (A)
 HV001      16-23  
 HV002      24-27  
 HV003      28-30  
 HV004      31-34  
 HV005      35-42  
 HV006      43-44  
 HV007      45-46  
 HV008      47-50  
 HV009      51-52  
 HV010      53-54  
 HV011      55-56  
 HV012      57-58  
 HV013      59-60  
 HV014      61-62  
 HV015      63-63  
 HV016      64-65  
 HV017      66-66  
 HV018      67-69  
 HV019      70-71  
 HV020      72-72  
 HV021      73-76  
 HV022      77-80  
 HV023      81-82  
 HV024      83-84  
 HV025      85-85  
 HV026      86-86  
 HV027      87-87  
 HV028      88-95  
 HV030      96-97  
 HV031      98-99  
 HV032     100-101 
 HV033     102-109 
 HV201     110-111 
 HV202     112-113 
 HV203     114-114 
 HV204     115-117 
 HV205     118-119 
 HV206     120-120 
 HV207     121-121 
 HV208     122-122 
 HV209     123-123 
 HV210     124-124 
 HV211     125-125 
 HV212     126-126 
 HV213     127-128 
 HV214     129-130 
 HV215     131-132 
 HV216     133-134 
 HV217     135-135 
 HV218     136-137 
 HV219     138-138 
 HV220     139-140 
 HV221     141-141 
 HV222     142-143 
 HVIDX$01  144-145 
 HV101$01  146-147 
 HV102$01  148-148 
 HV103$01  149-149 
 HV104$01  150-150 
 HV105$01  151-152 
 HV106$01  153-153 
 HV107$01  154-155 
 HV108$01  156-157 
 HV109$01  158-158 
 HV110$01  159-159 
 HV111$01  160-160 
 HV112$01  161-162 
 HV113$01  163-163 
 HV114$01  164-165 
 HV115$01  166-166 
 HV116$01  167-167 
 HV117$01  168-168 
 HV118$01  169-169 
 HVIDX$02  170-171 
 HV101$02  172-173 
 HV102$02  174-174 
 HV103$02  175-175 
 HV104$02  176-176 
 HV105$02  177-178 
 HV106$02  179-179 
 HV107$02  180-181 
 HV108$02  182-183 
 HV109$02  184-184 
 HV110$02  185-185 
 HV111$02  186-186 
 HV112$02  187-188 
 HV113$02  189-189 
 HV114$02  190-191 
 HV115$02  192-192 
 HV116$02  193-193 
 HV117$02  194-194 
 HV118$02  195-195 
 HVIDX$03  196-197 
 HV101$03  198-199 
 HV102$03  200-200 
 HV103$03  201-201 
 HV104$03  202-202 
 HV105$03  203-204 
 HV106$03  205-205 
 HV107$03  206-207 
 HV108$03  208-209 
 HV109$03  210-210 
 HV110$03  211-211 
 HV111$03  212-212 
 HV112$03  213-214 
 HV113$03  215-215 
 HV114$03  216-217 
 HV115$03  218-218 
 HV116$03  219-219 
 HV117$03  220-220 
 HV118$03  221-221 
 HVIDX$04  222-223 
 HV101$04  224-225 
 HV102$04  226-226 
 HV103$04  227-227 
 HV104$04  228-228 
 HV105$04  229-230 
 HV106$04  231-231 
 HV107$04  232-233 
 HV108$04  234-235 
 HV109$04  236-236 
 HV110$04  237-237 
 HV111$04  238-238 
 HV112$04  239-240 
 HV113$04  241-241 
 HV114$04  242-243 
 HV115$04  244-244 
 HV116$04  245-245 
 HV117$04  246-246 
 HV118$04  247-247 
 HVIDX$05  248-249 
 HV101$05  250-251 
 HV102$05  252-252 
 HV103$05  253-253 
 HV104$05  254-254 
 HV105$05  255-256 
 HV106$05  257-257 
 HV107$05  258-259 
 HV108$05  260-261 
 HV109$05  262-262 
 HV110$05  263-263 
 HV111$05  264-264 
 HV112$05  265-266 
 HV113$05  267-267 
 HV114$05  268-269 
 HV115$05  270-270 
 HV116$05  271-271 
 HV117$05  272-272 
 HV118$05  273-273 
 HVIDX$06  274-275 
 HV101$06  276-277 
 HV102$06  278-278 
 HV103$06  279-279 
 HV104$06  280-280 
 HV105$06  281-282 
 HV106$06  283-283 
 HV107$06  284-285 
 HV108$06  286-287 
 HV109$06  288-288 
 HV110$06  289-289 
 HV111$06  290-290 
 HV112$06  291-292 
 HV113$06  293-293 
 HV114$06  294-295 
 HV115$06  296-296 
 HV116$06  297-297 
 HV117$06  298-298 
 HV118$06  299-299 
 HVIDX$07  300-301 
 HV101$07  302-303 
 HV102$07  304-304 
 HV103$07  305-305 
 HV104$07  306-306 
 HV105$07  307-308 
 HV106$07  309-309 
 HV107$07  310-311 
 HV108$07  312-313 
 HV109$07  314-314 
 HV110$07  315-315 
 HV111$07  316-316 
 HV112$07  317-318 
 HV113$07  319-319 
 HV114$07  320-321 
 HV115$07  322-322 
 HV116$07  323-323 
 HV117$07  324-324 
 HV118$07  325-325 
 HVIDX$08  326-327 
 HV101$08  328-329 
 HV102$08  330-330 
 HV103$08  331-331 
 HV104$08  332-332 
 HV105$08  333-334 
 HV106$08  335-335 
 HV107$08  336-337 
 HV108$08  338-339 
 HV109$08  340-340 
 HV110$08  341-341 
 HV111$08  342-342 
 HV112$08  343-344 
 HV113$08  345-345 
 HV114$08  346-347 
 HV115$08  348-348 
 HV116$08  349-349 
 HV117$08  350-350 
 HV118$08  351-351 
 HVIDX$09  352-353 
 HV101$09  354-355 
 HV102$09  356-356 
 HV103$09  357-357 
 HV104$09  358-358 
 HV105$09  359-360 
 HV106$09  361-361 
 HV107$09  362-363 
 HV108$09  364-365 
 HV109$09  366-366 
 HV110$09  367-367 
 HV111$09  368-368 
 HV112$09  369-370 
 HV113$09  371-371 
 HV114$09  372-373 
 HV115$09  374-374 
 HV116$09  375-375 
 HV117$09  376-376 
 HV118$09  377-377 
 HVIDX$10  378-379 
 HV101$10  380-381 
 HV102$10  382-382 
 HV103$10  383-383 
 HV104$10  384-384 
 HV105$10  385-386 
 HV106$10  387-387 
 HV107$10  388-389 
 HV108$10  390-391 
 HV109$10  392-392 
 HV110$10  393-393 
 HV111$10  394-394 
 HV112$10  395-396 
 HV113$10  397-397 
 HV114$10  398-399 
 HV115$10  400-400 
 HV116$10  401-401 
 HV117$10  402-402 
 HV118$10  403-403 
 HVIDX$11  404-405 
 HV101$11  406-407 
 HV102$11  408-408 
 HV103$11  409-409 
 HV104$11  410-410 
 HV105$11  411-412 
 HV106$11  413-413 
 HV107$11  414-415 
 HV108$11  416-417 
 HV109$11  418-418 
 HV110$11  419-419 
 HV111$11  420-420 
 HV112$11  421-422 
 HV113$11  423-423 
 HV114$11  424-425 
 HV115$11  426-426 
 HV116$11  427-427 
 HV117$11  428-428 
 HV118$11  429-429 
 HVIDX$12  430-431 
 HV101$12  432-433 
 HV102$12  434-434 
 HV103$12  435-435 
 HV104$12  436-436 
 HV105$12  437-438 
 HV106$12  439-439 
 HV107$12  440-441 
 HV108$12  442-443 
 HV109$12  444-444 
 HV110$12  445-445 
 HV111$12  446-446 
 HV112$12  447-448 
 HV113$12  449-449 
 HV114$12  450-451 
 HV115$12  452-452 
 HV116$12  453-453 
 HV117$12  454-454 
 HV118$12  455-455 
 HVIDX$13  456-457 
 HV101$13  458-459 
 HV102$13  460-460 
 HV103$13  461-461 
 HV104$13  462-462 
 HV105$13  463-464 
 HV106$13  465-465 
 HV107$13  466-467 
 HV108$13  468-469 
 HV109$13  470-470 
 HV110$13  471-471 
 HV111$13  472-472 
 HV112$13  473-474 
 HV113$13  475-475 
 HV114$13  476-477 
 HV115$13  478-478 
 HV116$13  479-479 
 HV117$13  480-480 
 HV118$13  481-481 
 HVIDX$14  482-483 
 HV101$14  484-485 
 HV102$14  486-486 
 HV103$14  487-487 
 HV104$14  488-488 
 HV105$14  489-490 
 HV106$14  491-491 
 HV107$14  492-493 
 HV108$14  494-495 
 HV109$14  496-496 
 HV110$14  497-497 
 HV111$14  498-498 
 HV112$14  499-500 
 HV113$14  501-501 
 HV114$14  502-503 
 HV115$14  504-504 
 HV116$14  505-505 
 HV117$14  506-506 
 HV118$14  507-507 
 HVIDX$15  508-509 
 HV101$15  510-511 
 HV102$15  512-512 
 HV103$15  513-513 
 HV104$15  514-514 
 HV105$15  515-516 
 HV106$15  517-517 
 HV107$15  518-519 
 HV108$15  520-521 
 HV109$15  522-522 
 HV110$15  523-523 
 HV111$15  524-524 
 HV112$15  525-526 
 HV113$15  527-527 
 HV114$15  528-529 
 HV115$15  530-530 
 HV116$15  531-531 
 HV117$15  532-532 
 HV118$15  533-533 
 HVIDX$16  534-535 
 HV101$16  536-537 
 HV102$16  538-538 
 HV103$16  539-539 
 HV104$16  540-540 
 HV105$16  541-542 
 HV106$16  543-543 
 HV107$16  544-545 
 HV108$16  546-547 
 HV109$16  548-548 
 HV110$16  549-549 
 HV111$16  550-550 
 HV112$16  551-552 
 HV113$16  553-553 
 HV114$16  554-555 
 HV115$16  556-556 
 HV116$16  557-557 
 HV117$16  558-558 
 HV118$16  559-559 
 HVIDX$17  560-561 
 HV101$17  562-563 
 HV102$17  564-564 
 HV103$17  565-565 
 HV104$17  566-566 
 HV105$17  567-568 
 HV106$17  569-569 
 HV107$17  570-571 
 HV108$17  572-573 
 HV109$17  574-574 
 HV110$17  575-575 
 HV111$17  576-576 
 HV112$17  577-578 
 HV113$17  579-579 
 HV114$17  580-581 
 HV115$17  582-582 
 HV116$17  583-583 
 HV117$17  584-584 
 HV118$17  585-585 
 HVIDX$18  586-587 
 HV101$18  588-589 
 HV102$18  590-590 
 HV103$18  591-591 
 HV104$18  592-592 
 HV105$18  593-594 
 HV106$18  595-595 
 HV107$18  596-597 
 HV108$18  598-599 
 HV109$18  600-600 
 HV110$18  601-601 
 HV111$18  602-602 
 HV112$18  603-604 
 HV113$18  605-605 
 HV114$18  606-607 
 HV115$18  608-608 
 HV116$18  609-609 
 HV117$18  610-610 
 HV118$18  611-611 
 HVIDX$19  612-613 
 HV101$19  614-615 
 HV102$19  616-616 
 HV103$19  617-617 
 HV104$19  618-618 
 HV105$19  619-620 
 HV106$19  621-621 
 HV107$19  622-623 
 HV108$19  624-625 
 HV109$19  626-626 
 HV110$19  627-627 
 HV111$19  628-628 
 HV112$19  629-630 
 HV113$19  631-631 
 HV114$19  632-633 
 HV115$19  634-634 
 HV116$19  635-635 
 HV117$19  636-636 
 HV118$19  637-637 
 HVIDX$20  638-639 
 HV101$20  640-641 
 HV102$20  642-642 
 HV103$20  643-643 
 HV104$20  644-644 
 HV105$20  645-646 
 HV106$20  647-647 
 HV107$20  648-649 
 HV108$20  650-651 
 HV109$20  652-652 
 HV110$20  653-653 
 HV111$20  654-654 
 HV112$20  655-656 
 HV113$20  657-657 
 HV114$20  658-659 
 HV115$20  660-660 
 HV116$20  661-661 
 HV117$20  662-662 
 HV118$20  663-663 
 HVIDX$21  664-665 
 HV101$21  666-667 
 HV102$21  668-668 
 HV103$21  669-669 
 HV104$21  670-670 
 HV105$21  671-672 
 HV106$21  673-673 
 HV107$21  674-675 
 HV108$21  676-677 
 HV109$21  678-678 
 HV110$21  679-679 
 HV111$21  680-680 
 HV112$21  681-682 
 HV113$21  683-683 
 HV114$21  684-685 
 HV115$21  686-686 
 HV116$21  687-687 
 HV117$21  688-688 
 HV118$21  689-689 
 HVIDX$22  690-691 
 HV101$22  692-693 
 HV102$22  694-694 
 HV103$22  695-695 
 HV104$22  696-696 
 HV105$22  697-698 
 HV106$22  699-699 
 HV107$22  700-701 
 HV108$22  702-703 
 HV109$22  704-704 
 HV110$22  705-705 
 HV111$22  706-706 
 HV112$22  707-708 
 HV113$22  709-709 
 HV114$22  710-711 
 HV115$22  712-712 
 HV116$22  713-713 
 HV117$22  714-714 
 HV118$22  715-715 
 HVIDX$23  716-717 
 HV101$23  718-719 
 HV102$23  720-720 
 HV103$23  721-721 
 HV104$23  722-722 
 HV105$23  723-724 
 HV106$23  725-725 
 HV107$23  726-727 
 HV108$23  728-729 
 HV109$23  730-730 
 HV110$23  731-731 
 HV111$23  732-732 
 HV112$23  733-734 
 HV113$23  735-735 
 HV114$23  736-737 
 HV115$23  738-738 
 HV116$23  739-739 
 HV117$23  740-740 
 HV118$23  741-741 
 HVIDX$24  742-743 
 HV101$24  744-745 
 HV102$24  746-746 
 HV103$24  747-747 
 HV104$24  748-748 
 HV105$24  749-750 
 HV106$24  751-751 
 HV107$24  752-753 
 HV108$24  754-755 
 HV109$24  756-756 
 HV110$24  757-757 
 HV111$24  758-758 
 HV112$24  759-760 
 HV113$24  761-761 
 HV114$24  762-763 
 HV115$24  764-764 
 HV116$24  765-765 
 HV117$24  766-766 
 HV118$24  767-767 
 HVIDX$25  768-769 
 HV101$25  770-771 
 HV102$25  772-772 
 HV103$25  773-773 
 HV104$25  774-774 
 HV105$25  775-776 
 HV106$25  777-777 
 HV107$25  778-779 
 HV108$25  780-781 
 HV109$25  782-782 
 HV110$25  783-783 
 HV111$25  784-784 
 HV112$25  785-786 
 HV113$25  787-787 
 HV114$25  788-789 
 HV115$25  790-790 
 HV116$25  791-791 
 HV117$25  792-792 
 HV118$25  793-793 
 HVIDX$26  794-795 
 HV101$26  796-797 
 HV102$26  798-798 
 HV103$26  799-799 
 HV104$26  800-800 
 HV105$26  801-802 
 HV106$26  803-803 
 HV107$26  804-805 
 HV108$26  806-807 
 HV109$26  808-808 
 HV110$26  809-809 
 HV111$26  810-810 
 HV112$26  811-812 
 HV113$26  813-813 
 HV114$26  814-815 
 HV115$26  816-816 
 HV116$26  817-817 
 HV117$26  818-818 
 HV118$26  819-819 
 HVIDX$27  820-821 
 HV101$27  822-823 
 HV102$27  824-824 
 HV103$27  825-825 
 HV104$27  826-826 
 HV105$27  827-828 
 HV106$27  829-829 
 HV107$27  830-831 
 HV108$27  832-833 
 HV109$27  834-834 
 HV110$27  835-835 
 HV111$27  836-836 
 HV112$27  837-838 
 HV113$27  839-839 
 HV114$27  840-841 
 HV115$27  842-842 
 HV116$27  843-843 
 HV117$27  844-844 
 HV118$27  845-845 
 HVIDX$28  846-847 
 HV101$28  848-849 
 HV102$28  850-850 
 HV103$28  851-851 
 HV104$28  852-852 
 HV105$28  853-854 
 HV106$28  855-855 
 HV107$28  856-857 
 HV108$28  858-859 
 HV109$28  860-860 
 HV110$28  861-861 
 HV111$28  862-862 
 HV112$28  863-864 
 HV113$28  865-865 
 HV114$28  866-867 
 HV115$28  868-868 
 HV116$28  869-869 
 HV117$28  870-870 
 HV118$28  871-871 
 SHDISTR   872-873 
 SH20      874-876 
 SH20A     877-879 
 SH25      880-881 
 SH26A     882-882 
 SH26B     883-883 
 SH26C     884-884 
 SH26D     885-885 
 SH26I     886-886 
 SH31      887-887 
 IDXH4$01  888-889 
 SH14$01   890-890 
 SH17$01   891-892 
 IDXH4$02  893-894 
 SH14$02   895-895 
 SH17$02   896-897 
 IDXH4$03  898-899 
 SH14$03   900-900 
 SH17$03   901-902 
 IDXH4$04  903-904 
 SH14$04   905-905 
 SH17$04   906-907 
 IDXH4$05  908-909 
 SH14$05   910-910 
 SH17$05   911-912 
 IDXH4$06  913-914 
 SH14$06   915-915 
 SH17$06   916-917 
 IDXH4$07  918-919 
 SH14$07   920-920 
 SH17$07   921-922 
 IDXH4$08  923-924 
 SH14$08   925-925 
 SH17$08   926-927 
 IDXH4$09  928-929 
 SH14$09   930-930 
 SH17$09   931-932 
 IDXH4$10  933-934 
 SH14$10   935-935 
 SH17$10   936-937 
 IDXH4$11  938-939 
 SH14$11   940-940 
 SH17$11   941-942 
 IDXH4$12  943-944 
 SH14$12   945-945 
 SH17$12   946-947 
 IDXH4$13  948-949 
 SH14$13   950-950 
 SH17$13   951-952 
 IDXH4$14  953-954 
 SH14$14   955-955 
 SH17$14   956-957 
 IDXH4$15  958-959 
 SH14$15   960-960 
 SH17$15   961-962 
 IDXH4$16  963-964 
 SH14$16   965-965 
 SH17$16   966-967 
 IDXH4$17  968-969 
 SH14$17   970-970 
 SH17$17   971-972 
 IDXH4$18  973-974 
 SH14$18   975-975 
 SH17$18   976-977 
 IDXH4$19  978-979 
 SH14$19   980-980 
 SH17$19   981-982 
 IDXH4$20  983-984 
 SH14$20   985-985 
 SH17$20   986-987 
 IDXH4$21  988-989 
 SH14$21   990-990 
 SH17$21   991-992 
 IDXH4$22  993-994 
 SH14$22   995-995 
 SH17$22   996-997 
 IDXH4$23  998-999 
 SH14$23  1000-1000
 SH17$23  1001-1002
 IDXH4$24 1003-1004
 SH14$24  1005-1005
 SH17$24  1006-1007
 IDXH4$25 1008-1009
 SH14$25  1010-1010
 SH17$25  1011-1012
 IDXH4$26 1013-1014
 SH14$26  1015-1015
 SH17$26  1016-1017
 IDXH4$27 1018-1019
 SH14$27  1020-1020
 SH17$27  1021-1022
 IDXH4$28 1023-1024
 SH14$28  1025-1025
 SH17$28  1026-1027
.
VARIABLE LABELS
 HHID     "Case Identification"
/HV000    "Country code and phase"
/HV001    "Cluster number"
/HV002    "Household number"
/HV003    "Respondent's line number"
/HV004    "Ultimate area unit"
/HV005    "Sample weight"
/HV006    "Month of interview"
/HV007    "Year of interview"
/HV008    "Date of interview (CMC)"
/HV009    "Number of household members"
/HV010    "Number of eligible women in HH"
/HV011    "Number of eligible men in HH"
/HV012    "Number of de jure members"
/HV013    "Number of de facto members"
/HV014    "Number of children 5 and under"
/HV015    "Result of household interview"
/HV016    "Day of interview"
/HV017    "Number of visits"
/HV018    "Interviewer identification"
/HV019    "Keyer identification"
/HV020    "Ever-married sample"
/HV021    "Primary sampling unit"
/HV022    "Sample stratum number"
/HV023    "Sample domain"
/HV024    "Region"
/HV025    "Type of place of residence"
/HV026    "Place of residence"
/HV027    "Selection for male/husb. int."
/HV028    "Sample weight for male subsamp"
/HV030    "Field supervisor -NA"
/HV031    "Field editor -NA"
/HV032    "Office editor -NA"
/HV033    "Ultimate area selection prob."
/HV201    "Source of drinking water"
/HV202    "Source of non-drinking water"
/HV203    "Same source of water"
/HV204    "Time to get to water source"
/HV205    "Type of toilet facility"
/HV206    "Has electricity"
/HV207    "Has radio"
/HV208    "Has television"
/HV209    "Has refrigerator -NA"
/HV210    "Has bicycle"
/HV211    "Has motorcycle -NA"
/HV212    "Has car -NA"
/HV213    "Main floor material"
/HV214    "Main wall material"
/HV215    "Main roof material"
/HV216    "Rooms for sleeping"
/HV217    "Relationship structure"
/HV218    "Line number of head of househ."
/HV219    "Sex of head of household"
/HV220    "Age of head of household"
/HV221    "Has telephone -NA"
/HV222    "Type of salt used for cook -NA"
/HVIDX$01 "Line number"
/HV101$01 "Relationship to head"
/HV102$01 "Usual resident"
/HV103$01 "Slept last night"
/HV104$01 "Sex of household member"
/HV105$01 "Age of household members"
/HV106$01 "Highest educational level"
/HV107$01 "Highest year of education"
/HV108$01 "Education in single years"
/HV109$01 "Educational attainment"
/HV110$01 "Member still in school"
/HV111$01 "Mother alive -NA"
/HV112$01 "Mother's line number -NA"
/HV113$01 "Father alive -NA"
/HV114$01 "Father's line number -NA"
/HV115$01 "Current marital status -NA"
/HV116$01 "Currently, formerly, never m."
/HV117$01 "Eligibility for female intview"
/HV118$01 "Eligibility for male interview"
/HVIDX$02 "Line number"
/HV101$02 "Relationship to head"
/HV102$02 "Usual resident"
/HV103$02 "Slept last night"
/HV104$02 "Sex of household member"
/HV105$02 "Age of household members"
/HV106$02 "Highest educational level"
/HV107$02 "Highest year of education"
/HV108$02 "Education in single years"
/HV109$02 "Educational attainment"
/HV110$02 "Member still in school"
/HV111$02 "Mother alive -NA"
/HV112$02 "Mother's line number -NA"
/HV113$02 "Father alive -NA"
/HV114$02 "Father's line number -NA"
/HV115$02 "Current marital status -NA"
/HV116$02 "Currently, formerly, never m."
/HV117$02 "Eligibility for female intview"
/HV118$02 "Eligibility for male interview"
/HVIDX$03 "Line number"
/HV101$03 "Relationship to head"
/HV102$03 "Usual resident"
/HV103$03 "Slept last night"
/HV104$03 "Sex of household member"
/HV105$03 "Age of household members"
/HV106$03 "Highest educational level"
/HV107$03 "Highest year of education"
/HV108$03 "Education in single years"
/HV109$03 "Educational attainment"
/HV110$03 "Member still in school"
/HV111$03 "Mother alive -NA"
/HV112$03 "Mother's line number -NA"
/HV113$03 "Father alive -NA"
/HV114$03 "Father's line number -NA"
/HV115$03 "Current marital status -NA"
/HV116$03 "Currently, formerly, never m."
/HV117$03 "Eligibility for female intview"
/HV118$03 "Eligibility for male interview"
/HVIDX$04 "Line number"
/HV101$04 "Relationship to head"
/HV102$04 "Usual resident"
/HV103$04 "Slept last night"
/HV104$04 "Sex of household member"
/HV105$04 "Age of household members"
/HV106$04 "Highest educational level"
/HV107$04 "Highest year of education"
/HV108$04 "Education in single years"
/HV109$04 "Educational attainment"
/HV110$04 "Member still in school"
/HV111$04 "Mother alive -NA"
/HV112$04 "Mother's line number -NA"
/HV113$04 "Father alive -NA"
/HV114$04 "Father's line number -NA"
/HV115$04 "Current marital status -NA"
/HV116$04 "Currently, formerly, never m."
/HV117$04 "Eligibility for female intview"
/HV118$04 "Eligibility for male interview"
/HVIDX$05 "Line number"
/HV101$05 "Relationship to head"
/HV102$05 "Usual resident"
/HV103$05 "Slept last night"
/HV104$05 "Sex of household member"
/HV105$05 "Age of household members"
/HV106$05 "Highest educational level"
/HV107$05 "Highest year of education"
/HV108$05 "Education in single years"
/HV109$05 "Educational attainment"
/HV110$05 "Member still in school"
/HV111$05 "Mother alive -NA"
/HV112$05 "Mother's line number -NA"
/HV113$05 "Father alive -NA"
/HV114$05 "Father's line number -NA"
/HV115$05 "Current marital status -NA"
/HV116$05 "Currently, formerly, never m."
/HV117$05 "Eligibility for female intview"
/HV118$05 "Eligibility for male interview"
/HVIDX$06 "Line number"
/HV101$06 "Relationship to head"
/HV102$06 "Usual resident"
/HV103$06 "Slept last night"
/HV104$06 "Sex of household member"
/HV105$06 "Age of household members"
/HV106$06 "Highest educational level"
/HV107$06 "Highest year of education"
/HV108$06 "Education in single years"
/HV109$06 "Educational attainment"
/HV110$06 "Member still in school"
/HV111$06 "Mother alive -NA"
/HV112$06 "Mother's line number -NA"
/HV113$06 "Father alive -NA"
/HV114$06 "Father's line number -NA"
/HV115$06 "Current marital status -NA"
/HV116$06 "Currently, formerly, never m."
/HV117$06 "Eligibility for female intview"
/HV118$06 "Eligibility for male interview"
/HVIDX$07 "Line number"
/HV101$07 "Relationship to head"
/HV102$07 "Usual resident"
/HV103$07 "Slept last night"
/HV104$07 "Sex of household member"
/HV105$07 "Age of household members"
/HV106$07 "Highest educational level"
/HV107$07 "Highest year of education"
/HV108$07 "Education in single years"
/HV109$07 "Educational attainment"
/HV110$07 "Member still in school"
/HV111$07 "Mother alive -NA"
/HV112$07 "Mother's line number -NA"
/HV113$07 "Father alive -NA"
/HV114$07 "Father's line number -NA"
/HV115$07 "Current marital status -NA"
/HV116$07 "Currently, formerly, never m."
/HV117$07 "Eligibility for female intview"
/HV118$07 "Eligibility for male interview"
/HVIDX$08 "Line number"
/HV101$08 "Relationship to head"
/HV102$08 "Usual resident"
/HV103$08 "Slept last night"
/HV104$08 "Sex of household member"
/HV105$08 "Age of household members"
/HV106$08 "Highest educational level"
/HV107$08 "Highest year of education"
/HV108$08 "Education in single years"
/HV109$08 "Educational attainment"
/HV110$08 "Member still in school"
/HV111$08 "Mother alive -NA"
/HV112$08 "Mother's line number -NA"
/HV113$08 "Father alive -NA"
/HV114$08 "Father's line number -NA"
/HV115$08 "Current marital status -NA"
/HV116$08 "Currently, formerly, never m."
/HV117$08 "Eligibility for female intview"
/HV118$08 "Eligibility for male interview"
/HVIDX$09 "Line number"
/HV101$09 "Relationship to head"
/HV102$09 "Usual resident"
/HV103$09 "Slept last night"
/HV104$09 "Sex of household member"
/HV105$09 "Age of household members"
/HV106$09 "Highest educational level"
/HV107$09 "Highest year of education"
/HV108$09 "Education in single years"
/HV109$09 "Educational attainment"
/HV110$09 "Member still in school"
/HV111$09 "Mother alive -NA"
/HV112$09 "Mother's line number -NA"
/HV113$09 "Father alive -NA"
/HV114$09 "Father's line number -NA"
/HV115$09 "Current marital status -NA"
/HV116$09 "Currently, formerly, never m."
/HV117$09 "Eligibility for female intview"
/HV118$09 "Eligibility for male interview"
/HVIDX$10 "Line number"
/HV101$10 "Relationship to head"
/HV102$10 "Usual resident"
/HV103$10 "Slept last night"
/HV104$10 "Sex of household member"
/HV105$10 "Age of household members"
/HV106$10 "Highest educational level"
/HV107$10 "Highest year of education"
/HV108$10 "Education in single years"
/HV109$10 "Educational attainment"
/HV110$10 "Member still in school"
/HV111$10 "Mother alive -NA"
/HV112$10 "Mother's line number -NA"
/HV113$10 "Father alive -NA"
/HV114$10 "Father's line number -NA"
/HV115$10 "Current marital status -NA"
/HV116$10 "Currently, formerly, never m."
/HV117$10 "Eligibility for female intview"
/HV118$10 "Eligibility for male interview"
/HVIDX$11 "Line number"
/HV101$11 "Relationship to head"
/HV102$11 "Usual resident"
/HV103$11 "Slept last night"
/HV104$11 "Sex of household member"
/HV105$11 "Age of household members"
/HV106$11 "Highest educational level"
/HV107$11 "Highest year of education"
/HV108$11 "Education in single years"
/HV109$11 "Educational attainment"
/HV110$11 "Member still in school"
/HV111$11 "Mother alive -NA"
/HV112$11 "Mother's line number -NA"
/HV113$11 "Father alive -NA"
/HV114$11 "Father's line number -NA"
/HV115$11 "Current marital status -NA"
/HV116$11 "Currently, formerly, never m."
/HV117$11 "Eligibility for female intview"
/HV118$11 "Eligibility for male interview"
/HVIDX$12 "Line number"
/HV101$12 "Relationship to head"
/HV102$12 "Usual resident"
/HV103$12 "Slept last night"
/HV104$12 "Sex of household member"
/HV105$12 "Age of household members"
/HV106$12 "Highest educational level"
/HV107$12 "Highest year of education"
/HV108$12 "Education in single years"
/HV109$12 "Educational attainment"
/HV110$12 "Member still in school"
/HV111$12 "Mother alive -NA"
/HV112$12 "Mother's line number -NA"
/HV113$12 "Father alive -NA"
/HV114$12 "Father's line number -NA"
/HV115$12 "Current marital status -NA"
/HV116$12 "Currently, formerly, never m."
/HV117$12 "Eligibility for female intview"
/HV118$12 "Eligibility for male interview"
/HVIDX$13 "Line number"
/HV101$13 "Relationship to head"
/HV102$13 "Usual resident"
/HV103$13 "Slept last night"
/HV104$13 "Sex of household member"
/HV105$13 "Age of household members"
/HV106$13 "Highest educational level"
/HV107$13 "Highest year of education"
/HV108$13 "Education in single years"
/HV109$13 "Educational attainment"
/HV110$13 "Member still in school"
/HV111$13 "Mother alive -NA"
/HV112$13 "Mother's line number -NA"
/HV113$13 "Father alive -NA"
/HV114$13 "Father's line number -NA"
/HV115$13 "Current marital status -NA"
/HV116$13 "Currently, formerly, never m."
/HV117$13 "Eligibility for female intview"
/HV118$13 "Eligibility for male interview"
/HVIDX$14 "Line number"
/HV101$14 "Relationship to head"
/HV102$14 "Usual resident"
/HV103$14 "Slept last night"
/HV104$14 "Sex of household member"
/HV105$14 "Age of household members"
/HV106$14 "Highest educational level"
/HV107$14 "Highest year of education"
/HV108$14 "Education in single years"
/HV109$14 "Educational attainment"
/HV110$14 "Member still in school"
/HV111$14 "Mother alive -NA"
/HV112$14 "Mother's line number -NA"
/HV113$14 "Father alive -NA"
/HV114$14 "Father's line number -NA"
/HV115$14 "Current marital status -NA"
/HV116$14 "Currently, formerly, never m."
/HV117$14 "Eligibility for female intview"
/HV118$14 "Eligibility for male interview"
/HVIDX$15 "Line number"
/HV101$15 "Relationship to head"
/HV102$15 "Usual resident"
/HV103$15 "Slept last night"
/HV104$15 "Sex of household member"
/HV105$15 "Age of household members"
/HV106$15 "Highest educational level"
/HV107$15 "Highest year of education"
/HV108$15 "Education in single years"
/HV109$15 "Educational attainment"
/HV110$15 "Member still in school"
/HV111$15 "Mother alive -NA"
/HV112$15 "Mother's line number -NA"
/HV113$15 "Father alive -NA"
/HV114$15 "Father's line number -NA"
/HV115$15 "Current marital status -NA"
/HV116$15 "Currently, formerly, never m."
/HV117$15 "Eligibility for female intview"
/HV118$15 "Eligibility for male interview"
/HVIDX$16 "Line number"
/HV101$16 "Relationship to head"
/HV102$16 "Usual resident"
/HV103$16 "Slept last night"
/HV104$16 "Sex of household member"
/HV105$16 "Age of household members"
/HV106$16 "Highest educational level"
/HV107$16 "Highest year of education"
/HV108$16 "Education in single years"
/HV109$16 "Educational attainment"
/HV110$16 "Member still in school"
/HV111$16 "Mother alive -NA"
/HV112$16 "Mother's line number -NA"
/HV113$16 "Father alive -NA"
/HV114$16 "Father's line number -NA"
/HV115$16 "Current marital status -NA"
/HV116$16 "Currently, formerly, never m."
/HV117$16 "Eligibility for female intview"
/HV118$16 "Eligibility for male interview"
/HVIDX$17 "Line number"
/HV101$17 "Relationship to head"
/HV102$17 "Usual resident"
/HV103$17 "Slept last night"
/HV104$17 "Sex of household member"
/HV105$17 "Age of household members"
/HV106$17 "Highest educational level"
/HV107$17 "Highest year of education"
/HV108$17 "Education in single years"
/HV109$17 "Educational attainment"
/HV110$17 "Member still in school"
/HV111$17 "Mother alive -NA"
/HV112$17 "Mother's line number -NA"
/HV113$17 "Father alive -NA"
/HV114$17 "Father's line number -NA"
/HV115$17 "Current marital status -NA"
/HV116$17 "Currently, formerly, never m."
/HV117$17 "Eligibility for female intview"
/HV118$17 "Eligibility for male interview"
/HVIDX$18 "Line number"
/HV101$18 "Relationship to head"
/HV102$18 "Usual resident"
/HV103$18 "Slept last night"
/HV104$18 "Sex of household member"
/HV105$18 "Age of household members"
/HV106$18 "Highest educational level"
/HV107$18 "Highest year of education"
/HV108$18 "Education in single years"
/HV109$18 "Educational attainment"
/HV110$18 "Member still in school"
/HV111$18 "Mother alive -NA"
/HV112$18 "Mother's line number -NA"
/HV113$18 "Father alive -NA"
/HV114$18 "Father's line number -NA"
/HV115$18 "Current marital status -NA"
/HV116$18 "Currently, formerly, never m."
/HV117$18 "Eligibility for female intview"
/HV118$18 "Eligibility for male interview"
/HVIDX$19 "Line number"
/HV101$19 "Relationship to head"
/HV102$19 "Usual resident"
/HV103$19 "Slept last night"
/HV104$19 "Sex of household member"
/HV105$19 "Age of household members"
/HV106$19 "Highest educational level"
/HV107$19 "Highest year of education"
/HV108$19 "Education in single years"
/HV109$19 "Educational attainment"
/HV110$19 "Member still in school"
/HV111$19 "Mother alive -NA"
/HV112$19 "Mother's line number -NA"
/HV113$19 "Father alive -NA"
/HV114$19 "Father's line number -NA"
/HV115$19 "Current marital status -NA"
/HV116$19 "Currently, formerly, never m."
/HV117$19 "Eligibility for female intview"
/HV118$19 "Eligibility for male interview"
/HVIDX$20 "Line number"
/HV101$20 "Relationship to head"
/HV102$20 "Usual resident"
/HV103$20 "Slept last night"
/HV104$20 "Sex of household member"
/HV105$20 "Age of household members"
/HV106$20 "Highest educational level"
/HV107$20 "Highest year of education"
/HV108$20 "Education in single years"
/HV109$20 "Educational attainment"
/HV110$20 "Member still in school"
/HV111$20 "Mother alive -NA"
/HV112$20 "Mother's line number -NA"
/HV113$20 "Father alive -NA"
/HV114$20 "Father's line number -NA"
/HV115$20 "Current marital status -NA"
/HV116$20 "Currently, formerly, never m."
/HV117$20 "Eligibility for female intview"
/HV118$20 "Eligibility for male interview"
/HVIDX$21 "Line number"
/HV101$21 "Relationship to head"
/HV102$21 "Usual resident"
/HV103$21 "Slept last night"
/HV104$21 "Sex of household member"
/HV105$21 "Age of household members"
/HV106$21 "Highest educational level"
/HV107$21 "Highest year of education"
/HV108$21 "Education in single years"
/HV109$21 "Educational attainment"
/HV110$21 "Member still in school"
/HV111$21 "Mother alive -NA"
/HV112$21 "Mother's line number -NA"
/HV113$21 "Father alive -NA"
/HV114$21 "Father's line number -NA"
/HV115$21 "Current marital status -NA"
/HV116$21 "Currently, formerly, never m."
/HV117$21 "Eligibility for female intview"
/HV118$21 "Eligibility for male interview"
/HVIDX$22 "Line number"
/HV101$22 "Relationship to head"
/HV102$22 "Usual resident"
/HV103$22 "Slept last night"
/HV104$22 "Sex of household member"
/HV105$22 "Age of household members"
/HV106$22 "Highest educational level"
/HV107$22 "Highest year of education"
/HV108$22 "Education in single years"
/HV109$22 "Educational attainment"
/HV110$22 "Member still in school"
/HV111$22 "Mother alive -NA"
/HV112$22 "Mother's line number -NA"
/HV113$22 "Father alive -NA"
/HV114$22 "Father's line number -NA"
/HV115$22 "Current marital status -NA"
/HV116$22 "Currently, formerly, never m."
/HV117$22 "Eligibility for female intview"
/HV118$22 "Eligibility for male interview"
/HVIDX$23 "Line number"
/HV101$23 "Relationship to head"
/HV102$23 "Usual resident"
/HV103$23 "Slept last night"
/HV104$23 "Sex of household member"
/HV105$23 "Age of household members"
/HV106$23 "Highest educational level"
/HV107$23 "Highest year of education"
/HV108$23 "Education in single years"
/HV109$23 "Educational attainment"
/HV110$23 "Member still in school"
/HV111$23 "Mother alive -NA"
/HV112$23 "Mother's line number -NA"
/HV113$23 "Father alive -NA"
/HV114$23 "Father's line number -NA"
/HV115$23 "Current marital status -NA"
/HV116$23 "Currently, formerly, never m."
/HV117$23 "Eligibility for female intview"
/HV118$23 "Eligibility for male interview"
/HVIDX$24 "Line number"
/HV101$24 "Relationship to head"
/HV102$24 "Usual resident"
/HV103$24 "Slept last night"
/HV104$24 "Sex of household member"
/HV105$24 "Age of household members"
/HV106$24 "Highest educational level"
/HV107$24 "Highest year of education"
/HV108$24 "Education in single years"
/HV109$24 "Educational attainment"
/HV110$24 "Member still in school"
/HV111$24 "Mother alive -NA"
/HV112$24 "Mother's line number -NA"
/HV113$24 "Father alive -NA"
/HV114$24 "Father's line number -NA"
/HV115$24 "Current marital status -NA"
/HV116$24 "Currently, formerly, never m."
/HV117$24 "Eligibility for female intview"
/HV118$24 "Eligibility for male interview"
/HVIDX$25 "Line number"
/HV101$25 "Relationship to head"
/HV102$25 "Usual resident"
/HV103$25 "Slept last night"
/HV104$25 "Sex of household member"
/HV105$25 "Age of household members"
/HV106$25 "Highest educational level"
/HV107$25 "Highest year of education"
/HV108$25 "Education in single years"
/HV109$25 "Educational attainment"
/HV110$25 "Member still in school"
/HV111$25 "Mother alive -NA"
/HV112$25 "Mother's line number -NA"
/HV113$25 "Father alive -NA"
/HV114$25 "Father's line number -NA"
/HV115$25 "Current marital status -NA"
/HV116$25 "Currently, formerly, never m."
/HV117$25 "Eligibility for female intview"
/HV118$25 "Eligibility for male interview"
/HVIDX$26 "Line number"
/HV101$26 "Relationship to head"
/HV102$26 "Usual resident"
/HV103$26 "Slept last night"
/HV104$26 "Sex of household member"
/HV105$26 "Age of household members"
/HV106$26 "Highest educational level"
/HV107$26 "Highest year of education"
/HV108$26 "Education in single years"
/HV109$26 "Educational attainment"
/HV110$26 "Member still in school"
/HV111$26 "Mother alive -NA"
/HV112$26 "Mother's line number -NA"
/HV113$26 "Father alive -NA"
/HV114$26 "Father's line number -NA"
/HV115$26 "Current marital status -NA"
/HV116$26 "Currently, formerly, never m."
/HV117$26 "Eligibility for female intview"
/HV118$26 "Eligibility for male interview"
/HVIDX$27 "Line number"
/HV101$27 "Relationship to head"
/HV102$27 "Usual resident"
/HV103$27 "Slept last night"
/HV104$27 "Sex of household member"
/HV105$27 "Age of household members"
/HV106$27 "Highest educational level"
/HV107$27 "Highest year of education"
/HV108$27 "Education in single years"
/HV109$27 "Educational attainment"
/HV110$27 "Member still in school"
/HV111$27 "Mother alive -NA"
/HV112$27 "Mother's line number -NA"
/HV113$27 "Father alive -NA"
/HV114$27 "Father's line number -NA"
/HV115$27 "Current marital status -NA"
/HV116$27 "Currently, formerly, never m."
/HV117$27 "Eligibility for female intview"
/HV118$27 "Eligibility for male interview"
/HVIDX$28 "Line number"
/HV101$28 "Relationship to head"
/HV102$28 "Usual resident"
/HV103$28 "Slept last night"
/HV104$28 "Sex of household member"
/HV105$28 "Age of household members"
/HV106$28 "Highest educational level"
/HV107$28 "Highest year of education"
/HV108$28 "Education in single years"
/HV109$28 "Educational attainment"
/HV110$28 "Member still in school"
/HV111$28 "Mother alive -NA"
/HV112$28 "Mother's line number -NA"
/HV113$28 "Father alive -NA"
/HV114$28 "Father's line number -NA"
/HV115$28 "Current marital status -NA"
/HV116$28 "Currently, formerly, never m."
/HV117$28 "Eligibility for female intview"
/HV118$28 "Eligibility for male interview"
/SHDISTR  "District of residence"
/SH20     "Time to get to water source"
/SH20A    "Time to wait to get water:mins"
/SH25     "Toilet facility : children"
/SH26A    "Almirah"
/SH26B    "Table/chair/bench"
/SH26C    "Watch/clock"
/SH26D    "Cot/bed"
/SH26I    "Agricultural land"
/SH31     "Urban slum"
/IDXH4$01 "Index to household schedule"
/SH14$01  "Works for money"
/SH17$01  "Husbands line number"
/IDXH4$02 "Index to household schedule"
/SH14$02  "Works for money"
/SH17$02  "Husbands line number"
/IDXH4$03 "Index to household schedule"
/SH14$03  "Works for money"
/SH17$03  "Husbands line number"
/IDXH4$04 "Index to household schedule"
/SH14$04  "Works for money"
/SH17$04  "Husbands line number"
/IDXH4$05 "Index to household schedule"
/SH14$05  "Works for money"
/SH17$05  "Husbands line number"
/IDXH4$06 "Index to household schedule"
/SH14$06  "Works for money"
/SH17$06  "Husbands line number"
/IDXH4$07 "Index to household schedule"
/SH14$07  "Works for money"
/SH17$07  "Husbands line number"
/IDXH4$08 "Index to household schedule"
/SH14$08  "Works for money"
/SH17$08  "Husbands line number"
/IDXH4$09 "Index to household schedule"
/SH14$09  "Works for money"
/SH17$09  "Husbands line number"
/IDXH4$10 "Index to household schedule"
/SH14$10  "Works for money"
/SH17$10  "Husbands line number"
/IDXH4$11 "Index to household schedule"
/SH14$11  "Works for money"
/SH17$11  "Husbands line number"
/IDXH4$12 "Index to household schedule"
/SH14$12  "Works for money"
/SH17$12  "Husbands line number"
/IDXH4$13 "Index to household schedule"
/SH14$13  "Works for money"
/SH17$13  "Husbands line number"
/IDXH4$14 "Index to household schedule"
/SH14$14  "Works for money"
/SH17$14  "Husbands line number"
/IDXH4$15 "Index to household schedule"
/SH14$15  "Works for money"
/SH17$15  "Husbands line number"
/IDXH4$16 "Index to household schedule"
/SH14$16  "Works for money"
/SH17$16  "Husbands line number"
/IDXH4$17 "Index to household schedule"
/SH14$17  "Works for money"
/SH17$17  "Husbands line number"
/IDXH4$18 "Index to household schedule"
/SH14$18  "Works for money"
/SH17$18  "Husbands line number"
/IDXH4$19 "Index to household schedule"
/SH14$19  "Works for money"
/SH17$19  "Husbands line number"
/IDXH4$20 "Index to household schedule"
/SH14$20  "Works for money"
/SH17$20  "Husbands line number"
/IDXH4$21 "Index to household schedule"
/SH14$21  "Works for money"
/SH17$21  "Husbands line number"
/IDXH4$22 "Index to household schedule"
/SH14$22  "Works for money"
/SH17$22  "Husbands line number"
/IDXH4$23 "Index to household schedule"
/SH14$23  "Works for money"
/SH17$23  "Husbands line number"
/IDXH4$24 "Index to household schedule"
/SH14$24  "Works for money"
/SH17$24  "Husbands line number"
/IDXH4$25 "Index to household schedule"
/SH14$25  "Works for money"
/SH17$25  "Husbands line number"
/IDXH4$26 "Index to household schedule"
/SH14$26  "Works for money"
/SH17$26  "Husbands line number"
/IDXH4$27 "Index to household schedule"
/SH14$27  "Works for money"
/SH17$27  "Husbands line number"
/IDXH4$28 "Index to household schedule"
/SH14$28  "Works for money"
/SH17$28  "Husbands line number"
.
MISSING VALUE
 HV018    (999)
/HV019    (99)
/HV026    (9)
/HV030    (99)
/HV031    (99)
/HV032    (99)
/HV201    (99)
/HV202    (99)
/HV203    (9)
/HV204    (999)
/HV205    (99)
/HV206    (9)
/HV207    (9)
/HV208    (9)
/HV209    (9)
/HV210    (9)
/HV211    (9)
/HV212    (9)
/HV213    (99)
/HV214    (99)
/HV215    (99)
/HV216    (99)
/HV219    (9)
/HV220    (99)
/HV221    (9)
/HV222    (99)
/HV101$01 (99)
/HV102$01 (9)
/HV103$01 (9)
/HV104$01 (9)
/HV105$01 (99)
/HV106$01 (9)
/HV107$01 (99)
/HV108$01 (99)
/HV109$01 (9)
/HV110$01 (9)
/HV111$01 (9)
/HV112$01 (99)
/HV113$01 (9)
/HV114$01 (99)
/HV115$01 (9)
/HV116$01 (9)
/HV101$02 (99)
/HV102$02 (9)
/HV103$02 (9)
/HV104$02 (9)
/HV105$02 (99)
/HV106$02 (9)
/HV107$02 (99)
/HV108$02 (99)
/HV109$02 (9)
/HV110$02 (9)
/HV111$02 (9)
/HV112$02 (99)
/HV113$02 (9)
/HV114$02 (99)
/HV115$02 (9)
/HV116$02 (9)
/HV101$03 (99)
/HV102$03 (9)
/HV103$03 (9)
/HV104$03 (9)
/HV105$03 (99)
/HV106$03 (9)
/HV107$03 (99)
/HV108$03 (99)
/HV109$03 (9)
/HV110$03 (9)
/HV111$03 (9)
/HV112$03 (99)
/HV113$03 (9)
/HV114$03 (99)
/HV115$03 (9)
/HV116$03 (9)
/HV101$04 (99)
/HV102$04 (9)
/HV103$04 (9)
/HV104$04 (9)
/HV105$04 (99)
/HV106$04 (9)
/HV107$04 (99)
/HV108$04 (99)
/HV109$04 (9)
/HV110$04 (9)
/HV111$04 (9)
/HV112$04 (99)
/HV113$04 (9)
/HV114$04 (99)
/HV115$04 (9)
/HV116$04 (9)
/HV101$05 (99)
/HV102$05 (9)
/HV103$05 (9)
/HV104$05 (9)
/HV105$05 (99)
/HV106$05 (9)
/HV107$05 (99)
/HV108$05 (99)
/HV109$05 (9)
/HV110$05 (9)
/HV111$05 (9)
/HV112$05 (99)
/HV113$05 (9)
/HV114$05 (99)
/HV115$05 (9)
/HV116$05 (9)
/HV101$06 (99)
/HV102$06 (9)
/HV103$06 (9)
/HV104$06 (9)
/HV105$06 (99)
/HV106$06 (9)
/HV107$06 (99)
/HV108$06 (99)
/HV109$06 (9)
/HV110$06 (9)
/HV111$06 (9)
/HV112$06 (99)
/HV113$06 (9)
/HV114$06 (99)
/HV115$06 (9)
/HV116$06 (9)
/HV101$07 (99)
/HV102$07 (9)
/HV103$07 (9)
/HV104$07 (9)
/HV105$07 (99)
/HV106$07 (9)
/HV107$07 (99)
/HV108$07 (99)
/HV109$07 (9)
/HV110$07 (9)
/HV111$07 (9)
/HV112$07 (99)
/HV113$07 (9)
/HV114$07 (99)
/HV115$07 (9)
/HV116$07 (9)
/HV101$08 (99)
/HV102$08 (9)
/HV103$08 (9)
/HV104$08 (9)
/HV105$08 (99)
/HV106$08 (9)
/HV107$08 (99)
/HV108$08 (99)
/HV109$08 (9)
/HV110$08 (9)
/HV111$08 (9)
/HV112$08 (99)
/HV113$08 (9)
/HV114$08 (99)
/HV115$08 (9)
/HV116$08 (9)
/HV101$09 (99)
/HV102$09 (9)
/HV103$09 (9)
/HV104$09 (9)
/HV105$09 (99)
/HV106$09 (9)
/HV107$09 (99)
/HV108$09 (99)
/HV109$09 (9)
/HV110$09 (9)
/HV111$09 (9)
/HV112$09 (99)
/HV113$09 (9)
/HV114$09 (99)
/HV115$09 (9)
/HV116$09 (9)
/HV101$10 (99)
/HV102$10 (9)
/HV103$10 (9)
/HV104$10 (9)
/HV105$10 (99)
/HV106$10 (9)
/HV107$10 (99)
/HV108$10 (99)
/HV109$10 (9)
/HV110$10 (9)
/HV111$10 (9)
/HV112$10 (99)
/HV113$10 (9)
/HV114$10 (99)
/HV115$10 (9)
/HV116$10 (9)
/HV101$11 (99)
/HV102$11 (9)
/HV103$11 (9)
/HV104$11 (9)
/HV105$11 (99)
/HV106$11 (9)
/HV107$11 (99)
/HV108$11 (99)
/HV109$11 (9)
/HV110$11 (9)
/HV111$11 (9)
/HV112$11 (99)
/HV113$11 (9)
/HV114$11 (99)
/HV115$11 (9)
/HV116$11 (9)
/HV101$12 (99)
/HV102$12 (9)
/HV103$12 (9)
/HV104$12 (9)
/HV105$12 (99)
/HV106$12 (9)
/HV107$12 (99)
/HV108$12 (99)
/HV109$12 (9)
/HV110$12 (9)
/HV111$12 (9)
/HV112$12 (99)
/HV113$12 (9)
/HV114$12 (99)
/HV115$12 (9)
/HV116$12 (9)
/HV101$13 (99)
/HV102$13 (9)
/HV103$13 (9)
/HV104$13 (9)
/HV105$13 (99)
/HV106$13 (9)
/HV107$13 (99)
/HV108$13 (99)
/HV109$13 (9)
/HV110$13 (9)
/HV111$13 (9)
/HV112$13 (99)
/HV113$13 (9)
/HV114$13 (99)
/HV115$13 (9)
/HV116$13 (9)
/HV101$14 (99)
/HV102$14 (9)
/HV103$14 (9)
/HV104$14 (9)
/HV105$14 (99)
/HV106$14 (9)
/HV107$14 (99)
/HV108$14 (99)
/HV109$14 (9)
/HV110$14 (9)
/HV111$14 (9)
/HV112$14 (99)
/HV113$14 (9)
/HV114$14 (99)
/HV115$14 (9)
/HV116$14 (9)
/HV101$15 (99)
/HV102$15 (9)
/HV103$15 (9)
/HV104$15 (9)
/HV105$15 (99)
/HV106$15 (9)
/HV107$15 (99)
/HV108$15 (99)
/HV109$15 (9)
/HV110$15 (9)
/HV111$15 (9)
/HV112$15 (99)
/HV113$15 (9)
/HV114$15 (99)
/HV115$15 (9)
/HV116$15 (9)
/HV101$16 (99)
/HV102$16 (9)
/HV103$16 (9)
/HV104$16 (9)
/HV105$16 (99)
/HV106$16 (9)
/HV107$16 (99)
/HV108$16 (99)
/HV109$16 (9)
/HV110$16 (9)
/HV111$16 (9)
/HV112$16 (99)
/HV113$16 (9)
/HV114$16 (99)
/HV115$16 (9)
/HV116$16 (9)
/HV101$17 (99)
/HV102$17 (9)
/HV103$17 (9)
/HV104$17 (9)
/HV105$17 (99)
/HV106$17 (9)
/HV107$17 (99)
/HV108$17 (99)
/HV109$17 (9)
/HV110$17 (9)
/HV111$17 (9)
/HV112$17 (99)
/HV113$17 (9)
/HV114$17 (99)
/HV115$17 (9)
/HV116$17 (9)
/HV101$18 (99)
/HV102$18 (9)
/HV103$18 (9)
/HV104$18 (9)
/HV105$18 (99)
/HV106$18 (9)
/HV107$18 (99)
/HV108$18 (99)
/HV109$18 (9)
/HV110$18 (9)
/HV111$18 (9)
/HV112$18 (99)
/HV113$18 (9)
/HV114$18 (99)
/HV115$18 (9)
/HV116$18 (9)
/HV101$19 (99)
/HV102$19 (9)
/HV103$19 (9)
/HV104$19 (9)
/HV105$19 (99)
/HV106$19 (9)
/HV107$19 (99)
/HV108$19 (99)
/HV109$19 (9)
/HV110$19 (9)
/HV111$19 (9)
/HV112$19 (99)
/HV113$19 (9)
/HV114$19 (99)
/HV115$19 (9)
/HV116$19 (9)
/HV101$20 (99)
/HV102$20 (9)
/HV103$20 (9)
/HV104$20 (9)
/HV105$20 (99)
/HV106$20 (9)
/HV107$20 (99)
/HV108$20 (99)
/HV109$20 (9)
/HV110$20 (9)
/HV111$20 (9)
/HV112$20 (99)
/HV113$20 (9)
/HV114$20 (99)
/HV115$20 (9)
/HV116$20 (9)
/HV101$21 (99)
/HV102$21 (9)
/HV103$21 (9)
/HV104$21 (9)
/HV105$21 (99)
/HV106$21 (9)
/HV107$21 (99)
/HV108$21 (99)
/HV109$21 (9)
/HV110$21 (9)
/HV111$21 (9)
/HV112$21 (99)
/HV113$21 (9)
/HV114$21 (99)
/HV115$21 (9)
/HV116$21 (9)
/HV101$22 (99)
/HV102$22 (9)
/HV103$22 (9)
/HV104$22 (9)
/HV105$22 (99)
/HV106$22 (9)
/HV107$22 (99)
/HV108$22 (99)
/HV109$22 (9)
/HV110$22 (9)
/HV111$22 (9)
/HV112$22 (99)
/HV113$22 (9)
/HV114$22 (99)
/HV115$22 (9)
/HV116$22 (9)
/HV101$23 (99)
/HV102$23 (9)
/HV103$23 (9)
/HV104$23 (9)
/HV105$23 (99)
/HV106$23 (9)
/HV107$23 (99)
/HV108$23 (99)
/HV109$23 (9)
/HV110$23 (9)
/HV111$23 (9)
/HV112$23 (99)
/HV113$23 (9)
/HV114$23 (99)
/HV115$23 (9)
/HV116$23 (9)
/HV101$24 (99)
/HV102$24 (9)
/HV103$24 (9)
/HV104$24 (9)
/HV105$24 (99)
/HV106$24 (9)
/HV107$24 (99)
/HV108$24 (99)
/HV109$24 (9)
/HV110$24 (9)
/HV111$24 (9)
/HV112$24 (99)
/HV113$24 (9)
/HV114$24 (99)
/HV115$24 (9)
/HV116$24 (9)
/HV101$25 (99)
/HV102$25 (9)
/HV103$25 (9)
/HV104$25 (9)
/HV105$25 (99)
/HV106$25 (9)
/HV107$25 (99)
/HV108$25 (99)
/HV109$25 (9)
/HV110$25 (9)
/HV111$25 (9)
/HV112$25 (99)
/HV113$25 (9)
/HV114$25 (99)
/HV115$25 (9)
/HV116$25 (9)
/HV101$26 (99)
/HV102$26 (9)
/HV103$26 (9)
/HV104$26 (9)
/HV105$26 (99)
/HV106$26 (9)
/HV107$26 (99)
/HV108$26 (99)
/HV109$26 (9)
/HV110$26 (9)
/HV111$26 (9)
/HV112$26 (99)
/HV113$26 (9)
/HV114$26 (99)
/HV115$26 (9)
/HV116$26 (9)
/HV101$27 (99)
/HV102$27 (9)
/HV103$27 (9)
/HV104$27 (9)
/HV105$27 (99)
/HV106$27 (9)
/HV107$27 (99)
/HV108$27 (99)
/HV109$27 (9)
/HV110$27 (9)
/HV111$27 (9)
/HV112$27 (99)
/HV113$27 (9)
/HV114$27 (99)
/HV115$27 (9)
/HV116$27 (9)
/HV101$28 (99)
/HV102$28 (9)
/HV103$28 (9)
/HV104$28 (9)
/HV105$28 (99)
/HV106$28 (9)
/HV107$28 (99)
/HV108$28 (99)
/HV109$28 (9)
/HV110$28 (9)
/HV111$28 (9)
/HV112$28 (99)
/HV113$28 (9)
/HV114$28 (99)
/HV115$28 (9)
/HV116$28 (9)
/SH20     (999)
/SH20A    (999)
/SH25     (99)
/SH26A    (9)
/SH26B    (9)
/SH26C    (9)
/SH26D    (9)
/SH26I    (9)
/SH31     (9)
/SH14$01  (9)
/SH14$02  (9)
/SH14$03  (9)
/SH14$04  (9)
/SH14$05  (9)
/SH14$06  (9)
/SH14$07  (9)
/SH14$08  (9)
/SH14$09  (9)
/SH14$10  (9)
/SH14$11  (9)
/SH14$12  (9)
/SH14$13  (9)
/SH14$14  (9)
/SH14$15  (9)
/SH14$16  (9)
/SH14$17  (9)
/SH14$18  (9)
/SH14$19  (9)
/SH14$20  (9)
/SH14$21  (9)
/SH14$22  (9)
/SH14$23  (9)
/SH14$24  (9)
/SH14$25  (9)
/SH14$26  (9)
/SH14$27  (9)
/SH14$28  (9)
.
VALUE LABELS
 HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
/HV020   
     0 "All woman sample"
     1 "Ever married sample"
/HV023   
     0 "National"
     1 "Country specific"
/HV024   
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/HV025   
     1 "Urban"
     2 "Rural"
/HV026   
     0 "Dhaka/Chittagong"
     1 "Small city"
     2 "Town"
     3 "Village"
/HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
/HV201   
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
/HV202   
    10 "PIPED WATER"
    11 "Piped inside dwelln'"
    12 "Piped outside dwellg"
    20 "WELL WATER"
    21 "Tubewell"
    22 "Surface/other well"
    30 "SURFACE WATER"
    31 "Pond/tank/lake"
    32 "River/stream"
    41 "Rainwater"
    96 "Other"
/HV203   
     0 "No"
     1 "Yes"
/HV204   
   996 "On premises"
/HV205   
    10 "FLUSH TOILET"
    11 "Septic tank/modern"
    20 "PIT TOILET LATRINE"
    21 "Water sealed/slab"
    22 "Pit latrine"
    23 "Open latrine"
    24 "Hanging latrine"
    30 "NO FACILITY"
    31 "No facility/bush"
    96 "OTHER"
/HV206   
     0 "No"
     1 "Yes"
/HV207   
     0 "No"
     1 "Yes"
/HV208   
     0 "No"
     1 "Yes"
/HV210   
     0 "No"
     1 "Yes"
/HV213   
    10 "NATURAL"
    11 "Earth"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
/HV214   
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Wood"
    30 "FINISHED"
    31 "Brick/cement"
    32 "Tin"
    96 "OTHER"
/HV215   
    10 "NATURAL"
    11 "Jute/bamboo/mud"
    20 "RUDIMENTARY"
    21 "Tin"
    30 "FINISHED"
    31 "Cement/concrete"
    96 "OTHER"
/HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
/HV219   
     1 "Male"
     2 "Female"
/HV220   
    97 "97+"
    98 "DK"
/HV101$01
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$01
     0 "No"
     1 "Yes"
/HV103$01
     0 "No"
     1 "Yes"
/HV104$01
     1 "Male"
     2 "Female"
/HV105$01
    96 "96 or older"
    98 "DK"
/HV106$01
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$01
    98 "DK"
/HV108$01
    97 "Inconsistent"
    98 "DK"
/HV109$01
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$01
     0 "No"
     1 "Yes"
/HV116$01
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$01
     0 "Not eligible"
     1 "Eligible"
/HV118$01
     0 "Not eligible"
     1 "Eligible"
/HV101$02
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$02
     0 "No"
     1 "Yes"
/HV103$02
     0 "No"
     1 "Yes"
/HV104$02
     1 "Male"
     2 "Female"
/HV105$02
    96 "96 or older"
    98 "DK"
/HV106$02
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$02
    98 "DK"
/HV108$02
    97 "Inconsistent"
    98 "DK"
/HV109$02
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$02
     0 "No"
     1 "Yes"
/HV116$02
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$02
     0 "Not eligible"
     1 "Eligible"
/HV118$02
     0 "Not eligible"
     1 "Eligible"
/HV101$03
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$03
     0 "No"
     1 "Yes"
/HV103$03
     0 "No"
     1 "Yes"
/HV104$03
     1 "Male"
     2 "Female"
/HV105$03
    96 "96 or older"
    98 "DK"
/HV106$03
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$03
    98 "DK"
/HV108$03
    97 "Inconsistent"
    98 "DK"
/HV109$03
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$03
     0 "No"
     1 "Yes"
/HV116$03
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$03
     0 "Not eligible"
     1 "Eligible"
/HV118$03
     0 "Not eligible"
     1 "Eligible"
/HV101$04
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$04
     0 "No"
     1 "Yes"
/HV103$04
     0 "No"
     1 "Yes"
/HV104$04
     1 "Male"
     2 "Female"
/HV105$04
    96 "96 or older"
    98 "DK"
/HV106$04
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$04
    98 "DK"
/HV108$04
    97 "Inconsistent"
    98 "DK"
/HV109$04
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$04
     0 "No"
     1 "Yes"
/HV116$04
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$04
     0 "Not eligible"
     1 "Eligible"
/HV118$04
     0 "Not eligible"
     1 "Eligible"
/HV101$05
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$05
     0 "No"
     1 "Yes"
/HV103$05
     0 "No"
     1 "Yes"
/HV104$05
     1 "Male"
     2 "Female"
/HV105$05
    96 "96 or older"
    98 "DK"
/HV106$05
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$05
    98 "DK"
/HV108$05
    97 "Inconsistent"
    98 "DK"
/HV109$05
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$05
     0 "No"
     1 "Yes"
/HV116$05
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$05
     0 "Not eligible"
     1 "Eligible"
/HV118$05
     0 "Not eligible"
     1 "Eligible"
/HV101$06
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$06
     0 "No"
     1 "Yes"
/HV103$06
     0 "No"
     1 "Yes"
/HV104$06
     1 "Male"
     2 "Female"
/HV105$06
    96 "96 or older"
    98 "DK"
/HV106$06
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$06
    98 "DK"
/HV108$06
    97 "Inconsistent"
    98 "DK"
/HV109$06
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$06
     0 "No"
     1 "Yes"
/HV116$06
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$06
     0 "Not eligible"
     1 "Eligible"
/HV118$06
     0 "Not eligible"
     1 "Eligible"
/HV101$07
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$07
     0 "No"
     1 "Yes"
/HV103$07
     0 "No"
     1 "Yes"
/HV104$07
     1 "Male"
     2 "Female"
/HV105$07
    96 "96 or older"
    98 "DK"
/HV106$07
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$07
    98 "DK"
/HV108$07
    97 "Inconsistent"
    98 "DK"
/HV109$07
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$07
     0 "No"
     1 "Yes"
/HV116$07
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$07
     0 "Not eligible"
     1 "Eligible"
/HV118$07
     0 "Not eligible"
     1 "Eligible"
/HV101$08
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$08
     0 "No"
     1 "Yes"
/HV103$08
     0 "No"
     1 "Yes"
/HV104$08
     1 "Male"
     2 "Female"
/HV105$08
    96 "96 or older"
    98 "DK"
/HV106$08
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$08
    98 "DK"
/HV108$08
    97 "Inconsistent"
    98 "DK"
/HV109$08
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$08
     0 "No"
     1 "Yes"
/HV116$08
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$08
     0 "Not eligible"
     1 "Eligible"
/HV118$08
     0 "Not eligible"
     1 "Eligible"
/HV101$09
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$09
     0 "No"
     1 "Yes"
/HV103$09
     0 "No"
     1 "Yes"
/HV104$09
     1 "Male"
     2 "Female"
/HV105$09
    96 "96 or older"
    98 "DK"
/HV106$09
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$09
    98 "DK"
/HV108$09
    97 "Inconsistent"
    98 "DK"
/HV109$09
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$09
     0 "No"
     1 "Yes"
/HV116$09
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$09
     0 "Not eligible"
     1 "Eligible"
/HV118$09
     0 "Not eligible"
     1 "Eligible"
/HV101$10
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$10
     0 "No"
     1 "Yes"
/HV103$10
     0 "No"
     1 "Yes"
/HV104$10
     1 "Male"
     2 "Female"
/HV105$10
    96 "96 or older"
    98 "DK"
/HV106$10
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$10
    98 "DK"
/HV108$10
    97 "Inconsistent"
    98 "DK"
/HV109$10
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$10
     0 "No"
     1 "Yes"
/HV116$10
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$10
     0 "Not eligible"
     1 "Eligible"
/HV118$10
     0 "Not eligible"
     1 "Eligible"
/HV101$11
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$11
     0 "No"
     1 "Yes"
/HV103$11
     0 "No"
     1 "Yes"
/HV104$11
     1 "Male"
     2 "Female"
/HV105$11
    96 "96 or older"
    98 "DK"
/HV106$11
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$11
    98 "DK"
/HV108$11
    97 "Inconsistent"
    98 "DK"
/HV109$11
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$11
     0 "No"
     1 "Yes"
/HV116$11
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$11
     0 "Not eligible"
     1 "Eligible"
/HV118$11
     0 "Not eligible"
     1 "Eligible"
/HV101$12
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$12
     0 "No"
     1 "Yes"
/HV103$12
     0 "No"
     1 "Yes"
/HV104$12
     1 "Male"
     2 "Female"
/HV105$12
    96 "96 or older"
    98 "DK"
/HV106$12
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$12
    98 "DK"
/HV108$12
    97 "Inconsistent"
    98 "DK"
/HV109$12
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$12
     0 "No"
     1 "Yes"
/HV116$12
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$12
     0 "Not eligible"
     1 "Eligible"
/HV118$12
     0 "Not eligible"
     1 "Eligible"
/HV101$13
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$13
     0 "No"
     1 "Yes"
/HV103$13
     0 "No"
     1 "Yes"
/HV104$13
     1 "Male"
     2 "Female"
/HV105$13
    96 "96 or older"
    98 "DK"
/HV106$13
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$13
    98 "DK"
/HV108$13
    97 "Inconsistent"
    98 "DK"
/HV109$13
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$13
     0 "No"
     1 "Yes"
/HV116$13
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$13
     0 "Not eligible"
     1 "Eligible"
/HV118$13
     0 "Not eligible"
     1 "Eligible"
/HV101$14
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$14
     0 "No"
     1 "Yes"
/HV103$14
     0 "No"
     1 "Yes"
/HV104$14
     1 "Male"
     2 "Female"
/HV105$14
    96 "96 or older"
    98 "DK"
/HV106$14
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$14
    98 "DK"
/HV108$14
    97 "Inconsistent"
    98 "DK"
/HV109$14
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$14
     0 "No"
     1 "Yes"
/HV116$14
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$14
     0 "Not eligible"
     1 "Eligible"
/HV118$14
     0 "Not eligible"
     1 "Eligible"
/HV101$15
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$15
     0 "No"
     1 "Yes"
/HV103$15
     0 "No"
     1 "Yes"
/HV104$15
     1 "Male"
     2 "Female"
/HV105$15
    96 "96 or older"
    98 "DK"
/HV106$15
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$15
    98 "DK"
/HV108$15
    97 "Inconsistent"
    98 "DK"
/HV109$15
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$15
     0 "No"
     1 "Yes"
/HV116$15
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$15
     0 "Not eligible"
     1 "Eligible"
/HV118$15
     0 "Not eligible"
     1 "Eligible"
/HV101$16
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$16
     0 "No"
     1 "Yes"
/HV103$16
     0 "No"
     1 "Yes"
/HV104$16
     1 "Male"
     2 "Female"
/HV105$16
    96 "96 or older"
    98 "DK"
/HV106$16
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$16
    98 "DK"
/HV108$16
    97 "Inconsistent"
    98 "DK"
/HV109$16
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$16
     0 "No"
     1 "Yes"
/HV116$16
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$16
     0 "Not eligible"
     1 "Eligible"
/HV118$16
     0 "Not eligible"
     1 "Eligible"
/HV101$17
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$17
     0 "No"
     1 "Yes"
/HV103$17
     0 "No"
     1 "Yes"
/HV104$17
     1 "Male"
     2 "Female"
/HV105$17
    96 "96 or older"
    98 "DK"
/HV106$17
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$17
    98 "DK"
/HV108$17
    97 "Inconsistent"
    98 "DK"
/HV109$17
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$17
     0 "No"
     1 "Yes"
/HV116$17
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$17
     0 "Not eligible"
     1 "Eligible"
/HV118$17
     0 "Not eligible"
     1 "Eligible"
/HV101$18
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$18
     0 "No"
     1 "Yes"
/HV103$18
     0 "No"
     1 "Yes"
/HV104$18
     1 "Male"
     2 "Female"
/HV105$18
    96 "96 or older"
    98 "DK"
/HV106$18
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$18
    98 "DK"
/HV108$18
    97 "Inconsistent"
    98 "DK"
/HV109$18
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$18
     0 "No"
     1 "Yes"
/HV116$18
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$18
     0 "Not eligible"
     1 "Eligible"
/HV118$18
     0 "Not eligible"
     1 "Eligible"
/HV101$19
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$19
     0 "No"
     1 "Yes"
/HV103$19
     0 "No"
     1 "Yes"
/HV104$19
     1 "Male"
     2 "Female"
/HV105$19
    96 "96 or older"
    98 "DK"
/HV106$19
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$19
    98 "DK"
/HV108$19
    97 "Inconsistent"
    98 "DK"
/HV109$19
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$19
     0 "No"
     1 "Yes"
/HV116$19
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$19
     0 "Not eligible"
     1 "Eligible"
/HV118$19
     0 "Not eligible"
     1 "Eligible"
/HV101$20
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$20
     0 "No"
     1 "Yes"
/HV103$20
     0 "No"
     1 "Yes"
/HV104$20
     1 "Male"
     2 "Female"
/HV105$20
    96 "96 or older"
    98 "DK"
/HV106$20
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$20
    98 "DK"
/HV108$20
    97 "Inconsistent"
    98 "DK"
/HV109$20
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$20
     0 "No"
     1 "Yes"
/HV116$20
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$20
     0 "Not eligible"
     1 "Eligible"
/HV118$20
     0 "Not eligible"
     1 "Eligible"
/HV101$21
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$21
     0 "No"
     1 "Yes"
/HV103$21
     0 "No"
     1 "Yes"
/HV104$21
     1 "Male"
     2 "Female"
/HV105$21
    96 "96 or older"
    98 "DK"
/HV106$21
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$21
    98 "DK"
/HV108$21
    97 "Inconsistent"
    98 "DK"
/HV109$21
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$21
     0 "No"
     1 "Yes"
/HV116$21
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$21
     0 "Not eligible"
     1 "Eligible"
/HV118$21
     0 "Not eligible"
     1 "Eligible"
/HV101$22
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$22
     0 "No"
     1 "Yes"
/HV103$22
     0 "No"
     1 "Yes"
/HV104$22
     1 "Male"
     2 "Female"
/HV105$22
    96 "96 or older"
    98 "DK"
/HV106$22
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$22
    98 "DK"
/HV108$22
    97 "Inconsistent"
    98 "DK"
/HV109$22
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$22
     0 "No"
     1 "Yes"
/HV116$22
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$22
     0 "Not eligible"
     1 "Eligible"
/HV118$22
     0 "Not eligible"
     1 "Eligible"
/HV101$23
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$23
     0 "No"
     1 "Yes"
/HV103$23
     0 "No"
     1 "Yes"
/HV104$23
     1 "Male"
     2 "Female"
/HV105$23
    96 "96 or older"
    98 "DK"
/HV106$23
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$23
    98 "DK"
/HV108$23
    97 "Inconsistent"
    98 "DK"
/HV109$23
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$23
     0 "No"
     1 "Yes"
/HV116$23
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$23
     0 "Not eligible"
     1 "Eligible"
/HV118$23
     0 "Not eligible"
     1 "Eligible"
/HV101$24
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$24
     0 "No"
     1 "Yes"
/HV103$24
     0 "No"
     1 "Yes"
/HV104$24
     1 "Male"
     2 "Female"
/HV105$24
    96 "96 or older"
    98 "DK"
/HV106$24
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$24
    98 "DK"
/HV108$24
    97 "Inconsistent"
    98 "DK"
/HV109$24
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$24
     0 "No"
     1 "Yes"
/HV116$24
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$24
     0 "Not eligible"
     1 "Eligible"
/HV118$24
     0 "Not eligible"
     1 "Eligible"
/HV101$25
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$25
     0 "No"
     1 "Yes"
/HV103$25
     0 "No"
     1 "Yes"
/HV104$25
     1 "Male"
     2 "Female"
/HV105$25
    96 "96 or older"
    98 "DK"
/HV106$25
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$25
    98 "DK"
/HV108$25
    97 "Inconsistent"
    98 "DK"
/HV109$25
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$25
     0 "No"
     1 "Yes"
/HV116$25
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$25
     0 "Not eligible"
     1 "Eligible"
/HV118$25
     0 "Not eligible"
     1 "Eligible"
/HV101$26
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$26
     0 "No"
     1 "Yes"
/HV103$26
     0 "No"
     1 "Yes"
/HV104$26
     1 "Male"
     2 "Female"
/HV105$26
    96 "96 or older"
    98 "DK"
/HV106$26
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$26
    98 "DK"
/HV108$26
    97 "Inconsistent"
    98 "DK"
/HV109$26
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$26
     0 "No"
     1 "Yes"
/HV116$26
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$26
     0 "Not eligible"
     1 "Eligible"
/HV118$26
     0 "Not eligible"
     1 "Eligible"
/HV101$27
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$27
     0 "No"
     1 "Yes"
/HV103$27
     0 "No"
     1 "Yes"
/HV104$27
     1 "Male"
     2 "Female"
/HV105$27
    96 "96 or older"
    98 "DK"
/HV106$27
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$27
    98 "DK"
/HV108$27
    97 "Inconsistent"
    98 "DK"
/HV109$27
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$27
     0 "No"
     1 "Yes"
/HV116$27
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$27
     0 "Not eligible"
     1 "Eligible"
/HV118$27
     0 "Not eligible"
     1 "Eligible"
/HV101$28
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/HV102$28
     0 "No"
     1 "Yes"
/HV103$28
     0 "No"
     1 "Yes"
/HV104$28
     1 "Male"
     2 "Female"
/HV105$28
    96 "96 or older"
    98 "DK"
/HV106$28
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
/HV107$28
    98 "DK"
/HV108$28
    97 "Inconsistent"
    98 "DK"
/HV109$28
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
/HV110$28
     0 "No"
     1 "Yes"
/HV116$28
     0 "Never married"
     1 "Currently married"
     2 "Formerly/ever marr."
/HV117$28
     0 "Not eligible"
     1 "Eligible"
/HV118$28
     0 "Not eligible"
     1 "Eligible"
/SH20    
   996 "On premises"
/SH25    
     0 "No children"
    10 "FLUSH TOILET"
    11 "Septic tank/modern"
    20 "PIT TOILET LATRINE"
    21 "Water sealed/slab"
    22 "Pit latrine"
    23 "Open latrine"
    24 "Hanging latrine"
    30 "NO FACILITY"
    31 "No facility/bush"
    96 "OTHER"
/SH26A   
     0 "No"
     1 "Yes"
/SH26B   
     0 "No"
     1 "Yes"
/SH26C   
     0 "No"
     1 "Yes"
/SH26D   
     0 "No"
     1 "Yes"
/SH26I   
     0 "No"
     1 "Yes"
/SH31    
     0 "No"
     1 "Yes"
/SH14$01 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$01 
     0 "Not marr./husb away"
/SH14$02 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$02 
     0 "Not marr./husb away"
/SH14$03 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$03 
     0 "Not marr./husb away"
/SH14$04 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$04 
     0 "Not marr./husb away"
/SH14$05 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$05 
     0 "Not marr./husb away"
/SH14$06 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$06 
     0 "Not marr./husb away"
/SH14$07 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$07 
     0 "Not marr./husb away"
/SH14$08 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$08 
     0 "Not marr./husb away"
/SH14$09 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$09 
     0 "Not marr./husb away"
/SH14$10 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$10 
     0 "Not marr./husb away"
/SH14$11 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$11 
     0 "Not marr./husb away"
/SH14$12 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$12 
     0 "Not marr./husb away"
/SH14$13 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$13 
     0 "Not marr./husb away"
/SH14$14 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$14 
     0 "Not marr./husb away"
/SH14$15 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$15 
     0 "Not marr./husb away"
/SH14$16 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$16 
     0 "Not marr./husb away"
/SH14$17 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$17 
     0 "Not marr./husb away"
/SH14$18 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$18 
     0 "Not marr./husb away"
/SH14$19 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$19 
     0 "Not marr./husb away"
/SH14$20 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$20 
     0 "Not marr./husb away"
/SH14$21 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$21 
     0 "Not marr./husb away"
/SH14$22 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$22 
     0 "Not marr./husb away"
/SH14$23 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$23 
     0 "Not marr./husb away"
/SH14$24 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$24 
     0 "Not marr./husb away"
/SH14$25 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$25 
     0 "Not marr./husb away"
/SH14$26 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$26 
     0 "Not marr./husb away"
/SH14$27 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$27 
     0 "Not marr./husb away"
/SH14$28 
     0 "No"
     1 "Yes"
     8 "Don't know"
/SH17$28 
     0 "Not marr./husb away"
.
