class Config:
    parse_parameters = {'C01': {'ncol_before': 6, 'ncol_after': 5},
                        'C02': {'ncol_before': 6, 'ncol_after': 9},
                        'C03': {'ncol_before': 6, 'ncol_after': 11},
                        'C04': {'ncol_before': 6, 'ncol_after': 12},
                        'C05': {'ncol_before': 6, 'ncol_after': 11},
                        'C06': {'ncol_before': 6, 'ncol_after': 10},
                        'C07': {'ncol_before': 6, 'ncol_after': 13},
                        'C08': {'ncol_before': 6, 'ncol_after': 13},
                        'C09': {'ncol_before': 6, 'ncol_after': 9},
                        'C10': {'ncol_before': 6, 'ncol_after': 12},
                        'C11': {'ncol_before': 6, 'ncol_after': 10},
                        'C12': {'ncol_before': 6, 'ncol_after': 18},
                        'C13': {'ncol_before': 6, 'ncol_after': 7},
                        'C14': {'ncol_before': 6, 'ncol_after': 10},
                        'C15': {'ncol_before': 6, 'ncol_after': 9},
                        }
    cols_dict = {'C01': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community', 'Area in Acres',
                         'Total Households', 'Population-Total', 'Population-In Households'],
                 'C02': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Households-Total', 'Households-General', 'Households-Institutional',
                         'Households-Others', 'Population-Both', 'Population-Male', 'Population-Female', 'Sex Ratio'],
                 'C03': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'General Households', 'Percentage of Households comprising-1 person',
                         'Percentage of Households comprising-2 persons',
                         'Percentage of Households comprising-3 persons',
                         'Percentage of Households comprising-4 persons',
                         'Percentage of Households comprising-5 persons',
                         'Percentage of Households comprising-6 persons',
                         'Percentage of Households comprising-7 persons',
                         'Percentage of Households comprising-8+ persons', 'Average size of Household'],
                 'C04': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community', 'All ages',
                         'Percentage of population in the age group 0-4',
                         'Percentage of population in the age group 5-9',
                         'Percentage of population in the age group 10-14',
                         'Percentage of population in the age group 15-19',
                         'Percentage of population in the age group 20-24',
                         'Percentage of population in the age group 25-29',
                         'Percentage of population in the age group 30-49',
                         'Percentage of population in the age group 50-59',
                         'Percentage of population in the age group 60-64',
                         'Percentage of population in the age group 65+', ],
                 'C05': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Total Male', '% Male-Never married', '% Male-Married', '% Male-Widowed',
                         '% Male-Divorced/Separated',
                         'Total Female', '% Female-Never married', '% Female-Married', '% Female-Widowed',
                         '% Female-Divorced/Separated'],
                 'C06': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Literate (can write a letter)-Both-Yes', 'Literate (can write a letter)-Both-No',
                         'Literate (can write a letter)-Male-Yes', 'Literate (can write a letter)-Male-No',
                         'Literate (can write a letter)-Female-Yes', 'Literate (can write a letter)-Female-No',
                         'Literacy Rate (%)-Both', 'Literacy Rate (%)-Male', 'Literacy Rate (%)-Female', ],
                 'C07': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Population aged 3-5 years-Attending school-Male',
                         'Population aged 3-5 years-Attending school-Female',
                         'Population aged 3-5 years-Not attending school-Male',
                         'Population aged 3-5 years-Not attending school-Female',
                         'Population aged 6-10 years-Attending school-Male',
                         'Population aged 6-10 years-Attending school-Female',
                         'Population aged 6-10 years-Not attending school-Male',
                         'Population aged 6-10 years-Not attending school-Female',
                         'Population aged 11-14 years-Attending school-Male',
                         'Population aged 11-14 years-Attending school-Female',
                         'Population aged 11-14 years-Not attending school-Male',
                         'Population aged 11-14 years-Not attending school-Female', ],
                 'C08': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Population aged 15-19 years-Attending school-Male',
                         'Population aged 15-19 years-Attending school-Female',
                         'Population aged 15-19 years-Not attending school-Male',
                         'Population aged 15-19 years-Not attending school-Female',
                         'Population aged 20-24 years-Attending school-Male',
                         'Population aged 20-24 years-Attending school-Female',
                         'Population aged 20-24 years-Not attending school-Male',
                         'Population aged 20-24 years-Not attending school-Female',
                         'Population aged 25-29 years-Attending school-Male',
                         'Population aged 25-29 years-Attending school-Female',
                         'Population aged 25-29 years-Not attending school-Male',
                         'Population aged 25-29 years-Not attending school-Female', ],

                 'C09': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Total Population', 'Type of disability (%)-All', 'Type of disability (%)-Speech',
                         'Type of disability (%)-Vision', 'Type of disability (%)-Hearing',
                         'Type of disability (%)-Physical', 'Type of disability (%)-Mental',
                         'Type of disability (%)-Autism', ],
                 'C10': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Population aged 7+ and not attending school-Both',
                         'Population aged 7+ and not attending school-Male',
                         'Population aged 7+ and not attending school-Female',
                         'Employment Status-Employed-Male', 'Employment Status-Employed-Female',
                         'Employment Status-Looking for work-Male', 'Employment Status-Looking for work-Female',
                         'Employment Status-Household work-Male', 'Employment Status-Household work-Female',
                         'Employment Status-Do not work-Male', 'Employment Status-Do not work-Female',],
                 'C11': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Population aged 7+, not attending school and employed-Both',
                         'Population aged 7+, not attending school and employed-Male',
                         'Population aged 7+, not attending school and employed-Female',
                         'Field of Activity-Agriculture-Male', 'Field of Activity-Agriculture-Female',
                         'Field of Activity-Industry-Male', 'Field of Activity-Industry-Female',
                         'Field of Activity-Service-Male', 'Field of Activity-Service-Female', ],
                 'C12_e': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                           'Administrative Unit Residence Community',
                           'Ethnic-Households', 'Ethnic-Population-Both', 'Ethnic-Population-Male',
                           'Ethnic-Population-Female',
                           'Ethnic Population in Main Groups-Rakhain', 'Ethnic Population in Main Groups-Chakma',
                           'Ethnic Population in Main Groups-Marma', 'Ethnic Population in Main Groups-Others', ],
                 'C12': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Ethnic-Households', 'Ethnic-Population-Both', 'Ethnic-Population-Male',
                         'Ethnic-Population-Female',
                         'Ethnic Population in Main Groups-Malpahari', 'Ethnic Population in Main Groups-Chakma',
                         'Ethnic Population in Main Groups-Dalu', 'Ethnic Population in Main Groups-Others', ],
                 'C13': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Total', 'Muslim', 'Hindu', 'Christian', 'Buddhist', 'Others'],
                 'C14': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Number of Households', 'Type of Structure (%)-Pucka', 'Type of Structure (%)-Semi-pucka',
                         'Type of Structure (%)-Kutcha', 'Type of Structure (%)-Jhupri',
                         'Toilet Facility (%)-Sanitary (water-sealed)',
                         'Toilet Facility (%)-Sanitary (non water-sealed)',
                         'Toilet Facility (%)-Non-sanitary', 'Toilet Facility (%)-None', ],
                 'C15': ['ZL', 'UZ', 'UN/WA', 'MZ/MH', 'Vill', 'RMO',
                         'Administrative Unit Residence Community',
                         'Number of Households',
                         'Source of Drinking Water (%)-Tap', 'Source of Drinking Water (%)-Tube-Well',
                         'Source of Drinking Water (%)-Other',
                         'Electricity Connection (%)',
                         'Housing Tenancy (%)-Owned', 'Housing Tenancy (%)-Rented', 'Housing Tenancy (%)-Rent free'],
                 }
