DATA LIST FILE='BDMR31FL.DAT' RECORDS=1
/
 MCASEID     1-15   (A)
 MV000      16-18   (A)
 MV001      19-26
 MV002      27-30
 MV003      31-33
 MV004      34-37
 MV005      38-45
 MV006      46-47
 MV007      48-49
 MV008      50-53
 MV009      54-55
 MV010      56-57
 MV011      58-61
 MV012      62-63
 MV013      64-65
 MV014      66-66
 MV015      67-67
 MV016      68-69
 MV021      70-73
 MV022      74-77
 MV023      78-79
 MV024      80-81
 MV025      82-82
 MV026      83-83
 MV027      84-84
 MV028      85-87
 MV029      88-89
 MV030      90-91
 MV031      92-93
 MV032      94-95
 MV033      96-103
 MV034$1   104-105
 MV034$2   106-107
 MV034$3   108-109
 MV034$4   110-111
 MV034$5   112-113
 MV034$6   114-115
 MV034$7   116-117
 MV034$8   118-119
 MV035     120-120
 MV801     121-124
 MV802     125-128
 MV803     129-130
 MV101     131-132
 MV102     133-133
 MV103     134-134
 MV104     135-136
 MV105     137-137
 MV106     138-138
 MV107     139-140
 MV108     141-141
 MV109     142-142
 MV110     143-143
 MV111     144-144
 MV112     145-145
 MV130     146-146
 MV131     147-148
 MV133     149-150
 MV134     151-151
 MV135     152-152
 MV136     153-154
 MV138     155-156
 MV148     157-157
 MV149     158-158
 MV150     159-160
 MV151     161-161
 MV152     162-163
 MV201     164-165
 MV202     166-167
 MV203     168-169
 MV204     170-171
 MV205     172-173
 MV206     174-175
 MV207     176-177
 MV213     178-178
 MV218     179-180
 MV225     181-181
 MV301     182-182
 MV302     183-183
 MV304A01  184-184
 MV304$01  185-185
 MV305$01  186-186
 MV304A02  187-187
 MV304$02  188-188
 MV305$02  189-189
 MV304A03  190-190
 MV304$03  191-191
 MV305$03  192-192
 MV304A04  193-193
 MV304$04  194-194
 MV305$04  195-195
 MV304A05  196-196
 MV304$05  197-197
 MV305$05  198-198
 MV304A06  199-199
 MV304$06  200-200
 MV305$06  201-201
 MV304A07  202-202
 MV304$07  203-203
 MV305$07  204-204
 MV304A08  205-205
 MV304$08  206-206
 MV305$08  207-207
 MV304A09  208-208
 MV304$09  209-209
 MV305$09  210-210
 MV304A10  211-211
 MV304$10  212-212
 MV305$10  213-213
 MV304A11  214-214
 MV304$11  215-215
 MV305$11  216-216
 MV304A12  217-217
 MV304$12  218-218
 MV305$12  219-219
 MV304A13  220-220
 MV304$13  221-221
 MV305$13  222-222
 MV304A14  223-223
 MV304$14  224-224
 MV305$14  225-225
 MV304A15  226-226
 MV304$15  227-227
 MV305$15  228-228
 MV312     229-230
 MV313     231-231
 MV361     232-232
 MV362     233-233
 MV363     234-235
 MV364     236-236
 MV366A    237-237
 MV366B    238-238
 MV367     239-239
 MV375A    240-241
 MV376     242-243
 MV384A    244-244
 MV384B    245-245
 MV384C    246-246
 MV384D    247-247
 MV384E    248-248
 MV501     249-249
 MV502     250-250
 MV503     251-251
 MV505     252-253
 MV507     254-255
 MV508     256-257
 MV509     258-261
 MV510     262-262
 MV511     263-264
 MV512     265-266
 MV513     267-267
 MV525     268-269
 MV527     270-272
 MV531     273-274
 MV532     275-275
 MV534     276-276
 MV535     277-277
 MV602     278-278
 MV603     279-281
 MV604     282-282
 MV605     283-283
 MV610     284-284
 MV611     285-285
 MV612     286-286
 MV613     287-288
 MV614     289-289
 MV616     290-292
 MV621     293-293
 MV627     294-295
 MV628     296-297
 MV629     298-299
 MV630A    300-300
 MV630B    301-301
 MV630C    302-302
 MV630D    303-303
 MV630E    304-304
 MV630F    305-305
 MV630G    306-306
 MV630H    307-307
 MV630I    308-308
 MV630J    309-309
 MV630K    310-310
 MV630L    311-311
 MV630X    312-312
 MV714     313-313
 MV716     314-316
 MV717     317-318
 MV719     319-319
 MV731     320-320
 MV732     321-321
 MV733     322-323
 MV736     324-331
 MV740     332-332
 MV751     333-333
 MV752A    334-334
 MV752B    335-335
 MV752C    336-336
 MV752D    337-337
 MV752E    338-338
 MV752F    339-339
 MV752G    340-340
 MV752H    341-341
 MV752I    342-342
 MV752J    343-343
 MV752K    344-344
 MV752L    345-345
 MV752M    346-346
 MV752N    347-347
 MV752O    348-348
 MV752X    349-349
 MV753     350-350
 MV754A    351-351
 MV754B    352-352
 MV754C    353-353
 MV754D    354-354
 MV754E    355-355
 MV754F    356-356
 MV754G    357-357
 MV754H    358-358
 MV754I    359-359
 MV754J    360-360
 MV754K    361-361
 MV754L    362-362
 MV754M    363-363
 MV754N    364-364
 MV754O    365-365
 MV754X    366-366
 MV754Z    367-367
 MV755B    368-368
 MV755C    369-369
 MV755D    370-370
 MV755E    371-371
 MV755F    372-372
 MV755L    373-373
 MV755M    374-374
 MV755N    375-375
 MV755O    376-376
 MV755X    377-377
 MV755Z    378-378
 MV756     379-379
 MV757     380-380
 MV758     381-381
 MV760A    382-382
 MV760B    383-383
 MV760C    384-384
 MV760D    385-385
 MV760E    386-386
 MV760F    387-387
 MV760G    388-388
 MV760I    389-389
 MV760L    390-390
 MV760M    391-391
 MV760N    392-392
 MV760O    393-393
 MV760P    394-394
 MV760V    395-395
 MV760W    396-396
 MV760X    397-397
 MV760Y    398-398
 MV760Z    399-399
 MV761     400-400
 MV762     401-402
 MV763     403-404
 MV764     405-405
 MV765     406-406
 MSDISTR   407-408
 MSFORMAT  409-409
 MSADJUST  410-410
 MSINTY    411-412
 MSINTM    413-414
 MS304$01  415-415
 MS304$02  416-416
 MS304$03  417-417
 MS304$04  418-418
 MS304$05  419-419
 MS304$06  420-420
 MS304$07  421-421
 MS304$08  422-422
 MS304$09  423-423
 MS304$10  424-424
 MS304$11  425-425
 MS304$12  426-426
 MS304$13  427-427
 MS304$14  428-428
 MS304$15  429-429
 MS304$16  430-430
 MS304$17  431-431
 MS304$18  432-432
 MS304$19  433-433
 MS304$20  434-434
 MS309     435-436
 MS311     437-438
 MS316     439-439
 MS317     440-441
 MS320S    442-442
 MS320     443-444
 MS320A    445-445
 MS320C    446-449
 MS320E    450-451
 MS320D    452-452
 MS321M    453-454
 MS321Y    455-456
 MS321C    457-460
 MS321F    461-461
 MS321XA   462-462
 MS321XB   463-463
 MS321XC   464-464
 MS321XD   465-465
 MS321XE   466-467
 MS321XF   468-471
 MS322B    472-472
 MS322C    473-474
 MS323     475-476
 MS323B    477-477
 MS325     478-478
 MS325A    479-479
 MS325B    480-480
 MS325C    481-481
 MS325H    482-482
 MS325I    483-484
 MS325J    485-485
 MS326     486-487
 MS328HI   488-489
 MS347A    490-490
 MS347B    491-491
 MS347CA   492-492
 MS347CB   493-493
 MS347CC   494-494
 MS347CD   495-495
 MS347CE   496-496
 MS348C    497-497
 MS349A    498-498
 MS349B    499-499
 MS349C    500-500
 MS349D    501-501
 MS349E    502-502
 MS350     503-503
 MS352     504-505
 MS353     506-506
 MS354     507-507
 MS355     508-508
 MS356     509-510
 MS357A    511-511
 MS357B    512-512
 MS357C    513-513
 MS357D    514-514
 MS357E    515-515
 MS357F    516-516
 MS357G    517-517
 MS358     518-518
 MS359     519-519
 MS360     520-520
 MS361     521-521
 MS408A    522-522
 MS408B    523-523
 MS408C    524-524
 MS408D    525-525
 MS508     526-527
 MS512     528-528
 MS514     529-529
.
VARIABLE LABELS
 MCASEID  "Case Identification"
/MV000    "Country code and phase"
/MV001    "Cluster number"
/MV002    "Household number"
/MV003    "Respondent's line number"
/MV004    "Ultimate area unit"
/MV005    "Sample weight"
/MV006    "Month of interview"
/MV007    "Year of interview"
/MV008    "Date of interview (CMC)"
/MV009    "Respondent's month of birth"
/MV010    "Respondent's year of birth"
/MV011    "Date of birth (CMC)"
/MV012    "Current age - respondent"
/MV013    "Age 5-year groups"
/MV014    "Completeness of information"
/MV015    "Result of individual interview"
/MV016    "Day of interview"
/MV021    "Primary sampling unit"
/MV022    "Sample stratum number"
/MV023    "Sample domain"
/MV024    "Region"
/MV025    "Type of place of residence"
/MV026    "De facto place of residence"
/MV027    "Number of visits"
/MV028    "Interviewer identification"
/MV029    "Keyer identification"
/MV030    "Field supervisor - NA"
/MV031    "Field editor - NA"
/MV032    "Office editor - NA"
/MV033    "Ultimate area selection prob."
/MV034$1  "Line numbers of wives"
/MV034$2  "Line numbers of wives"
/MV034$3  "Line numbers of wives"
/MV034$4  "Line numbers of wives"
/MV034$5  "Line numbers of wives"
/MV034$6  "Line numbers of wives"
/MV034$7  "Line numbers of wives"
/MV034$8  "Line numbers of wives"
/MV035    "Number of wives, partners"
/MV801    "Time interview started"
/MV802    "Time interview ended"
/MV803    "Length of interview in minutes"
/MV101    "Region"
/MV102    "Type of place of residence"
/MV103    "Childhood place of residen- NA"
/MV104    "Years lived in place of res."
/MV105    "Type of place of previous resi"
/MV106    "Highest educational level"
/MV107    "Highest year of education"
/MV108    "Literacy"
/MV109    "Reads newspaper once a week"
/MV110    "Watches TV every week"
/MV111    "Listens to radio every da - NA"
/MV112    "Listens to radio every week"
/MV130    "Religion"
/MV131    "Ethnicity - NA"
/MV133    "Education in single years"
/MV134    "De facto place of residence"
/MV135    "Usual resident or visitor"
/MV136    "Number of household members"
/MV138    "Number of eligible men in HH"
/MV148    "Respondent still in school"
/MV149    "Educational attainment"
/MV150    "Relationship to household head"
/MV151    "Sex of household head"
/MV152    "Age of household head"
/MV201    "Total children ever born"
/MV202    "Sons at home"
/MV203    "Daughters at home"
/MV204    "Sons elsewhere"
/MV205    "Daughters elsewhere"
/MV206    "Sons who have died"
/MV207    "Daughters who have died"
/MV213    "Partner currently pregnan - NA"
/MV218    "Number of living children"
/MV225    "Current pregnancy wanted - NA"
/MV301    "Knowledge of any method"
/MV302    "Ever use of any method"
/MV304A01 "Type of method"
/MV304$01 "Knows method"
/MV305$01 "Ever used method"
/MV304A02 "Type of method"
/MV304$02 "Knows method"
/MV305$02 "Ever used method"
/MV304A03 "Type of method"
/MV304$03 "Knows method"
/MV305$03 "Ever used method"
/MV304A04 "Type of method"
/MV304$04 "Knows method"
/MV305$04 "Ever used method"
/MV304A05 "Type of method"
/MV304$05 "Knows method"
/MV305$05 "Ever used method"
/MV304A06 "Type of method"
/MV304$06 "Knows method"
/MV305$06 "Ever used method"
/MV304A07 "Type of method"
/MV304$07 "Knows method"
/MV305$07 "Ever used method"
/MV304A08 "Type of method"
/MV304$08 "Knows method"
/MV305$08 "Ever used method"
/MV304A09 "Type of method"
/MV304$09 "Knows method"
/MV305$09 "Ever used method"
/MV304A10 "Type of method"
/MV304$10 "Knows method"
/MV305$10 "Ever used method"
/MV304A11 "Type of method"
/MV304$11 "Knows method"
/MV305$11 "Ever used method"
/MV304A12 "Type of method"
/MV304$12 "Knows method"
/MV305$12 "Ever used method"
/MV304A13 "Type of method"
/MV304$13 "Knows method"
/MV305$13 "Ever used method"
/MV304A14 "Type of method"
/MV304$14 "Knows method"
/MV305$14 "Ever used method"
/MV304A15 "Type of method"
/MV304$15 "Knows method"
/MV305$15 "Ever used method"
/MV312    "Current contraceptive method"
/MV313    "Current use by method type"
/MV361    "Pattern of use"
/MV362    "Intention to use"
/MV363    "Preferred future method"
/MV364    "Contraceptive use & intention"
/MV366A   "Acceptability of radio me - NA"
/MV366B   "Acceptability of TV messa - NA"
/MV367    "Wanted last child - NA"
/MV375A   "Main reason not using a method"
/MV376    "Main reason not to use a meth."
/MV384A   "Heard FP on radio last month"
/MV384B   "Heard FP on TV last month"
/MV384C   "Heard FP newspaper last mon-NA"
/MV384D   "Heard FP on poster last month"
/MV384E   "Heard FP brochures last m - NA"
/MV501    "Current marital status"
/MV502    "Currently/formerly/never marr."
/MV503    "Number of unions"
/MV505    "Number of wives, partners"
/MV507    "Month of first marriage"
/MV508    "Year of first marriage"
/MV509    "Date of first marriage (CMC)"
/MV510    "Completeness of date inform."
/MV511    "Age at first marriage"
/MV512    "Years since first marriage"
/MV513    "Marital duration (grouped)"
/MV525    "Age at first intercourse - NA"
/MV527    "Time since last intercourse"
/MV531    "Age at first intercourse - NA"
/MV532    "Flag for MV531"
/MV534    "Have a regular sex partne - NA"
/MV535    "Have ever been married - NA"
/MV602    "Fertility preference"
/MV603    "Preferred waiting time"
/MV604    "Preferred waiting time (grpd)"
/MV605    "Desire for more children"
/MV610    "Wife approves FP"
/MV611    "Discussed FP with partner"
/MV612    "Respondent approves FP"
/MV613    "Ideal number of children"
/MV614    "Ideal number of children (grp)"
/MV616    "Time for future birth"
/MV621    "Wifes desire for children"
/MV627    "Ideal number of boys"
/MV628    "Ideal number of girls"
/MV629    "Ideal number of either sex"
/MV630A   "Discussed FP with partner - NA"
/MV630B   "Discussed FP with mother - NA"
/MV630C   "Discussed FP with father - NA"
/MV630D   "Discussed FP with sister( - NA"
/MV630E   "Discussed FP with brother - NA"
/MV630F   "Discussed FP with daughte - NA"
/MV630G   "Discussed FP with mother- - NA"
/MV630H   "Discussed FP with friends - NA"
/MV630I   "Discussed FP -country spe - NA"
/MV630J   "Discussed FP -country spe - NA"
/MV630K   "Discussed FP -country spe - NA"
/MV630L   "Discussed FP -country spe - NA"
/MV630X   "Discussed FP with others - NA"
/MV714    "Respondent currently working"
/MV716    "Respondent's occupation"
/MV717    "Respondent's occupation"
/MV719    "Work for family, others, - NA"
/MV731    "Worked in last 12 months - NA"
/MV732    "Employment all year/seaso - NA"
/MV733    "Months worked in last 12 - NA"
/MV736    "Earnings for work - NA"
/MV740    "Type of land where resp. works"
/MV751    "Ever heard of AIDS - NA"
/MV752A   "AIDS: radio - NA"
/MV752B   "AIDS: television - NA"
/MV752C   "AIDS: newspapers/magazine - NA"
/MV752D   "AIDS: pamphlets/posters - NA"
/MV752E   "AIDS: clinic/health worke - NA"
/MV752F   "AIDS: churches/mosques - NA"
/MV752G   "AIDS: schools/teachers - NA"
/MV752H   "AIDS: community meetings - NA"
/MV752I   "AIDS: friends/relatives - NA"
/MV752J   "AIDS: work place - NA"
/MV752K   "AIDS: country specific - NA"
/MV752L   "AIDS: country specific - NA"
/MV752M   "AIDS: country specific - NA"
/MV752N   "AIDS: country specific - NA"
/MV752O   "AIDS: country specific - NA"
/MV752X   "AIDS: other responses - NA"
/MV753    "Ways to avoid AIDS - NA"
/MV754A   "AIDS: Safe sex - NA"
/MV754B   "AIDS: abstain from sex - NA"
/MV754C   "AIDS: use condoms during - NA"
/MV754D   "AIDS: only one sex partne - NA"
/MV754E   "AIDS: avoid sex prostitut - NA"
/MV754F   "AIDS: avoid sex homosexua - NA"
/MV754G   "AIDS: avoid blood transfu - NA"
/MV754H   "AIDS: avoid injections - NA"
/MV754I   "AIDS: avoid kissing - NA"
/MV754J   "AIDS: avoid mosquito bite - NA"
/MV754K   "AIDS: protection trad. he - NA"
/MV754L   "AIDS: country specific - NA"
/MV754M   "AIDS: country specific - NA"
/MV754N   "AIDS: country specific - NA"
/MV754O   "AIDS: country specific - NA"
/MV754X   "AIDS: other responses - NA"
/MV754Z   "AIDS: DK ways to avoid AI - NA"
/MV755B   "Safe sex: abstain from se - NA"
/MV755C   "Safe sex: use condoms dur - NA"
/MV755D   "Safe sex: only one partne - NA"
/MV755E   "Safe sex: avoid prostitut - NA"
/MV755F   "Safe sex: avoid homosexua - NA"
/MV755L   "Safe sex: country specifi - NA"
/MV755M   "Safe sex: country specifi - NA"
/MV755N   "Safe sex: country specifi - NA"
/MV755O   "Safe sex: country specifi - NA"
/MV755X   "Safe sex: other responses - NA"
/MV755Z   "Safe sex: DK meaning - NA"
/MV756    "Can a healthy person have - NA"
/MV757    "Is AIDS a fatal disease - NA"
/MV758    "Chances of getting AIDS - NA"
/MV760A   "Behavior: Did not start s - NA"
/MV760B   "Behavior: Stopped all sex - NA"
/MV760C   "Behavior: Started using c - NA"
/MV760D   "Behavior: Only one sex pa - NA"
/MV760E   "Behavior: Reduced partner - NA"
/MV760F   "Behavior: Ask spouse fait - NA"
/MV760G   "Behavior: No homosexual c - NA"
/MV760I   "Behavior: Stopped injecti - NA"
/MV760L   "Behavior: Country specifi - NA"
/MV760M   "Behavior: Country specifi - NA"
/MV760N   "Behavior: Country specifi - NA"
/MV760O   "Behavior: Country specifi - NA"
/MV760P   "Behavior: Avoid sex w. pr - NA"
/MV760V   "Behavior: No nonsexual ch - NA"
/MV760W   "Behavior: Other nonsexual - NA"
/MV760X   "Behavior: Other responses - NA"
/MV760Y   "Behavior: No change - NA"
/MV760Z   "Behavior: Don't know - NA"
/MV761    "Last intercourse used con - NA"
/MV762    "Source for condoms"
/MV763    "Partners in last 12 month - NA"
/MV764    "Knowledge of condom - NA"
/MV765    "Ever use of condom - NA"
/MSDISTR  "District of residence"
/MSFORMAT "Type of date format used"
/MSADJUST "Month of interview adjusted 1m"
/MSINTY   "Year of interview(unadjusted)"
/MSINTM   "Month of interview(unadjusted)"
/MS304$01 "Knows source of method"
/MS304$02 "Knows source of method"
/MS304$03 "Knows source of method"
/MS304$04 "Knows source of method"
/MS304$05 "Knows source of method"
/MS304$06 "Knows source of method"
/MS304$07 "Knows source of method"
/MS304$08 "Knows source of method"
/MS304$09 "Knows source of method"
/MS304$10 "Knows source of method"
/MS304$11 "Knows source of method"
/MS304$12 "Knows source of method"
/MS304$13 "Knows source of method"
/MS304$14 "Knows source of method"
/MS304$15 "Knows source of method"
/MS304$16 "Knows source of method"
/MS304$17 "Knows source of method"
/MS304$18 "Knows source of method"
/MS304$19 "Knows source of method"
/MS304$20 "Knows source of method"
/MS309    "First method used"
/MS311    "Living children at first use"
/MS316    "Currently using second method"
/MS317    "Second method currently used"
/MS320S   "Condom package seen"
/MS320    "Brand of condoms shown"
/MS320A   "Reason can't show condom pack"
/MS320C   "Reason can't show condom pack"
/MS320E   "Times used condoms last month"
/MS320D   "Use condom every time have sex"
/MS321M   "Month of sterilization (imp.)"
/MS321Y   "Year of sterilization (imp.)"
/MS321C   "Date of sterilization (CMC)"
/MS321F   "Completeness of information"
/MS321XA  "Years since sterilization"
/MS321XB  "Age at sterilization"
/MS321XC  "Marital duration at steriliz."
/MS321XD  "Wife's sterilization:date form"
/MS321XE  "Wife's sterilization : month"
/MS321XF  "Wife's sterilization: year"
/MS322B   "Sterilization regret"
/MS322C   "Method used most recently"
/MS323    "Source of current method"
/MS323B   "Paid for use of contr.source"
/MS325    "Who obtained pills/condoms"
/MS325A   "Got pls,cndm at HF,doctor,shop"
/MS325B   "Informed of side effects/probs"
/MS325C   "Informed of other methods"
/MS325H   "Got method he wanted"
/MS325I   "Method wanted at HF."
/MS325J   "Who had most inflc. at 1st use"
/MS326    "Reason for current method"
/MS328HI  "Knows source for method"
/MS347A   "Satellite clinic last 3 months"
/MS347B   "Visited satellite clinic"
/MS347CA  "Sat.Clinic: Family Plng.Meths."
/MS347CB  "Sat.Clinic: Immunization"
/MS347CC  "Sat.Clinic: Ch.growth monitor."
/MS347CD  "Sat.Clinic: Other"
/MS347CE  "Sat.Clinic: Does not know"
/MS348C   "Read about FP on Billboard"
/MS349A   "Inf. on radio acceptable:pill"
/MS349B   "Inf. on radio acct'ble:condoms"
/MS349C   "Inf. on radio acct'ble:injctns"
/MS349D   "Inf. on radio acct'ble:IUD's"
/MS349E   "Inf. on radio acct'ble:sterlzn"
/MS350    "Visit by FPW in last 6 mnths"
/MS352    "No. visits by FPW last 6 mnths"
/MS353    "Months since last visit by FPW"
/MS354    "Received supplies from FPW"
/MS355    "Supplies received from FPW"
/MS356    "How many cycles/condoms rec'vd"
/MS357A   "Meths.disc.w FPW: Pills"
/MS357B   "Meths.disc.w FPW: IUD"
/MS357C   "Meths.disc.w FPW: Injection"
/MS357D   "Meths.disc.w FPW: Condom"
/MS357E   "Meths.disc.w FPW: Female Ster."
/MS357F   "Meths.disc.w FPW: Male Ster."
/MS357G   "Meths.disc.w FPW: Never disc."
/MS358    "Most men known by rsp use FP"
/MS359    "Has recommended FP to someone"
/MS360    "Visit Health Facility last 6m"
/MS361    "Spoke with psn at HF about FP"
/MS408A   "Children under 10"
/MS408B   "Presence of wife"
/MS408C   "Other males"
/MS408D   "Other females"
/MS508    "Source of preferred method"
/MS512    "Discussed children"
/MS514    "Wife allowed to go out alone"
.
MISSING VALUE
 MV015    (9)
/MV026    (9)
/MV028    (999)
/MV029    (99)
/MV035    (9)
/MV801    (9999)
/MV802    (9999)
/MV803    (99)
/MV104    (99)
/MV105    (9)
/MV106    (9)
/MV107    (99)
/MV108    (9)
/MV109    (9)
/MV110    (9)
/MV112    (9)
/MV130    (9)
/MV133    (99)
/MV134    (9)
/MV135    (9)
/MV148    (9)
/MV149    (9)
/MV150    (99)
/MV152    (99)
/MV304$01 (9)
/MV305$01 (9)
/MV304$02 (9)
/MV305$02 (9)
/MV304$03 (9)
/MV305$03 (9)
/MV304$04 (9)
/MV305$04 (9)
/MV304$05 (9)
/MV305$05 (9)
/MV304$06 (9)
/MV305$06 (9)
/MV304$07 (9)
/MV305$07 (9)
/MV304$08 (9)
/MV305$08 (9)
/MV304$09 (9)
/MV305$09 (9)
/MV304$10 (9)
/MV305$10 (9)
/MV304$11 (9)
/MV305$11 (9)
/MV304$12 (9)
/MV305$12 (9)
/MV304$13 (9)
/MV305$13 (9)
/MV304$14 (9)
/MV305$14 (9)
/MV304$15 (9)
/MV305$15 (9)
/MV312    (99)
/MV313    (9)
/MV362    (9)
/MV363    (99)
/MV375A   (99)
/MV376    (99)
/MV384A   (9)
/MV384B   (9)
/MV384D   (9)
/MV501    (9)
/MV502    (9)
/MV503    (9)
/MV505    (99)
/MV527    (999)
/MV602    (9)
/MV603    (999)
/MV604    (9)
/MV605    (9)
/MV610    (9)
/MV611    (9)
/MV612    (9)
/MV613    (99)
/MV616    (999)
/MV621    (9)
/MV627    (99)
/MV628    (99)
/MV629    (99)
/MV714    (9)
/MV716    (999)
/MV717    (99)
/MV731    (9)
/MV740    (9)
/MV762    (99)
/MS304$01 (9)
/MS304$02 (9)
/MS304$03 (9)
/MS304$04 (9)
/MS304$05 (9)
/MS304$06 (9)
/MS304$07 (9)
/MS304$08 (9)
/MS304$09 (9)
/MS304$10 (9)
/MS304$11 (9)
/MS304$12 (9)
/MS304$13 (9)
/MS304$14 (9)
/MS304$15 (9)
/MS304$16 (9)
/MS304$17 (9)
/MS304$18 (9)
/MS304$19 (9)
/MS304$20 (9)
/MS309    (99)
/MS311    (99)
/MS316    (9)
/MS317    (99)
/MS320S   (9)
/MS320    (99)
/MS320A   (9)
/MS320C   (9999)
/MS320E   (99)
/MS320D   (9)
/MS321XE  (99)
/MS321XF  (9999)
/MS322B   (9)
/MS322C   (99)
/MS323    (99)
/MS323B   (9)
/MS325    (9)
/MS325A   (9)
/MS325B   (9)
/MS325C   (9)
/MS325H   (9)
/MS325I   (99)
/MS325J   (9)
/MS326    (99)
/MS328HI  (99)
/MS347A   (9)
/MS347B   (9)
/MS347CA  (9)
/MS347CB  (9)
/MS347CC  (9)
/MS347CD  (9)
/MS347CE  (9)
/MS348C   (9)
/MS349A   (9)
/MS349B   (9)
/MS349C   (9)
/MS349D   (9)
/MS349E   (9)
/MS350    (9)
/MS352    (99)
/MS353    (9)
/MS354    (9)
/MS355    (9)
/MS356    (99)
/MS357A   (9)
/MS357B   (9)
/MS357C   (9)
/MS357D   (9)
/MS357E   (9)
/MS357F   (9)
/MS357G   (9)
/MS358    (9)
/MS359    (9)
/MS360    (9)
/MS361    (9)
/MS408A   (9)
/MS408B   (9)
/MS408C   (9)
/MS408D   (9)
/MS508    (99)
/MS512    (9)
/MS514    (9)
.
VALUE LABELS
 MV013
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60+"
/MV014
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/MV015
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
/MV023
     0 "National"
     1 "Country specific"
/MV024
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/MV025
     1 "Urban"
     2 "Rural"
/MV026
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/MV035
     0 "No wives/partners"
/MV803
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
/MV101
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
/MV102
     1 "Urban"
     2 "Rural"
/MV104
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
/MV105
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
/MV106
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
/MV108
     1 "Reads easily"
     2 "Reads with difficult"
     3 "Cannot read"
/MV109
     0 "No"
     1 "Yes"
/MV110
     0 "No"
     1 "Yes"
/MV112
     0 "No"
     1 "Yes"
/MV130
     1 "Islam"
     2 "Christianity"
     3 "Hinduism"
     4 "Buddhism"
     5 "Other"
/MV133
    97 "Inconsistent"
/MV134
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
/MV135
     1 "Usual resident"
     2 "Visitor"
/MV148
     0 "No"
     1 "Yes"
/MV149
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
/MV150
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grand-son"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
/MV151
     1 "Male"
     2 "Female"
/MV301
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
/MV302
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
/MV304A01
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$01
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$01
     0 "No"
     1 "Yes"
/MV304A02
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$02
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$02
     0 "No"
     1 "Yes"
/MV304A03
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$03
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$03
     0 "No"
     1 "Yes"
/MV304A04
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$04
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$04
     0 "No"
     1 "Yes"
/MV304A05
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$05
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$05
     0 "No"
     1 "Yes"
/MV304A06
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$06
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$06
     0 "No"
     1 "Yes"
/MV304A07
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$07
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$07
     0 "No"
     1 "Yes"
/MV304A08
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$08
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$08
     0 "No"
     1 "Yes"
/MV304A09
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$09
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$09
     0 "No"
     1 "Yes"
/MV304A10
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$10
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$10
     0 "No"
     1 "Yes"
/MV304A11
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$11
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$11
     0 "No"
     1 "Yes"
/MV304A12
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$12
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$12
     0 "No"
     1 "Yes"
/MV304A13
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$13
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$13
     0 "No"
     1 "Yes"
/MV304A14
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$14
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$14
     0 "No"
     1 "Yes"
/MV304A15
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
/MV304$15
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
/MV305$15
     0 "No"
     1 "Yes"
/MV312
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/MV313
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
/MV361
     1 "Currently using"
     3 "Ever used"
     4 "Never used"
/MV362
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
/MV363
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    98 "Don't know"
/MV364
     1 "Using modern method"
     2 "Using tradit. method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
/MV375A
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    95 "No reason"
    96 "Other"
    98 "DK"
/MV376
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    96 "Other"
    98 "DK"
/MV384A
     0 "No"
     1 "Yes"
/MV384B
     0 "No"
     1 "Yes"
/MV384D
     0 "No"
     1 "Yes"
/MV501
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
/MV502
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
/MV503
     1 "Once"
     2 "More than once"
/MV510
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
/MV513
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
/MV527
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
/MV532
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
/MV602
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infec"
     6 "Never had sex"
     7 "Man declared infec."
/MV603
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
/MV604
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
/MV605
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
/MV610
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
/MV611
     0 "Never"
     1 "Once or twice"
     2 "More often"
/MV612
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
/MV613
    95 "Up to God"
    96 "Non-numeric response"
    98 "DK"
/MV614
     6 "6+"
     7 "Non-numeric response"
/MV616
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
/MV621
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "DK"
/MV627
    95 "Up to God"
    96 "Other"
/MV628
    95 "Up to God"
    96 "Other"
/MV629
    95 "Up to God"
    96 "Other"
/MV714
     0 "No"
     1 "Yes"
/MV716
     0 "Not working"
/MV717
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
/MV731
     0 "No"
     1 "In the past year"
     2 "Currently working"
/MV740
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
/MV762
    11 "Government hospital"
    12 "Government health c."
    13 "Family planning clin"
    14 "Mobile clinic"
    15 "Public field worker"
    16 "Other public"
    21 "Private hosp, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Private mobile clin"
    25 "Private field worker"
    26 "Other private"
    31 "Shop"
    32 "Church"
    33 "Friends, relatives"
    96 "Other"
    98 "DK source for condom"
/MSFORMAT
     1 "Bengali"
     2 "English"
/MSADJUST
     0 "Not adjusted"
     1 "Adjusted"
/MS304$01
     0 "No"
     1 "Yes"
/MS304$02
     0 "No"
     1 "Yes"
/MS304$03
     0 "No"
     1 "Yes"
/MS304$04
     0 "No"
     1 "Yes"
/MS304$05
     0 "No"
     1 "Yes"
/MS304$06
     0 "No"
     1 "Yes"
/MS304$07
     0 "No"
     1 "Yes"
/MS304$08
     0 "No"
     1 "Yes"
/MS304$09
     0 "No"
     1 "Yes"
/MS304$10
     0 "No"
     1 "Yes"
/MS304$11
     0 "No"
     1 "Yes"
/MS304$12
     0 "No"
     1 "Yes"
/MS304$13
     0 "No"
     1 "Yes"
/MS304$14
     0 "No"
     1 "Yes"
/MS304$15
     0 "No"
     1 "Yes"
/MS304$16
     0 "No"
     1 "Yes"
/MS304$17
     0 "No"
     1 "Yes"
/MS304$18
     0 "No"
     1 "Yes"
/MS304$19
     0 "No"
     1 "Yes"
/MS304$20
     0 "No"
     1 "Yes"
/MS309
     0 "Never used"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/MS316
     0 "No"
     1 "Yes"
/MS317
     0 "Not using 2nd method"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
/MS320S
     0 "No"
     1 "Yes"
/MS320
     1 "Raja"
     2 "Panther"
     3 "Majestic"
     4 "Sensation"
     5 "Latex"
     6 "Tahiti"
     7 "Circle rubber"
     8 "Sultan"
     9 "Gent"
    10 "Durex"
    96 "Other condom brand"
    98 "Don't know brand"
/MS320A
     1 "Wife keeps"
     2 "Ran out"
     3 "Other"
/MS320C
  9995 "Partner obtained"
  9996 "Free"
  9998 "Don't know"
/MS320D
     0 "No"
     1 "Yes"
/MS321F
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
/MS321XA
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
/MS321XB
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45+"
/MS321XC
     0 "Single,before marr."
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
/MS321XD
     1 "Bengali"
     2 "English"
/MS321XE
    98 "DK month"
/MS321XF
  9997 "Inconsistent"
  9998 "DK year"
/MS322B
     0 "Does not regret"
     1 "Wants another child"
     2 "Partner wants child"
     3 "Side effects"
     4 "Other reason"
/MS322C
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
/MS323
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/MS323B
     0 "No"
     1 "Yes"
     8 "Don't know"
/MS325
     1 "Respondent"
     2 "Wife"
     3 "Son/daughter"
     4 "Other relative"
     5 "Other"
/MS325A
     0 "No"
     1 "Yes"
/MS325B
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/MS325C
     0 "No"
     1 "Yes"
     8 "Cannot remember"
/MS325H
     0 "No"
     1 "Yes"
/MS325I
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
/MS325J
     1 "Respondent had most"
     2 "Wife had most"
     3 "Husb. and wife equal"
     4 "Other relative"
     5 "Other"
/MS326
     1 "Recomm. FP worker"
     2 "Recomm. friend, rel."
     3 "Side effects others"
     4 "Method easy to use"
     5 "Access, availability"
     6 "Cost"
     7 "Wanted permanent m."
     8 "Wife preferred"
     9 "Wanted more effect."
    10 "Other"
    98 "DK"
/MS328HI
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/MS347A
     1 "Yes"
     0 "No"
     8 "DK"
/MS347B
     1 "Yes"
     0 "No"
/MS347CA
     0 "No"
     1 "Yes"
/MS347CB
     0 "No"
     1 "Yes"
/MS347CC
     0 "No"
     1 "Yes"
/MS347CD
     0 "No"
     1 "Yes"
/MS347CE
     0 "No"
     1 "Yes"
/MS348C
     0 "No"
     1 "Yes"
/MS349A
     0 "No"
     1 "Yes"
/MS349B
     0 "No"
     1 "Yes"
/MS349C
     0 "No"
     1 "Yes"
/MS349D
     0 "No"
     1 "Yes"
     8 "DK"
/MS349E
     0 "No"
     1 "Yes"
     8 "DK"
/MS350
     0 "No visit"
     1 "Yes, for Fmly Plng."
     2 "Yes, for other rsn."
     8 "DK"
/MS352
    98 "DK"
/MS353
     0 "Less than 1 mth ago"
     8 "DK"
/MS354
     0 "No"
     1 "Yes"
/MS355
     1 "Pills"
     2 "Condoms"
     3 "Injection"
     4 "Other"
/MS357A
     0 "Yes"
     1 "No"
/MS357B
     0 "Yes"
     1 "No"
/MS357C
     0 "Yes"
     1 "No"
/MS357D
     0 "Yes"
     1 "No"
/MS357E
     0 "Yes"
     1 "No"
/MS357F
     0 "Yes"
     1 "No"
/MS357G
     0 "Yes"
     1 "No"
/MS358
     0 "No"
     1 "Yes"
     8 "DK"
/MS359
     0 "No"
     1 "Yes"
/MS360
     0 "No"
     1 "Yes"
/MS361
     0 "No"
     1 "Yes"
/MS408A
     0 "No"
     1 "Yes"
/MS408B
     0 "No"
     1 "Yes"
/MS408C
     0 "No"
     1 "Yes"
/MS408D
     0 "No"
     1 "Yes"
/MS508
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Traditional doctor"
    22 "Qualified doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
/MS512
     0 "No"
     1 "Yes"
/MS514
     0 "Not allowed to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
.
