infix using BDMR31FL.dct

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Sample weight"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Respondent's month of birth"
label variable mv010    "Respondent's year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age - respondent"
label variable mv013    "Age 5-year groups"
label variable mv014    "Completeness of information"
label variable mv015    "Result of individual interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor - NA"
label variable mv031    "Field editor - NA"
label variable mv032    "Office editor - NA"
label variable mv033    "Ultimate area selection prob."
label variable mv034_1  "Line numbers of wives"
label variable mv034_2  "Line numbers of wives"
label variable mv034_3  "Line numbers of wives"
label variable mv034_4  "Line numbers of wives"
label variable mv034_5  "Line numbers of wives"
label variable mv034_6  "Line numbers of wives"
label variable mv034_7  "Line numbers of wives"
label variable mv034_8  "Line numbers of wives"
label variable mv035    "Number of wives, partners"
label variable mv801    "Time interview started"
label variable mv802    "Time interview ended"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "Childhood place of residen- NA"
label variable mv104    "Years lived in place of res."
label variable mv105    "Type of place of previous residence"
label variable mv106    "Highest educational level"
label variable mv107    "Highest year of education"
label variable mv108    "Literacy"
label variable mv109    "Reads newspaper once a week"
label variable mv110    "Watches TV every week"
label variable mv111    "Listens to radio every da - NA"
label variable mv112    "Listens to radio every week"
label variable mv130    "Religion"
label variable mv131    "Ethnicity - NA"
label variable mv133    "Education in single years"
label variable mv134    "De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members"
label variable mv138    "Number of eligible men in HH"
label variable mv148    "Respondent still in school"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv213    "Partner currently pregnan - NA"
label variable mv218    "Number of living children"
label variable mv225    "Current pregnancy wanted - NA"
label variable mv301    "Knowledge of any method"
label variable mv302    "Ever use of any method"
label variable m304a_01 "Type of method"
label variable mv304_01 "Knows method"
label variable mv305_01 "Ever used method"
label variable m304a_02 "Type of method"
label variable mv304_02 "Knows method"
label variable mv305_02 "Ever used method"
label variable m304a_03 "Type of method"
label variable mv304_03 "Knows method"
label variable mv305_03 "Ever used method"
label variable m304a_04 "Type of method"
label variable mv304_04 "Knows method"
label variable mv305_04 "Ever used method"
label variable m304a_05 "Type of method"
label variable mv304_05 "Knows method"
label variable mv305_05 "Ever used method"
label variable m304a_06 "Type of method"
label variable mv304_06 "Knows method"
label variable mv305_06 "Ever used method"
label variable m304a_07 "Type of method"
label variable mv304_07 "Knows method"
label variable mv305_07 "Ever used method"
label variable m304a_08 "Type of method"
label variable mv304_08 "Knows method"
label variable mv305_08 "Ever used method"
label variable m304a_09 "Type of method"
label variable mv304_09 "Knows method"
label variable mv305_09 "Ever used method"
label variable m304a_10 "Type of method"
label variable mv304_10 "Knows method"
label variable mv305_10 "Ever used method"
label variable m304a_11 "Type of method"
label variable mv304_11 "Knows method"
label variable mv305_11 "Ever used method"
label variable m304a_12 "Type of method"
label variable mv304_12 "Knows method"
label variable mv305_12 "Ever used method"
label variable m304a_13 "Type of method"
label variable mv304_13 "Knows method"
label variable mv305_13 "Ever used method"
label variable m304a_14 "Type of method"
label variable mv304_14 "Knows method"
label variable mv305_14 "Ever used method"
label variable m304a_15 "Type of method"
label variable mv304_15 "Knows method"
label variable mv305_15 "Ever used method"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current use by method type"
label variable mv361    "Pattern of use"
label variable mv362    "Intention to use"
label variable mv363    "Preferred future method"
label variable mv364    "Contraceptive use & intention"
label variable mv366a   "Acceptability of radio me - NA"
label variable mv366b   "Acceptability of TV messa - NA"
label variable mv367    "Wanted last child - NA"
label variable mv375a   "Main reason not using a method"
label variable mv376    "Main reason not to use a meth."
label variable mv384a   "Heard FP on radio last month"
label variable mv384b   "Heard FP on TV last month"
label variable mv384c   "Heard FP newspaper last mon-NA"
label variable mv384d   "Heard FP on poster last month"
label variable mv384e   "Heard FP brochures last m - NA"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never marr."
label variable mv503    "Number of unions"
label variable mv505    "Number of wives, partners"
label variable mv507    "Month of first marriage"
label variable mv508    "Year of first marriage"
label variable mv509    "Date of first marriage (CMC)"
label variable mv510    "Completeness of date inform."
label variable mv511    "Age at first marriage"
label variable mv512    "Years since first marriage"
label variable mv513    "Marital duration (grouped)"
label variable mv525    "Age at first intercourse - NA"
label variable mv527    "Time since last intercourse"
label variable mv531    "Age at first intercourse - NA"
label variable mv532    "Flag for MV531"
label variable mv534    "Have a regular sex partne - NA"
label variable mv535    "Have ever been married - NA"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time"
label variable mv604    "Preferred waiting time (grpd)"
label variable mv605    "Desire for more children"
label variable mv610    "Wife approves FP"
label variable mv611    "Discussed FP with partner"
label variable mv612    "Respondent approves FP"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grp)"
label variable mv616    "Time for future birth"
label variable mv621    "Wifes desire for children"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv630a   "Discussed FP with partner - NA"
label variable mv630b   "Discussed FP with mother - NA"
label variable mv630c   "Discussed FP with father - NA"
label variable mv630d   "Discussed FP with sister( - NA"
label variable mv630e   "Discussed FP with brother - NA"
label variable mv630f   "Discussed FP with daughte - NA"
label variable mv630g   "Discussed FP with mother- - NA"
label variable mv630h   "Discussed FP with friends - NA"
label variable mv630i   "Discussed FP -country spe - NA"
label variable mv630j   "Discussed FP -country spe - NA"
label variable mv630k   "Discussed FP -country spe - NA"
label variable mv630l   "Discussed FP -country spe - NA"
label variable mv630x   "Discussed FP with others - NA"
label variable mv714    "Respondent currently working"
label variable mv716    "Respondent's occupation"
label variable mv717    "Respondent's occupation"
label variable mv719    "Work for family, others, - NA"
label variable mv731    "Worked in last 12 months - NA"
label variable mv732    "Employment all year/seaso - NA"
label variable mv733    "Months worked in last 12 - NA"
label variable mv736    "Earnings for work - NA"
label variable mv740    "Type of land where resp. works"
label variable mv751    "Ever heard of AIDS - NA"
label variable mv752a   "AIDS: radio - NA"
label variable mv752b   "AIDS: television - NA"
label variable mv752c   "AIDS: newspapers/magazine - NA"
label variable mv752d   "AIDS: pamphlets/posters - NA"
label variable mv752e   "AIDS: clinic/health worke - NA"
label variable mv752f   "AIDS: churches/mosques - NA"
label variable mv752g   "AIDS: schools/teachers - NA"
label variable mv752h   "AIDS: community meetings - NA"
label variable mv752i   "AIDS: friends/relatives - NA"
label variable mv752j   "AIDS: work place - NA"
label variable mv752k   "AIDS: country specific - NA"
label variable mv752l   "AIDS: country specific - NA"
label variable mv752m   "AIDS: country specific - NA"
label variable mv752n   "AIDS: country specific - NA"
label variable mv752o   "AIDS: country specific - NA"
label variable mv752x   "AIDS: other responses - NA"
label variable mv753    "Ways to avoid AIDS - NA"
label variable mv754a   "AIDS: Safe sex - NA"
label variable mv754b   "AIDS: abstain from sex - NA"
label variable mv754c   "AIDS: use condoms during - NA"
label variable mv754d   "AIDS: only one sex partne - NA"
label variable mv754e   "AIDS: avoid sex prostitut - NA"
label variable mv754f   "AIDS: avoid sex homosexua - NA"
label variable mv754g   "AIDS: avoid blood transfu - NA"
label variable mv754h   "AIDS: avoid injections - NA"
label variable mv754i   "AIDS: avoid kissing - NA"
label variable mv754j   "AIDS: avoid mosquito bite - NA"
label variable mv754k   "AIDS: protection trad. he - NA"
label variable mv754l   "AIDS: country specific - NA"
label variable mv754m   "AIDS: country specific - NA"
label variable mv754n   "AIDS: country specific - NA"
label variable mv754o   "AIDS: country specific - NA"
label variable mv754x   "AIDS: other responses - NA"
label variable mv754z   "AIDS: DK ways to avoid AI - NA"
label variable mv755b   "Safe sex: abstain from se - NA"
label variable mv755c   "Safe sex: use condoms dur - NA"
label variable mv755d   "Safe sex: only one partne - NA"
label variable mv755e   "Safe sex: avoid prostitut - NA"
label variable mv755f   "Safe sex: avoid homosexua - NA"
label variable mv755l   "Safe sex: country specifi - NA"
label variable mv755m   "Safe sex: country specifi - NA"
label variable mv755n   "Safe sex: country specifi - NA"
label variable mv755o   "Safe sex: country specifi - NA"
label variable mv755x   "Safe sex: other responses - NA"
label variable mv755z   "Safe sex: DK meaning - NA"
label variable mv756    "Can a healthy person have - NA"
label variable mv757    "Is AIDS a fatal disease - NA"
label variable mv758    "Chances of getting AIDS - NA"
label variable mv760a   "Behavior: Did not start s - NA"
label variable mv760b   "Behavior: Stopped all sex - NA"
label variable mv760c   "Behavior: Started using c - NA"
label variable mv760d   "Behavior: Only one sex pa - NA"
label variable mv760e   "Behavior: Reduced partner - NA"
label variable mv760f   "Behavior: Ask spouse fait - NA"
label variable mv760g   "Behavior: No homosexual c - NA"
label variable mv760i   "Behavior: Stopped injecti - NA"
label variable mv760l   "Behavior: Country specifi - NA"
label variable mv760m   "Behavior: Country specifi - NA"
label variable mv760n   "Behavior: Country specifi - NA"
label variable mv760o   "Behavior: Country specifi - NA"
label variable mv760p   "Behavior: Avoid sex w. pr - NA"
label variable mv760v   "Behavior: No nonsexual ch - NA"
label variable mv760w   "Behavior: Other nonsexual - NA"
label variable mv760x   "Behavior: Other responses - NA"
label variable mv760y   "Behavior: No change - NA"
label variable mv760z   "Behavior: Don't know - NA"
label variable mv761    "Last intercourse used con - NA"
label variable mv762    "Source for condoms"
label variable mv763    "Partners in last 12 month - NA"
label variable mv764    "Knowledge of condom - NA"
label variable mv765    "Ever use of condom - NA"
label variable msdistr  "District of residence"
label variable msformat "Type of date format used"
label variable msadjust "Month of interview adjusted 1m"
label variable msinty   "Year of interview(unadjusted)"
label variable msintm   "Month of interview(unadjusted)"
label variable ms304_01 "Knows source of method"
label variable ms304_02 "Knows source of method"
label variable ms304_03 "Knows source of method"
label variable ms304_04 "Knows source of method"
label variable ms304_05 "Knows source of method"
label variable ms304_06 "Knows source of method"
label variable ms304_07 "Knows source of method"
label variable ms304_08 "Knows source of method"
label variable ms304_09 "Knows source of method"
label variable ms304_10 "Knows source of method"
label variable ms304_11 "Knows source of method"
label variable ms304_12 "Knows source of method"
label variable ms304_13 "Knows source of method"
label variable ms304_14 "Knows source of method"
label variable ms304_15 "Knows source of method"
label variable ms304_16 "Knows source of method"
label variable ms304_17 "Knows source of method"
label variable ms304_18 "Knows source of method"
label variable ms304_19 "Knows source of method"
label variable ms304_20 "Knows source of method"
label variable ms309    "First method used"
label variable ms311    "Living children at first use"
label variable ms316    "Currently using second method"
label variable ms317    "Second method currently used"
label variable ms320s   "Condom package seen"
label variable ms320    "Brand of condoms shown"
label variable ms320a   "Reason can't show condom pack"
label variable ms320c   "Reason can't show condom pack"
label variable ms320e   "Times used condoms last month"
label variable ms320d   "Use condom every time have sex"
label variable ms321m   "Month of sterilization (imp.)"
label variable ms321y   "Year of sterilization (imp.)"
label variable ms321c   "Date of sterilization (CMC)"
label variable ms321f   "Completeness of information"
label variable ms321xa  "Years since sterilization"
label variable ms321xb  "Age at sterilization"
label variable ms321xc  "Marital duration at steriliz."
label variable ms321xd  "Wife's sterilization:date form"
label variable ms321xe  "Wife's sterilization : month"
label variable ms321xf  "Wife's sterilization: year"
label variable ms322b   "Sterilization regret"
label variable ms322c   "Method used most recently"
label variable ms323    "Source of current method"
label variable ms323b   "Paid for use of contr.source"
label variable ms325    "Who obtained pills/condoms"
label variable ms325a   "Got pls,cndm at HF,doctor,shop"
label variable ms325b   "Informed of side effects/probs"
label variable ms325c   "Informed of other methods"
label variable ms325h   "Got method he wanted"
label variable ms325i   "Method wanted at HF."
label variable ms325j   "Who had most inflc. at 1st use"
label variable ms326    "Reason for current method"
label variable ms328hi  "Knows source for method"
label variable ms347a   "Satellite clinic last 3 months"
label variable ms347b   "Visited satellite clinic"
label variable ms347ca  "Sat.Clinic: Family Plng.Meths."
label variable ms347cb  "Sat.Clinic: Immunization"
label variable ms347cc  "Sat.Clinic: Ch.growth monitor."
label variable ms347cd  "Sat.Clinic: Other"
label variable ms347ce  "Sat.Clinic: Does not know"
label variable ms348c   "Read about FP on Billboard"
label variable ms349a   "Inf. on radio acceptable:pill"
label variable ms349b   "Inf. on radio acct'ble:condoms"
label variable ms349c   "Inf. on radio acct'ble:injctns"
label variable ms349d   "Inf. on radio acct'ble:IUD's"
label variable ms349e   "Inf. on radio acct'ble:sterlzn"
label variable ms350    "Visit by FPW in last 6 mnths"
label variable ms352    "No. visits by FPW last 6 mnths"
label variable ms353    "Months since last visit by FPW"
label variable ms354    "Received supplies from FPW"
label variable ms355    "Supplies received from FPW"
label variable ms356    "How many cycles/condoms rec'vd"
label variable ms357a   "Meths.disc.w FPW: Pills"
label variable ms357b   "Meths.disc.w FPW: IUD"
label variable ms357c   "Meths.disc.w FPW: Injection"
label variable ms357d   "Meths.disc.w FPW: Condom"
label variable ms357e   "Meths.disc.w FPW: Female Ster."
label variable ms357f   "Meths.disc.w FPW: Male Ster."
label variable ms357g   "Meths.disc.w FPW: Never disc."
label variable ms358    "Most men known by rsp use FP"
label variable ms359    "Has recommended FP to someone"
label variable ms360    "Visit Health Facility last 6m"
label variable ms361    "Spoke with psn at HF about FP"
label variable ms408a   "Children under 10"
label variable ms408b   "Presence of wife"
label variable ms408c   "Other males"
label variable ms408d   "Other females"
label variable ms508    "Source of preferred method"
label variable ms512    "Discussed children"
label variable ms514    "Wife allowed to go out alone"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60+"
;
label define MV014   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
     9 "Missing"
;
label define MV023   
     0 "National"
     1 "Country specific"
;
label define MV024   
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define MV035   
     0 "No wives/partners"
     9 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
    99 "Missing"
;
label define MV101   
     1 "Barishal"
     2 "Chittagong"
     3 "Dhaka"
     4 "Khulna"
     5 "Rajshani"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
    99 "Missing"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
     9 "Missing"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     9 "Missing"
;
label define MV108   
     1 "Reads easily"
     2 "Reads with difficult"
     3 "Cannot read"
     9 "Missing"
;
label define MV109   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV110   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV112   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV130   
     1 "Islam"
     2 "Christianity"
     3 "Hinduism"
     4 "Buddhism"
     5 "Other"
     9 "Missing"
;
label define MV133   
    97 "Inconsistent"
    99 "Missing"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
     9 "Missing"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
     9 "Missing"
;
label define MV148   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     9 "Missing"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grand-son"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
    99 "Missing"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric"
     2 "Knows only trad. mth"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric"
     2 "Used only trad. meth"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes, spontaneously"
     2 "Yes, probed"
     8 "Not asked"
     9 "Missing"
;
label define MV305   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     9 "Missing"
;
label define MV361   
     1 "Currently using"
     3 "Ever used"
     4 "Never used"
;
label define MV362   
     1 "In next 12 months"
     2 "Use later"
     3 "Unsure about timing"
     4 "Unsure about use"
     5 "Does not intend"
     6 "Never had sex"
     9 "Missing"
;
label define MV363   
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    98 "Don't know"
    99 "Missing"
;
label define MV364   
     1 "Using modern method"
     2 "Using tradit. method"
     3 "Non-user intend to"
     4 "Does not intend to"
     5 "Never had sex"
;
label define MV375A  
    11 "Not married"
    20 "FERTILITY-RELATED"
    21 "Not having sex"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    27 "Pregnant"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    95 "No reason"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV376   
    11 "Not married"
    20 "FERTILITY-RELATED"
    22 "Infrequent sex"
    23 "Menopausal, hyster."
    24 "Subfecund, infecund"
    25 "Postpartum, breastf."
    26 "Wants more children"
    30 "OPPOSITION TO USE"
    31 "Respondent opposed"
    32 "Partner opposed"
    33 "Others opposed"
    34 "Religious prohibit."
    35 "Fatalistic"
    40 "LACK OF KNOWLEDGE"
    41 "Knows no method"
    42 "Knows no source"
    50 "METHOD-RELATED"
    51 "Health concerns"
    52 "Fear side effects"
    53 "Lack of access"
    54 "Cost too much"
    55 "Inconvenient to use"
    56 "Interfere with body"
    61 "Up to woman to use"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MV384A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV384B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV384D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV501   
     0 "Never married"
     1 "Married"
     2 "Living together"
     3 "Widowed"
     4 "Divorced"
     5 "Not living together"
     9 "Missing"
;
label define MV502   
     0 "Never married"
     1 "Currently married"
     2 "Formerly married"
     9 "Missing"
;
label define MV503   
     1 "Once"
     2 "More than once"
     9 "Missing"
;
label define MV510   
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV527   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After concep >= 1 yr"
     3 "After concep < 1 yr"
     4 "At marr, never marr"
     5 "At marr,after concep"
     6 "After marriage"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized"
     5 "Wife declared infec"
     6 "Never had sex"
     7 "Man declared infec."
     9 "Missing"
;
label define MV603   
   993 "After marriage"
   994 "Soon, now"
   996 "Other, Non-numeric"
   997 "Inconsistent"
   998 "Don't know"
   999 "Missing"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
     9 "Missing"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized"
     7 "Declared infecund"
     8 "Never had sex"
     9 "Missing"
;
label define MV610   
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define MV611   
     0 "Never"
     1 "Once or twice"
     2 "More often"
     9 "Missing"
;
label define MV612   
     0 "Disapproves"
     1 "Approves"
     8 "Don't know"
     9 "Missing"
;
label define MV613   
    95 "Up to God"
    96 "Non-numeric response"
    98 "DK"
    99 "Missing"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "DK"
   999 "Missing"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "DK"
     9 "Missing"
;
label define MV627   
    95 "Up to God"
    96 "Other"
    99 "Missing"
;
label define MV628   
    95 "Up to God"
    96 "Other"
    99 "Missing"
;
label define MV629   
    95 "Up to God"
    96 "Other"
    99 "Missing"
;
label define MV714   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MV716   
     0 "Not working"
   999 "Missing"
;
label define MV717   
     0 "Not working"
     1 "Prof., Tech., Manag."
     2 "Clerical"
     3 "Sales"
     4 "Agric-self employed"
     5 "Agric-employee"
     6 "Household & domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    98 "Don't know"
    99 "Missing"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
     9 "Missing"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
     9 "Missing"
;
label define MV762   
    11 "Government hospital"
    12 "Government health c."
    13 "Family planning clin"
    14 "Mobile clinic"
    15 "Public field worker"
    16 "Other public"
    21 "Private hosp, clinic"
    22 "Pharmacy"
    23 "Private doctor"
    24 "Private mobile clin"
    25 "Private field worker"
    26 "Other private"
    31 "Shop"
    32 "Church"
    33 "Friends, relatives"
    96 "Other"
    98 "DK source for condom"
    99 "Missing"
;
label define MSFORMAT
     1 "Bengali"
     2 "English"
;
label define MSADJUST
     0 "Not adjusted"
     1 "Adjusted"
;
label define MS304   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS309   
     0 "Never used"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define MS316   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS317   
     0 "Not using 2nd method"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    99 "Missing"
;
label define MS320S  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS320   
     1 "Raja"
     2 "Panther"
     3 "Majestic"
     4 "Sensation"
     5 "Latex"
     6 "Tahiti"
     7 "Circle rubber"
     8 "Sultan"
     9 "Gent"
    10 "Durex"
    96 "Other condom brand"
    98 "Don't know brand"
    99 "Missing"
;
label define MS320A  
     1 "Wife keeps"
     2 "Ran out"
     3 "Other"
     9 "Missing"
;
label define MS320C  
  9995 "Partner obtained"
  9996 "Free"
  9998 "Don't know"
  9999 "Missing"
;
label define MS320D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS321F  
     1 "Month and year"
     5 "Year - m imp, a calc"
     7 "Month - date placed"
     8 "None - date placed"
;
label define MS321XA 
     1 "<2"
     2 "2-3"
     3 "4-5"
     4 "6-7"
     5 "8-9"
     6 "10+"
;
label define MS321XB 
     1 "<25"
     2 "25-29"
     3 "30-34"
     4 "35-39"
     5 "40-44"
     6 "45+"
;
label define MS321XC 
     0 "Single,before marr."
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25+"
;
label define MS321XD 
     1 "Bengali"
     2 "English"
;
label define MS321XE 
    98 "DK month"
    99 "Missing"
;
label define MS321XF 
  9997 "Inconsistent"
  9998 "DK year"
  9999 "Missing"
;
label define MS322B  
     0 "Does not regret"
     1 "Wants another child"
     2 "Partner wants child"
     3 "Side effects"
     4 "Other reason"
     9 "Missing"
;
label define MS322C  
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Norplant"
    12 "Abstinence"
    13 "Specific method 1"
    14 "Specific method 2"
    15 "Specific method 3"
    99 "Missing"
;
label define MS323   
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MS323B  
     0 "No"
     1 "Yes"
     8 "Don't know"
     9 "Missing"
;
label define MS325   
     1 "Respondent"
     2 "Wife"
     3 "Son/daughter"
     4 "Other relative"
     5 "Other"
     9 "Missing"
;
label define MS325A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS325B  
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define MS325C  
     0 "No"
     1 "Yes"
     8 "Cannot remember"
     9 "Missing"
;
label define MS325H  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS325I  
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm/Foam/Jelly"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    99 "Missing"
;
label define MS325J  
     1 "Respondent had most"
     2 "Wife had most"
     3 "Husb. and wife equal"
     4 "Other relative"
     5 "Other"
     9 "Missing"
;
label define MS326   
     1 "Recomm. FP worker"
     2 "Recomm. friend, rel."
     3 "Side effects others"
     4 "Method easy to use"
     5 "Access, availability"
     6 "Cost"
     7 "Wanted permanent m."
     8 "Wife preferred"
     9 "Wanted more effect."
    10 "Other"
    98 "DK"
    99 "Missing"
;
label define MS328HI 
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Private clinic,doct."
    22 "Traditional doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MS347A  
     1 "Yes"
     0 "No"
     8 "DK"
     9 "Missing"
;
label define MS347B  
     1 "Yes"
     0 "No"
     9 "Missing"
;
label define MS347CA 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CB 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CC 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CD 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS347CE 
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS348C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS349D  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MS349E  
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MS350   
     0 "No visit"
     1 "Yes, for Fmly Plng."
     2 "Yes, for other rsn."
     8 "DK"
     9 "Missing"
;
label define MS352   
    98 "DK"
    99 "Missing"
;
label define MS353   
     0 "Less than 1 mth ago"
     8 "DK"
     9 "Missing"
;
label define MS354   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS355   
     1 "Pills"
     2 "Condoms"
     3 "Injection"
     4 "Other"
     9 "Missing"
;
label define MS357A  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357B  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357C  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357D  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357E  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357F  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS357G  
     0 "Yes"
     1 "No"
     9 "Missing"
;
label define MS358   
     0 "No"
     1 "Yes"
     8 "DK"
     9 "Missing"
;
label define MS359   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS360   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS361   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408A  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408B  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408C  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS408D  
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS508   
    11 "Hospital/Medical clg"
    12 "Family welfare cent."
    13 "Thana health complex"
    14 "Satellite clinic"
    21 "Traditional doctor"
    22 "Qualified doctor"
    23 "Pharmacy"
    31 "Shop"
    32 "Friends, relatives"
    41 "Fieldworker, FWA"
    96 "Other"
    98 "DK"
    99 "Missing"
;
label define MS512   
     0 "No"
     1 "Yes"
     9 "Missing"
;
label define MS514   
     0 "Not allowed to go out"
     1 "Yes, alone"
     2 "Yes, with children"
     6 "Other"
     9 "Missing"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv108    MV108   
label values mv109    MV109   
label values mv110    MV110   
label values mv112    MV112   
label values mv130    MV130   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv148    MV148   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values mv304_01 MV304   
label values mv305_01 MV305   
label values m304a_02 M304A   
label values mv304_02 MV304   
label values mv305_02 MV305   
label values m304a_03 M304A   
label values mv304_03 MV304   
label values mv305_03 MV305   
label values m304a_04 M304A   
label values mv304_04 MV304   
label values mv305_04 MV305   
label values m304a_05 M304A   
label values mv304_05 MV304   
label values mv305_05 MV305   
label values m304a_06 M304A   
label values mv304_06 MV304   
label values mv305_06 MV305   
label values m304a_07 M304A   
label values mv304_07 MV304   
label values mv305_07 MV305   
label values m304a_08 M304A   
label values mv304_08 MV304   
label values mv305_08 MV305   
label values m304a_09 M304A   
label values mv304_09 MV304   
label values mv305_09 MV305   
label values m304a_10 M304A   
label values mv304_10 MV304   
label values mv305_10 MV305   
label values m304a_11 M304A   
label values mv304_11 MV304   
label values mv305_11 MV305   
label values m304a_12 M304A   
label values mv304_12 MV304   
label values mv305_12 MV305   
label values m304a_13 M304A   
label values mv304_13 MV304   
label values mv305_13 MV305   
label values m304a_14 M304A   
label values mv304_14 MV304   
label values mv305_14 MV305   
label values m304a_15 M304A   
label values mv304_15 MV304   
label values mv305_15 MV305   
label values mv312    MV312   
label values mv313    MV313   
label values mv361    MV361   
label values mv362    MV362   
label values mv363    MV363   
label values mv364    MV364   
label values mv375a   MV375A  
label values mv376    MV376   
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384d   MV384D  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv510    MV510   
label values mv513    MV513   
label values mv527    MV527   
label values mv532    MV532   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv610    MV610   
label values mv611    MV611   
label values mv612    MV612   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv714    MV714   
label values mv716    MV716   
label values mv717    MV717   
label values mv731    MV731   
label values mv740    MV740   
label values mv762    MV762   
label values msformat MSFORMAT
label values msadjust MSADJUST
label values ms304_01 MS304   
label values ms304_02 MS304   
label values ms304_03 MS304   
label values ms304_04 MS304   
label values ms304_05 MS304   
label values ms304_06 MS304   
label values ms304_07 MS304   
label values ms304_08 MS304   
label values ms304_09 MS304   
label values ms304_10 MS304   
label values ms304_11 MS304   
label values ms304_12 MS304   
label values ms304_13 MS304   
label values ms304_14 MS304   
label values ms304_15 MS304   
label values ms304_16 MS304   
label values ms304_17 MS304   
label values ms304_18 MS304   
label values ms304_19 MS304   
label values ms304_20 MS304   
label values ms309    MS309   
label values ms316    MS316   
label values ms317    MS317   
label values ms320s   MS320S  
label values ms320    MS320   
label values ms320a   MS320A  
label values ms320c   MS320C  
label values ms320d   MS320D  
label values ms321f   MS321F  
label values ms321xa  MS321XA 
label values ms321xb  MS321XB 
label values ms321xc  MS321XC 
label values ms321xd  MS321XD 
label values ms321xe  MS321XE 
label values ms321xf  MS321XF 
label values ms322b   MS322B  
label values ms322c   MS322C  
label values ms323    MS323   
label values ms323b   MS323B  
label values ms325    MS325   
label values ms325a   MS325A  
label values ms325b   MS325B  
label values ms325c   MS325C  
label values ms325h   MS325H  
label values ms325i   MS325I  
label values ms325j   MS325J  
label values ms326    MS326   
label values ms328hi  MS328HI 
label values ms347a   MS347A  
label values ms347b   MS347B  
label values ms347ca  MS347CA 
label values ms347cb  MS347CB 
label values ms347cc  MS347CC 
label values ms347cd  MS347CD 
label values ms347ce  MS347CE 
label values ms348c   MS348C  
label values ms349a   MS349A  
label values ms349b   MS349B  
label values ms349c   MS349C  
label values ms349d   MS349D  
label values ms349e   MS349E  
label values ms350    MS350   
label values ms352    MS352   
label values ms353    MS353   
label values ms354    MS354   
label values ms355    MS355   
label values ms357a   MS357A  
label values ms357b   MS357B  
label values ms357c   MS357C  
label values ms357d   MS357D  
label values ms357e   MS357E  
label values ms357f   MS357F  
label values ms357g   MS357G  
label values ms358    MS358   
label values ms359    MS359   
label values ms360    MS360   
label values ms361    MS361   
label values ms408a   MS408A  
label values ms408b   MS408B  
label values ms408c   MS408C  
label values ms408d   MS408D  
label values ms508    MS508   
label values ms512    MS512   
label values ms514    MS514   
